### ISSUE TITLE
Diagram out potential IA for browse pages

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1003]
Per the design session today, we want to explore having parent-child browse pages, which would allow us to create more specialized views and filters for more specific types of, say, filings or committees.

I'm going to work on mapping out what those pages and their respective filters and columns could be.

**Comment by noahmanger** [comment]
Here's a first pass at a map of browse pages and sub-pages / sub-views:

![browse ia](https://cloud.githubusercontent.com/assets/1696495/11969810/b285e604-a8d4-11e5-8d76-14e5246a6404.png)

The idea is that each category (blue box) contains a view of all items in that category (brown) (which is what we have now), and then multiple sub-pages (white) for more narrow data sets. Each sub-page:

1. Applies some set of basic filtering behind the scenes, such as limiting to all presidential candidates, or all PACs. Even though this uses the same filtering technique as the "all" view, I think we should keep these filters hidden in order to keep the interface as clear as possible.

2. Presents a different set of filters and columns: In the case of the filings sub-views, this allows us to have filters and columns specifically relevant to the different forms. In the case of candidates, even though all financial filters may be applicable to all offices, the sub-view gives us a reason to show different information than we're showing on the "all" view. In both cases, it allows us to show a more limited and relevant set of filters and columns.

3. Gives an easy-to-navigate to destination for common queries. This allows us to more closely replicate areas where FEC users have grown accustomed to finding information on the old site, while still sticking within our design principles of having one single place for everything and a common interface to all data. 

The more work I do on this the more excited I am. In addition to all of the above, this is a great chance to more closely mirror the user's mental model of the data. You really see this in providing specific destinations to the different types of committees, since we've learned that people don't really have an overarching concept of "a committee". 

Last thing, I've started a spreadsheet that I'll share in Slack for tracking which columns, filters, and details panel items we'll want to include in each subview.

**Comment by jenniferthibault** [comment]
This is great Noah—thanks so much for putting it together. It all makes sense to me, and jives with how I've been thinking about this section as well. Heads up @onezerojeremy

**Comment by jenniferthibault** [comment]
We've been working off of Noah's mockups here & have been doing lots of brainstorming with him and @onezerojeremy. (You've seen some debate in the slack channel :) )

Here's the latest thinking for the IA of the data side of the site *I recommend opening in a new tab so you can see text better*:
![data side ia](https://cloud.githubusercontent.com/assets/11636908/12344582/d03e434a-bb0c-11e5-97fe-8ee3d3d3d80f.png)



Noah's 3 points above still stand, but here are a few new additions:

1. We are introducing a "partition" of sorts to how users can find and experience the data.  We don't need or want the data set tables to play the role of providing high-level summaries, introductions to the data, etc, and that we'll use a new kind of page that will be better suited for that purpose. 
 - this will allow power users to get right to the data downloads, and novice users, or people who are more interested in a guided experience to "explore" the data more visually. It's not a hard wall, users will be able to go back and forth, but hopefully find the entry point more tailored to what they want.
 - These feature pages would be
      - a) organized and bundled around familiar concepts (rather than the shape of the data) and 
      - b) provide a high level overview of that data.
 - We are considering two different options for approaches to these pages at the moment:
      - written, narrative explainers 
      - dashboards

While we're still working through *exactly* how to approach those feature pages, you can see the sort of questions that could guide that introduction in the mockup. 

2. On the data set index side, the structure would more closely mirror the existing categories, with the introduction of child pages. 
- I've been working off of Noah's [existing spreadsheet](https://docs.google.com/a/gsa.gov/spreadsheets/d/1Taw16OJBprxgoKY78DUrwTGMVZX75RCE34af2CFihc0/edit?usp=sharing) of columns, filters, and details to build a [new, more robust spreadsheet](https://docs.google.com/a/gsa.gov/spreadsheets/d/1-LjKQy3dOJI9FJmrhNEfgsr-uD7HzzH0qf1zpo3azTE/edit?usp=sharing) that specificies the language of the filters and how they should be grouped/subgrouped. 
      - I look forward to @emileighoutlaw 's common sense language to finish wrangling these filters, and help making sure that the language is consistent from one filter category to another
      - We really really need @LindsayYoung and @jmcarp 's data perspective on a) if this is correct, b) if this is possible, and c) if this is missing things, or has overstated things. Consider this a working space.



(Orange outlines are areas of uncertainty, on the data set index side, I could especially use @LindsayYoung / @jmcarp  's expertise to whether or not we need these, and on the featurette side, I could use @onezerojeremy 's aid in refining)

___

My brain is a little melted at the moment, and this could likely do with some synchronous working sessions. Excited and exhausted at the same time to hear what you all think!

Nearest steps forward from here:
- [ ] Finalize spreadsheet of filters applied and data columns
 - [ ] Review with 18F team 
 - [ ] Review with FEC
- [ ] Design how users navigate between the different categories of browse pages (could be done in sync with finalizing the filters)
- [ ] Separately, decide on structure of the featurette side
- [ ] Design questions that guide each featurette

**Comment by jenniferthibault** [comment]
I should have mentioned, this does _not_ take into account the partitioning in https://github.com/18F/openFEC-web-app/issues/1023, which I'd like to chat about to maek sure I understand what some options could be.

**Comment by emileighoutlaw** [comment]
This is amazing work, Jen, Noah, and Jeremy! Looking at the spreadsheet now.

I'll let @LindsayYoung weigh in, but my understanding of IE reports is that they *are* Form 5. Am I wrong? I'll keep posting comments here and in the spreadsheet, as I make my way through.

Thanks so much for the common-sense explainer and introduction to all this, Jen <3

**Comment by LindsayYoung** [comment]
For the filings, we have all the reports, notices, RAFI's etc. Tell me if you think something is missing.

Independent expenditures are a type of spending and can be disclosed in different places. The forms that a committee fills out are dependent on what kind of entity they are. If you are a PAC doing independent expenditures, you are going to report that on a F3x, if you are a independent expenditure only committee, you are going to report that on the F5. There will also be 24 and 48 hour notices, which are preliminary reports of the independent expenditure spending close to an election.

Partitioning will mean for the really big tables you can query over 2 or 4 years at a time. We will make it as big of a window as possible while still being performant.

**Comment by emileighoutlaw** [comment]
Thanks, Lindsay! I take that to mean that we do have data for Form 6, Form 8, and Form 12? Should they be included under the "All filings" list in Jen's mockup?

A couple more IE questions:

1. Since independent expenditures are reported on several forms, would the data box called `IE reports` thus include information from Form 3X, Form 5, and so on (i.e., essentially grouping information drawn from the forms already listed under `All filings`)? 

2. Will "Independent expenditures" in the `All other spending` section be the same data as what's in the "IE reports" in "All filings" ?

**Comment by LindsayYoung** [comment]
Looking at filings is not the best way to find IEs. We are not showing IE totals on the filings browse view at all. On the election and committee pages, there are summaries of the IE spending. For the IE browse view, it is going to be data on the transaction level. 

I think 1. would be confusing because while F3X can have IEs most of them don't. If people are interested in IEs they should look at the IE transactions browse view and not the filings view. 

We don't have anything on the API for seeing and filtering the different data types together so we want to make sure we really want to do with some user testing of that grouping before doing the additional work. I am not sure those kinds of spending make sense together since it might be hard to describe how they are different things.

**Comment by jenniferthibault** [comment]
Based on a week of great workshopping with the team, here is the latest information architecture for the data side, 

![data side ia copy 2](https://cloud.githubusercontent.com/assets/11636908/12492928/b91b53d0-c050-11e5-96ba-9dcaf55ba5ff.png)


For a better feel of how this navigation could play out , poke around [this (still WIP) InVision interactive prototype.](https://invis.io/XD5P2IG89) If you find a link that isn't linked, return to the first page, which has the most comprehensive interactions installed. 

I'll follow up with a brief intro-to-this mockup, but it may benefit from 1-on-1 walkthroughs, and I'd like to demo this at tomorrow's Sprint check in, then have a review with the FEC team at a follow-up meeting.

**Comment by noahmanger** [comment]
This is looking really awesome and interesting. The main question or concern I have is how exactly the "All totaled receipts" / "all totaled disbursements" pages work. Is each row in those tables a report? Or is it a committee entry? I think we do want a way for people to view the financial reports with summary data filed by committees. I see the value in breaking out of the "filing" model, but I want to make sure we're not losing anything.

Also, RFAIs under "Committees" feels just a little weird, but I'm not sure where I'd put it otherwise.

**Comment by jenniferthibault** [comment]
We have some ongoing comments in the filter spreadsheet about this—mostly similar open questions. I'd love to sort this one out more concretely before we go into tomorrow's meeting and demo it. - or, change it somehow. @LindsayYoung I'm going to timebox it to 30 minutes, and calendar us for tomorrow morning.

**Comment by emileighoutlaw** [comment]
I'm going to jump into that meeting, if y'all don't mind. I promise not to sidetrack, but I definitely want to be a fly on the wall.

**Comment by jenniferthibault** [comment]
You're always welcome to join, @emileighoutlaw !

**Comment by emileighoutlaw** [comment]
I think the InVision prototype looks fantastic! I have language thoughts, but I think it's a little too early for that so I'll stick to bigger/more structural notes right now. :+1:? 

## Learn how money is raised and spent ...
- I think the third option is more `Search and download advanced data tables` (rather than view)

## Explore more activity ...
This is the featurette section for novice users, right? This wouldn't be comprehensive (and tell me if it's an outrageous idea), but I *think* it would be most clear to readers and meet their needs if the options were:

> - Candidates and their committees
- PACs*** 
- Individual contributors
- Corporations and labor organizations
- Elections





***I know this wouldn't be comprehensive of all outside committees, but my understanding is that the vast majority of folks are interested in PACs and Super PACs

**Comment by emileighoutlaw** [comment]
p.s. I've been thinking about the language on the `Advanced data tables` page. Been jamming on that here, if anyone wants to take a look:

https://docs.google.com/a/gsa.gov/document/d/1SIoewqAtvjG4qDRLVhqBin8b3EgwDuDlgkf8eF-9cxQ/edit?usp=sharing

**Comment by jenniferthibault** [comment]
Some changes based on chatting with Lindsay this morning, and marking a spot for an area she brought up earlier that we should have tables on, Elections.

The Totaled Receipts/Disbursements didn't make much sense (I was interpreting incorrectly) so they've been removed. Added in in place of them is Financial Report Summary data for committees, which will be very similar to the FEC's existing [2016 Committee Report Summary](http://www.fec.gov/data/CampaignAndCommitteeSummary.do?format=html)  These are marked in orange.

![data side ia copy 2](https://cloud.githubusercontent.com/assets/11636908/12518218/39dcb234-c105-11e5-8188-74086045f5cd.png)


Thank you for kicking off the language and wording review Emileigh! I :heart: `Search and download advanced data tables`, and look forward to the more detailed changes. I'll try to get in what I can into the prototype as fast as I can!

On structure, I totally see the user intention driving the change of "Outside committees" to "PACs", but wonder if we want to exclude other types, or if we want to maybe specify but not limit. Something like "PACs and other outside committees" or... "Outside committees (including PACs and SuperPACs)" in a way that allows it to help users find it within the broader category. I'm concerned that we wouldn't want to do a whole featurette section on JUST PACs, though we'd certainly want that to be one of the detail views.

Question, what was your thoughts behind dropping transactions from the featurettes @emileighoutlaw ?

**Comment by emileighoutlaw** [comment]
I love
> Outside committees
(including PACs and Super PACs)


Great thought! I originally wasn't sure how much even *within* the featurette we want to talk about Joint Fundraising Committees and Party Committees. But there is an appetite for that (and we think there's valuable info in there)? 

I think I'm not opposed to including transactions, but I think it might need to be more specific language or more specific content (or both). From the  `Transactions` section of `Advanced data table` we've pulled out `Individual contributors` already into our list. What else do we think we want to tease out for novice users?

**Comment by noahmanger** [comment]
Alright! After lots of painstaking work, I think we have a really good outline for all of the new browse pages. Still subject to word-smithing and potentially moving pages around based on more research and testing, but this identifies the main **categories** for the datatable pages, as well as each page within them. 

![browse ia](https://cloud.githubusercontent.com/assets/1696495/13023822/83430020-d1a1-11e5-8e69-30fb13b7d52d.png)


Notably, after our last session, we agreed that "e-Filings" doesn't need to be it's own category, or really even exist as a separate page. Instead, we want to explore having it as an option on all pages to toggle between raw eFilings data and "processed data". 

This is a separate story, though, so I'll make a new story card for it. 

Closing this.
