### ISSUE TITLE
Wireframe interface for parent-child browse pages

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1004]
Related to https://github.com/18F/openFEC-web-app/issues/1003 , let's start wireframing options for how navigation between different levels of browse pages could work. This includes:
- Do browse categories have their own sub-landing pages?
- How do you go from a "All committees" browse page to more specific child pages?
- What happens with the data landing page? With the main home page?

**Comment by jenniferthibault** [comment]
A *really* preliminary first look at how this could be broken out between child and parent views, based on sketching with @noahmanger @onezerojeremy and @jwchumley :

**DESKTOP**
**Parent:** Would allow users to navigate between different data categories (Candidate/Committee/Receipts/Disbursements/Filings), and select a child view of the data. 
![committee-browse-landing](https://cloud.githubusercontent.com/assets/11636908/11908452/501407f8-a5aa-11e5-8038-0af76de38afb.png)

**Child** Would allow users to navigate between different child views of the data, users could use the main nav for navigating between data categories, or we'd provide some additional way to do that. This would also introduce space for a data visualization (which would probably be different depending on the category) followed by the data tables. 
![committee-browse-child](https://cloud.githubusercontent.com/assets/11636908/11908455/548b7582-a5aa-11e5-8ec4-3ae232b8778d.png)

**MOBILE**
**Parent**
![committee-browse-landing-mobile](https://cloud.githubusercontent.com/assets/11636908/11908460/58957858-a5aa-11e5-9743-8f8c0d9bc0af.png)

**Child**
![committee-browse-child-mobile](https://cloud.githubusercontent.com/assets/11636908/11908464/5e2619ee-a5aa-11e5-98b5-05feccf2ff2e.png)

**Comment by noahmanger** [comment]
Yaaaay. A few thoughts:
- It feels a little like the "Browse data for:" bar breaks the pattern slightly of how we've been using the breadcrumb bar. We don't usualyl show other sibling pages. I'm not opposed to it, but we should square that circle. (Is that the phrase?)
- Really interested in the potential for data viz on the sub-pages. I'd also be interested in seeing how it might work as a toggle view instead of all on the same page (partly a concern for load times)
- On the main page, I wonder what else we could do on this. Things like: blurbs about what each of the child views are, top-level stats about things, or any other story telling or visualization.

Lookin good!

**Comment by jwchumley** [comment]
I think on the browse committee data section we need some delineation between those options that apply to all committees like the overview and financial data and maybe an all filings option, and those that are specialty sets like three pac options.

**Comment by jenniferthibault** [comment]
I'm throwing a ton of ideas around, and collecting them [on InVision here](https://invis.io/EU5GFOCKY). Haven't detailed out thoughts behind it yet, and I think I have a few more things to work out so hold off on feedback for now. (Ignore reg/reporting stuff that's in the same InVision link)

**Comment by noahmanger** [comment]
Closing this in favor of https://github.com/18F/openFEC-web-app/issues/1003 which has the more recent discussion and links to mocks.
