### ISSUE TITLE
So that users understand what's happening, make the behind-the-scenes limits and interactions of the data download more apparent.

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC-web-app#1013]
From internal pre-release testing:
Make the behind-the-scenes limits and interactions of the data download more apparent. For example:
- We cap at five downloads at the same time
- If you export a query that’s already in your downloads bar, it’s ignored

Steps to completion:
- [x] @jenniferthibault to mock up design and placement
- [ ] @emileighoutlaw to wordsmith
 
Thanks for raising this @patphongs & @jmcarp for the catch.

**Comment by jenniferthibault** [comment]
These are two options for how we could introduce these alerts, but I'm curious to see if @noahmanger has other ideas. I've worked these into the latest complete mockups with the filter tags, even though those haven't been implemented yet.

**1: sliding "drawer" above the downloads bar**
pro: it feels nicer, and could have a nice sliding interaction
con: it feels like the message is far from the action
![waiting copy 2](https://cloud.githubusercontent.com/assets/11636908/12043831/f6193178-ae56-11e5-9157-9e05826caf72.png)

**2: tooltip**
pro:  keeps the message close to the action
con: feels kind of cramped and odd
![waiting copy 3](https://cloud.githubusercontent.com/assets/11636908/12043854/3999c354-ae57-11e5-8091-e4070a37f017.png)


These are both for the download cap, here's basic text for the duplicate download. (I'm hoping that by the "hold up pardner" you can tell that this is @emileighoutlaw 's domain, not mine, and neither is a serious recommendation :) )

![screen shot 2015-12-29 at 6 05 42 pm](https://cloud.githubusercontent.com/assets/11636908/12043883/776e9c72-ae57-11e5-819e-4a9546e96496.png)

**Comment by noahmanger** [comment]
Aw, I really like the "hold up, pardner" ;)

I'd vote for the tooltip, as it's the most consistent between this and the way we implement the export cap. In both cases, we're disabling the export button, but for different reasons. I would just make it look the same way as that tooltip looks, so not having it have the notification style inside a tooltip, but instead just text inside a tooltip.

**Comment by jenniferthibault** [comment]
Heh. I like that—here's what it could look like 
![waiting copy 4](https://cloud.githubusercontent.com/assets/11636908/12052729/ced49d30-aedf-11e5-8ff2-d6e2ca55b036.png)

**Comment by emileighoutlaw** [comment]
Second that "hold up pardner" is *awesome*, and I wish we could use it. The placeholder text touches on some good things, and I have greedily borrowed from it. :)

> We limit each user to 5 exports at a time— this keeps things running smoothly. 

(simplest, most succinct option, I think.)

> Each user is limited to 5 exports at a time. This helps us keep things running smoothly.

(passive voice, but in this case it might make our role sound less harsh. "you are limited" is different than "we limit you.")


**Note 1:** I purposefully left off anything about `wait for one to finish before requesting another`. *To me* this is clear from the first sentence alone. But that doesn't mean it will be clear to most people. I'm curious to hear if anyone (particularly @onezerojeremy) thinks this is an important thing to express explicitly.

**Note 2:** We could easily add a `Thanks for your patience` to the end of any message, if we think that would engender patience among users (although I also know that thanking people for patience can often have the opposite effect).

**A question** (just for my understanding): if the user gets this error and then clicks the `x` button by one of their exports, will that clear a space for another export?

**Comment by onezerojeremy** [comment]
>A question (just for my understanding): if the user gets this error and then clicks the x button by one of their exports, will that clear a space for another export?
a question for @jmcarp, I think, but my guess is it will not 

> I purposefully left off anything about wait for one to finish before requesting another
seems like reasonable reasoning to me

In testing last week, people were a little confused about the downloads contextual overlay: mainly they thought that the export processing bar was indicating that the file was downloading not exporting; that it was automatically downloading upon clicking export. I've seen this before in earlier testing, so I think it's worth noting here. This has less to do with the limit, so let me know if I should move it elsewhere. 

The other thing I'm thinking about is, I think, the size of the exports you're requesting. I'd rather de-incentivize folks for downloading one monster download just under the limit, rather than 10 smallish downloads.

**Comment by noahmanger** [comment]
Yes, when they click the "x" they'll be able to add a new download in place.

**Comment by noahmanger** [comment]
@emileighoutlaw how does this work for the tooltip on Receipts and Disbursements, where the export button will be disabled with a tooltip for the time being:

> Data exports for this page are coming soon.

**Comment by jenniferthibault** [comment]
@emileighoutlaw - on last thing. It was easy to glance over, but do you have a rewrite for the second tooltip that shows up if a user is trying to export a data set that's already exporting?

Right now it's 
> Hold up pardner, that data set is already exporting. Use the filters to select a different batch.

**Comment by emileighoutlaw** [comment]
How about:

> You're already exporting this data set.

Yes to Noah's:
> Data exports for this page are coming soon.


And finally (to make a decision):
> Each user is limited to 5 exports at a time. This helps us keep things running smoothly.

**Comment by noahmanger** [comment]
For both the "You've already requested 5 exports" and "You've already requested this export", should the export button be disabled? I'm thinking yes, but then that means that every time you request an export it will be disabled until you change the filters (which is maybe correct, just checking).

**Comment by emileighoutlaw** [comment]
I think that makes sense to me!

**Comment by jenniferthibault** [comment]
Conceptually it seems just a teeny tiny bit odd, but maybe it won't feel that way when it's implemented. Worth moving forward with for now, but observing users on this would be helpful in the future to gut-check.

**Comment by noahmanger** [comment]
Ok, so I implemented a version of the "You're already exporting this data" that only disables the export button and shows the tooltip when you click on the export button for a query that's already pending. Does that work? We could ship that and then refine down the road.

**Comment by emileighoutlaw** [comment]
To me that sounds good. I'd love to know more about Jen's thoughts on this when we aren't under the rush of a release day. :)

**Comment by jenniferthibault** [comment]
That works !! Thanks for the hustle @noahmanger  & @emileighoutlaw

**Comment by noahmanger** [comment]
We implemented this! Great idea. This really makes the whole interaction feel better.
