### ISSUE TITLE
Export Feature: Mismatch between exported CSV and Manifest Records

### ISSUE THREAD

**Issue by patphongs** [18F/openFEC-web-app#1014]
The results from the exported CSV and the # of records shown inside of the filter page and manifest.txt do not match. 

For example, when exporting all committee records, the number of records shown on the manifest.txt and filter page is 54,214. However, the number of rows in the exported CSV is 54,736 excluding the header row. The assumption is that the # of rows inside of the CSV file should equal the number of records in the manifest and filter page.

https://fec-stage-proxy.18f.gov/data/committees/

**Comment by PaulClark2** [comment]
See https://github.com/18F/openFEC/issues/1430 for more details

**Comment by noahmanger** [comment]
Closing this in favor of #1430
