### ISSUE TITLE
Bug: On wide screens, sections collapse on committee pages disbursement tabs

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC-web-app#1016]
Small styling glitch, I'm guessing we either need to make a new section, look at the existing open/close HTML to make sure things are closed at the right point, or adjust a breakpoint:

https://beta.fec.gov/data/committee/C00000935/?tab=disbursements
![screen shot 2016-01-06 at 4 30 52 pm](https://cloud.githubusercontent.com/assets/11636908/12155497/5f0b3b08-b493-11e5-8406-d3b189fe6667.png)

The "Disbursements by recipient" text should be the title of the table, and in its own section line.

Looks ok on smaller screens:
![screen shot 2016-01-06 at 4 36 16 pm](https://cloud.githubusercontent.com/assets/11636908/12155540/ae024bde-b493-11e5-8120-12d0ae00b56d.png)

**Comment by noahmanger** [comment]
Oh weird. Well, those two tables shouldn't even be showing up at the same time. When you toggle between them, it shows up correctly...looking into it.

**Comment by noahmanger** [comment]
Ah, found it. Dumb mistake. Thanks for catching!
