### ISSUE TITLE
Disable export on empty table

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC-web-app#1019]
The export table button should be disabled, and an appropriate tooltip displayed, when the table is empty. This will be quick to implement--just need language for the tooltip.

cc @emileighoutlaw @jenniferthibault

**Comment by emileighoutlaw** [comment]
Trying to get a good solution *tout suite*. What do y'all think of:

> This table has no data to export.

**Comment by jenniferthibault** [comment]
This works for me, but I can only think of one scenario in which this message would happen:

- When a user has applied filters that return no data matching their search parameters.

Are there others that we should plan for @jmcarp @noahmanger ?

**Comment by jmcarp** [comment]
@jenniferthibault yep, that's the only scenario when we'd get no data at the moment. The only other scenario that comes to mind is if we ever in the future allow users to export tables from, e.g., election pages--which don't have (explicit) filters but often have tables with no data.

**Comment by emileighoutlaw** [comment]
I did wonder if there was a need to be more explicit and add something like `Remove filters or change search parameters`. My thinking was that less explanation might actually be more clear (because the tooltip will be easier to read and absorb quickly). 

Open to adding a second line if we think it'll be helpful though!

**Comment by jenniferthibault** [comment]
Personally, I like the helpful tip. I think the number of people who actually see this tooltip though will be very small. If there's zero results, and the button is deactivated, that's a pretty strong cue.

Your call, @emileighoutlaw !

**Comment by emileighoutlaw** [comment]
Yeah, there does seem to be something a little curt about just saying "This table has no data to export." How about:

> This table has no data to export— try removing filters or changing your search.

?

**Comment by jenniferthibault** [comment]
:+1: :+1:
