### ISSUE TITLE
missing support/oppose on the independent expenditures 

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC-web-app#1021]
I am not seeing support/oppose on the independent expenditures https://beta.fec.gov/data/elections/president/2016/?tab=spending

**Comment by jmcarp** [comment]
@noahmanger noticed this yesterday. It's an interesting bug, since the column does show up for the 2012 election. We verified that this wasn't introduced by the latest release and went ahead with the deploy, but we do need to figure this one out.

**Comment by noahmanger** [comment]
Yeah it's really weird. The tables display correctly on the candidate and committee pages, and the data is in the response for the 2016 election. :head desk:

**Comment by noahmanger** [comment]
This is working now. Any idea what changed? Was it just a data hiccup?

**Comment by jmcarp** [comment]
Not sure about this--we haven't pushed code to production since this issue was filed, and as far as I could tell, we were getting the expected data all along. Other than the nightly data updates, I'm not sure what else could have changed here.

**Comment by noahmanger** [comment]
Resolved a long time ago.
