### ISSUE TITLE
Implement redesigned typeahead filters

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1022]
**[Story](https://18f.storiesonboard.com/m/fec/!card/0IUxlAq1iQGHnDnTzAVHwQ):** So that users can easily filter to the candidates they're looking for, improve and implement autocomplete filters.

After [designs](https://github.com/18F/openFEC-web-app/issues/982) are completed, update the typeahead filters.

Dependency: https://github.com/18F/openFEC-web-app/issues/982

**Comment by noahmanger** [comment]
Small thing to include in here. The `.tt-hint` input needs to have `tabindex=-1` set so that it doesn't capture focus when tabbing through filters. https://github.com/18F/openFEC-web-app/issues/958

**Comment by noahmanger** [comment]
Should we also include the multiple values issue with this as well? https://github.com/18F/fec-style/issues/219

**Comment by jmcarp** [comment]
Yes, I have a (kind of lame) fix for 18F/fec-style#219 included in the work in progress patch--you can't add the same value twice, although the option still shows up in the typeahead results. I can look into a nicer fix as part of this task.
