### ISSUE TITLE
Bug: Overflow events don't expand on calendar

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/openFEC-web-app#1033]
When a calendar dates has `+ more events`, you can click to expand and see the events. But you can't subscribe to or get additional information about them, when they pop up.

![moreevents](https://cloud.githubusercontent.com/assets/10552702/12337267/00dd6f16-bad7-11e5-8955-7bfb20fca9f9.gif)

**Comment by emileighoutlaw** [comment]
@jmcarp: this is one I'd love to address for usability testing, if we can.

**Comment by noahmanger** [comment]
This looks to be resolved by changing the way that overflow events are rendered.
