### ISSUE TITLE
Bug: deselecting calendar filters

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/openFEC-web-app#1034]
Before usability sessions today, we noticed a couple adding and removing filters.

1. You can close out of the short filters by clicking anywhere on the box (not just the X). Is that the intended functionality? (It's a cursor hover over the text, not a pointer)
2. Some filters won't close once opened. And if you check and uncheck them in the side nav, they appear multiple times. (I originally thought this was just with long-text boxes, like independent expenditures. But it's an issue with open meetings too.)

![filters](https://cloud.githubusercontent.com/assets/10552702/12337375/aeb64a18-bad7-11e5-9b7b-cda2b0854f7d.gif)

Open meeting filter:
![openmeeting](https://cloud.githubusercontent.com/assets/10552702/12337483/54db7332-bad8-11e5-839a-5f147824d430.gif)

**Comment by jmcarp** [comment]
1. Not sure--that's a question for @noahmanger.
2. This should be fixed now--check out https://fec-proxy.18f.gov/calendar/.

**Comment by emileighoutlaw** [comment]
:+1:

**Comment by noahmanger** [comment]
Ah, I noticed this in the `styling-calendar-patch` but neglected to comment on it. Josh's refactor to simplify the code switched from listening for clicks on just the remove button to [listening for clicks on the entire tag](https://github.com/18F/fec-style/commit/431e6beb6d0efb7a5487e4d7ee0c8d75e25af201#diff-88b30edb2887f4b686dd1d93063060b9R39). I'd prefer to go back to clicking on the X only.

**Comment by jmcarp** [comment]
@noahmanger ack, meant to preserve the original behavior in that refactor. Pushed a fix to my open PR against `styling-calendar` at https://github.com/jmcarp/fec-style/commit/bd42ec9d404b87f20681415d1b58d142c07999c4.
