### ISSUE TITLE
Bug: Event details around edges cut off on calendar 

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC-web-app#1037]
On month view: On days at the bottom edge of the calendar, event details are cut off when opened. 

<img width="958" alt="screen shot 2016-01-19 at 10 02 25 pm" src="https://cloud.githubusercontent.com/assets/11636908/12438832/a1ac40fa-bef8-11e5-99b6-9954035a51e7.png">
<img width="974" alt="screen shot 2016-01-19 at 10 02 42 pm" src="https://cloud.githubusercontent.com/assets/11636908/12438833/a1af6d5c-bef8-11e5-97a9-5e21f3763af5.png">

On days at the right hand edge of the month view calendar, the event detail panel is squooshed into one column. At least it isn't cut off, as above! Ideally, (if possible) the tooltip should shift to accommodate the day's placement. For example, if the day falls at the far right of the calendar, the body of the tooltip should remain the same size, but shift left.

<img width="473" alt="screen shot 2016-01-19 at 10 03 05 pm" src="https://cloud.githubusercontent.com/assets/11636908/12438835/a4abb6b4-bef8-11e5-9871-3bde49614052.png">

**Comment by noahmanger** [comment]
Resolved in upcoming PR.
