### ISSUE TITLE
Bug: Weekly view calendar controls not working

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC-web-app#1038]
When I change the calendar view from monthly to weekly, it seems that all functionality and controls in the calendar stop working, (or responding to clicks). 

![fec-calendar](https://cloud.githubusercontent.com/assets/11636908/12438987/e3bcb096-bef9-11e5-88b6-21b9cb35583d.gif)

I'm on Chrome Version 47.0.2526.111

**Comment by noahmanger** [comment]
Duplicate of https://github.com/18F/fec-style/issues/224
