### ISSUE TITLE
To make functionality more universal between grid and list views, add "add to calendar" ability from list view

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC-web-app#1040]
Currently a user can't add a calendar event to their own calendar from the quarterly list view, and must return to the monthly grid view in order to do so. Users should be able to access the same functionality from grid and list views. h/t Josh for the common sense detail here :mag: 

- [x] @jenniferthibault to design
- [x] @jmcarp to implement

**Comment by jenniferthibault** [comment]
I believe I've found a logical place for this, and like the idea of the abbreviated icon. The one thing I can't decide is if it's weird to have the dropdown come out of the opposite corner from the arrow. 

For example, on the left is what I would instinctively shorten the button to without text. Icon on the left, arrow on the right. But because of it's placement on the page, the dropdown would be anchored to the left corner. Is that weird enough that we want to reverse it here, and use the right option with the arrow and anchor on the left side?

<img width="431" alt="screen shot 2016-01-21 at 5 47 33 pm" src="https://cloud.githubusercontent.com/assets/11636908/12497011/3c20fcf6-c067-11e5-93d8-578b5a2f25e7.png">


I've mocked up both designs in context below. Thoughts @noahmanger ? 

![calendar_list](https://cloud.githubusercontent.com/assets/11636908/12496956/ec82da20-c066-11e5-91c5-5c038dcd674f.png)

When looking closer at this page, I also thought of an enhancement that we may want to keep in mind: the "Sort by: event type  |  date" that appears in the upper left of the list, in case users want to view a purely chronological list of all events. I don't have indication from usability testing, just a lingering hunch. cc @emileighoutlaw

**Comment by emileighoutlaw** [comment]
I think that's a great hunch! We haven't seen anyone ask for that specific functionality yet, but we also haven't asked folks to navigate through a list view with a lot of different event types, either. 

And I like "Sort by: Event type | Date" as the language :)

**Comment by jmcarp** [comment]
There's a rough implementation of list view exporting on dev now. As usual, it works but doesn't look quite right--should be close enough for @noahmanger to clean up.

I would guess that extra sort options on the list view would be a separate issue. It shouldn't take much time to implement. But for the sake of argument (which I enjoy), I wonder how much value this adds--when is it useful to collapse events across categories? Anyway, let's discuss in another issue.

**Comment by jenniferthibault** [comment]
Thanks @jmcarp - good call on the new issue. I wasn't saying we should implement based on my hunch, but just that it was an option to consider if we see behavior around it. Moving that to a new issue for discussion next up.

Transferring this to @noahmanger for styling. 
Verdict on the arrow side: since it's a left-screen-side button, let's have the dropdown arrow and the menu be anchored to the left corner. I showed the two to some folks on the design team, and that was their instinct for how it should behave as well.
<img width="178" alt="screen shot 2016-01-25 at 9 41 11 am" src="https://cloud.githubusercontent.com/assets/11636908/12553881/cea4d1fa-c347-11e5-9288-2fe538641e5c.png">

**Comment by noahmanger** [comment]
Small point on the arrow: on the other dropdowns, we anchor the dropdown panel to the left side of the button, but the arrow is still on the right. Do you want to change this there too?

**Comment by jenniferthibault** [comment]
Can we? That would be awesome.

**Comment by noahmanger** [comment]
This is done.
