### ISSUE TITLE
Bug: Many calendar times are set to midnight

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/openFEC-web-app#1041]
This isn't critical to usability testing, but when I was looking at the calendar this morning, I noticed many of the event times are defaulting to midnight (12 a.m.)

![timing](https://cloud.githubusercontent.com/assets/10552702/12451541/0a063c6e-bf58-11e5-8afa-7ab85eba648b.gif)

**Comment by jmcarp** [comment]
Thanks for flagging this--we were showing full start times for all-day events, which are always midnight. This is fixed in https://github.com/jmcarp/fec-cms/commit/f05ea4c09ebe7aa013a85aa458e9cb5087b11e75 so that we omit the hour and minute of start times for all-day events.
