### ISSUE TITLE
On calendar: order time intervals from smallest to largest

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC-web-app#1042]
The current time interval order is largest --> smallest:

![screen shot 2016-01-21 at 5 00 09 pm](https://cloud.githubusercontent.com/assets/11636908/12495942/a89bc2dc-c060-11e5-842a-dd49f7b38e9e.png)

Let's reverse that to smallest --> largest in order to fit a more chronologically expanding sense of time.
**Week | Month | Quarter**

**Comment by jmcarp** [comment]
Done in https://github.com/jmcarp/fec-cms/commit/b7784e50b117a831b2b0dc727c098483e73d0eea.
