### ISSUE TITLE
Update methodology disclaimer on disbursement aggregates

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1044]
I'm pretty sure this language in the disclaimer is innaccurate, and actually these aggregates are based on combining certain category codes, correct?

<img width="983" alt="screen shot 2016-01-22 at 2 53 30 pm" src="https://cloud.githubusercontent.com/assets/1696495/12525274/0f66dc24-c118-11e5-8199-a4c47106293d.png">

**Comment by jmcarp** [comment]
We use some codes and lots of text matching:

https://github.com/18F/openFEC/blob/develop/data/sql_incremental_aggregates/prepare_schedule_b_aggregate_purpose.sql#L1-L21

I don't know where the codes come from--we're using the `disb_tp` column.

**Comment by emileighoutlaw** [comment]
If it's both codes and free text input, I think the simplest clarification would be to say "these totals are summed based, in part...." 

Suggested tweak:
>These totals are calculated, in part, using free-text input as reported by this committee. Variations in spelling or abbreviation can produce multiple totals for the same category. For the most complete information, view the [list of itemized transactions](link).

**Comment by LindsayYoung** [comment]
Slightly off topic, @noahmanger the $0 is showing as a full bar, is that captured somewhere?

**Comment by noahmanger** [comment]
Oh wow I totally missed that. Well I wonder why $0 rows are even showing up?
