### ISSUE TITLE
Novice user discovery spike 

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1045]
In order to help us better understand the needs of novice users when designing exploratory data pages, we need to undertake a small discovery spike. 

@brethauer @jenniferthibault and @emileighoutlaw Let's talk on Monday to flesh out the details. 

(cc @onezerojeremy just to stay informed, but I don't think you need to worry about this).

**Comment by jenniferthibault** [comment]
:tada: :tada:

**Comment by emileighoutlaw** [comment]
# So excited

**Comment by brethauer** [comment]
Hey team here is my brief writeup/overview on the plan: Please comment if you feel so inclined!
https://docs.google.com/document/d/1n5CN0eR8z8Cy5xTvDQL0Qgpo-XjqFYmpEq9qiIS8G6A/edit

**Comment by noahmanger** [comment]
Might be good to work in some usability testing around their [graphic tools](http://fec.gov/portal/graphic_presentation.shtml). I can explain more on Monday, but this is something we talked about doing and I think could get us some interesting data.

**Comment by brethauer** [comment]
Mid-research synthesis doc:
https://docs.google.com/document/d/1hsSbfwUFUqodp-hR3rtIFiFXwsisCs-VLv8mkcm_bo4/edit#

**Comment by brethauer** [comment]
Themes and research questions we want to focus in on for the remaining sprint:

**Theme: What inspires story ideas?**
- How can we get people excited about the potential of the data?
- Explore idea: example questions on the dashboard along with how they might be answered

**Theme: Building up enough knowledge and being able to self-guide**
- What are the most common stumbling blocks in trying to use FEC data?
- What is easiest to mess up?  Hardest to understand?
- Most common types of confusion people have when trying to understand.

**Theme: What are (and how can we convey) the "meat and potatoes" data/info chunks that most stories are built on?**
- Dig into what these areas are: Regional, topic, others?
- Learn what a "Campaign Finance 101" for a journalist might include
 (what do you wish you knew when you started? what steps do you always do / come back to when looking at data?)

Story text analysis: What are the most common types of data points and analyses used and done in stories that use campaign finance data.  
Potentially look at twitter and reddit questions around the topic as sources.

**Comment by jenniferthibault** [comment]
I did some thinking about how this fits in to the bigger picture of our design process for the dashboard side: take a peek at the Dashboard section [here] and let me know how we could make that better. (https://docs.google.com/a/gsa.gov/document/d/1OouA9iN10C420O2rKLkxQptQfcb-rSw_uZR4F-tAvk8/edit?usp=sharing) 

I also wanted to rough out the timing for these activities leading up to the workshop with FEC. Loosely, what do you think of this plan as a guideline?
![calendar](https://cloud.githubusercontent.com/assets/11636908/12961787/35cc606c-d010-11e5-9373-763f08f0bca7.png)

**Comment by emileighoutlaw** [comment]
Yes! That timeline looks great to me!
