### ISSUE TITLE
To allow users to sort the event calendar list view by their preference add a "sort by" option

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC-web-app#1047]
This option is subject to findings from usability testing.
An enhancement we could offer to the list view is to enable sorting the list purely by chronological order instead of by event type as it is now.

<img width="762" alt="screen shot 2016-01-25 at 9 45 36 am" src="https://cloud.githubusercontent.com/assets/11636908/12554005/80b7a3d6-c348-11e5-8f4c-42975555a019.png">

Discussion of merits and how much value it adds welcome. h/t @jmcarp , @emileighoutlaw

**Comment by noahmanger** [comment]
This is merged.
