### ISSUE TITLE
Bug: Permalinks don't work with dates

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/openFEC-web-app#1049]
Noticed in usability testing: if you add dates as a data filter, it doesn't permalink:

![permalinks](https://cloud.githubusercontent.com/assets/10552702/12556733/65e36a24-c355-11e5-911a-099448875e82.gif)

**Comment by jmcarp** [comment]
Should be resolved in https://github.com/18F/fec-style/commit/9d5d95a12dda4a3804f36b3995fffc685367c56d.

FWIW, the permalinks and filters were working fine--just needed to update the filter tags.

**Comment by emileighoutlaw** [comment]
Awesome. Thanks for the update @jmcarp :)
