### ISSUE TITLE
Bug: Can't remove dates from sidebar

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/openFEC-web-app#1050]
Noticed in usability: 
1. You can click the radio button to add dates in the sidebar, but you can't un-click it to remove dates.
2. If you remove the date filters from the top bar, the radio button stays "clicked" in the sidebar.

![dates](https://cloud.githubusercontent.com/assets/10552702/12557104/45266bea-c357-11e5-8cfa-1e0deca3a629.gif)

**Comment by noahmanger** [comment]
We removed radio buttons for dates so I'm closing this.
