### ISSUE TITLE
Bernie's senate candidate page 404ing

### ISSUE THREAD

**Issue by leahbannon** [18F/openFEC-web-app#1054]
I went https://beta.fec.gov/data/candidate/S4VT00033/?cycle=2018&election_full=true

from a candidate search for "sanders"

The API seems to have it. S4VT00033

**Comment by noahmanger** [comment]
Ah! Thanks for catching. This is related to this bug https://github.com/18F/openFEC-web-app/issues/1031

I'm going to close this, but move your comment to there.
