### ISSUE TITLE
Filter content and visual design

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/openFEC-web-app#1062]
During our long IE discussion in Slack, I noticed that these two filters are separated by a HR. 

![screen shot 2016-02-02 at 4 55 31 pm](https://cloud.githubusercontent.com/assets/10552702/12765804/53efe688-c9ce-11e5-9a41-38e7920522b6.png)

It seems like there might be a more elegant way to show that these two go together. Just as a jumping off point, maybe:

> Candidate supported or opposed
[ ] Supporting
[ ] Opposing
[ text box ]

What do you think @jenniferthibault? 

https://fec-proxy.18f.gov/data/independent-expenditures/?max_date=01-29-2016

**Comment by jenniferthibault** [comment]
I think that's great. Those are especially the kind of changes I'd like to see made in the [mega filter spreadsheet](https://docs.google.com/a/gsa.gov/spreadsheets/d/1-LjKQy3dOJI9FJmrhNEfgsr-uD7HzzH0qf1zpo3azTE/edit?usp=sharing) before they get mocked up or implemented too!

**Comment by noahmanger** [comment]
+1 . Makes sense, though let's not push that in this release.

**Comment by emileighoutlaw** [comment]
Captured in the mega spreadsheet for future implementation :)

**Comment by noahmanger** [comment]
Since this is included in the master spreadsheet, I'm going to close the issue, as we'll address it as we work through that spreadsheet.
