### ISSUE TITLE
Tabs receipts, disbursements, and between committees missing data on committee pages

### ISSUE THREAD

**Issue by evankroske** [18F/openFEC-web-app#1069]
I've checked [two][1] [committees][2] pages, and both of them now have no data on tab "Receipts from Individuals", "Disbursements", and "Between Committees". The console contains the following interesting errors:

- `XMLHttpRequest cannot load https://api.open.fec.gov/v1/committee/C00575795/     schedules/schedule_b/by_pur…0kTkxxq9JNfIRlrOPorXc60dqOVEs4GE&sort=-             total&per_page=10&page=1&cycle=2016. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://beta.fec.gov' is therefore   not allowed access. The response had HTTP status code 500.`
- `Failed to load resource: the server responded with a status of 500 (Internal    Server Error)
XMLHttpRequest cannot load https://api.open.fec.gov/v1/committee/C00575795/     schedules/schedule_a/by_state/?                                                 api_key=oXyFx4md0kTkxxq9JNfIRlrOPorXc60dqOVEs4GE&cycle=2016&per_page=99. No     'Access-Control-Allow-Origin' header is present on the requested resource.      Origin 'https://beta.fec.gov' is therefore not allowed access. The response had HTTP status code 500.`

[1]: https://beta.fec.gov/data/committee/C00575795/?cycle=2016&tab=disbursements
[2]: https://beta.fec.gov/data/committee/C00580100/?cycle=2016&tab=between-committees

**Comment by evankroske** [comment]
[Looks like the web app's API key was revoked.][1] However, if I try to request the resource with my own API key, I receive a server error (500). (I'm not going to put my API key in a GitHub issue, but I'll share it privately if someone is interested.)

[1]: https://api.open.fec.gov/v1/committee/C00575795/schedules/schedule_a/by_state/?api_key=oXyFx4md0kTkxxq9JNfIRlrOPorXc60dqOVEs4GE&cycle=2016&per_page=99

**Comment by evankroske** [comment]
And the resource is available again. The tabs are working correctly now.

**Comment by evankroske** [comment]
Never mind, I'm still seeing the following error message sometimes:

> API_KEY_UNAUTHORIZED

> The api_key supplied is not authorized to access the given service. Contact us at https://api.open.fec.gov/contact/ for assistance

This looks like an api.data.gov problem.

**Comment by jmcarp** [comment]
Thanks for flagging this, and sorry for the disruption. This looks to be resolved now. For the record, the CORS errors showed up because of an unrelated underlying issue--when we hit a 500, we don't get the usual CORS headers, so we get that additional error. And the 403 is expected if you're hitting that URL from curl or a browser--that API key is only meant to be used through beta.fec.gov.

**Comment by evankroske** [comment]
Yep, that explains why my API key worked and yours didn't. Thanks for looking into this!
