### ISSUE TITLE
Recent filings section treats documents without a receipt date as most recent.

### ISSUE THREAD

**Issue by porta-antiporta** [18F/openFEC-web-app#1071]
On https://beta.fec.gov/data/ in the recent filings section, there are several filings (mostly dating from the 80s from the document name) that are sorted as latest because they don't have a receipt date.  

Given the culprits are pretty dated submissions, no receipt date should probably be sorted somewhere other than as most recent in the list.  The 5 culprits take up half of the available slots.

- Year-end 2011- 	CHANGE FOR THE BETTER	
- Year-end 1981-	UNITED ASSN OF JOURNEYMEN & APPRETICES PLUMBING & PIPEFITTING LOCAL 630 PAC	
- July Quarterly 1982-	NEW MEXICANS FOR BILL RICHARDSON	
- Pre-Primary 1982-	CITIZENS FOR JOHN RARIG	
- September Monthly 1982-	HUMPAC (AKA AMERICAN MEDICORP GOOD G

**Comment by noahmanger** [comment]
Good catch. We lost the "hide null when sorting" functionality somewhere. @jmcarp do you have time to look at this today?
