### ISSUE TITLE
Enhancement: Additional column in filter? 

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/openFEC-web-app#1072]
I was looking at a lot of IE data today, and when more than a few years are selected, they look really long. Would it make sense to split this into two columns? 

<img width="329" alt="screen shot 2016-02-04 at 2 45 49 pm" src="https://cloud.githubusercontent.com/assets/10552702/12827996/492ec506-cb50-11e5-8182-887aa1d6f86a.png">

**Comment by noahmanger** [comment]
I think this will be addressed when we introduce accordions in the filter panel. I'd prefer that option to columns, but am open to columns.
