### ISSUE TITLE
Develop discovery plan for design of data dashboard features

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC-web-app#1076]
In order to understand what users want from the experience of the dashboard/featurette side of the data site, develop a plan for discovery activities. 

Dependencies: https://github.com/18F/openFEC-web-app/issues/1045

**Comment by jenniferthibault** [comment]
[This is the Google document](https://docs.google.com/a/gsa.gov/document/d/1OouA9iN10C420O2rKLkxQptQfcb-rSw_uZR4F-tAvk8/edit?usp=sharing) I've been working in to think about what we need to know before designing out the dashboard/featurette side.

@brethauer & @emileighoutlaw I'd specifically like you to take a look to see how your activities and results from last week's novice interviews cover these areas, or leave gaps that we should pursue this week. Thoughts, comments of all sorts welcome, but that^ specifically needed.

fyi also @noahmanger

**Comment by noahmanger** [comment]
Can we close this, since the plan has been developed and the implementation of that plan is captured in other issues?

**Comment by jenniferthibault** [comment]
Yep: All research is captured in the murally & google doc—moving forward with analyzing common questions in an affinity diagram today http://mur.al/YEK5jlaG
