### ISSUE TITLE
Bug: Stewart Mills (MN House District 8) contributions by state don't display

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/openFEC-web-app#1082]
**url**:  https://beta.fec.gov/data/elections/house/MN/08/2016/

When you view the House candidates in Minnesota District 8:

- View by contribution size looks great! 
- View by contribution state shows nothing for Stewart Mills

### This looks right (by contribution size):
<img width="1056" alt="screen shot 2016-02-08 at 2 44 34 pm" src="https://cloud.githubusercontent.com/assets/10552702/12896971/d2caa616-ce72-11e5-8cf8-612581a0c8e8.png">

### This is not right (by contribution state):
<img width="1071" alt="screen shot 2016-02-08 at 2 44 04 pm" src="https://cloud.githubusercontent.com/assets/10552702/12896980/dd1086cc-ce72-11e5-80cb-0cd95de04f7d.png">

<img width="1077" alt="screen shot 2016-02-08 at 2 44 27 pm" src="https://cloud.githubusercontent.com/assets/10552702/12897040/30ea51e2-ce73-11e5-9218-828c33f2fda2.png">

**Comment by LindsayYoung** [comment]
This is working :)
https://beta.fec.gov/data/elections/house/MN/08/2014/?tab=comparison
![screen shot 2016-03-28 at 5 47 44 pm](https://cloud.githubusercontent.com/assets/4406333/14091329/a957d0c6-f50d-11e5-8d0b-07137339f421.png)
