### ISSUE TITLE
Research: Audit campaign finance content

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/openFEC-web-app#1087]
### Background:
As part of our novice research phase, one of the things we'd like to quantify is "What types of stories are journalists publishing about campaign finance." I'll be leading a small content audit with that we'll capture in a Google Doc (forthcoming).

### What we hope to learn:
- Are there "meat and potatoes" campaign finance stories?
- If so, what?

Knowing this will help us better convey the evergreen “core” concepts or information chunks.

**Comment by emileighoutlaw** [comment]
Related: https://github.com/18F/openFEC-web-app/issues/1045#issuecomment-182079312

**Comment by jenniferthibault** [comment]
Reading back through yesterday's notes, a second point to investigate while you're reading these intro articles is **how and what people explain about campaign finance 101.**

**Comment by emileighoutlaw** [comment]
Capturing information in [Mural.ly](http://mur.al/bZzjED9y)
