### ISSUE TITLE
Research: Audit campaign finance visualizations

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC-web-app#1090]
Using [this doc](https://docs.google.com/spreadsheets/d/1M77EOzvPpDBTHH3jR3GA6vqpD140AYX0wm-0p0a_hGw/edit#gid=0) as a starting point, I'm going to pull together examples of how other sites are presenting campaign finance data as interactive visualizations.  I'll probably make this in Mural.ly 

**Goal:**
- Spot patterns of compelling data viz structures and formats (and spot what's not)
- Spot trends in data analysis (what questions do people ask of the data)
- Get up to speed on what's happening now in campaign finance data viz

**Related:**
- https://github.com/18F/openFEC-web-app/issues/1087

**Comment by jenniferthibault** [comment]
Murally has been started [here](https://app.mural.ly/t/gsa6/m/gsa6/1455123969160)

**Comment by jenniferthibault** [comment]
All research is captured in the murally—moving forward with analyzing common questions in an affinity diagram today http://mur.al/YEK5jlaG

**Comment by evankroske** [comment]
Can you configure your murally to be read-only? It looks like anyone can move around your sticky notes right now.

**Comment by jenniferthibault** [comment]
Thanks for the check on this,  now configured for read-only, and I swapped the link out above. http://mur.al/bVoQNdOw
