### ISSUE TITLE
Add "Number of candidates" and "Candidate share" to EC page

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1101]
Trying to summarize what we've discussed on Slack:

### On /data/electioneering-communications:
- [x] Add columns and details panel rows  for "Number of candidates" and "Candidate share". 
- [x] Add a disclaimer explaining the "Candidate share" calculation

Also:
- We will still keep "Disbursement amount" in the table as well as the filter.
- We will not add a filter for "Candidate share"

### On Candidate / Committee / Election pages:
1. [x] Table aggregates will continue to aggregate based on "Candidate share" (no change required)
2. [x] Add a disclaimer explaining that "Candidate share is a derived calculation

**Comment by ChristianHilland** [comment]
Amy P. and I looked at the EC forms in greater detail. While we don't often receive many questions about ECs these days from the public, there was a need several years ago (and there probably still is) to determine the total amount that that is being spent for or against a particular candidate. The only way for us to do with the available FEC Form was to divide the disbursement cost to a particular vendor by the number of candidates listed.  I agree that we should include a disclaimer on the new page. Currently, we state, "In an effort to help users work with this complicated data, we have divided the reported expenditure equally by the number of candidates named in the report. The resulting dataset provides the user with the reported expenditure amount, the number of reported candidates and the calculated pro rata amount per candidate." Please let me know if you have any questions.

**Comment by emileighoutlaw** [comment]
Okay! This makes complete sense to me! Thanks for taking the time to explain.

Would it be possible to tweak the disclaimer language a little? I'm thinking something like:

> To help users work with this complicated data, we divide each report's _disbursement amount_ by the number of candidates named in that report. The resulting number is listed as the _amount per candidate_.

**Comment by emileighoutlaw** [comment]
In addition to the disclaimer language, this is my attempt to get on the same page with everyone as to what changes we need! :) 

### Table view
For the table view (shown below), we want to show the following filters:
- Disbursement amount
- Number of candidates mentioned
- Amount per candidate

![screen shot 2016-02-16 at 2 52 20 pm](https://cloud.githubusercontent.com/assets/10552702/13089194/892718ea-d4bd-11e5-9592-05dd56d95135.png)

### Filter view
Do we want to include `number of candidates mentioned` and `amount per candidate` in the filter view (shown below)?

By that I mean, do people need to _search_ for `amount per candidate`, or is it just something that they need to see in the resulting table?

![screen shot 2016-02-16 at 2 52 31 pm](https://cloud.githubusercontent.com/assets/10552702/13089076/040169e0-d4bd-11e5-850b-8505a970da7d.png)

**Comment by ChristianHilland** [comment]
I'm tagging @paulclark2 and @apike for their input as well. 

1) I would suggest this disclaimer or similar language:

To help users work with this data, we divide each itemized disbursement amount by the number of federal candidates named in connection with that disbursement. The resulting number is listed as the notional amount per candidate.

2) Filter question: I don't think we should include "amount per candidate" or "number of candidates mentioned" as filter options.

**Comment by apike** [comment]
@ChristianHilland Glad to hear you're interested in my input, but I'm a little out of the loop here. Did you mean to say @apike or perhaps somebody else?

**Comment by ChristianHilland** [comment]
Sorry about that. Thanks for the message.

**Comment by amypike** [comment]
So sorry, Allen (@apike).  He meant me, @amypike.

**Comment by apike** [comment]
No problem, cool project - good luck :)

**Comment by PaulClark2** [comment]
@emileighoutlaw @ChristianHilland @amypike 

1) I think Christian's language is closer to what we are doing.  EC reporting is different from other "other spending" reporting because the filer does not disclose a specific amount for each candidate.   Looking at a EC (Form 9) filing might help.  

http://docquery.fec.gov/pdf/532/12970531532/12970531532.pdf
Page 2 (12970531533) two (2) disbursements four (4) candidates (we divide each disbursement by two (2))

Page 3 (12970531534) two(2) disbursements three (3) candidates  (we divide the first disbursement by one (1) and we divide the second disbursement by two (2)).  

Page 4 (12970531535) one (1) disbursement two (2) candidates (we divide this disbursement by two (2)) 

So were aren't divided the total disbursement amount disclosed on the report by the number of candidates disclosed on the report.  

2) I agree we don't need filters for "amount per candidate" or "number of candidates mentioned."

**Comment by noahmanger** [comment]
Ok, I've added the columns, and included this disclaimer in a tooltip in the details panel like so:

<img width="1085" alt="screen shot 2016-02-16 at 5 31 30 pm" src="https://cloud.githubusercontent.com/assets/1696495/13097100/360dbdf6-d4d3-11e5-82ff-966d0d2cf6c4.png">

I used Christian's language. I think it should be slightly tweaked for the disclaimer on the aggregates, though. Maybe:

> To help users work with this data, we divide each itemized disbursement amount by the number of federal candidates named in connection with that disbursement. The resulting number is listed as the notional amount per candidate. **These subtotals reflect the sum of each this _per candidate_ amount.**

**Comment by noahmanger** [comment]
Also, in the IE aggregate table disclaimer, we explain that the subtotals don't contain 24 and 48 hour reports. Do we want to use the same language (if that's the case)?

**Comment by PaulClark2** [comment]
No, we don't need a disclaimer about 24-hour and 48-hour reports for ECs.  All EC filings are 24-hour notices.  

@ChristianHilland @amypike Can you take a look at the disclaimer language above.

**Comment by PaulClark2** [comment]
@noahmanger We think we should exclude, "These subtotals reflect the sum of each this per candidate amount." from the disclaimer.  In theory if you sum across all the candidate share amounts you should get the total disbursement amount for the EC filing but in practice this isn't always true.  Some filers include disbursements but do not include a candidate or candidates.  In these cases, the disbursement is excluded from the EC set.  

In the details panel, we'd like to change "Amount" to "Amount spent."  Do you thin there is any need for a tool tip for this amount?   

@ChristianHilland @amypike  Did I forget anything?

**Comment by amypike** [comment]
@PaulClark2, you've hit everything we discussed!  Thank you!

**Comment by emileighoutlaw** [comment]
Since the disclaimer is connected to the text "Amount per candidate" would it be possible to say:

> To help users work with this data, we divide each itemized disbursement amount by the number of federal candidates named in connection with that disbursement. The resulting number is listed here.

**Comment by amypike** [comment]
@emileighoutlaw, that sounds great, thank you!  We have one suggestion - "The resulting amount is listed here" rather than "the resulting number is listed here." @PaulClark2 @ChristianHilland

**Comment by emileighoutlaw** [comment]
Sounds good to me! Sound good to others?

> To help users work with this data, we divide each itemized disbursement amount by the number of federal candidates named in connection with that disbursement. The resulting amount is listed here.

**Comment by ChristianHilland** [comment]
Works for me.
