### ISSUE TITLE
Copy edits to Electioneering Communications table

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1102]
- [ ] Change "Committee" to "Spender"
- [ ] Change "Amount" to "Disbursement amount"

**Comment by LindsayYoung** [comment]
And just to confirm-- disbursement amount is just going to be in the panel. the column is going to show candidate share, right?

**Comment by noahmanger** [comment]
It depends where this conversation goes: https://github.com/18F/openFEC-web-app/issues/1101

**Comment by ChristianHilland** [comment]
Yes, I think the Disbursement Amount on that screen should be the per candidate amount. Does that answer your question?

**Comment by emileighoutlaw** [comment]
Hey there. This is a pretty complicated issue, so this is my attempt to get on the same page with everyone as to what changes we need! :) 

### Table view
For the table view (shown below), we want to show the following filters:
- Disbursement amount
- Number of candidates
- Amount per candidate

![screen shot 2016-02-16 at 2 52 20 pm](https://cloud.githubusercontent.com/assets/10552702/13089194/892718ea-d4bd-11e5-9592-05dd56d95135.png)

### Filter view
Do we want to include `number of candidates mentioned` and `amount per candidate` in the filter view (shown below)?

By that I mean, do people need to _search_ for `amount per candidate`, or is it just something that they need to see in the resulting table?

![screen shot 2016-02-16 at 2 52 31 pm](https://cloud.githubusercontent.com/assets/10552702/13089076/040169e0-d4bd-11e5-850b-8505a970da7d.png)

**Comment by noahmanger** [comment]
Sorry, bad idea on my part to have these as two separate issues. I'm closing this in favor of #1101 so that we're not having this conversation in two places.
