### ISSUE TITLE
small bug: can't show full cycle before our data begins

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC-web-app#1107]
Example, the cycle starts in the 70s and full cycle errors, 
https://beta.fec.gov/data/candidate/S2KY00012/?cycle=1982&election_full=true

**Comment by jmcarp** [comment]
This doesn't seem to be related to the fact that the cycle includes years from the 1970s--and it looks like an improvement to the `election_full` flag we're passing to our candidate and committee history endpoints clears up the error on this page. See https://github.com/18F/openFEC/pull/1542.

**Comment by LindsayYoung** [comment]
thanks!
