### ISSUE TITLE
Reverse order of years in election cycle toggles: create chronologically ascending order

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC-web-app#1108]
Currently, the election cycles are ordered:
Full cycle :: most recent two-year period – most distant two-year period
I'm going to call this chronologically descending order. 

Which looks like this:
<img width="476" alt="screen shot 2016-02-25 at 1 56 49 pm" src="https://cloud.githubusercontent.com/assets/11636908/13333121/69e042fa-dbd3-11e5-858e-56730bae2878.png">

and this, as @LindsayYoung pointed out: https://github.com/18F/openFEC-web-app/pull/1073#issuecomment-188921031
![screen shot 2016-02-25 at 1 31 53 pm](https://cloud.githubusercontent.com/assets/4406333/13329836/2b093fdc-dbc4-11e5-9d8b-49dab15586e4.png)

This feels really intuitively wrong to me, (and @LindsayYoung ) and I went hunting to see why we changed it to that, because I remembered designing it in chronologically ascending order. 

It looks like we [initially designed it to be chronologically ascending](https://github.com/18F/FEC/issues/73#issue-111854790) but with the full cycle button on the right. That was changed in [this issue](https://github.com/18F/openFEC-web-app/issues/942#issuecomment-157400328), when we were reacting to user research [here](https://github.com/18F/FEC/issues/73#issuecomment-155252546) saying that users wanted the full cycle button before the list. 

I think it's possible we may have misinterpreted the feedback as "switch the whole order of the list" instead of just "put the full cycle item first." I'd like to build the pattern to put earliest years first, followed incrementally by latest years, in the same model as a traditional timeline. leftmost = early, rightmost = current.

**Comment by noahmanger** [comment]
Ah yep. I think you're right, and I agree. Thanks for doing the archaeology! Let's switch it back.
