### ISSUE TITLE
Restore or drop perfbar

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC-web-app#1120]
We have perfBar installed, but haven't used it since disabling it last fall. My memory is that I ran into problems with gulp at the time, but I'm not sure at this point. In any case, let's either restore perfBar and do something useful with it, like hooking it up to new relic, or drop it altogether. Meanwhile, perfBar seems to have had about one commit in the last year, so it may be dead.

**Comment by noahmanger** [comment]
I'm not familiar at all with it. In the interest of removing cruft, I vote to just drop it.
