### ISSUE TITLE
Define/explain "federal funds" category in candidate data

### ISSUE THREAD

**Issue by AmyKort** [18F/openFEC-web-app#1122]
We're using "Federal Funds" as the label for funds the Department of the Treasury provides to candidates from the Primary Matching Payment Account. We should provide some clarification that here "Federal funds" means public funding for a presidential candidate. In other guidance, the FEC uses the term "federal funds" to refer to funds raised within the limits, prohibitions and reporting requirements of FECA. (For an example of that usage, see: http://www.fec.gov/pages/brochures/locparty.shtml#Federal_Funds

https://beta.fec.gov/data/committee/C00578658/?cycle=2016

**Comment by emileighoutlaw** [comment]
I do think a definition would be helpful. But my first question is, should we call it something other than "federal funds." Just because we're calling it that right now doesn't mean we were right in the first place. I hate to have the same term applied to do different things across the site.

**Comment by emileighoutlaw** [comment]
Maybe we could call it "federal matching funds" if it's always matching funds?

**Comment by AmyKort** [comment]
You could have matching funds for primary candidates, the general election grant from the Presidential Election Campaign Fund for general election candidates, and for prior cycle data there will also be public funding for convention committees. It looks like we refer to these funds as "federal funds" on our forms, so I'm not sure whether we want to change that language in the data. I do think, though, for a novice user (or someone reading our compliance information) the label is potentially confusing--or doesn't provide enough information. So, I'm probably leaning toward some sort of definition, if we decide this is actually a problem that needs solving.

**Comment by emileighoutlaw** [comment]
I wonder if this is more an explanation than a definition, in which case a tooltip could be in order?

@jenniferthibault, what do you think?

**Comment by AmyKort** [comment]
If it helps, look at 11 CFR 300.2(g), which defines "federal funds" as funds that "comply with the limitations, prohibitions, and reporting requirements of the Act."

I'm having a harder time coming up with a blanket definition for the thing we are actually trying to describe.

**Comment by PaulClark2** [comment]
Maybe something like "Presidential public funds" with a tool tip with additional explanatory text.  Committees report both primary matching funds and the general election grant on Line 16.

**Comment by emileighoutlaw** [comment]
Just reiterating that I do like the idea of giving it another name, other than federal funds, since we're going to use that elsewhere on the site to mean something different. But I am curious to hear what Jen's thoughts on all this are, once she's released from jury duty. :)

**Comment by AmyKort** [comment]
My personal preference would be to change the label to something other than Federal funds, but I am coming at this from a particular perspective--and it is not a data perspective. So you shouldn't trust me here.
I think Paul's idea works. Will "Presidential public funds"  cover public funding for conventions? Our prior presidential election year data will show those funds. In our Public Funding of Presidential Elections brochure we call it the Public Funding of Presidential Elections :). But, that's a little wordy for a chart.

https://github.com/18F/openFEC-web-app/issues/1122#issuecomment-195541905

**Comment by emileighoutlaw** [comment]
I think my comment might have been unclear. I am totally in favor of changing the label!

**Comment by AmyKort** [comment]
You were clear. I was agreeing with you . . . badly.

**Comment by emileighoutlaw** [comment]
As long as Amy and I are in agreement, all is right in the world. :dancers:

**Comment by PaulClark2** [comment]
So we also use the term "federal funds" on the Form 4 (nominating convention).  If we want a single term for both the F3P and F4 public funding perhaps we should drop "presidential" from my suggestion and just use "public funding."

**Comment by AmyKort** [comment]
I'm fine either way. They are presidential nominating conventions.

**Comment by PaulClark2** [comment]
True and using "presidential public funds" might add some clarity.

**Comment by jenniferthibault** [comment]
Catching up—it seems like if it's a thing that will add clarification and is used in more than one place, it might be better suited for a glossary term than a tooltip.

**Comment by emileighoutlaw** [comment]
I'm also in favor of glossary term, if we're calling it "presidential public funds" or "public funds." 

I'm leaning slightly toward "presidential public funds," just because "public funds" sounds a bit like money from the public. 

Is there anywhere we can look for a non-contentious glossary definition for this?

**Comment by AmyKort** [comment]
If we change the label to Presidential public funds, or something like it,
I agree we should try for a glossary entry. Let me look through our
educational materials for some language we can use as a starting point.

**Comment by AmyKort** [comment]
This is slightly modified language from our Public Funding brochure. Can we turn this into something we like? 

Public funding of Presidential elections means that qualified presidential candidates receive federal government funds to pay for the valid expenses of their political campaigns in both the primary and general elections. Prior to the 2016 presidential election, national political parties could also receive federal money for their national nominating conventions.

**Comment by emileighoutlaw** [comment]
I love that definition. So plain language!

> Public funding of presidential elections means that qualified presidential candidates receive federal government funds to pay for certain expenses of their political campaigns in both the primary and general elections. Prior to the 2016 presidential election, national political parties could also receive federal money for their national nominating conventions.


What do you think about that? The word valid immediately makes me want a definition of "valid", while "certain" makes me feel less like that. But that's an anecdotal feeling.

**Comment by AmyKort** [comment]
How about:

Public funding of presidential elections means that qualified presidential candidates may elect to receive federal government funds to pay for certain expenses of their political campaigns in both the primary and general elections. Prior to the 2016 presidential election, national political parties could also receive federal money for their national nominating conventions.

**Comment by emileighoutlaw** [comment]
Would it be possible to say "choose" rather than "elect." Since we are talking about "elections", I think it will be helpful to the reader?

**Comment by AmyKort** [comment]
Sounds good!

**Comment by noahmanger** [comment]
Resolved.
