### ISSUE TITLE
Bug: "Clear filters" doesn't clear typeahead checkboxes

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1124]
As reported in #1123 , the "clear filters" button doesn't clear the checkboxes generated by the typeahead filter.

![gif](http://g.recordit.co/Q5YooJjie4.gif)

**Comment by ccostino** [comment]
@noahmanger, I think I've uncovered where the issue is, but before I fix it I'd like to know what the appropriate behavior is for when we clear all of the filters.  Should the typeahead filters work just like the other checkbox filters in that the checkboxes remain but are cleared, or should we also remove them all together?

**Comment by noahmanger** [comment]
I think they should work like the others and just uncheck the checkbox. @jenniferthibault do you agree?

**Comment by jenniferthibault** [comment]
I don't have real data on this, but I interpret "Clear filters" as start from a clean slate, which to me indicates the checkboxes are removed altogether, since a user might then be intending to start an entirely different search. 

What's your thoughts on why they should stick around @noahmanger ?

**Comment by noahmanger** [comment]
Well the current behavior is that for checkboxes generated from dropdowns, when cleared, they still stay visible. So my argument is just for consistency.

**Comment by jenniferthibault** [comment]
When cleared by x'ing out of the filter tag that's generated? Or when cleared by deselecting it from the dropdown list?

When deselecting from the dropdown list, I'd also expect the checkbox to stay. When clearing it as a filter tag I'd expect the checkbox to go away. 

If this is introducing a minutiae interaction we hadn't distinguished before, I'm ok with leaving it as is! Just wanted to make sure I'm looking at the same interaction you are.

**Comment by noahmanger** [comment]
Yeah, whether you clear it by X-ing out a tag or by unchecking the box, it stays. Right now we're not distinguishing between the two, so I'd like to keep it as is.

**Comment by jenniferthibault** [comment]
:+1:

**Comment by ccostino** [comment]
Awesome, thanks @noahmanger and @jenniferthibault!

**Comment by noahmanger** [comment]
@jenniferthibault and @onezerojeremy : while we're in the land of filter interaction design, do we want to tackle this: should "clear filters" remove the checkboxes completely, rather than just uncheck them?

**Comment by jenniferthibault** [comment]
I think so! That would be grand.

**Comment by noahmanger** [comment]
Since this isn't a bug, and the work is now captured in a [new issue](https://github.com/18F/openFEC-web-app/issues/1356), I'm going to close this.
