### ISSUE TITLE
Comments re: Candidates page 

### ISSUE THREAD

**Issue by ChristianHilland** [18F/openFEC-web-app#1126]
https://beta.fec.gov/data/candidates/

Here are a couple of comments for the Candidate page:

1) I think it would be helpful to the user if the **Receipt Date** field were to be displayed on the table.

2) *_Candidates raising more than $5,000 *_filter:  I think the Statutory Candidate option is wonderful. I'm not sure how helpful the "Future Candidate," "Not yet a candidate," and "Statutory candidate in prior cycle" options are. I can see these options being a bit confusing. I'm tagging @PaulClark2 and @amykort for input.

**Comment by emileighoutlaw** [comment]
Hey Christian! Great comments! We're actually in the process of working on this very thing in this issue:

https://github.com/18F/openFEC-web-app/issues/859

Which is to say, I completely agree with everything you wrote!
