### ISSUE TITLE
Suggested New Feature: Email Alerts for new report filings

### ISSUE THREAD

**Issue by ChristianHilland** [18F/openFEC-web-app#1127]
I've mentioned this before, but I figured I'd make a post about it on GitHub so that it's on our radar.

Once we have .FEC files (and HTML/PDF links) of committees' campaign finance reports available on the beta site, it would be a extremely helpful to build an email alert system. This system would allow users to sign-up to be notified via email once a particular committee(s) has filed a new report.

**Comment by noahmanger** [comment]
Forgot to respond to this earlier, but thanks! I totally agree and this is something we've heard a lot before. We have a place on the story map for this, and will address it once we prioritize that theme.
