### ISSUE TITLE
Purpose (purpose of disbursement / category code)

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#1129]
This is related to https://github.com/18F/openFEC-web-app/issues/1123 item 2 and probably https://github.com/18F/openFEC/blob/develop/data/functions/purpose.sql

For the purpose of disbursement aggregates on the committee pages, I'm still a little unclear what's included in the section that uses "cleaned" with category code descriptions.  Is it all Schedule B transactions excluding the transactions specifically identified by transaction codes above the "cleaned" section.  My other point of uncertainty is are we only using the category code or is it a combination of category code and disbursement description. 

The concern here is, do the aggregates mislead users because they do not include all disbursements that might be associated with a category.   Looking at 2011 to 2016 operating expenditures only, there are 3.7 million operating expenditure transactions but only 1.1 million of those transactions have a category code.  That leaves 2.6 million with no category code.  I don't think we are displaying a "no category" category.    @ChristianHilland @amykort @jwchumley @noahmanger @LindsayYoung 

See for example, https://beta.fec.gov/data/committee/C00370007/?tab=disbursements

`select count(*) from sched_b where extract(year from disb_dt) >= 2011 and ((filing_form = 'F3' and line_num = '17') or (filing_form = 'F3X' and line_num like '21%') or (filing_form = 'F3P' and line_num = '23'));   3,721,495 rows`

`select count(*)  from sched_b where extract(year from disb_dt) >= 2011 and catg_cd is null and ((filing_form = 'F3' and line_num = '17') or (filing_form = 'F3X' and line_num like '21%') or (filing_form = 'F3P' and line_num = '23'));  2,629,615 rows`

`select count(*)  from sched_b where extract(year from disb_dt) >= 2011 and catg_cd is not null and ((filing_form = 'F3' and line_num = '17') or (filing_form = 'F3X' and line_num like '21%') or (filing_form = 'F3P' and line_num = '23')); 1,091,880 rows`

**Comment by noahmanger** [comment]
Where are we at with this? Do we want to address this this sprint @LindsayYoung ?
