### ISSUE TITLE
So that users can make faster comparisons, add percentages to contributions on committee pages

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC-web-app#1136]
This is likely a task for down the road when we revisit committee and candidate pages, but wanted to log it now:

<img width="813" alt="screen shot 2016-03-17 at 11 48 05 am" src="https://cloud.githubusercontent.com/assets/11636908/13851862/2bdd4912-ec36-11e5-8cd2-912219a2912e.png">

h/t @LindsayYoung

**Comment by noahmanger** [comment]
:+1: Adding to the icebox until we pick up that priority.
