### ISSUE TITLE
Consider consolidating code for feedback tool

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/openFEC-web-app#1144]
Looks like this old feedback page may be ready for deletion:
https://github.com/18F/openFEC-web-app/blob/64a6d02e77e6edd81f217f0ef10f9dae2438950d/openfecwebapp/templates/feedback.html

For reference, I believe this is the current page that we're using:
https://github.com/18F/fec-style/blob/9480b11322a385e0f8e3ced7b02ffa52ae5e8b4c/js/templates/feedback.html

**Comment by jmcarp** [comment]
Those files do different things--the first formats the comment for submission to github as markdown, and the second shows the comment dialog on the site as html. We're using both. If there's time to review #1110 later on, we'll be able to delete the first file.

**Comment by emileighoutlaw** [comment]
Ahhh okay, that makes complete sense. Thanks so much for clarifying, Josh.
