### ISSUE TITLE
Make operating expenditures datatable page

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1148]
Using the current filters and columns available, make an operating expenditures datatable page.

**Comment by noahmanger** [comment]
@LindsayYoung / @PaulClark2  do we already have a filter to limit a query to operating expenditures? I can't find it.

**Comment by PaulClark2** [comment]
I don't think we do but @LindsayYoung will need to confirm. It's a fairly straightforward query.  We need to select all the uncategorized transactions on Line 17 of Form 3, Line 23 on Form 3P and Line 21 on Form 3X. 

Here's how we are doing it for the bulk download file (http://www.fec.gov/finance/disclosure/ftpdet.shtml#a2015_2016)
 
FROM f_item_receipt_or_exp f_item
JOIN f_rpt_or_form_sub frpt ON f_item.v_sum_link_id=frpt.sub_id
WHERE f_item.transaction_tp IS NULL 
AND f_item.sched_tp_cd = 'SB'
       AND (   (frpt.form_tp = 'F3' AND line_num = '17')
            OR (frpt.form_tp = 'F3P' AND line_num = '23')
            OR (frpt.form_tp = 'F3X' AND line_num LIKE '21%'))

**Comment by noahmanger** [comment]
@LindsayYoung do you know if we have this already?
