### ISSUE TITLE
Implement new site menu

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1155]
Code the new dropdown menu system with links to datatable pages that currently exist. 

- [x] Implement on CMS
- [x] Implement on web app

Dependency: [Visual design](https://github.com/18F/openFEC-web-app/issues/1153)

Next step:
- [ ] Implement mobile version after verifying in testing

**Comment by noahmanger** [comment]
Thinking through the best strategy on this, and I'd love folks' thoughts (ping @adborden ):

The [desktop](https://cloud.githubusercontent.com/assets/11636908/14497782/fddcb40e-0165-11e6-971f-9bf4985cebd6.png) and [mobile](https://cloud.githubusercontent.com/assets/11636908/14396216/5109d406-fda4-11e5-8619-0c487e6b923c.png) views are pretty different.

Rather than  try to shoehorn one into the other with media queries and complicated CSS rules (which might not even be possible), I'm wondering if we might just want to generate two separate sets of markup for each.

In [my PR](https://github.com/18F/fec-style/pull/316) for this, I introduced a new handlebars template in fec-style that is used to generate the desktop dropdown menus. We could do a similar thing for the mobile menus. And we could even go one step further and have each of them be populated by set of data with all of the links, which would reduce the risk of making a change in one place but not another.

Instinctively this _feels_ more complicated than it should be, but I'm also not thinking of any better ideas.

**Comment by noahmanger** [comment]
@jenniferthibault I'm thinking I'm going to hold off on the mobile version until we've validated the main menu in testing next week. Sound good?

**Comment by jenniferthibault** [comment]
sounds good!

**Comment by adborden** [comment]
Hmm, yeah the two seem pretty different. I'm not really into splitting them into two templates... but thinking about how the next level of menus (like after tapping Advanced datatables) would work on mobile starts to look pretty hairy in my mind.

My hunch is that you're going to need some JS to do the heavy lifting anyway. You might start down the path of two templates and then find that the complexity is less in the dom/CSS and then decide to merge the templates back anyway. I'm curious if there are any pure-CSS menus with nested menus that exist (I've never seen any). Anyway, sounds good!

**Comment by jenniferthibault** [comment]
Holding off on building mobile sounds very smart to me!

**Comment by noahmanger** [comment]
@adborden Yeah, it's not really possible to do this with just CSS, AFAIK. At least not possible to do it in a way that also accounts for keyboard navigability for accessibility.

I guess other approaches would be to:
- Set conditionals in the templates that format the markup based on a screen size variable passed to them
- Break up the different sections into different templates, and then arrange them differently in the DOM with JS. 

I agree that trying to stay away from separate templates is probably a good thing.

**Comment by adborden** [comment]
> Break up the different sections into different templates, and then arrange them differently in the DOM with JS.

+1

**Comment by jenniferthibault** [comment]
Changes ready to implement from design discussion in https://github.com/18F/fec-style/issues/343

- [ ] lowercase `- all`
- [ ] reorder Spending section
- All disbursements
  - Operating expenditures
  - Expenditures to committees
- Independent expenditures

![desktop - nav intermediate copy 3](https://cloud.githubusercontent.com/assets/11636908/15405919/1d4f28e8-1dd2-11e6-9ccf-c8a3ba94d673.png)

**Comment by emileighoutlaw** [comment]
One more thought on this one — we have the interactive overviews as "coming soon" and none of the other greyed-out sections. That's intentional, yes? Just checking in.

**Comment by jenniferthibault** [comment]
It was intentional, but now I'm not sure the reasoning was terribly well thought out. (I can say that because it was me :) ) 
Dropping the "coming soon" would be 👍 . I don't necessarily find it confusing like this, but it is inconsistent. Your call @emileighoutlaw !

**Comment by emileighoutlaw** [comment]
Let's just drop it for now? Unless @noahmanger has strong feelings against it? I'm enthused about consistency these days.

**Comment by noahmanger** [comment]
👍

**Comment by noahmanger** [comment]
I'm going to leave off the full button for now while we don't have anything there.

**Comment by noahmanger** [comment]
Desktop version is done. Opening a separate issue for mobile.
