### ISSUE TITLE
Figure out solution for comparing election totals

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1180]
Back in February, we prioritized five types of data that we wanted the dashboard pages to address:
1. Totals for all 
2. Compare totals of individual entities to other individual entities
3. Compare election totals
4. Compare totals of groups of things
5. See how much was raised and spent in different ways (location, size of contribution, etc.)

Of those five, #3 is the only one we haven't really thought about yet. The point of value here is that it allows users to compare contests to one another: which elections have the most outside spending? Which ones have the most fundraising? Etc. 

I can think of two options:
1. Include election totals on one of the planned overview pages. This way, on the "Fundraising overview" page you could see elections ranked by the amount of combined receipts all candidates have brought in.
2. Create a separate "Elections overview" page that includes these kind of comparisons. 

I want to spend some time sketching out solutions next sprint, but wanted to capture this in case folks have thoughts (and to make sure we come back to it).

**Comment by noahmanger** [comment]
Alright, spent some time on this, so I want to capture my thinking and would love to know folks' thoughts. 

I think that of the two options I listed above, #2 is the best for a couple reasons:
- It lets us keep the fundraising and spending overview pages as simple as possible by not mixing different types of info
- I think it gives us an opportunity to create a better lead into the election pages than the current election search page.

I have a few ideas for the ways we could do this, each of which combines the functionality of the election search with an overview of election financial totals.

# Option A
![image](https://cloud.githubusercontent.com/assets/1696495/15264423/d14f3dba-1927-11e6-9339-afa53df0d30c.png)

This option follows the model of the candidate / pac / party committee overview pages, with a set of filters on the left and a combination of graphs and charts on the right. 

By including state and zip code filters here, this page could also function effectively as the election search, but instead of presenting elections as a set of search results, it presents them as a table of elections with financial data for each.

# Option B
![image](https://cloud.githubusercontent.com/assets/1696495/15264484/5942158a-1928-11e6-82d5-c777985b9159.png)

This approach separates the election lookup functionality from the display of data. The map at the top could function as a zoom-able, click-able map as well as a choropleth of financial data. 

# Option C
![image](https://cloud.githubusercontent.com/assets/1696495/15264522/c7f70b2a-1928-11e6-9566-15059cafa687.png)

This goes more in the direction of the fundraising / spending overviews, presenting a page of tables and visualizations. The zip code search could generate a list of search results either her or on a separate page.

# Other thoughts
- I'm still not fully confident in all the different types of data we need to show on these pages, outside of total candidate fundraising, candidate spending and independent expenditures in elections. 
- I wonder what other kinds of information or context we want to bring in here: perhaps election dates?
- I've toyed a little with consolidating **all** election pages into a single page. Like something that starts at the broad national level, comparing elections to one another, but when you zoom in you get effectively the election pages we have now. But I'm not sold on this as a good idea. 😄

**Comment by jenniferthibault** [comment]
Quick high-level recap which @noahmanger may flesh out with details from our discussion later:

We like the idea of the elections page being it's own page (which also integrates election/candidate by location search). There won't be any functionality for it on the data landing page, it will just be a card-like link.

Since we're building out the data landing page designs, I think we can build its placeholder, but de-prioritize interaction designs here until the interactive overview interactions are further along.

**Comment by noahmanger** [comment]
Main take-aways from our team review in addition to that:
- Potentially add party committee expenditures per election
- Potentially add a column for total candidates in the race

We like Option B the most, but with a few changes:
- The columns should be limited to top-level Total Candidate Receipts, Total Candidate Spending and Total Independent Expenditures, rather than sub-totals.
- We should look to way to even do away with as many of the filters as possible, instead relying on the filters in the location look up
- Try to integrate the location lookup and display of data in smart way (e.g. use the location look-up map as a choropleth; use the map to control which locations are showed in the table), but be careful about confusing our patterns.

There's lots of UX questions still to sort out, but that's a topic for another sprint.
