### ISSUE TITLE
Before release: Apply standard alt style to search page dropdown button

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC-web-app#1182]
From: https://fec-stage-proxy.18f.gov/data/?search_type=candidates&search=zebra
 
<img width="1015" alt="screen shot 2016-04-13 at 1 05 20 pm" src="https://cloud.githubusercontent.com/assets/11636908/14502388/0f9bbc22-0179-11e6-8858-580c2ba3e7d2.png">

The search button has inverse styling applied, so it looks like it's missing.

**Comment by noahmanger** [comment]
Fixed!
