### ISSUE TITLE
Bug: Receipts from non-committees showing up when filtering for committees

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/openFEC-web-app#1185]
On our receipts page, when we filter to "committees" it looks like results are showing a lot more than committees. I'm wondering if this a data issue or an issue of the filter having the wrong name? 

cc @LindsayYoung @ccostino 

<img width="1257" alt="screen shot 2016-04-13 at 5 32 21 pm" src="https://cloud.githubusercontent.com/assets/10552702/14510110/c9f52328-019d-11e6-8abc-9a5f899e4cb8.png">

Here's a URL: https://beta.fec.gov/data/receipts/?committee_id=C00571372&contributor_type=committee&max_date=04-13-2016

**Comment by noahmanger** [comment]
I see that this is still the way it shows up. @PaulClark2 and @LindsayYoung : any idea what's up? Is it that our "committees" filter is just a filter for "not an individual"?

**Comment by noahmanger** [comment]
Seeing something that's perhaps related reported in one of the rounds of FEC feedback:

![image](https://cloud.githubusercontent.com/assets/1696495/16251355/2eaa212a-37da-11e6-84db-92c495461f8a.png)

**Comment by PaulClark2** [comment]
I'm not sure how the "committee" filter works.  

PAC contributions: 33
`select * from ofec_sched_a where cmte_id = 'C00571372' and line_num = '11C';`

Political party committee contributions: 1
`select * from ofec_sched_a where cmte_id = 'C00571372' and line_num = '11B';`

**Comment by LindsayYoung** [comment]
That value comes from entity_tp in sched_a the codes are : 
 IND
 ORG
 COM
 CCM
 PTY
 PAC
 CAN
 TRB
 PRT

We use IND for individual and I am not seeing how we develop the committee. I don't have time to look into this further at the moment, but I will try to circle back on it.

**Comment by LindsayYoung** [comment]
I am pretty sure we got this as good as possible here:
https://github.com/18F/openFEC/pull/1866

Though, reopen if you think this is still a problem.
