### ISSUE TITLE
Implement changes to search results pattern 

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC-web-app#1202]
The interaction pattern from https://github.com/18F/fec-style/issues/318#issuecomment-214396124 uses the side menu from Registration & Reporting to align how search results are presented across the legal resources side and the data side.

![search_candidate or committee-copy copy](https://cloud.githubusercontent.com/assets/11636908/14867330/046035f4-0c96-11e6-9a37-364d477e23ec.png)

This issue is specifically for the data side — @edmullen is creating a separate issue for the style changes for the legal side, which are less substantial.

There may be an initial step to implement this which excludes the election results, not sure!

**Comment by edmullen** [comment]
@jenniferthibault I have one suggestion. I think the highlighted text should be bold as well as the highlight. On legal the highlight text sometimes is with paragraphs and the bold helps it stand out amongst other text.

**Comment by jenniferthibault** [comment]
👍 that sounds like a great improvement to me! Let's add it in.
