### ISSUE TITLE
Incorrect destination for Campaign Finance Data in breadcrumb

### ISSUE THREAD

**Issue by edmullen** [18F/openFEC-web-app#1215]
The "Campaign Finance Data" link in the breadcrumb leads to the homepage, not the campaign data section. 

![image](https://cloud.githubusercontent.com/assets/2654503/15398948/ae22643a-1db3-11e6-944b-85864c2495a1.png)

**Comment by noahmanger** [comment]
Ah! Thanks for the catch. I'll roll this into this release.
