### ISSUE TITLE
Implement sticky tag/download area on data table pages

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC-web-app#1224]
I thought we had planned to release this with the typeahead filters as part of the filter panel experience improvement, but I'm not seeing it on staging. 

Not sure if this is intentionally left out of this release or accidentally—should address that question before release.

**Comment by noahmanger** [comment]
Yeah, the version we had implemented was a super crudely-coded version. I'd like to actually implement it correctly and then get it in the next release. So I'm going to remove the tag, but move it to this sprint. Thanks!

**Comment by jenniferthibault** [comment]
Sounds great, thank you!
