### ISSUE TITLE
Adjust "Reports and filings" child element text in mega menu

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC-web-app#1226]
Currently:
- All filings
- Authorized committee
- Unauthorized committee

Should be:
- All filings
- Authorized committee **reports**
- Unauthorized committee **reports**

Even though these aren't activated, it establishes the IA elements for the site and data.

- [ ] Implement on web app
- [ ] Implement on cms

**Comment by emileighoutlaw** [comment]
@amykort, can you tap in here and explain to me what the technical difference between `filing` and `report` is? I'm getting hung up on having both words in the same category section.

**Comment by AmyKort** [comment]
Generally, we talk about reports, statements and notices. So, you've got your quarterly report on your form 3, and your statements of candidacy and organization, and you might have to file a 48 hour notice of contributions. Taken together, these are all filings. I don't know that this is a hard and fast rule more than a convention. Generally, if there are "statements" in a group, we don't call those groups "reports."

**Comment by emileighoutlaw** [comment]
This is great! Thanks so much for being such a patient teacher, Amy. To keep everything consistent, what if we said:

> All filings
- Authorized committee filings
- Unauthorized committee filings

**Comment by AmyKort** [comment]
Looks good to me!

**Comment by noahmanger** [comment]
Made this change.
