### ISSUE TITLE
Clarify relationship between filters and typeahead on receipts page

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1227]
As noted separately [here](https://github.com/18F/FEC/issues/323) and in usability testing, users are confused by the presence of committee suggestions in the typeahead filter when the individuals checkbox is checked. 

![image](https://cloud.githubusercontent.com/assets/1696495/15443429/1c171758-1e9d-11e6-98cb-cc0379384886.png)

I think the solution to this is to have the checkbox set a property on the name filter so that it either searches through committees or not depending on the property.

But I understand @LindsayYoung had potential concerns. Can you elaborate?

**Comment by noahmanger** [comment]
Alright, I think I have a good solution to this put together. 

![demo](http://g.recordit.co/AtjypFCDTk.gif)

If no checkboxes, both checkboxes, or just committees is selected, the typeahead allows free text and committee suggestions.

If only individuals is selected, it only does a free text search and doesn't show committee suggestions.

We're not actually changing the way the search query works in terms of the data that shows up, we're just alleviating the confusion caused by seeing committee suggestions when you specify you're only interested in individuals.

**Comment by jenniferthibault** [comment]
This approach seems smart to me, sorry for missing the issue. Is anything blocking it from being implemented?

**Comment by noahmanger** [comment]
Nope! The code is all here: https://github.com/18F/fec-style/pull/361.

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/fec-style/pull/361

**Comment by LindsayYoung** [comment]
I think the way you implemented it works really well!!
