### ISSUE TITLE
Implement new data landing page

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1229]
Based on the designs from https://github.com/18F/fec-style/issues/322 , implement and style the static components of the new data landing page. This does not include implementing the charts. Those will be a separate issue.

**Comment by noahmanger** [comment]
**Criteria for completion:**
- [ ] Overall layout is updated
- [ ] Links to advanced data page
- [ ] Links to elections page

**Comment by emileighoutlaw** [comment]
Here's the final content for this! https://docs.google.com/document/d/1ZuatMQS9VUb0cD_MRqFHZto5Isd4O4rtmFoN7Nk4VXA/edit

Let me know if I should post this somewhere else. :)

**Comment by noahmanger** [comment]
Resolved in https://github.com/18F/openFEC-web-app/pull/1282
