### ISSUE TITLE
Mega menu: Profile search copy and functionality conflict

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC-web-app#1238]
In the mega menu, the Profile search says "Search for candidates and committees" which hints to our intent to have a combined search of those two categories both here and on the data landing page. However, the current functionality of the typeahead is only searching the candidates table.

![screen shot 2016-05-26 at 1 16 57 pm](https://cloud.githubusercontent.com/assets/11636908/15583536/3b67c322-2344-11e6-8ca4-35b18af0dc7b.png)

Ultimately, we would like it to search both, and I don't want to lose track of that. Is that captured in an issue somewhere?

For now, we could adjust the language, but it seems like the interaction expectation is for searching both.

cc @noahmanger @emileighoutlaw @LindsayYoung

**Comment by noahmanger** [comment]
I agree with @LindsayYoung (in the [the other issue](https://github.com/18F/FEC/issues/334) and everyone else that eventually a combined search is what we want.

That's not currently captured anywhere, but I just made a [new story card](https://18f.storiesonboard.com/m/fec/!card/9stsaTJQ58bADDnYAeLMIA) as a placeholder. I think this is a good thing to do, but also think given all we need to do in the coming months we'll need to be careful to prioritize it appropriately. 

In the mean time, what should we do? Personally, I'm ok having just the candidate search here, and we could edit the label. Or we could bring back the select?

**Comment by emileighoutlaw** [comment]
Bah! I can't believe I missed this. 

For the time being, it seems okay to have this search be for candidates (if someone navigates to candidate page, they can click through to the authorized committees).

If we do that, the language should say "Search for candidates", so it properly reflects the functionality of the search. I can do a PR for that, if we're all in agreement.

**Comment by jenniferthibault** [comment]
👍  to just candidates for now, but I'd like to see the combined search happen sooner than later, as that's also the intent for the new designs on the data landing page.

**Comment by noahmanger** [comment]
This content change has been made.
