### ISSUE TITLE
Advanced data page content

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/openFEC-web-app#1245]
This issue is where I'll draft the introductory content for our advanced data index. 

To include:
- Candidates
- Committees
- Receipts
- Spending

![unnamed](https://cloud.githubusercontent.com/assets/10552702/15754350/d0726e78-28c5-11e6-9170-1840d4277c76.png)

We'll incorporate as fast as I can get this written and approved

**Comment by jenniferthibault** [comment]
A small content question on this page. Looking at consistency between the breadcrumbs and the page title, `Advanced data` or `Advanced data index`, which should it be?

<img width="579" alt="screen shot 2016-06-06 at 10 16 43 am" src="https://cloud.githubusercontent.com/assets/11636908/15824974/d5fb4ea2-2bcf-11e6-851a-38608c05ba06.png">

**Comment by emileighoutlaw** [comment]
Good question. I've been preferring `Advanced data` to `advanced data index`, so I'd like to go with that, unless someone else makes a strong case against it.

**Comment by noahmanger** [comment]
Changed the title!

**Comment by emileighoutlaw** [comment]
GitHub issue: https://docs.google.com/document/d/1nNcHO7dK6qvjnLbCpIrdChXw7k82wTKGfP36Y-7zurw/edit

I'll ping appropriate folks when I have a draft done :)

**Comment by emileighoutlaw** [comment]
okay @noahmanger and @jenniferthibault — I'm coming in under the Friday wire, but this content draft is finished: https://docs.google.com/document/d/1nNcHO7dK6qvjnLbCpIrdChXw7k82wTKGfP36Y-7zurw/edit#

**Comment by jenniferthibault** [comment]
Thanks Emileigh! I left a few clarifying questions in your doc.

**Comment by emileighoutlaw** [comment]
@jenniferthibault is taking one more peek! :)

**Comment by jenniferthibault** [comment]
Thanks for the bump! I had meant to offer some design solutions for your card idea for linking the reg/reporting side.

I think this is a good use of the pattern we established on the reg/reporting side where we link to reporting deadlines. How about this visual pattern?

![screen shot 2016-06-24 at 3 39 42 pm](https://cloud.githubusercontent.com/assets/11636908/16348668/0cf580e8-3a22-11e6-942a-e1b7d208558a.png)

**Comment by noahmanger** [comment]
Oh I love that! Though we do have separate pages for PAC and party committee requirements

**Comment by jenniferthibault** [comment]
HUZZAH! 

I think I have a better solution overall and it's creating a consistent pattern. When we're cross-linking to other sections, I think this mini-link-with-an-icon-without-a-box thing that's developing should be a pattern. It's probably a distant relative to our card pattern, but doesn't call HUGE attention to it. Higher prominence than text links, lower prominence than cards with colored backgrounds.

This is a little fast and sloppy, but I think you'll get the gist. cc @noahmanger @onezerojeremy 

![screen shot 2016-06-24 at 4 17 45 pm](https://cloud.githubusercontent.com/assets/11636908/16349485/37876a10-3a27-11e6-8c0f-3498840ef1cf.png)

**Comment by emileighoutlaw** [comment]
I LOVE the way that looks!!

**Comment by onezerojeremy** [comment]
plus one to making this a pattern! icons like this provide shortcuts that have found an item they're looking for once to find it again quickly, aka, [recognition over recall](https://www.nngroup.com/articles/recognition-and-recall/)


I would definitely say that we should try to limit the number of these to the more important links, so as to have them retain their visual prominence!

**Comment by noahmanger** [comment]
Belatedly: I like it! It's a nice way to build the color-coding identification as well.

**Comment by noahmanger** [comment]
Can this move to implementation?

**Comment by jenniferthibault** [comment]
Yup!

**Comment by noahmanger** [comment]
Added!
