### ISSUE TITLE
Implement chart feedback box

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1249]
So that the team can collect data on the usefulness and comprehension of the charts, implement the chart feedback tool as designed in https://github.com/18F/fec-style/issues/357

**Criteria for completion:**
- [x] Code resting state
- [x] Reaction buttons trigger custom Google Analytics events
- [x] Users can submit free-form feedback to the FEC repo
- [x] Free-form feedback includes the reaction
- [x] User sees a success message upon submitting feedback

**Comment by jenniferthibault** [comment]
Designs are ready here: https://github.com/18F/fec-style/issues/357

**Comment by noahmanger** [comment]
Resolved in https://github.com/18F/openFEC-web-app/pull/1282
