### ISSUE TITLE
Content: Money received or money raised?

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/openFEC-web-app#1261]
On the novice data landing page, we're writing _**raising**_ as our more human readable term for **_receipts_** (with an explanation of **_receipts_** immediately following). 

I was noticing on the data filters, that we have **_money received_**, and I'm thinking it would improve our site consistency to change this accordion filter to _**money raised**_. 

<img width="303" alt="screen shot 2016-06-09 at 1 30 13 pm" src="https://cloud.githubusercontent.com/assets/10552702/15941648/c6afef9c-2e46-11e6-88b7-566096e3d71f.png">

We have this content pattern a lot of different places on the beta: https://github.com/18F/openFEC-web-app/search?utf8=%E2%9C%93&q=%22Money+received%22

**Comment by noahmanger** [comment]
Thanks for flagging! I just put in a PR to fix it.
