### ISSUE TITLE
Content: Use of "spender" in filter

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/openFEC-web-app#1262]
Our independent expenditure filters have a "**_spender_**" filter:
<img width="298" alt="screen shot 2016-06-09 at 4 14 14 pm" src="https://cloud.githubusercontent.com/assets/10552702/15946677/764fd294-2e5d-11e6-92b5-234badd6fd60.png">

Communication costs have a "**_committee or ID_**" filter:
<img width="321" alt="screen shot 2016-06-09 at 4 13 56 pm" src="https://cloud.githubusercontent.com/assets/10552702/15946686/86f82a88-2e5d-11e6-90aa-cfb7003a50c3.png">

Is the communication cost "**_committee of ID_**" filter also the "**_spender_**"? And if so, can we call it "**_spender_**"? 

This is probably a @LindsayYoung question, but I'm also cc'ing @jenniferthibault and @noahmanger in case they happen to know the answer (I'm sure we've talked about this, but I can't remember now."

**Comment by LindsayYoung** [comment]
Independent expenditures can me made by people and groups that are not committees. So we need "spender" for that field. 

Communication costs are a type of spending from communication cost committees. But I don't see why we couldn't call them spenders. We do on the election page. 
https://beta.fec.gov/data/committees/?committee_type=C

I am gong to flag @amykort for confirmation on that.

**Comment by AmyKort** [comment]
I think spender would be fine for both. Thanks!

@PaulClark2

**Comment by PaulClark2** [comment]
I agree. "Spender" works for both.
