### ISSUE TITLE
Capitalization of senate and house

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/openFEC-web-app#1269]
Senate and House should be capitalized in these headers:
<img width="919" alt="screen shot 2016-06-13 at 11 20 06 pm" src="https://cloud.githubusercontent.com/assets/10552702/16030266/88df5340-31bd-11e6-9bba-c3429d7a51c9.png">
<img width="1020" alt="screen shot 2016-06-13 at 11 20 16 pm" src="https://cloud.githubusercontent.com/assets/10552702/16030268/8b3a151c-31bd-11e6-8a2f-cd9bf380ea6c.png">

But I cannot figure out where these suckers are hiding in the code. @ccostino or @LindsayYoung can one of you point me to the templates where these are, so I can fix them? :)

**Comment by ccostino** [comment]
Hmm, these titles may not actually be in a template in and of itself if what I'm looking at is correct: https://github.com/18F/openFEC-web-app/blob/develop/static/js/pages/candidates-office.js#L27

@noahmanger are you able to provide more context to this?

**Comment by noahmanger** [comment]
Ah yep, that's where they're being generated. It's because that entire area is created by the data table component.
