### ISSUE TITLE
Write content for "About this data" on landing page

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1275]
In order for advanced users to understand what data is included in the totals shown on the landing page, write blurbs to explain what the data is. The blurbs should address:
- [x] The time period included. I believe this is everything reported from January 1, 2015 to May 25, 2016. 
- [x] The forms included. I believe this is Forms 3, 3P, 3X and 5, but someone should verify
- [x] Anything else necessary to understand what is or is not included

@PaulClark2 can you weigh in here? This is referring to the charts generated from the data you gave me in that spreadsheet a couple weeks ago.

![image](https://cloud.githubusercontent.com/assets/1696495/16124784/56ec8742-33a5-11e6-8173-e19cfe4da7b4.png)

**Comment by emileighoutlaw** [comment]
Word. Thanks for opening this, Noah.

**Comment by PaulClark2** [comment]
@noahmanger 
1- January 1, 2015 to May 25, 2016 is correct. 
2 - The data includes Forms 3, 3P, 3X, 5, 7 and 9
3 - I'll post the formulas

**Comment by PaulClark2** [comment]
Money Spent = PAC and Party Adjusted Disbursements + Congressional 
Adjusted Disbursements + Presidential Adjusted Disbursements + Independent Expenditures (Form 5 Filers Only) + Communication Costs + Electioneering Communications 

Money Raised = PAC and Party Adjusted Receipts + Congressional Adjusted Receipts 
+ Presidential Adjusted Receipts + Total Contributions (Form 5 filers) + Total Donations (Form 9 filers)

**Congressional Formulas
(all Form 3 filers)**

**Disbursements**
Adjusted Disbursements equals Total Disbursements 
minus the sum of Transfers to Other Authorized Committees, Loan Repayments Made, Total Contribution Refunds and Other Disbursements

(Form 3 Line Numbers: Adjusted Disbursements = Form 3 Line 22 - (Line 18 + Line 19(c) + Line 20(d) + Line 21))

**Receipts** 
Adjusted Receipts equals Total Receipts 
minus the sum of Contributions from Political Party Committees, Contributions from Other Political Committees, Offsets to Operating Expenditures, Total Loan Repayments Made and Total Contribution Refunds

(Form 3 Line Numbers: Adjusted Receipts = Form 3 Line 16 - (Line 11(b) +  Line 11(c) + Line 14 + Line 19(c) + Line 20(d)))

**Presidential Formulas
(all Form 3P filers)**

**Disbursements**
Adjusted Disbursements equals Total Disbursements 
minus the sum of Total Offsets to Expenditures, Transfers to Other Authorized Committees, Total Loan Repayments, Total Contribution Refunds and Other Disbursements

(Form 3P Line Numbers: Adjusted Disbursements = Form 3P Line 30 - (Line 20(d) + Line 24 + Line 27(c) + Line 28(d) + Line 29)

**Receipts** 
Adjusted Receipts equals Total Receipts
minus the sum of Contributions from Political Party Committees, Contributions from Other Political Committees, Total Offsets to Expenditures, Total Loan Repayments Made and Total Contribution Refunds

(Form 3P Line Numbers:  Adjusted Receipts = Form 3P Line 22 - (Line 17(b) +  Line 17(c) + Line 20(d) + Line 27(c) + Line 28(d)))

**PAC and Party Formulas
(all Form 3X filers)**

**Disbursements**
Adjusted Disbursements equals Total Disbursements 
minus the sum of Nonfederal Share of Allocated Disbursements, Transfers to Affiliated Committees, Contributions to Candidates and Other Political Committees, Loan Repayments Made, Total Contribution Refunds and Other Disbursements

(Form 3X Line Numbers: Adjusted Disbursements = Form 3X Line 31 - (Line 21(a)(ii) + Line 22 + Line 23 + Line 26 + Line 28(d) + Line 29))

**Receipts** 
Adjusted Receipts equals Total Receipts 
minus the sum of Contributions from Political Party Committees, Contributions from Other Political Committees, Offsets to Expenditures, Refunds of Contributions Made to Federal Candidates and Committees , Transfers from Nonfederal Account for Allocated Activity, Loan Repayments Made and Total Contribution Refunds

(Form 3X Line Numbers: Adjusted Receipts = Form 3X Line 19 - (Line 11(b) +  Line 11(c) + Line 15 + Line 16 + Line 18(a) + Line 26 + Line 28(d)))

**Independent Expenditures
(Form 5 Filers Only)**

**Disbursements**
Adjusted Disbursements equals Total Independent Expenditures 

(Form 5 Line Numbers: Adjusted Disbursements = Form 5 Line 7)

Receipts 
Adjusted Receipts equals Total Contributions 

(Form 5 Line Numbers: Adjusted Disbursements = Form 5 Line 6)

****Communication Costs** 
(Form 7 Filers)**

Disbursements
Adjusted Disbursements equals Total Communication Costs
(Form 7 Line Numbers: Adjusted Disbursements = Total Communication Costs)

**Electioneering Communications
(Form 9 Filers)**

**Disbursements**
Adjusted Disbursements equals Total Disbursements/Obligations
(Form 9 Line Numbers: Adjusted Disbursements = Form 9 Line 10)

**Receipts** 
Adjusted Receipts equals Total Donations  

(Form 9 Line Numbers: Adjusted Disbursements = Form 9 Line 9)

**Comment by PaulClark2** [comment]
The Estimated Cost of the Election figures exclude certain transactions that reflect the movement of money internally within the campaign finance system. The Estimated Cost of the Election formulas are described XXX. 

The methodology and formulas for calculating an estimated cost of the election have the following known limitations. The estimate includes only election activity disclosed to the FEC and does not include election activity disclosed to other Federal agencies. Any cash on hand carried over from previous cycles is not captured in the estimated Money Raised formulas, but if a committee spends these funds, these amounts will be captured in the estimated Money Spent formulas. For Independent Expenditures (Form 5 filers), the total reported receipts for 2014 are less than five percent of the total reported disbursements, and for Electioneering Communications, the total reported receipts are less than two percent of the total reported disbursements. Independent Expenditure (Form 5) contributions and Electioneering Communications (Form 9) donations may include amounts in the estimated Money Raised for other filers.   


Now we need to make all this information user friendly. @noahmanger @emileighoutlaw @amykort

**Comment by emileighoutlaw** [comment]
Easy peasy ;)

**Comment by emileighoutlaw** [comment]
Working on content here: https://docs.google.com/document/d/1pyNqDv5Gc5LcGrWMEQhNa0pgsDU4mn6sfaX93su9BfY/edit#

**Comment by emileighoutlaw** [comment]
Here's a first draft of this. @PaulClark2, can you take a look and let me know what you think?




### About this data
This data includes Forms 3, 3P, 3X, 5, 7 and 9 from January 1, 2015 to May 25, 2016.

### Methodology
**Money raised** includes each of the following:
- _Adjusted receipts_ for PACs, parties, congressional filers and presidential filers
- Total contributions for independent expenditure (Form 5) filers
- Total donations for electioneering communications (Form 9) filers

_Adjusted receipts_ are total receipts minus the following:
- Contribution refunds
- Contributions from political party committees and other political committees
- Loan repayments
- Offsets to operating expenditures
- Transfers from nonfederal accounts for allocated activities

**Money spent** includes each of the following:
- _Adjusted disbursements_ for PACs, parties, congressional filers and presidential filers
- Total independent expenditures for independent expenditure (Form 5) filers
- Total disbursements and obligations electioneering communication (Form 9) filers
- Total communications costs for communication cost (Form 7) filers

_Adjusted disbursements_ are total disbursements minus the following:
- Contribution refunds
- Contributions to candidates and other political committees
- Loan repayments
- Nonfederal share of allocated disbursements
- Offsets to expenditures
- Other disbursements
- Transfers to other authorized committees and affiliated committees

**Comment by PaulClark2** [comment]
@emileighoutlaw this looks good to me.

**Comment by jwchumley** [comment]
I compared Paul's presentation with @emileighoutlaw 's. I think Emileigh has everything accounted for  and it is easy to read but I think for anyone trying to seriously make sense of the numbers (press people and researchers) they are going to need the formulas and the form by form breakout as per Paul.  It could be a link from this but I don't think we should lose it.

**Comment by emileighoutlaw** [comment]
I hear you Jeff and Paul. If we think the line-by-line breakdown is likely to be useful to folks (I'm looking at y'all and @noahmanger for thoughts on this), we could do our "About this data" for money raised and money spent like this: 

**About this data for money raised**

### About this data
This data includes Forms 3, 3P, 3X, 5, 7 and 9 from January 1, 2015 to May 25, 2016.

### Methodology overview
**Money raised** includes each of the following:
- _Adjusted receipts_ for PACs, parties, congressional filers and presidential filers
- Total contributions for independent expenditure (Form 5) filers
- Total donations for electioneering communications (Form 9) filers

_Adjusted receipts_ are total receipts minus the following:
- Contribution refunds
- Contributions from political party committees and other political committees
- Loan repayments
- Offsets to operating expenditures
- Transfers from nonfederal accounts for allocated activities

The form-by-form breakdown for adjusted receipts is:
- **Form 3**: _line 16 - (line 11(b) + line 11(c) + line 14 + line 19(c) + line 20(d))_
- **Form 3P**: _line 22 - (line 17(b) + line 17(c) + line 20(d) + line 27(c) + line 28(d))_
- **Form 3X**: _line 19 - (line 11(b) + line 11(c) + line 15 + line 16 + line 18(a) + line 26 + line 28(d))_


------------
**About this data for money spent**

### About this data
This data includes Forms 3, 3P, 3X, 5, 7 and 9 from January 1, 2015 to May 25, 2016.

**Money spent** includes each of the following:
- _Adjusted disbursements_ for PACs, parties, congressional filers and presidential filers
- Total independent expenditures for independent expenditure (Form 5) filers
- Total disbursements and obligations electioneering communication (Form 9) filers
- Total communications costs for communication cost (Form 7) filers

_Adjusted disbursements_ are total disbursements minus the following:
- Contribution refunds
- Contributions to candidates and other political committees
- Loan repayments
- Nonfederal share of allocated disbursements
- Offsets to expenditures
- Other disbursements
- Transfers to other authorized committees and affiliated committees

The form-by-form breakdown for adjusted disbursements is:
- **Form 3**: _line 22 - (line 18 + line 19(c) + line 20(d) + line 21)_
- **Form 3P**: _line 30 - (line 20(d) + line 24 + line 27(c) + line 28(d) + line 29)_
- **Form 3X** l_ine 31 - (line 21(a)(ii) + line 22 + line 23 + line 26 + line 28(d) + line 29)_

**Comment by PaulClark2** [comment]
I like it! Thanks Emileigh

**Comment by jwchumley** [comment]
Me Too. Very clear.
