### ISSUE TITLE
Committee ID Example

### ISSUE THREAD

**Issue by patphongs** [18F/openFEC-web-app#1297]
![screen shot 2016-06-22 at 1 26 32 pm](https://cloud.githubusercontent.com/assets/12799132/16276621/279e3e5e-387d-11e6-849e-caff4614c966.png)

The committee ID presented in the examples under the search box on the data landing page doesn't look valid. I think there should be a real example? Also, should there be an example for Candidate & Committee IDs? Just a thought.

**Comment by noahmanger** [comment]
Good catch @patphongs ! What ID should we use. @PaulClark2 or @ChristianHilland do you have thoughts?

**Comment by jenniferthibault** [comment]
We talked through this is Slack this morning—there was no preference for which specific entities to show, but we decided on the following logic:
- We'd use the corresponding ID's for the candidate and committee names selected, in a format close to how things are presented in the typeahead
- Examples should not be current candidates or their committees
- Use an example of one democrat and one republican (not one D and a  PAC, or one R and a PAC)

Which updates our example to: 
_Example: Obama for America, C00431445; Bush, George W., P00003335_

Being addressed in #1306

**Comment by noahmanger** [comment]
Resolved in #1306
