### ISSUE TITLE
Obama for America

### ISSUE THREAD

**Issue by patphongs** [18F/openFEC-web-app#1298]
![screen shot 2016-06-22 at 2 04 10 pm](https://cloud.githubusercontent.com/assets/12799132/16277739/3c22f39c-3882-11e6-9363-e9b1029594d5.png)

![screen shot 2016-06-22 at 2 02 29 pm](https://cloud.githubusercontent.com/assets/12799132/16277678/fd731870-3881-11e6-87b7-2c308a12a554.png)

This seems to be an issue in production as well. The type ahead will be able to find Obama for America, only if you type "obama for a", anything typed passed that, it cannot find it.

**Comment by noahmanger** [comment]
Strange! Thanks for catching.
