### ISSUE TITLE
Close Glossary Interaction

### ISSUE THREAD

**Issue by patphongs** [18F/openFEC-web-app#1299]
When the glossary side panel close button is clicked, the page will automatically scrolls all the way to the top. It would be best if we can have it stay where it was, so the user won't lose their place in the content they were looking at. Especially if the user is scrolled fairly far down the page.

![interactive_glossary_scroll_bug](https://cloud.githubusercontent.com/assets/12799132/16278436/fe0c871e-3884-11e6-8bf5-bb02b36dd31e.gif)

**Comment by noahmanger** [comment]
Good suggestion. We've heard this before. Moving to the backlog.

**Comment by noahmanger** [comment]
@xtine for future reference, the glossary code is all handled here: https://github.com/18F/glossary . We'll then need to republish to NPM, likely with a minor version bump.

**Comment by xtine** [comment]
Update to glossary code here: 18F/glossary#24

**Comment by noahmanger** [comment]
Resolved.
