### ISSUE TITLE
Design improved data table experience

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1303]
*This issue is synthesizing several issues, including usability findings, including https://github.com/18F/fec-style/issues/270 , https://github.com/18F/openFEC/issues/1726 , https://github.com/18F/openFEC/issues/1653, https://github.com/18F/FEC/issues/370 and https://github.com/18F/openFEC/issues/1685*

So that users on desktop and mobile can better understand what data they’re looking at, improve the design of the filter + data table patterns to better communicate the state and status of data tables in relation to the filters. 

**Criteria for the design:**
- [ ] Users see a clear transition state upon applying filters to know that a change is in progress
- [ ] If the request is successful, users see a noticeable change, either in the results, the result count, or somewhere else
- [ ] If the request is not successful, they should see an error
- [ ] If the request has no results returned, they should see a message indicating no results 
- [ ] If the user is farther down the page and no results are visible, when they apply filters they should still know that something has happened
- [ ] Users understand what the dataset _is_ (this needs some more exploration about what type of things users need to know)

This issue will be complete once we have changes ready to be implemented, regardless of fidelity.

cc @jenniferthibault @onezerojeremy

**Comment by onezerojeremy** [comment]
Ok! Had some time to work on this yesterday, and have scheduled a initial critique session for late this afternoon with @noahmanger & @jenniferthibault. In advance of that, if folks have read-ahead time, here some things to look at. Target practice starts now!


## success metrics part 1
- [ ] Users see a clear transition state upon applying filters to know that a change is in progress
- [ ] If the request is successful, users see a noticeable change, either in the results, the result count, or somewhere else
- [ ] If the request is not successful, they should see an error
- [ ] If the request has no results returned, they should see a message indicating no results 
- [ ] If the user is farther down the page and no results are visible, when they apply filters they should still know that something has happened
I have two primary ideas for tactics that might address these. Both are essentially trying to nudge us toward tighter colocation of feedback with action taken. Tactic A is doing so through the use of in-place notifications, Tactic B is doing so through by bringing the tag system and filter control panel closer together. I put them together into pdfs, which feels like the wrong way to go, but I wanted to get youses something to look at. 
- Tactic A: in place notifications
![inplace notification](https://cloud.githubusercontent.com/assets/474916/16496746/89cdbc18-3ec1-11e6-922e-9128b705ef4f.png)

- [tactic A: in place notifications.pdf](https://github.com/18F/openFEC-web-app/files/341921/tactic.A.in.place.notifications.pdf)

- Tactic B: colocated tag system and filter system
![filters panel open summary filters](https://cloud.githubusercontent.com/assets/474916/16496736/78ab0832-3ec1-11e6-9ac6-1d059c29a885.png)


- [tactic B: consolidate filter triggers & actions.pdf](https://github.com/18F/openFEC-web-app/files/341923/tactic.B.consolidate.filter.triggers.actions.pdf)


## success metrics part 2
- [ ] Users understand what the dataset _is_ (this needs some more exploration about what type of things users need to know)
This might be helped by being a touch more explicit in how the filter tags live together. 
![conceptual and or](https://cloud.githubusercontent.com/assets/474916/16496426/c9567836-3ebf-11e6-9935-c7f8886c14bb.png)
Not terribly confident in this exact implementation but /shrug.

Notably, I haven't touched the results panel yet in wires (i have some sketches I can talk about at our afternoon design sync)

There are trade-offs in every direction, but I'm hoping something in here will spark something in yous.

**Comment by jenniferthibault** [comment]
Jotting some real fast thoughts now so I don't forget when we talk later!

- do users ever see the total number of results their search gives, or just how many a new filter increases/decreases the results by?
- are filters/tag panels open or closed by default?
- filter panel stacked on top: woah! breaking change for legal, would want to consult them if we go this way

Would love a walkthrough of B2 in your PDF — having a hard time understanding w/out notes or markup

Excited to talk later!

**Comment by jenniferthibault** [comment]
Notes from convo:

Tactic A:
- Is the button-y-ness important to this? Can we show progress without requiring the user to hit a button to start the effect (non- button notifier of activity)
- Is it possible to eliminate the first button/icon/element altogether and show progress 
- Consider alternate copy to test: "Added X results, Removed X results, Viewing x results, You've filtered away all the results"
- Need a new pattern for form-style validations or alerts
- Opportunity for subtle animations 

Tactic B:
- Bring in (#) applied in each accordion panel on desktop & mobile
- separate filters from tags: even when you close the filter panel, tags should be visible with the data
 - make filter panel not sticky on mobile so you can view more results
- status icon on the filters itself to show "filters applied"

Top horizontal filter panel:
- big pattern breaking change, but works for lots of reasons, hold of on implementing this until we see if their other smaller changes improve the experience

Tag top area: and/or
- Make comprehensible sentence out of it: Viewing 13,890 candidates matching: `tag` and `tag` and `tag`
- figure out the formula/visual expression of how to show x, y, and z for categories

Export area
- Add share
- on mobile, just share

**Comment by noahmanger** [comment]
Closing in favor of the more granular issues.
