### ISSUE TITLE
Optimize data table column widths 

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1304]
So that users can clearly read the data in the data tables, ensure that columns are sized appropriately. 

**Criteria for completion:**
The following pages should have columns with the proper widths:
- [x] Candidates
- [x] Candidates > President
- [x] Candidates > Senate
- [x] Candidates > House
- [x] Committees
- [x] Receipts
- [x] Individual contributions
- [x] Disbursements
- [x] IEs
- [x] ECs
- [x] CCs
- [x] Filings
- [x] Candidate pages
- [x] Committee pages
- [x] Election pages

*This issue consolidates the following issues:
- https://github.com/18F/openFEC-web-app/issues/1263
- https://github.com/18F/FEC/issues/268
- https://github.com/18F/FEC/issues/369
- https://github.com/18F/FEC/issues/314
- https://github.com/18F/FEC/issues/131
- https://github.com/18F/openFEC/issues/1759

**Comment by noahmanger** [comment]
Ok! I've been spending some time on thi 

![image](https://cloud.githubusercontent.com/assets/1696495/16327478/21d9ceb8-3984-11e6-80d1-f99c3c58569a.png)

![image](https://cloud.githubusercontent.com/assets/1696495/16327479/27a10136-3984-11e6-8e0a-baa88f7568ae.png)

![image](https://cloud.githubusercontent.com/assets/1696495/16327480/2e75841e-3984-11e6-989d-7cf6cd4ded98.png)

Remaining to dos:
- [ ] Check how they look with open detail panel
- [ ] Check how they look at different screen sizes

**Comment by noahmanger** [comment]
One thing I'd love to solve: We have several columns that include _really_ long words, which can't break onto multiple lines:
![image](https://cloud.githubusercontent.com/assets/1696495/16352787/8c9634ba-3a26-11e6-9ac7-2b7000b92a28.png)

In some cases, these words are the longest thing in the column by far, forcing the column to take up more space than the data needs, and also they tend to run into the sort icons (which are just background images). @jenniferthibault any ideas? @emileighoutlaw any thoughts on how we could shorten language while still maintaining clarity?

**Comment by emileighoutlaw** [comment]
It looks like these columns are right below a big header that says "Disbursements" I be we can make "Disbursement amount" and "Disbursement date" just say "Amount" an "Date" without anyone being confused.

I'll keep thinking on the other two long column headers

**Comment by noahmanger** [comment]
I _think_ that could be possible, though there are cases where there's potentially multiple dates associated with a record (e.g. the date the transaction was made or received, the date it was reported to the FEC).

**Comment by jenniferthibault** [comment]
Yeah, remember that mega huge spreadsheet of all the filters and the columns for each data table? I think we hashed this out there, and it was determined that we needed to be specific.

**Comment by emileighoutlaw** [comment]
God, I have no memory of that, but I believe you that we hashed it out already. 

I've been brainstorming all afternoon, and I don't think there's a way to shorten these without using symbols as words, and for the sake of our lower level readers, we really don't want to do that.
