### ISSUE TITLE
Registration and Reporting Sticky Nav

### ISSUE THREAD

**Issue by patphongs** [18F/openFEC-web-app#1305]
There is an issue with the Registration and Reporting sticky nav on staging. This causes the menu to not be sticky. Got the error below when inspecting.

`7b553844284a.js:418 Uncaught SyntaxError: Failed to execute 'querySelector' on 'Document': '/data' is not a valid selector.`

**Comment by noahmanger** [comment]
Thanks @patphongs ! Fixed.
