### ISSUE TITLE
Infoviz: What's spent on day-to-day operating activities: Decide on what categories are shown

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC-web-app#1318]
Decide on what categories are in this chart on the spending breakdown page

![screen shot 2016-06-30 at 1 19 50 pm](https://cloud.githubusercontent.com/assets/11636908/16497505/5d6b87aa-3ec5-11e6-8dab-ef39434adc65.png)

Following task will be to write the copy for each category (heads up @emileighoutlaw) 

![screen shot 2016-06-30 at 1 20 54 pm](https://cloud.githubusercontent.com/assets/11636908/16497538/7f31912c-3ec5-11e6-87bb-782bab1a5513.png)

cc @noahmanger

**Comment by noahmanger** [comment]
I believe we want to use these disbursement purpose categories that we created for the disbursements page: 
![image](https://cloud.githubusercontent.com/assets/1696495/16601260/6048f6ca-42c0-11e6-93a8-d2f4e4e10260.png)

Written out:
Transfers
Contributions
Loan repayments
Refunds
Administrative
Travel
Fundraising
Advertising
Polling
Materials
Events
Other

@PaulClark2 and @amykort does that sound right?

**Comment by noahmanger** [comment]
And as soon as I submitted this I realized that we just want to include operating expenditures. So with that, my take would be that we just want:

Administrative
Travel
Fundraising
Advertising
Polling
Materials
Events
Other (maybe?)

So excluding: transfers, contributions, loan repayments and refunds.

**Comment by PaulClark2** [comment]
Noah, your second list seems right to me if we are just looking at operating expenditures and want to be consistent with the disbursements page.

**Comment by noahmanger** [comment]
Cool. What's included in the "Other"? Will that always be operating expenditures?

**Comment by PaulClark2** [comment]
I think I'm confused. Is the goal here to show all the ways committees spend their money?  Or are we just confirming we are capturing everything?

Doesn't [openFEC/data/functions/purpose.sql](https://github.com/18F/openFEC/blob/81aa0d02a1f7248b18df6fff80729a375b15653a/data/functions/purpose.sql) define these categories?

transfers
contributions
loan repayments
refunds
administrative
travel
fundraising
advertising
polling
materials
events

and other is anything not included above

**Comment by PaulClark2** [comment]
"Other" would include operating expenditures that are not included in the categories above and "other disbursements" reported on Form 3 Line 21, Form 3P Line 29 and Form 3X Line 29.

**Comment by noahmanger** [comment]
Thanks! My thought is this is most interesting as a look at operating expenditures. Seems like including "other" in the list makes sense in that case.

**Comment by emileighoutlaw** [comment]
One thing to note about "other" categories is that people really like to know what's contained within them. Is there any way to be more specific about what those might be? I'm not sure where we'd explain it, but in my experience readers really hone in and harp on "other" categories.

**Comment by PaulClark2** [comment]
I wonder if we need an "about these data" section like we have on the data visualization page?

**Comment by noahmanger** [comment]
Good call. We'll have a "methodology" pop up here, which seems like the right place to include that explanation. I'm going to close this.
