### ISSUE TITLE
Infoviz: Where contributions come from: Decide on how the financial range is broken down

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC-web-app#1320]
How many categories is the financial range broken into, and what are they?

![screen shot 2016-06-30 at 1 23 48 pm](https://cloud.githubusercontent.com/assets/11636908/16497621/f81acde2-3ec5-11e6-8179-9f56b058dfcc.png)

cc @noahmanger

**Comment by noahmanger** [comment]
Same thoughts as I shared here https://github.com/18F/openFEC-web-app/issues/1319#issuecomment-230612586

**Comment by noahmanger** [comment]
I think we should use the same approach I suggested over [here](https://github.com/18F/openFEC-web-app/issues/1319#issuecomment-231481658): 5 buckets of equal ranges, with the ranges determined once we actually know the min and max. And if we discover that the shape of the data isn't communicated well with these, we can look to other methods.

Should we close this?

**Comment by jenniferthibault** [comment]
Makes sense to me!
