### ISSUE TITLE
Request: Provide context for what is included in the data tables

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC-web-app#1322]
@noahmanger commented on [Tue Jun 21 2016](https://github.com/18F/FEC/issues/370)

Another comment shared offline: 

![image](https://cloud.githubusercontent.com/assets/1696495/16251498/5c31a946-37db-11e6-8445-7d5d0f872ccd.png)

I think this raises an interesting question about if we want to bring in the "About this data" pattern from the overviews to the data table pages. 

---

@jenniferthibault commented on [Thu Jun 30 2016](https://github.com/18F/FEC/issues/370#issuecomment-229743714)

Moving this to the workflow, with design dependencies in https://github.com/18F/openFEC-web-app/issues/1303

**Comment by noahmanger** [comment]
Thanks. Yep, totally a good thing to be looking at in the context of designing these patterns. I could see it potentially relating to thinking @onezerojeremy started on the filter tag area.

**Comment by jenniferthibault** [comment]
Partly related to #1330

**Comment by jenniferthibault** [comment]
This could be referencing two ways of answering "what you're looking at"

Very very quick concept mockups:

1: What is the methodology for gathering the data, which might have a solution like this:

![screen shot 2016-07-15 at 2 22 55 pm](https://cloud.githubusercontent.com/assets/11636908/16884700/d89ece6c-4a98-11e6-9af4-1ac70dfeb94a.png)

2: Tell me more about the subject matter of this data, which might have a solution like this:
![screen shot 2016-07-15 at 2 30 28 pm](https://cloud.githubusercontent.com/assets/11636908/16884721/f4625ac4-4a98-11e6-90d1-f2b3cd0e8bf0.png)

I think the second gives better context, and allows us to cross-link when helpful, though they aren't mutually exclusive.

Thoughts @onezerojeremy ?

**Comment by onezerojeremy** [comment]
I really like the idea of linking to a thing that talks about the committee types! 
I am worried about it pushing the data down the page a bit, which leads me toward *2*, though i will say that button title doesn't really announce that it will have that content to me, which makes me thinks "about this table" or similar might be a simpler prompt

**Comment by noahmanger** [comment]
I really like the content of 2 + the link to the different types. I think that's exactly the kind of context that comment was referring to. Seems smart and helpful. But I share the concern about it pushing the data down. Two ideas: 1) make it collapsible; 2) put it at the bottom, below the table.

**Comment by jenniferthibault** [comment]
<img width="896" alt="screen shot 2016-07-19 at 9 26 29 am" src="https://cloud.githubusercontent.com/assets/11636908/16951678/ff9c4ac8-4d93-11e6-895d-d4e4c2904292.png">

Coupl'a thoughts circling around:

What I think is successful about having this info visible is that it gives semi-confident users a clear way to validate if they are where they think they are. This could be especially helpful in the slight confusion we saw in earlier usability tests on the nav (which probably lives in a google doc which I can't find right now) about what things are named. Similar to how the [advanced data index](https://beta.fec.gov/data/advanced/) gives a broad overview of the data, but this would be more targeted and specific to each table. It also feels like adding a bit of context at the top makes the experience feel more like an actual web PAGE, not just a table on the website. You see this type of pattern on pages like [OpenSecrets](https://www.opensecrets.org/pres16/outsidegroups.php), which gives an editorial intro before the data tables. (Obvs, our intro wouldn't be editorial, and could be much much shorter). Since it creates more of a page feel, I'm less concerned with pushing the data down , since it's still the primary feature of the page, and the tag function space will be visible.

In general, I don't think we should consider the space below tables usable design space, except for legally required disclaimers or something, since it's only visible when you filter down to few enough results to see it. Otherwise, the tables are so long (especially since we made the text wrap to new lines) that I don't think users expect to find anything below them. (I have not observed this behavior, but have others?)

I guess I'm struggling with a "methodology" type button & modal combination because I'm not actually sure what would go in there, so I'm designing a bit blind and it feels like a big space for what could potentially be small content. That, OR, if the intention was to put all the type of content that the current FEC site has, that feels like toooooo much and maybe the wrong way to go about it, when perhaps info tooltips by the filters or column titles (or something else) would work better.
(sorry for the slow connection!)
![pkhbd9ej2n](https://cloud.githubusercontent.com/assets/11636908/16952066/ada6d092-4d95-11e6-9b89-227d30fb873a.gif)

**Comment by onezerojeremy** [comment]
So it seems like we've got a couple different things we're designing against here and I think it might make sense to do a short synchronous session to see if we can figure out a pattern that makes sense, and/or get consensus. 

What's keeping me from endorsing the visible text pattern outright: It has definitely seemed like a great number of folks don't read the one-to-two lines of text that goes under the heading (in usability testing). 

If folks are skipping the text and looking first at the data to see if they are where they need to be, we may want to consider how the data table itself can help describe what it contains. One thought to that end would entail switching out the "name" column title for a more descriptive one like "committee name". Notably, this doesn't solve the "candidate - committee" relationship confusion problem.

**Comment by jenniferthibault** [comment]
🕐 today at 4:30 ET/ 1:30 PT

**Comment by jenniferthibault** [comment]
Since this is a new area of learning, we are going to move this to the icebox until we've tested the changes to the filtering and tagging experience in the following issues:

https://github.com/18F/openFEC-web-app/issues/1328
https://github.com/18F/fec-style/issues/416
https://github.com/18F/openFEC-web-app/issues/1330
