### ISSUE TITLE
Show number of applied filters in accordion heading

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1327]
So that users know that a grouping of filters has filters applied within it, show the number of active filters in the accordion header area.

Example:
![image](https://cloud.githubusercontent.com/assets/1696495/16510948/ba583b18-3eff-11e6-9c29-ef742b29f394.png)

**Criteria for completion:**
- [x] When a filter is applied, the number increases by 1
- [x] When a filter is removed, the number decreases by 1
- [x] If no filters are applied, no numbers are shown
- [x] If filters are applied on page load, the numbers are shown

**Question:**
In a case like this:
![image](https://cloud.githubusercontent.com/assets/1696495/16510973/06ee2ea6-3f00-11e6-889b-e1951fe45a16.png)

Do we say the number of filters applied is 2 (Democrat and Republican) or 1 (Political party)? I _think_ it's more useful to show 2, as you'll see the number increment with every addition, but wanted to check.

cc @jenniferthibault @onezerojeremy

**Comment by jenniferthibault** [comment]
Yes, I'd also say 2. Same as the way I would expect the number to increase by each state you select.

**Comment by onezerojeremy** [comment]
Agreed. 2! State, or committee, or whatever. 

I think there is a weird thing here, which i came across when i was digging into the ixd: I think it's best articulated in thinking about the checkboxes for `individual` vs `committee` contributions. Effectively, this state, the default, 
<img width="185" alt="screen shot 2016-07-01 at 1 08 50 pm" src="https://cloud.githubusercontent.com/assets/474916/16528794/041a51cc-3f8d-11e6-887b-a5cebcf4d3c8.png"> 

is equivalent to this 
<img width="185" alt="screen shot 2016-07-01 at 1 08 56 pm" src="https://cloud.githubusercontent.com/assets/474916/16528800/0e815b7e-3f8d-11e6-9ffc-c1d27c665968.png">

This feels weird to me, but I haven't figured out if it's a big problem, or how to fix it.
