### ISSUE TITLE
Complete interaction design & visual style of in place notifications for filter panels

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC-web-app#1328]
So that users on desktop and mobile can better understand what data they’re looking at, improve the design of the filter + data table patterns to better communicate the state and status of data tables in relation to the filters.

Mockups to work off of:
https://github.com/18F/openFEC-web-app/issues/1303#issuecomment-229720027

![inplace notification](https://cloud.githubusercontent.com/assets/474916/16496746/89cdbc18-3ec1-11e6-922e-9128b705ef4f.png)

**Criteria for completion**
- [ ] Uses the new validation-style form alerts in https://github.com/18F/fec-style/issues/416
- [x] Complete interaction design of mockups 
- [ ] Visually style new patterns & elements

**Design considerations:**
- Is the button-y-ness important to this? Can we show progress without requiring the user to hit a button to start the effect (non- button notifier of activity)
- Is it possible to eliminate the first button/icon/element altogether and show progress (some ux-ey confirmation needed still, @onezerojeremy )
- Consider alternate copy to test: "Added X results, Removed X results, Viewing x results, You've filtered away all the results" ( @emileighoutlaw @onezerojeremy   )
- Opportunity for subtle animations (do in implementation stage)

**Comment by onezerojeremy** [comment]
Oh on the mock-ups, I had applied the pattern to searches and the state look-up. 

![inplace notification type-ahead](https://cloud.githubusercontent.com/assets/474916/16528979/2d6448de-3f8e-11e6-8d3a-362104c29332.png)

![inplace notification state selection](https://cloud.githubusercontent.com/assets/474916/16528983/32ce558a-3f8e-11e6-9ba0-a323c4c6773f.png)

but had not touched the ixd for date fields or check box fields.
![todo inplace notifications](https://cloud.githubusercontent.com/assets/474916/16529071/bbf159c0-3f8e-11e6-9257-472b8ed831e9.png)

So in getting back to the button question, i know that one reason to avoid buttons was to avoid the issue of "why do i need to submit this didn't it already"? Are there others? If not, I think given that the button is only active when there is something to submit, and then only on the search fields that don't have a selection built in which triggers, I think I might advocate for trying the button/notifier design on simple search fields (which currently lack the affordance of a trigger other than hitting `enter`), but only if i'm right in surmising that the use case we were struggling with previously is with a single submit button being available and that prompting the user to think "but wait didn't i just do that" and not something else.  

OH OH. Then I just remembered! Those fields submit on loss of focus, so even if it's not coded like a button, it'll work like one. heh. right?

And in no way should we remove the ability of users to hit enter and submit.

**Comment by onezerojeremy** [comment]
couple updates: 

adding check box: 
![inplace notifications checkboxes](https://cloud.githubusercontent.com/assets/474916/16595593/f2fcf5aa-42bd-11e6-8a85-467ff6359f4b.png)

adding state box:
![inplace notification state selection](https://cloud.githubusercontent.com/assets/474916/16595595/f655a990-42bd-11e6-8f8b-1f995cbaedbd.png)

**Comment by onezerojeremy** [comment]
Adding date: 
![todo inplace notifications date](https://cloud.githubusercontent.com/assets/474916/16598159/94b2730a-42ca-11e6-909b-955447c7eaff.png)

Which I think finishes the IXD lift here, but perhaps I'm wrong. thoughts @jenniferthibault @noahmanger ?

**Comment by noahmanger** [comment]
Yes! This is looking really sharp. I have some super granular questions and thoughts, but think it'd be easier to go over synchronously, so I just put time on the calendar to huddle up.

**Comment by jenniferthibault** [comment]
Wanted to first say that it is absolutely fabulous working with you in this way @onezerojeremy ! I feel like I could concentrate on the purely visual bits so much better when the interaction has been so well thought through. 

Below are the updated screens with visual styling. I focused mainly on:
- which icons to use for "in progress"
  - Let's go with the animated loading dots @noahmanger created for the data download pattern instead of the loading flag/graph, which doesn't work very well at small sizes 
- which icon to use for "apply" (when not a search field)
  - I'm interested in using the right-facing arrow that also commonly stands for "play" or "begin" 
- how to bring in form validation (all positive scenarios in this one, to be continued in https://github.com/18F/fec-style/issues/416 )
  - indroducing colored field borders & color-changing borders on applied filter check boxes
- type positioning
  - Making confirmation text flush left instead of right, and breaking into two lines so that we can line up the word for the thing that was applied, and the word for records changed.

The small IDX twiddly bits I included here from our char was to show that the applied filters also turn into check boxes above the form fields, as we discussed. The exception to this pattern seemed to be in fields without typeaheads—is that a mistake? See City  & Employer fields [here](https://beta.fec.gov/data/receipts/?two_year_transaction_period=2016&contributor_name=gates&contributor_city=boston&min_date=01-01-2015&max_date=07-08-2016&is_individual=true)

![inplace notification](https://cloud.githubusercontent.com/assets/11636908/16701502/23323fec-452e-11e6-9a53-5b93a8e6747b.png)


![inplace notification type-ahead](https://cloud.githubusercontent.com/assets/11636908/16701510/28010b20-452e-11e6-86f8-65ee6cb76d1e.png) 


![inplace notification state selection](https://cloud.githubusercontent.com/assets/11636908/16701513/2bb6860a-452e-11e6-8166-0bec630e6b31.png)

![inplace notifications checkboxes](https://cloud.githubusercontent.com/assets/11636908/16701534/52a172ac-452e-11e6-8c01-b6835236f237.png)

![inplace notifications date](https://cloud.githubusercontent.com/assets/11636908/16701535/52aa5a5c-452e-11e6-8434-96a3e1deba85.png)

Thoughts @noahmanger / @onezerojeremy ??

& I think read for @emileighoutlaw & I to synchronously go over microcopy

**Comment by noahmanger** [comment]
Hooboy. This looks _good_.

To answer your question about non-typeahead-fields and checkboxes, I believe that in general these filters only accept one value at time, unlike others that allow multiple. If they can accept multiple values, then I think we want them to trigger the checkboxes; if not, maybe the value just stays in the input. Though maybe that's confusing?

Again, this looks super solid. I don't have anything else now, but I'm looking forward to enlisting @xtine 's brain on this when she starts next week, which might provoke more questions or ideas.

**Comment by jenniferthibault** [comment]
Ahh yep, you're right, they only accept one. So a small change to the ending state of the search field without a typeahead, since we need to accommodate the clear "x" functionality in the design:

<img width="721" alt="screen shot 2016-07-08 at 5 33 05 pm" src="https://cloud.githubusercontent.com/assets/11636908/16702130/1e5a762a-4532-11e6-87e5-afbee0235fc6.png">

**Comment by emileighoutlaw** [comment]
Hello there fellow designers! Here's my content recommendation:

> Filter added.
> Increased by ##,### results.

> Filter removed.
> Increased by ##,### results.

> Filter added.
> Narrowed by ##,### results.

> Filter removed.
> Narrowed by ##,### results.


**My thinking (not required reading):**
I know it's possible to be more precise than `Filter removed`. However, personalizing these interactions to be specific (for example, `Date added` or `Party removed`) requires more effort on the reader's part to pay attention to the new text below every filter. These small seconds of attention add up to a lot of cognitive burden during extensive filter adding and over multiple searches. 

Consistency is key, so I wanted all the verbs to make sense as pairs and never change. In this case, I like `added` and `removed` for filters. And so I didn't want to reuse those terms for what happens with the results. Something looks funky about `Filter removed. Removed ##,### results`. Also, "removing" results doesn't feel as precise to me as "narrowing" results. Narrowing feels like we're getting closer to an answer; removing feels like taking something away.

**Comment by jenniferthibault** [comment]
This all feels so good, thank you for laying out your thoughts @emileighoutlaw ! I <3 to read them. 

I think this is ready for implementation. Upon being implemented, it will need to be  combined with the full validation pattern designed in https://github.com/18F/fec-style/issues/416#issuecomment-231495189

**Comment by noahmanger** [comment]
Last thing before we close this out: can you add designs for what the interaction looks like in order to remove the checkbox for a dropdown (from [here](https://github.com/18F/openFEC-web-app/issues/1124#issuecomment-232454818))?

I think it should work like this:
- Without hovering, there's no X visible in the checkbox
- When you hover, the X becomes visible
- Clicking the X removes the item completely (and unselects the filter)

**Comment by jenniferthibault** [comment]
Since @onezerojeremy 's out, I took a stab. Here's the addendum to the checkbox interaction above:

![screen shot 2016-07-14 at 11 34 04 am](https://cloud.githubusercontent.com/assets/11636908/16845462/f7901728-49b6-11e6-812a-2f5cd186e048.png)

**Comment by onezerojeremy** [comment]
Love it!

**Comment by noahmanger** [comment]
Good stuff. Closing.
