### ISSUE TITLE
Visual design of co-located tag and filter system

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC-web-app#1329]
So that users on desktop and mobile can better understand what data they’re looking at, improve the design of the filter + data table patterns to better communicate the state and status of data tables in relation to the filters.

Mockups & discussion to work off of:
#1303 (comment)

**Design considerations**
- Bring in (#) applied in each accordion panel on desktop & mobile 
- Make filter panel not sticky on mobile so you can view more results 
- status icon on the filters itself to show "filters applied" on trigger that opens the filter panel 
- Mobile: make filter area modal style: view only filters or only data 
- When filter modal is closed, make tags applied still viewable

**Comment by jenniferthibault** [comment]
Looks like mockups in https://github.com/18F/openFEC-web-app/issues/1330 are just about ready for styling

**Comment by jenniferthibault** [comment]
Alrighty!

Here are my styled interpretations of @onezerojeremy 's mockups in #1330 : All thoughts welcome. 

### Desktop, panel expanded:
- I'd like to prevent grouped categories from breaking into two lines unless the whole category takes up a full line from start to finish. This will mean the design leans heavy on the left-hand side, but will prevent disjointed categories
- 
![screen shot 2016-07-14 at 11 48 39 pm](https://cloud.githubusercontent.com/assets/11636908/16863305/2970b4ec-4a1f-11e6-8d10-569ecd843cde.png)

### Desktop, panel closed:
- I'm borrowing the pattern from the closed table of contents pattern established by eRegs on the legal side: Let's make that a codified closed/open pattern. https://beta.fec.gov/regulations/2-2/2015-annual-2#2-2
- the data table sale shouldn't actually change, this is the product of using quick screen shots in my design files instead of building the tables :)
![screen shot 2016-07-14 at 11 47 40 pm](https://cloud.githubusercontent.com/assets/11636908/16863341/82d46cc2-4a1f-11e6-8edd-73c84ee37594.png)

![screen shot 2016-07-14 at 11 56 38 pm](https://cloud.githubusercontent.com/assets/11636908/16863358/beccc1fc-4a1f-11e6-82b4-152f6f85be90.png)

### Mobile, panel closed:
- This shows that you'd be able to view the tags and the data at the same time, but you wouldn't see the filters and the data or tags at the same time, answering the question @noahmanger , @xtine and I were wondering earlier.
- A difference from @onezerojeremy 's design is that on mobile, the download button drops off, and you will be left with just the share button. Because we couldn't actually think of a scenario where you'd download this data on a tiny screen, but you _might_ send it to yourself for later or share it on social media.

![screen shot 2016-07-14 at 11 53 38 pm](https://cloud.githubusercontent.com/assets/11636908/16863394/ff3b203a-4a1f-11e6-9744-caa6f7745dae.png)

### Mobile, panel open:
- Question: this makes it so that the filter panel toggler is in the middle of the page, but the panel itself would start just below the page title. @xtine / @noahmanger is that possible or crazy?

![screen shot 2016-07-14 at 11 53 25 pm](https://cloud.githubusercontent.com/assets/11636908/16863456/c51451dc-4a20-11e6-82b9-6fd94bc0f738.png)

**Comment by noahmanger** [comment]
Just want to log the feedback that came up in our demo discussion: I think we need to keep tinkering with the "and" / "or" design of the tags. I think simply including "or" in between tags of the same category is an option, but I think we all agree it feels clunky and hard to read. So here's a few other ideas:
- Separate those tags by commas
- Change the text to be something like "AND is one of these political parties:" / "AND was active in one of these years:" 
- Don't show the "or" in the tags at all, but include it in the filters. Maybe something like:

![image](https://cloud.githubusercontent.com/assets/1696495/16935289/f2113ad4-4d12-11e6-9251-04f69bd57b11.png)

**Comment by jenniferthibault** [comment]
Here is the last revision for this sprint that moves this concept toward implementation and testing.

## Changes:
- Refined panel open/close interaction on desktop to more elegantly integrate the eRegs panel pattern
  - On desktop, moves panel _next to_ data table instead of _under_ it so that as filters are added, the tags generated that create line breaks do not force the filter panel to jump down underneath the users selector
  - On mobile, this allows us to move the filter panel above the tag area, instead of in between the tags and the table results
- Makes tag container full 3/4 width, and bordered by a thin line above (separating from title & export options), thick line below (separating from table) that both extend to the edge of the filter panel
- Advances the tag groupings by distilling the "and's" away into just bounded areas, and removing the discreet category titles, and adding an explicit "or" between elements inside a bounded area.
 - This is the first concept we want to test, and the fastest way to that is probably through code and usability tests in this scenario: we don't necessarily think this is the 100% solved combination of elements, but it gives us just enough to learn from by removing some of the previous clutter.
(H/t @tram for an excellent critique session that led to these refinements, and @onezerojeremy for taking through testing options)
  - These changes allow us to decrease the vertical space taken up by the category titles that would often induce line breaks 
- Makes "clear all filters" a link, or unstyled button instead of a shaded button, for visual competition and differentiating it from tag styling

**Desktop: Panel Open**

<img width="904" alt="screen shot 2016-07-20 at 6 32 57 pm" src="https://cloud.githubusercontent.com/assets/11636908/17005500/9a08e14c-4ea8-11e6-8a7c-e5289fd5bda3.png">


** Desktop: Panel Closed**

<img width="901" alt="screen shot 2016-07-20 at 6 33 07 pm" src="https://cloud.githubusercontent.com/assets/11636908/17005504/9dfdfbc0-4ea8-11e6-96f8-0441e1bcccbe.png">


**Mobile**

<img width="647" alt="screen shot 2016-07-20 at 6 35 02 pm" src="https://cloud.githubusercontent.com/assets/11636908/17005521/b66e4f8e-4ea8-11e6-90b1-b57c7984df70.png">

**Comment by jenniferthibault** [comment]
One last bit: here is how these style changes would impact the tag/filter area pattern on the calendar:

<img width="1043" alt="screen shot 2016-07-22 at 11 16 53 am" src="https://cloud.githubusercontent.com/assets/11636908/17061713/d55dbd0c-4ffd-11e6-8718-de4257eb347a.png">


Closing and moving to implementation:
[Implement new styles to filter panel and results area, # 1379 ](https://github.com/18F/openFEC-web-app/issues/1379)
[Implement new functionality and styles to tags](https://github.com/18F/openFEC-web-app/issues/1380)
