### ISSUE TITLE
Links to receipts and disbursements need transaction period 

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC-web-app#1334]
With out supplying the right 2-year period, it will default to the current two-year period and look for dates outside of the table. 

Example:

The link to all receipts on this page:
https://beta.fec.gov/data/committee/C00171140/?cycle=1984&tab=receipts

links to:
https://beta.fec.gov/data/receipts/?committee_id=C00171140&min_date=01-01-1983&max_date=12-31-1984&is_individual=true

instead of:
https://beta.fec.gov/data/receipts/?two_year_transaction_period=1984&committee_id=C00171140&min_date=01-01-1983&max_date=12-31-1984&is_individual=true

I think these links are on:
 - committee pages
 - election pages

**Comment by noahmanger** [comment]
Ok, I have a fix for this here: https://github.com/18F/openFEC-web-app/pull/1336

**Comment by noahmanger** [comment]
Resolved by #1336
