### ISSUE TITLE
Provide further context around totals data in methodology section

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1353]
So that users understand the total raising and spending shown on charts, include a part in the methodology explaining (in plain language) that the totals are drawn from the "total receipts" / "total disbursements" as reported, and might differ from the itemized transactions. 

As originally noted [here](https://github.com/18F/openFEC-web-app/issues/1333).

**Criteria for completion:**
- [ ] "About this data" components for raising and spending updated to include additional information about why the data only is for certain periods and why it may be different from itemized totals

**Comment by emileighoutlaw** [comment]
I'm adding myself to this, because this seems like something I should be working on!
