### ISSUE TITLE
Design small graph preview images for data visualizations

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC-web-app#1354]
Separated from https://github.com/18F/openFEC/issues/1761#issuecomment-230016005

The graph formats are still evolving, so this issue isn't quite ready yet, but we will need thumbnail images of the data breakdown topics

<img width="749" alt="screen shot 2016-07-13 at 10 02 27 am" src="https://cloud.githubusercontent.com/assets/11636908/16806120/32d62f06-48e1-11e6-983d-c16373ecf8b1.png">

<img width="745" alt="screen shot 2016-07-13 at 10 02 37 am" src="https://cloud.githubusercontent.com/assets/11636908/16806119/32d59a00-48e1-11e6-9787-0e2139d3352c.png">

**Dependencies:**
Graphic/table formats in
https://github.com/18F/openFEC-web-app/issues/1333

**Comment by jenniferthibault** [comment]
This seemed like a quick one to pick up that could improve the structure and hierarchy of the overview/breakdown sections, so I took a stab at it.

Initially when we were going to have all of these graphs within a short time of each other, I thought that more realistic mini icons of the graphs (like the image above) would be interesting, if we could keep the data generic.

Now that these have a more spread out timeline, I think basic icons would help fill the space without feeling too unique on their own. These feel like they serve the purpose of drawing the eye to the links for now, and give a hint of the type of presentation you'll find, but maybe we'd want to revisit the initial approach later when the other graphs have been implemented. 

**We could use the icons as placeholders for coming content**
![screen shot 2017-03-06 at 4 17 04 pm](https://cloud.githubusercontent.com/assets/11636908/23630288/955426f4-0288-11e7-81c2-d79d24db695e.png)
![screen shot 2017-03-06 at 4 17 12 pm](https://cloud.githubusercontent.com/assets/11636908/23630293/990b7bc6-0288-11e7-8595-149314c2ab87.png)

**Or we could drop the coming soon ones (as is the approach now) **
![screen shot 2017-03-06 at 4 17 29 pm](https://cloud.githubusercontent.com/assets/11636908/23630294/9911dd68-0288-11e7-8b9b-bc37cdaedad3.png)
![screen shot 2017-03-06 at 4 17 36 pm](https://cloud.githubusercontent.com/assets/11636908/23630295/9912c3a4-0288-11e7-9357-9d78f26d7df2.png)


**Front end question:**
Would we want to export the whole circle as the image? Or just the icon itself?

cc @noahmanger & @xtine

**Comment by xtine** [comment]
@jenniferthibault: as long as they follow the convention in this folder (https://github.com/18F/fec-style/tree/master/fec-icons/icons), then it would be flexible to change shape, size, colors, etc if we want to repurpose it for differently later on.

**Comment by jenniferthibault** [comment]
Great, just added them in #644

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/fec-style/issues/644
