### ISSUE TITLE
Implement new checkbox loading & completion states

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1362]
In order for users to better understand what data is showing when, implement the new checkbox loading and completion states as [designed here](https://github.com/18F/openFEC-web-app/issues/1328).

**Criteria for completion:**
- [x] Upon selecting a checkbox, show a loading indicator for 250ms or until the data is loaded, whichever is longer
- [x] Upon success, outline the checkbox target area in green and show a check mark icon
- [x] Fade out the check mark icon after 5 seconds
- [x] Upon unchecking a checkbox, show the loading indicator
- [x] Upon success, show the check mark, but not the green outline
- [x] Upon success for both deselecting and selecting, show a message stating how many results were added or removed

This should be the same for:
- [x] All checkbox filters on data table pages
- [x] All checkbox filters on the election pages
- [x] All checkbox filters on the calendar page

**Comment by noahmanger** [comment]
I made some progress on this, but handing off to @xtine  to finish up.

**Comment by xtine** [comment]
![uqsxixn2iy](https://cloud.githubusercontent.com/assets/24054/17167220/cca0774a-5390-11e6-97c9-41d927997fc4.gif)
