### ISSUE TITLE
Implement new text input filter loading and completion state

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1363]
In order for users to better understand what data is showing when, implement the new text input filter loading and completion states as [designed here](https://github.com/18F/openFEC-web-app/issues/1328) and [here](https://github.com/18F/fec-style/issues/416)

![image](https://cloud.githubusercontent.com/assets/11636908/16701502/23323fec-452e-11e6-9a53-5b93a8e6747b.png)

![image](https://cloud.githubusercontent.com/assets/1696495/16970981/c02002cc-4dd4-11e6-847a-487188f4a502.png)

**Completion criteria:**
- [x] All text inputs filters have buttons with the appropriate icons (hint: use the `.combo` pattern `_form-styles.scss`
- [x] On hitting enter, blurring the input, or clicking the button, the button shows the loading indicator for a set amount of time
- [x] Upon success, the message shows the amount of results added or subtracted

Note, partially dependent on some UX design work happening here https://github.com/18F/openFEC/issues/1828

**Comment by xtine** [comment]
![vu6d7phxbu](https://cloud.githubusercontent.com/assets/24054/17167277/1c053f00-5391-11e6-94a6-fec3e981ed43.gif)
