### ISSUE TITLE
Implement new date filters

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1364]
In order for users to better understand what data is showing when, implement the new date filter s as [designed here](https://github.com/18F/openFEC-web-app/issues/1375).

**Completion criteria:**
- [x] Each stage of the interactions designed below are implemented for all date fields
- [x] Date inputs formatted as `mm/dd/yyyy` (slashes instead of dashes)
- [x] Loading message appears after the month picker if it's visible, or after the date inputs if it isn't

Note: this should work across all types of date fields, including those that don't have the "transaction period" filter. For an example of those, go to localhost:3000/independent-expenditures

**Comment by noahmanger** [comment]
We have some more design work to do before we can tackle this (https://github.com/18F/openFEC-web-app/issues/1375), so I'm going to suggest we move this out of this sprint since we have enough front-end to do as is.

**Comment by noahmanger** [comment]
Designs: ![image](https://cloud.githubusercontent.com/assets/474916/17559434/3cf63578-5eec-11e6-886d-208649fb1ffa.png)

**Comment by emileighoutlaw** [comment]
👋 ! The content in these designs looks solid to me!

It's much clearer now what the relationship is between the 2-year period and the date filters. And I am loving "Time period" as a choice for the microcopy.

I'm excited to see "beginning" and "ending" from our tag filters brought into the specific filters. That's a great move for consistency, and it hadn't even occurred to me. 

Is there something else I can be helpful with here, other than praising y'all?

**Comment by noahmanger** [comment]
Sounds good! I just updated the issue with completion criteria too.

**Comment by jenniferthibault** [comment]
Corresponding tag designs are in https://github.com/18F/openFEC-web-app/issues/1541

**Comment by noahmanger** [comment]
Note: need to refine the language on the labels to capture the "through"-ness of the date. @emileighoutlaw

**Comment by emileighoutlaw** [comment]
By "throughness" we mean the fact that it is inclusive of the ending day? @LindsayYoung

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/fec-style/pull/494
