### ISSUE TITLE
Migrate filings table off of data warehouse

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1371]

**Comment by LindsayYoung** [comment]
We want to accomplish quite a few things with this data, we first need to confirm all of these things are possible.

 - [ ] add filing_id (fix 18F/openFEC#1824)
 - [ ] add download link to the .fec file (would like it to use the .csv file extension)
 - [ ] have a clear boolean that shows if a record has been amended, and filter by that
 - [ ] link from an amended file to the amendment
 - [ ] link from an amendment to the amended file
 - [ ] confirm we still have RFAIs and all documents and forms
 - [ ] look at Jeff's sorting formula (There is an issue for it somewhere)
 - [ ] indicator if the filings are paper or electronic https://github.com/18F/openFEC/issues/1824

Here is the schema of the new table

Column         |            Type             | 
---|---|---
sub_id            |      sub_id   | 
cvg_start_dt           | numeric(8,0)                | 
cvg_end_dt             | numeric(8,0)                | 
receipt_dt             | numeric(8,0)                | 
election_yr            | numeric(4,0)                | 
cand_cmte_id           | character varying(9)        | 
form_tp                | character varying(8)        | 
rpt_yr                 | numeric(4,0)                | 
rpt_tp                 | character varying(3)        | 
amndt_ind              | character varying(1)        | 
request_tp             | character varying(3)        | 
to_from_ind            | character varying(1)        | 
begin_image_num        | character varying(18)       | 
end_image_num          | character varying(18)       | 
pages                  | numeric(8,0)                | 
ttl_receipts           | numeric(14,2)               | 
ttl_indt_contb         | numeric(14,2)               | 
net_dons               | numeric(14,2)               | 
ttl_disb               | numeric(14,2)               | 
ttl_indt_exp           | numeric(14,2)               | 
ttl_communication_cost | numeric(14,2)               | 
coh_bop                | numeric(14,2)               | 
coh_cop                | numeric(14,2)               | 
debts_owed_by_cmte     | numeric(14,2)               | 
debts_owed_to_cmte     | numeric(14,2)               | 
hse_pers_funds_amt     | numeric(14,2)               | 
sen_pers_funds_amt     | numeric(14,2)               | 
oppos_pers_fund_amt    | numeric(14,2)               | 
cand_pk                | numeric(19,0)               | 
cmte_pk                | numeric(19,0)               | 
tres_nm                | character varying(38)       | 
file_num               | numeric(7,0)                | 
prev_file_num          | numeric(7,0)                | 
lst_updt_dt            | timestamp without time zone | 
rpt_pgi                | character varying(5)        | 
pg_date                | timestamp without time zone |

**Comment by noahmanger** [comment]
It looks like RFAIs aren't currently included https://fec-stage-proxy.18f.gov/data/filings/?data_type=processed&form_type=RFAI

**Comment by jontours** [comment]
Ah, looks like there is a table disclosure.nml_form_rfai.  So they may be stored separately now.  I'll see if it will be simple to reference that table.

**Comment by jontours** [comment]
Okay after looking at the RFAI(s), which seem to be a type of notice that refers to an actual filing, they are mostly informational and have no reference to dollar amounts or anything, yet are still considered a filing conceptually?  Just want to make sure that seeing a bunch of zeros for the different amounts is to be expected for an RFAI type row.

**Comment by noahmanger** [comment]
Yes, that's right. They're just letters that the FEC sends. TBH I'm not sure why we've put them in the `/filings/` endpoint. @LindsayYoung can speak to that. But yeah, that's expected.

**Comment by noahmanger** [comment]
With RFAIs in and this shipped, I'm closing this.
