### ISSUE TITLE
Implement new functionality and styles to tags

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC-web-app#1380]
So that users on desktop and mobile can better understand what data they’re looking at, improve the communication framework used by the tags that show selected filters.

Using the designs from [Visual design of co-located tag and filter system #1329](https://github.com/18F/openFEC-web-app/issues/1329#issuecomment-234105298) for implementation on all data tables and the calendar 

**Criteria for completion**
- [x] Change intro copy to "Viewing   [x computed number x]   filtered results for:"
- [x] When any new filter is _applied_, [x computed number x] updates to show new calculation of results
- [x] When any new filter is _removed_, [x computed number x] updates to show new calculation of results
- [x] Add `$gray-light` container around tags in a category
- [x] When multiple filters in the same category are applied, an `or` is added between them
- [x] When filters are removed from a category, the `or` is also removed from between the generated tags
- [x] If adding a tag within a category would cause the line to break, the whole category moves to the next line.
- [x] strings of `or` tags should not break across lines _unless_ that category already takes up the _entire_ first line
- [x] Restyle "Clear all filters" as an unstyled button, anchored to the top right of the tag container 
- [ ] Review w/ @onezerojeremy & @jenniferthibault

**Comment by noahmanger** [comment]
I got a start on some of these elements in https://github.com/18F/openFEC-web-app/pull/1388 and https://github.com/18F/fec-style/pull/446 , but will leave the rest for separate PRs.

**Comment by xtine** [comment]
This is ready for a design review: https://github.com/18F/fec-style/pull/473

**Comment by noahmanger** [comment]
I just merged in the code, but will keep this open until the design review is complete.

**Comment by jenniferthibault** [comment]
👀 👍 ⚡  I don't have any changes.

**Comment by jenniferthibault** [comment]
Aw rats. Ok so I still stand by that statement. Stylistically, 👍 💯 

But immediately after posting that, I noticed one functional speedbump. 

If users can't remove the election cycle tags, how would someone change the cycle they're looking at? Adding a new one just makes "or" combinations that you can't clear out of.

<img width="1276" alt="screen shot 2016-08-22 at 10 07 45 am" src="https://cloud.githubusercontent.com/assets/11636908/17857583/51434d5a-6850-11e6-84b5-5ef37ea9bcdd.png">

**Comment by noahmanger** [comment]
Oh good catch. I just filed a patch for that: https://github.com/18F/fec-style/pull/481
