### ISSUE TITLE
Request: Redesign mega menu

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#1398]
The drop-down box is too busy:
![image](https://cloud.githubusercontent.com/assets/11817734/17479342/1b17c834-5d40-11e6-8f2b-ccfd8e81d868.png)

**Comment by jwchumley** [comment]
This one was strongly and universally disliked. I think for 2 basic reasons. 
1. It is easy to accidentally mouse  over and pop it up and sometimes hard to make it go away so annoying factor can be high.
2. The wording and groupings could be improved
       a. The word "profiles" wasn't recognized has helpful or having clear meaning.
       b. Committees is kind of small and hidden instead of prominent and near Candidates. They kind of go hand in hand and we often consider them as a set.

Priority: Medium but if effort is low payoff is relatively big.

**Comment by noahmanger** [comment]
Redesigned.
