### ISSUE TITLE
candidate profiles

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#1401]
Why is Hillary for America NOT listed first:
![image](https://cloud.githubusercontent.com/assets/11817734/17479437/8fbd6c02-5d40-11e6-850b-d4cfb2486262.png)

Shouldn’t the ACTIVE committee be listed first?

**Comment by noahmanger** [comment]
Duplicate of https://github.com/18F/openFEC-web-app/issues/1452

**Comment by jwchumley** [comment]
Principal campaign committee for the selected time period should be first or only. Other committees that are related have a place lower on the screen.
Priority: High
