### ISSUE TITLE
Request: Change presentation of authorized committees on candidate page

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#1402]
Delete the years for the campaign committees
![image](https://cloud.githubusercontent.com/assets/11817734/17479459/a4889940-5d40-11e6-9ee8-ae930922fce4.png)

It makes it look like 2008, 2010, and 2012 Election Cycle numbers are included in the totals.

**Comment by noahmanger** [comment]
Related from https://github.com/18F/openFEC-web-app/issues/1403 :
> For candidates with multiple such as the one listed above, perhaps an Active/Termination terms be added:
![image](https://cloud.githubusercontent.com/assets/11817734/17479475/b70a892a-5d40-11e6-9205-d93567c3d5c9.png)

**Comment by noahmanger** [comment]
And from https://github.com/18F/openFEC-web-app/issues/1457: 
> Campaign Committee blocks include total existence range years at the bottom of the block but it is at odds with the selected time period (cycle, 2 year period, etc) so it is confusing. Replace with a simple Active/Terminated marker.

**Comment by noahmanger** [comment]
Addressed by new candidate page designs.
