### ISSUE TITLE
Content: Add active and terminated tags to campaign committees

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#1403]
For candidates with multiple such as the one listed above, perhaps an Active/Termination terms be added:
![image](https://cloud.githubusercontent.com/assets/11817734/17479475/b70a892a-5d40-11e6-9205-d93567c3d5c9.png)

**Comment by noahmanger** [comment]
Closing to consolidate discussion in https://github.com/18F/openFEC-web-app/issues/1402
