### ISSUE TITLE
Request: Change candidate filings to only show those for the current cycle

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#1406]
For All candidate filings, it list “All years”

![image](https://cloud.githubusercontent.com/assets/11817734/17479512/f0ad99ce-5d40-11e6-931d-35e408a77e5f.png)

How can it be “all years” when the default is the 2016 Election Cycle?  And if it is truly meant to be “all years”, where are her F2s from 2007 and 2008.

**Comment by jwchumley** [comment]
Inconsistent. It says All years but presents only the form 2s filed during the selected 2 year cycle.
Priority: Med

**Comment by noahmanger** [comment]
No longer relevant.
