### ISSUE TITLE
Known issue: Rename "other spending" tab

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#1407]
“Other spending”

![image](https://cloud.githubusercontent.com/assets/11817734/17479529/05736924-5d41-11e6-9cf8-c9e96d708df0.png)

Until you click on it, one might think that the CANDIDATE did some sort of spending.  Change the name of the tab.

**Comment by emileighoutlaw** [comment]
This comment was brought to Paul more than once.

We've also seen this reinforced in usability sessions. We've been a hemmed in in terms of what we've been able to call this, but I'd love to revisit

**Comment by jwchumley** [comment]
Indirect spending?
Priority high.

Good luck.

**Comment by PaulClark2** [comment]
I don't think "indirect" is going to work. IEs are by definition direct support or opposition to a federal candidate by a person or committee not "controlled" by the candidate.

**Comment by jwchumley** [comment]
Just a thought.

________________________________

**Comment by emileighoutlaw** [comment]
How about this:

<img width="939" alt="screen shot 2016-08-30 at 10 00 19 am" src="https://cloud.githubusercontent.com/assets/10552702/18094366/dc6434e6-6e98-11e6-9cac-73f757f5cd7e.png">


I think the important thing to get in the tab — the thing that we saw users look for time and again in testing — are the words "oppose" and "support"

**Comment by jenniferthibault** [comment]
Unsolicited $0.02: This helps me understand what to expect to find in each tab much better. Long-phases on tabs aren't ideal, but since we aren't (yet) cramped for real estate on these tabs, it feels like a good solution!

**Comment by noahmanger** [comment]
+1. While long, it's much more descriptive and helpful. @amykort and @jwchumley what do you think?

**Comment by emileighoutlaw** [comment]
Pinging @PaulClark2 @jwchumley and @amykort on this one again! What do y'all think of the proposed new content above?

**Comment by jwchumley** [comment]
I like it. It's clear.

**Comment by AmyKort** [comment]
I like it too.

**Comment by noahmanger** [comment]
Just implemented in a pull request. This can be included in this week's release.

**Comment by noahmanger** [comment]
Resolved by #1583
