### ISSUE TITLE
Request: Increase prominence of "other spending" explanation

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#1408]
More emphasis needs to be placed on this:

![image](https://cloud.githubusercontent.com/assets/11817734/17479546/1fabbfd0-5d41-11e6-9f51-910861a3a0b2.png)

**Comment by emileighoutlaw** [comment]
This is similar to, but not the same, as https://github.com/18F/openFEC-web-app/issues/1407.

I wonder if changing the title of the tab would resolve this; more clarity in the title might solve what I think this issue is aiming at: a better understanding of what's included here.

**Comment by PaulClark2** [comment]
I agree #1407 and #1408 are related. It seems to me #1408 is about making the explanatory text more prominent and #1407 is about changing the name of the tab.

**Comment by emileighoutlaw** [comment]
Hey @PaulClark2! Is this still an issue now that the tab looks like this:

<img width="872" alt="screen shot 2016-09-23 at 9 51 56 am" src="https://cloud.githubusercontent.com/assets/10552702/18790181/713e39bc-8173-11e6-86da-21fa48c3c52b.png">

**Comment by PaulClark2** [comment]
@emileighoutlaw I think we can close both #1407 and this issue, #1408.

**Comment by emileighoutlaw** [comment]
Great!
