### ISSUE TITLE
Microcopy— add adjective to more information icon

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#1410]
I believe the following should read, “More financial information about the 2016 Election”:

![image](https://cloud.githubusercontent.com/assets/11817734/17479586/594f4d10-5d41-11e6-9891-95df355a6630.png)

The term ”information” by itself is too board.

**Comment by emileighoutlaw** [comment]
This was reinforced by Paul in another issue. 

This would be an easy change. I'd recommend `More financial information` and cutting the content there
