### ISSUE TITLE
Necessity of "Has raised more than $0" filter

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#1412]
Is the following a necessary field

![image](https://cloud.githubusercontent.com/assets/11817734/17479660/bd5033ce-5d41-11e6-98cc-bb48494bfe03.png)

**Comment by jwchumley** [comment]
I think the discussion here was more about was the filter necessary not about the text.  Whether it should be checked or not by default and whether it should be higher in the set of filters so you don't have to scroll down to find it were mentioned. I think more discussion with users would be required to make a decision. One this
