### ISSUE TITLE
candidate search

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#1414]
Since the default appears to be the last election cycles, the “Election Year” field should reflect that

![image](https://cloud.githubusercontent.com/assets/11817734/17479701/0079a946-5d42-11e6-9842-b7f1f1bc4f55.png)

It should mirror the default or whatever the user has selected.

https://beta.fec.gov/data/candidates/?election_year=2012&election_year=2014&election_year=2016&office=H&state=NY&district=05&has_raised_funds=true

**Comment by noahmanger** [comment]
Closing in favor of #1486
