### ISSUE TITLE
more information panel - candidates

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#1415]
The “flyout” is annoying and useless

![image](https://cloud.githubusercontent.com/assets/11817734/17479967/9698f110-5d43-11e6-9eee-42ed6eb85a4f.png)

Get rid of it, remove the “triangle button” and put a link to the most recent F2. This comment applies to all instances of the "details" panel.  I shouldn’t have to click on a “flyout” to get a link to the original image. Perhaps have the “View original image” link could replace the “triangle” button.  

https://beta.fec.gov/data/candidates/?election_year=2016&has_raised_funds=true

**Comment by jwchumley** [comment]
A lot of dislike here. Mostly, I think no one would be annoyed by the flyout if it only contained secondary level information.  I actually think on the Candidate grid it is less of a problem than on some of the other grids like filings and transaction grids. I think we could convince Jason that the candidate grid is OK on this score especially if we eventually have a "New Statements of Candidacy" list and a "New Statement of Organization" list.
