### ISSUE TITLE
Improve multi-step export and download process

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#1418]
I clicked “Export this data” and window opens at the bottom. I waited about a minute and nothing happens. I then clicked on Download and then I get my options.
This is an unnecessary stop and the “Export this data” should take care of this step.

![image](https://cloud.githubusercontent.com/assets/11817734/17480105/4bcbb46e-5d44-11e6-8387-3eb842ae74b0.png)

**Comment by emileighoutlaw** [comment]
This is an interesting piece of feedback. Making a note here that I remember we tested this specific interaction back before we launched downloads.
