### ISSUE TITLE
Retitle manifest.txt to be something more human readable

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#1420]
What is the point of “Manifest.txt”? I would rather see a Metadata file that describes the columns in the data.csv file

![image](https://cloud.githubusercontent.com/assets/11817734/17480157/7a4610aa-5d44-11e6-9ae0-b9857996eecb.png)

**Comment by emileighoutlaw** [comment]
Readme was suggested as an alternate retitling in a separate issue (which I closed in favor of this one)

**Comment by jwchumley** [comment]
Yes. Readme.txt would be a better name.
Priority: Low
