### ISSUE TITLE
Request: Improve organization of CSV files

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#1422]
In the CSV file, what is the purpose of the following fields: district_number, election_districts, cycles, candidate_status (there is no example of what the letters mean), incumbent_challenge, incumbent_challenge_full (seems redundant given the previous category), load date.
The data should represent whatever the parameters that are set forth on the web page

**Comment by emileighoutlaw** [comment]
Porting over from another issue:

> In the CSV, the “duplication” of categories:
committee_type, committee_type_full
designation, designation_full
organization_type, organization_type_full
party, party_full
Pick one type

**Comment by emileighoutlaw** [comment]
Related to: https://github.com/18F/openFEC-web-app/issues/1435
