### ISSUE TITLE
Reconsider "special" treatment of super PAC and joint fundraising committees

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#1423]
Under Committee Type, why are the following given “special” treatment:

![image](https://cloud.githubusercontent.com/assets/11817734/17480225/e041d8e4-5d44-11e6-899c-15abc41d217e.png)

For the IEs, since there are only two, is a drop-down necessary?

**Comment by jwchumley** [comment]
Agree. IE doesn't need drop down.  Joint fundraising committee should be on the dropdown with the others instead of a checkbox to be consistent.
