### ISSUE TITLE
Request: Don't restrict contribution search to two years

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#1430]
A lot of my users like the fact that the current IC search goes back to 1997. 

![image](https://cloud.githubusercontent.com/assets/11817734/17480357/88ce8df4-5d45-11e6-91c2-75f30e97fde2.png)

**Comment by jwchumley** [comment]
There was major gnashing of teeth on this one. I don't expect a tech solution asap but I think we really need to find a way to search across time.
Priority: Volcano (It may not blow right away but it will blow eventually if we don't rectify the situation)
