### ISSUE TITLE
Request: Add receipts filter for zip code

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#1432]
Missing Zip Code

![image](https://cloud.githubusercontent.com/assets/11817734/17480409/c84f878a-5d45-11e6-9ad2-3fcf5d06d536.png)

The current IC search has this field

**Comment by jwchumley** [comment]
Must have zip
Priority: High

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/openFEC-web-app/pull/2148
