### ISSUE TITLE
Request: Add primary/general (PGI) election filter for receipts

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#1433]
Add a field which indicates if the contribution is a Primary, General, Special, or Other (when applicable)

**Comment by noahmanger** [comment]
Related request to show the column: https://github.com/18F/openFEC-web-app/issues/1493

**Comment by jwchumley** [comment]
This is a request to add PGI to the grid. Jason's request. Not sure if it was important to anyone else.
Priority: Dependant

The grids in general have a lot of issues so improving the grid is high but the specific issues with the grid I think can be addressed as a group and prioritized within the grid list.

**Comment by noahmanger** [comment]
Is the request for this to also be a filter as well as be displayed in the table?

**Comment by jwchumley** [comment]
I'll pass the question to the experts.

________________________________
