### ISSUE TITLE
Request: Re-arrange download columns

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#1435]
The CSV file is a MESS.
•	The Contributor should be listed first, not in column L
•	Have the NAME of the committee receiving the contribution be present
•	Too many useless columns:
 	  
![image](https://cloud.githubusercontent.com/assets/11817734/17480533/5de4811a-5d46-11e6-957a-673bed5162a8.png)
![image](https://cloud.githubusercontent.com/assets/11817734/17480538/6184cdac-5d46-11e6-9a11-ede21eb18798.png)
![image](https://cloud.githubusercontent.com/assets/11817734/17480542/64a2d236-5d46-11e6-96a6-4d4a0999386f.png)

The contribution is to the Candidate’s Committee, not the Candidate
     
![image](https://cloud.githubusercontent.com/assets/11817734/17480544/69590e58-5d46-11e6-954c-f6d991891ea7.png)
![image](https://cloud.githubusercontent.com/assets/11817734/17480551/6d9c2428-5d46-11e6-978c-25ff24b3a464.png)
![image](https://cloud.githubusercontent.com/assets/11817734/17480555/7140af68-5d46-11e6-91b0-2c02f6264511.png)
![image](https://cloud.githubusercontent.com/assets/11817734/17480558/750513e6-5d46-11e6-869f-23332381debe.png)
![image](https://cloud.githubusercontent.com/assets/11817734/17480561/77d9d796-5d46-11e6-8c5b-49d4a4877479.png)
![image](https://cloud.githubusercontent.com/assets/11817734/17480563/7a6ba3ea-5d46-11e6-836e-2ac97dd2fca6.png)
![image](https://cloud.githubusercontent.com/assets/11817734/17480566/7cc3a188-5d46-11e6-89fb-b78b1fe4dd14.png)
![image](https://cloud.githubusercontent.com/assets/11817734/17480568/7ff2bccc-5d46-11e6-9750-932f7d7dc2ab.png)
![image](https://cloud.githubusercontent.com/assets/11817734/17480572/8206d0ca-5d46-11e6-8216-022435dcbd8b.png)
 
       
•	Redundant columns:
 
![image](https://cloud.githubusercontent.com/assets/11817734/17480577/8864984e-5d46-11e6-8790-8c5fcbbf816f.png)
![image](https://cloud.githubusercontent.com/assets/11817734/17480581/8b0fd496-5d46-11e6-982e-64d4dcc3856a.png)
![image](https://cloud.githubusercontent.com/assets/11817734/17480582/8d231d9c-5d46-11e6-9eca-76fcd9f5b2b4.png)
![image](https://cloud.githubusercontent.com/assets/11817734/17480584/8fd60a72-5d46-11e6-88a7-a18845df4a2f.png)
![image](https://cloud.githubusercontent.com/assets/11817734/17480590/92409962-5d46-11e6-91ef-a7555cb841a4.png)
![image](https://cloud.githubusercontent.com/assets/11817734/17480592/949bf044-5d46-11e6-9973-9dbedf518fdc.png)

•	In Contribution Receipt Date Box:
 
![image](https://cloud.githubusercontent.com/assets/11817734/17480513/48b55904-5d46-11e6-991e-9978cbeaa87b.png)

It looks there is a place for the time. Needs to be removed
The CSV file should be short, sweet, and to the point.

**Comment by jwchumley** [comment]
I think including most of the columns is OK if the most important ones come first.
Priority: Medium
