### ISSUE TITLE
Question: What are old report types?

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#1439]
What does this mean
![image](https://cloud.githubusercontent.com/assets/11817734/17480660/f3921682-5d46-11e6-8a34-097dfa66b00d.png)

**Comment by noahmanger** [comment]
These are report types provided in the data. Is there any action to take here?

**Comment by PaulClark2** [comment]
I think these report types are taken from a DW table. The data limitations don't make sense.  Can we confirm we aren't using an old DW reference table for report type?

**Comment by jwchumley** [comment]
Priority : High 
because getting of warehouse!
