### ISSUE TITLE
Question: Placement of "year end" filter

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#1440]
Why is the Year-End no part of a drop-down

![image](https://cloud.githubusercontent.com/assets/11817734/17480676/0b3b2152-5d47-11e6-8426-90234a20f902.png)

**Comment by noahmanger** [comment]
It's it's own checkbox because otherwise it would be part of every dropdown, which would be duplicative (triplicative? quadruplicative?). Do we need to take further action on this?
