### ISSUE TITLE
Request: add export option for individual contributions by employer-occupation 

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#1445]
For Contributor Employer and Occupation, why is there no export option? No one is going to click through 13,000 and 5,000 records respectively 10 records at a time.

**Comment by emileighoutlaw** [comment]
This seems similar to (but not the same as): https://github.com/18F/openFEC-web-app/issues/1447

**Comment by jwchumley** [comment]
Agreed. Maybe adding an export all option?
Priority: Medium

**Comment by noahmanger** [comment]
We shipped this in the last release.
