### ISSUE TITLE
Request: Clarify "Other" in disbursement purpose

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#1446]
Disbursements by purpose, what is Other:

![image](https://cloud.githubusercontent.com/assets/11817734/17480776/8f96710e-5d47-11e6-9e1a-3ea8172f69b0.png)

Why not just have a listing of the disbursements.

**Comment by emileighoutlaw** [comment]
Additional feedback from other issues:

> The by-purpose option is problematic because "Other" is almost always the biggest category.
> Disbursement by recipient tab has bad data or unintelligible data - by purpose isn't useful because of all the "other" data.

**Comment by jwchumley** [comment]
Step one is define  for us what "other" means in this context. Step two may be changing the wording so the meaning is clear at first blush or removing other as an option:

Priority: Revisit

**Comment by emileighoutlaw** [comment]
Closing in favor of: https://github.com/18F/fec-cms/issues/523
