### ISSUE TITLE
Request: rename "between committees" label

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#1448]
Disbursements “Between Committees” doesn’t make any sense. Needs to be thought out better.

**Comment by jwchumley** [comment]
Example: It looks like ACTBLUE is giving a lot of money to committees on the between committees tab when they are actually just bundling money from people to the committees. It might be OK to have them there but I think you need to know at a glance that there is a difference between the $300,000 in earmarks through actblue and the $3000 actblue actually contributes to a committee.

Priority: High

**Comment by noahmanger** [comment]
No longer relevant.
