### ISSUE TITLE
Request: reduce size of header for candidate profiles

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#1451]
reduce size of header

![image](https://cloud.githubusercontent.com/assets/11817734/17481066/04a0c6f6-5d49-11e6-9e82-cef3e179df03.png)

**Comment by jwchumley** [comment]
Yep. Too much realestate
Priority: High

**Comment by noahmanger** [comment]
This work is done and merged in, though not live yet.
