### ISSUE TITLE
Request: Remove districts from presidential and senate pages

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#1453]
remove district from header for pres and senate candidates

**Comment by emileighoutlaw** [comment]
From another issue:

Is a District necessary for a Presidential Candidate

![image](https://cloud.githubusercontent.com/assets/11817734/17479645/a3dccbf0-5d41-11e6-89db-626db1fbfec0.png)

**Comment by jwchumley** [comment]
Priority: High
