### ISSUE TITLE
Request: Add export featuer to candidate profiles -> other spending

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#1462]
Add export feature

**Comment by noahmanger** [comment]
Adding the downloads for the other spending tables on candidate pages is something we want to do, but it's more complex than the exports on the schedule A and B tables. We did add the ability to change the number of items per page though. So it's just a question of how high a priority this is.

**Comment by PaulClark2** [comment]
I think fixing the receipts and disbursement aggregates is more important. For example, if you look at Clinton's disbursements beta "says" the campaign has only spent $34,000 on travel.  I know that amount should be in the millions. The problem is in data/functions/purpose.sql
`when cleaned ~* 'travel reimbursement|commercial carrier ticket|reimbursement for use of private vehicle|advance payments? for corporate aircraft|lodging|meal' then 'TRAVEL'`

I suspect there are similar problems with the receipts aggregates.

**Comment by AmyKort** [comment]
I agree that fixing the aggregates is a higher priority.

**Comment by noahmanger** [comment]
Ah ok. This sounds like a separate issue, so I'm going to open a new one for it over at #1658.
