### ISSUE TITLE
Request: Link financial summary items to transactions

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#1466]
detailed summary page lines should link to transactions

**Comment by jwchumley** [comment]
Priority: High

**Comment by noahmanger** [comment]
I've got a working, interim concept going that I show over in #1588. Take a look and let me know if it might help this issue for the time being before we have the chance to a more thorough design.

**Comment by noahmanger** [comment]
Per the discussion [here](https://github.com/18F/openFEC-web-app/pull/1588), the interim solution I tried out doesn't serve the need, so we'll revisit this when looking at the overall design of this section. Moving to the backlog.

**Comment by noahmanger** [comment]
Closing in favor of https://github.com/18F/openFEC-web-app/issues/2125
