### ISSUE TITLE
Request: remove financial columns from committee filings tab table

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#1473]
filings tab remove all financial data

**Comment by jwchumley** [comment]
Strong consensus. Other data much more important for grid like links to all kinds of download and display options, Page count, image number
Priority: High

**Comment by LindsayYoung** [comment]
We will want to do this work when we migrate off of the warehouse filings view

**Comment by noahmanger** [comment]
This is done.
