### ISSUE TITLE
Candidate Search/Filters

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#1483]
remove default dem and rep in search box

**Comment by emileighoutlaw** [comment]
Related: https://github.com/18F/openFEC-web-app/issues/1417

**Comment by noahmanger** [comment]
Is this referring to removing the examples here?

![image](https://cloud.githubusercontent.com/assets/1696495/17501521/732def04-5d94-11e6-8053-557bf73c8baf.png)

Or to including all party filters in the dropdown like #1417 ?

**Comment by PaulClark2** [comment]
It's about the party filter, like #1417

**Comment by noahmanger** [comment]
Ah great. Closing in favor of #1417.

**Comment by jwchumley** [comment]
Yep. 
Priority: High
