### ISSUE TITLE
Request: Link receipts disclaimer to information about filing schedules

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#1488]
receipts blurb link to chart to explain

**Comment by noahmanger** [comment]
What is this referring to?

**Comment by PaulClark2** [comment]
![image](https://cloud.githubusercontent.com/assets/11817734/17515077/47713e5a-5e04-11e6-805f-3f7362ee953a.png)

They wanted to explanatory text to be near or included with the data grid.
