### ISSUE TITLE
Request: Show primary/general election indicator on receipts

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#1493]
PGI indicator

**Comment by noahmanger** [comment]
Can you elaborate what this means?

**Comment by PaulClark2** [comment]
In the all receipts data grid, they would like to see the PGI for the transaction.

**Comment by noahmanger** [comment]
Sorry, what's the PGI? Brain is failing me.

**Comment by PaulClark2** [comment]
No worries.  PGI = primary / general indicator.  It indicates the contribution is designated for the primary, general or some other election.

**Comment by jontours** [comment]
Which with the new sched_a and sched_b schema (fec_vsum...), I think that is being exposed as `election_type`.  But the column is no longer `rpt_pgi` for sched_a and b.

**Comment by PaulClark2** [comment]
@jontours, yes `election_tp`  (`election_type`) is the pgi data in the underlying SA and SB tables.

**Comment by noahmanger** [comment]
This was resolved in the last release.
