### ISSUE TITLE
Respond to requests from FEC power users

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#1503]
Internal user needs. Feature changes and request that will help staff help users that call in with questions about campaign finance data, candidates and committees. 

This is just the first round. There are more to come. 
- [ ]   https://github.com/18F/openFEC-web-app/issues/1398
- [ ]   https://github.com/18F/openFEC-web-app/issues/1399
- [ ]   https://github.com/18F/openFEC-web-app/issues/1400
- [ ]   https://github.com/18F/openFEC-web-app/issues/1402
- [ ]   https://github.com/18F/openFEC-web-app/issues/1404
- [ ]   https://github.com/18F/openFEC-web-app/issues/1405
- [ ]   https://github.com/18F/openFEC-web-app/issues/1406
- [ ]   https://github.com/18F/openFEC-web-app/issues/1407
- [ ]   https://github.com/18F/openFEC-web-app/issues/1408
- [ ]   https://github.com/18F/openFEC-web-app/issues/1409
- [ ]   https://github.com/18F/openFEC-web-app/issues/1410
- [ ]   https://github.com/18F/openFEC-web-app/issues/1412
- [ ]   https://github.com/18F/openFEC-web-app/issues/1415
- [ ]   https://github.com/18F/openFEC-web-app/issues/1416
- [ ]   https://github.com/18F/openFEC-web-app/issues/1417
- [ ]   https://github.com/18F/openFEC-web-app/issues/1418
- [ ]   https://github.com/18F/openFEC-web-app/issues/1419
- [ ]   https://github.com/18F/openFEC-web-app/issues/1420
- [ ]   https://github.com/18F/openFEC-web-app/issues/1421
- [ ]   https://github.com/18F/openFEC-web-app/issues/1422
- [ ]   https://github.com/18F/openFEC-web-app/issues/1423
- [ ]   https://github.com/18F/openFEC-web-app/issues/1429
- [ ]   https://github.com/18F/openFEC-web-app/issues/1430
- [ ]   https://github.com/18F/openFEC-web-app/issues/1431
- [ ]   https://github.com/18F/openFEC-web-app/issues/1432
- [ ]   https://github.com/18F/openFEC-web-app/issues/1433
- [ ]   https://github.com/18F/openFEC-web-app/issues/1434
- [ ]   https://github.com/18F/openFEC-web-app/issues/1435
- [ ]   https://github.com/18F/openFEC-web-app/issues/1436
- [ ]   https://github.com/18F/openFEC-web-app/issues/1437
- [ ]   https://github.com/18F/openFEC-web-app/issues/1438
- [ ]   https://github.com/18F/openFEC-web-app/issues/1439
- [ ]   https://github.com/18F/openFEC-web-app/issues/1440
- [ ]   https://github.com/18F/openFEC-web-app/issues/1441
- [ ]   https://github.com/18F/openFEC-web-app/issues/1442
- [ ]   https://github.com/18F/openFEC-web-app/issues/1443
- [ ]   https://github.com/18F/openFEC-web-app/issues/1444
- [ ]   https://github.com/18F/openFEC-web-app/issues/1445
- [ ]   https://github.com/18F/openFEC-web-app/issues/1446
- [ ]   https://github.com/18F/openFEC-web-app/issues/1447
- [ ]   https://github.com/18F/openFEC-web-app/issues/1448
- [ ]   https://github.com/18F/openFEC-web-app/issues/1449
- [ ]   https://github.com/18F/openFEC-web-app/issues/1450
- [ ]   https://github.com/18F/openFEC-web-app/issues/1451
- [ ]   https://github.com/18F/openFEC-web-app/issues/1452
- [ ]   https://github.com/18F/openFEC-web-app/issues/1453
- [ ]   https://github.com/18F/openFEC-web-app/issues/1455
- [ ]   https://github.com/18F/openFEC-web-app/issues/1456
- [ ]   https://github.com/18F/openFEC-web-app/issues/1457
- [ ]   https://github.com/18F/openFEC-web-app/issues/1458
- [ ]   https://github.com/18F/openFEC-web-app/issues/1460
- [ ]   https://github.com/18F/openFEC-web-app/issues/1461
- [ ]   https://github.com/18F/openFEC-web-app/issues/1462
- [ ]   https://github.com/18F/openFEC-web-app/issues/1463
- [ ]   https://github.com/18F/openFEC-web-app/issues/1464
- [ ]   https://github.com/18F/openFEC-web-app/issues/1465
- [ ]   https://github.com/18F/openFEC-web-app/issues/1466
- [ ]   https://github.com/18F/openFEC-web-app/issues/1467
- [ ]   https://github.com/18F/openFEC-web-app/issues/1469
- [ ]   https://github.com/18F/openFEC-web-app/issues/1471
- [ ]   https://github.com/18F/openFEC-web-app/issues/1472
- [ ]   https://github.com/18F/openFEC-web-app/issues/1473
- [ ]   https://github.com/18F/openFEC-web-app/issues/1476
- [ ]   https://github.com/18F/openFEC-web-app/issues/1477
- [ ]   https://github.com/18F/openFEC-web-app/issues/1478
- [ ]   https://github.com/18F/openFEC-web-app/issues/1479
- [ ]   https://github.com/18F/openFEC-web-app/issues/1480
- [ ]   https://github.com/18F/openFEC-web-app/issues/1481
- [ ]   https://github.com/18F/openFEC-web-app/issues/1482
- [ ]   https://github.com/18F/openFEC-web-app/issues/1483
- [ ]   https://github.com/18F/openFEC-web-app/issues/1484
- [ ]   https://github.com/18F/openFEC-web-app/issues/1486
- [ ]   https://github.com/18F/openFEC-web-app/issues/1487
- [ ]   https://github.com/18F/openFEC-web-app/issues/1488
- [ ]   https://github.com/18F/openFEC-web-app/issues/1489
- [ ]   https://github.com/18F/openFEC-web-app/issues/1490
- [ ]   https://github.com/18F/openFEC-web-app/issues/1492
- [ ]   https://github.com/18F/openFEC-web-app/issues/1493
- [ ]   https://github.com/18F/openFEC-web-app/issues/1494
- [ ]   https://github.com/18F/openFEC-web-app/issues/1496
- [ ]   https://github.com/18F/openFEC-web-app/issues/1497
- [ ]   https://github.com/18F/openFEC-web-app/issues/1499
- [ ]   https://github.com/18F/openFEC-web-app/issues/1501
- [ ]   https://github.com/18F/openFEC-web-app/issues/1502

**Comment by emileighoutlaw** [comment]
Hey @PaulClark2! Thanks for putting this list together. One question— several of these issues are asking for very similar or the same functionality/features/edits. Would it be okay if I combined those issues (making note that we received more than one comment on the topic) to make things a little easier on our end?

**Comment by PaulClark2** [comment]
@emileighoutlaw, absolutely. I entered the issues in an unfiltered manner.  It makes sense to consolidate them when possible.

**Comment by PaulClark2** [comment]
Renaming some if the issues would probably help, too.

**Comment by emileighoutlaw** [comment]
Updated this issue to reflect the ones we've consolidated so far :)

**Comment by PaulClark2** [comment]
Closed & combined issues	|	Releated issues
----	|	----
1401	|	closed see 1452
1402	|	now includes 1403 and 1457
1403	|	closed see 1402
1410	|	now includes 1454 and 1485
1411	|	closed see 1453
1413	|	closed see 1480
1414	|	closed see 1486
1422	|	now includes  1424 - 1428
1424	|	closed see 1422
1425	|	closed see 1422
1426	|	closed see 1422
1427	|	closed see 1422
1428	|	closed see 1422
1430	|	now includes  1498 and 1500
1435	|	now includes 1475 and 1501
1446	|	now includes 1468 and 1770
1454	|	closed see 1410
1457	|	closed see 1402
1459	|	closed see 1407
1468	|	closed see 1446
1470	|	closed see 1446
1474	|	closed see 1449
1475	|	closed see 1435
1485	|	closed see 1420
1491	|	closed see 1434
1495	|	closed see 1432
1497	|	closed see 1499
1498	|	closed see 1430
1500	|	closed see 1430
1501	|	closed see 1435
