### ISSUE TITLE
Write content explaining efiling vs. processed

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1526]
For the new efiling view of filings, we need to explain what the difference is between efiling and processed data (as well as land on the terms we're using for each).

![image](https://cloud.githubusercontent.com/assets/1696495/17682115/720c1208-62fe-11e6-84d6-2f28191e47db.png)

This should be ideally about a sentence or less that explains:
- What's the difference between the two data sets?
- What's the advantage of using one over the other?
- That some filters are only available for processed data

Tagging in @emileighoutlaw , and would like any thoughts @LindsayYoung has.

**Comment by PaulClark2** [comment]
This might help. It's from the Press Office.

http://www.fec.gov/press/tutorials/tutorial_docs/tutorial2/rawdatainst.pdf

http://www.fec.gov/press/data_tutorials.shtml

"A .FEC file contains all the transactions disclosed in a campaign finance report, and it can be exported into a Microsoft Excel spreadsheet for easier use and sortability. A .FEC file of a committee’s electronically submitted report becomes available to the public within seconds of being uploaded to the Commission’s server. The transactions from these files are eventually processed into a cleaner format by FEC staff and made public through the Viewer’s Two-Year Summary tab; that process, however, can take from several days to a few weeks after a filing deadline to complete. That’s why it’s important to know how to use .FEC files if users need the data from newly filed campaign finance reports in a hurry."

**Comment by PaulClark2** [comment]
Now to answer Noah's questions. 
Efiling: faster, includes all transactions, might be missing recipient/payee committee IDs, does not include categorization codes for transactions 

Processed: takes time to process, FEC staff add recipient/payee committee IDs, FEC staff adds categorization codes for transactions

**Comment by emileighoutlaw** [comment]
I've been working with Lindsay, and we like this draft for content. Any thoughts @PaulClark2 ? 


>**eFiling data**
eFiling data contains raw information from electronic filings. eFiling data is made available quickly, as filings are uploaded to FEC servers. Use eFiling data to access the most recent, unrefined information. Use processed data to access more comprehensive search options and all years of data.

>**Processed data**
Processed data has been reviewed by the FEC using a multi-step process. This process can take days (for electronic filings) or weeks (for paper filings). Use processed data to comprehensively search FEC data. Use eFiling data to access the most recent, raw information.

**Comment by noahmanger** [comment]
I like it. Can we just add something to efiling explaining "Not all filters are available for eFiling data."

And maybe to this sentence "Use processed data to comprehensively search FEC data" add: "including all efilings once they have been processed." 

I kind of think we should make it explicit that the historic filings that were submitted electronically are all available.

**Comment by emileighoutlaw** [comment]
Yup! I like it. Newer: 

>**eFiling data**
eFiling data contains raw information from electronic filings. eFiling data is made available quickly, as filings are uploaded to FEC servers. Not all filters are available for eFiling data— use eFiling data to access the most recent, unrefined information. Use processed data to access more comprehensive search options and all years of data.

>**Processed data**
Processed data has been reviewed by the FEC using a multi-step process. This process can take days (for electronic filings) or weeks (for paper filings). Use processed data to comprehensively search all FEC data, which includes eFilings, once they're processed. Use eFiling data to access the most recent, raw information.

**Comment by PaulClark2** [comment]
Christian does not like "eFiling" because it's too limited he prefers ".FEC."  Both electronically filed reports and those converted from paper to machine readable data files are .FEC files. 

**.FEC data**
.FEC files are available to the public immediately after a committee files a report electronically with the Commission. The information available in these files comes directly from the committee's report in a raw data format. Use processed data to access more comprehensive search options and all years of data.
 
**Processed data**
Processed data has been reviewed by the FEC using a multi-step process. This process can take days (for electronic filings) or weeks (for paper filings). Use processed data to comprehensively search all FEC data, which includes eFilings, once they're processed. Use eFiling data to access the most recent, raw information.



---------------------------
If/When we add paper .fec files we can add this sentence before the last sentence in the ".FEC data" section. "The .FEC files of reports filed on paper are made available to the public after the data from the filing been entered into the agency's database."

**Comment by emileighoutlaw** [comment]
This gets a 👍 from me. Tagging in @LindsayYoung to double check that "immediately" is okay in the .FEC data section.

**Comment by LindsayYoung** [comment]
For eFiling, we are only showing the eFiled records, not all .FEC reports.

**Comment by emileighoutlaw** [comment]
Right— I think we're talking about that in Slack. Should have clarified that the thumbs up is pending that **and** your input on "immediately"

**Comment by noahmanger** [comment]
Agreed with @LindsayYoung .  if we're only showing data for electronically filed reports, shouldn't it be called that and not `.fec data`? I'm not wed to efiling, but maybe "raw data" or "raw electronic filings"

**Comment by PaulClark2** [comment]
I think `eFiling data` is fine. Now that it's clear to me that not all .fec files are included

**Comment by LindsayYoung** [comment]
:+1: Thanks Paul

**Comment by PaulClark2** [comment]
I'm also good with changing `immediately` back to `quickly` or something similar.

**Comment by noahmanger** [comment]
👍  ok excellent. Thanks!

**Comment by noahmanger** [comment]
So what's the final language?

**Comment by emileighoutlaw** [comment]
Was just posting that:

**eFiling data**
eFiling files are available to the public quickly after a committee files a report electronically with the Commission. The information available in these files comes directly from the committee's report in a raw data format. Use processed data to access more comprehensive search options and all years of data.
 
**Processed data**
Processed data has been reviewed by the FEC using a multi-step process. This process can take days (for electronic filings) or weeks (for paper filings). Use processed data to comprehensively search all FEC data, which includes eFilings, once they're processed. Use eFiling data to access the most recent, raw information.


Everyone 👍 to this?

**Comment by PaulClark2** [comment]
`This process can take days (for electronic filings) or weeks (for paper filings).` Do we need to note that reports converted from paper to machine readable data files are not available from this table? 

I'm not sure we need it but we mention paper filings in the processed section. Many of our users know we convert these to .fec files.

**Comment by emileighoutlaw** [comment]
Thinking about this for a second, I'm not 100% sure either way. So let's just leave it as is for now, and we can very easily update the text in our next release?

**Comment by noahmanger** [comment]
Excellent. Thanks all! Closing.
