### ISSUE TITLE
Implement date range tag designs

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC-web-app#1541]
From the designs in https://github.com/18F/openFEC/issues/1872#issuecomment-241447101

<img width="950" alt="screen shot 2016-08-22 at 11 11 22 am" src="https://cloud.githubusercontent.com/assets/11636908/17890806/2be9f2d2-6906-11e6-9d7e-3ec2519f5c7d.png">

**Criteria for completion**
- Data sets that require a two-year transaction period to be set are loaded with a pre-applied filter, and tag set `01/01/yyyy` (beginning year)- `12/01/yyyy`(ending year)
- Beginning date tag and ending date tag are non-removeable
 - Tags can be edited, but not removed
- When a user edits the time period within the two-year period, the tags update, but remain non-removeable
- Beginning date tag and ending date tag are separated by an en-dash (–) (`&ndash;`) with a space on either side ( – )...maybe more than one space? There should be a visual buffer space, but I'm not sure what the mechanics of it should be :)
- If a user selects "Clear all filters" or refreshes the page, the tag should return to the full two-year period default

cc @noahmanger @xtine

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/fec-style/pull/494
