### ISSUE TITLE
Implement financial range tag designs

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC-web-app#1542]
From the designs in https://github.com/18F/openFEC/issues/1872#issuecomment-241447101

<img width="843" alt="screen shot 2016-08-22 at 11 07 55 am" src="https://cloud.githubusercontent.com/assets/11636908/17891054/94e259fe-6907-11e6-8ca7-7a57801246b0.png">

**Criteria for completion**
- If a user sets only the lower financial limit, a tag is generated that says `$x or more`
- If a user sets only the upper financial limit, a tag is generated that says `$y or less`
- If a user sets both limits, the first tag converts to `$x` , an en-dash is added, and a second tag is added with the second limit `$y` (the same en-dash & spacing from #1541 should be used)
- Both limit tags are removeable
- If a user has two limits set and removes one, the remaining tag converts back to `$x or more` or `$y or less`
- If a user changes the value of an existing limit they set, the existing tag updates in place

**Comment by jenniferthibault** [comment]
cc @noahmanger @xtine

**Comment by noahmanger** [comment]
Resolved by

**Comment by xtine** [comment]
I just found a possible need to change the financial range tags. In Presidential/Senate/House Candidate pages, there are multiple currency range filters that might need extra descriptions:

<img width="1188" alt="screen shot 2016-08-26 at 10 53 07 am" src="https://cloud.githubusercontent.com/assets/24054/18001610/9f4e46de-6b7b-11e6-9f40-472d4361b1ec.png">

**Comment by jenniferthibault** [comment]
ahhhhh rats. I'd love to check this at our design/front end pair up next week. It throws a proper monkey wrench in things.

**Comment by jenniferthibault** [comment]
Quick update: we talked about this at our team critique yesterday and decided to keep any changes in the icebox for now, until we are able to prioritize https://github.com/18F/openFEC/issues/1653 (about confusion on how applied filter work) for testing given the range of changes we've made to the filter & tag interactions that remain untested.

When we can prioritize that for testing, we will revisit this issue to determine which approach we'd like to implement for testing.

cc @nickykrause @onezerojeremy (just for a heads up & wrapping yesterday's discussion)

**Comment by noahmanger** [comment]
👍 moving to icebox.
