### ISSUE TITLE
Design HTML templates for reports

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1551]
So that users can view and share an HTML representation of a report, design a standalone report page for the most common types of financial reports.

There are four main types of financial reports, each of which contains slightly different data, thus requiring slightly different designs:
- [Form 3](http://fec.gov/pdf/forms/fecfrm3.pdf): House and Senate financial reports
- [Form 3P](http://fec.gov/pdf/forms/fecfrm3p.pdf): Presidential financial reports
- [Form 3X](http://fec.gov/pdf/forms/fecfrm3x.pdf): PAC and party committee financial reports
- [Form 5](http://fec.gov/pdf/forms/fecfrm5.pdf): Independent-expenditure-only reports

On fec.gov, you can view an HTML version of [reports like this](http://docquery.fec.gov/cgi-bin/forms/C00575795/1091726/) as well as a [page-by-page PDF version](http://docquery.fec.gov/cgi-bin/fecimg?_201607319022081796+0).

The Form 3*s (not Form 5) follow the same general structure:
- Cover page with basic info
- Summary
- Detailed summary 
- Allocation by state (presidential reports only)
- Attached schedules, for itemizing info

The current HTML view on fec.gov shows everything _except_ the itemized schedule data.

The first set of work on this is definitely to define the scope of the work better, which is my job. Once that's done, we can discuss design work.

For starters, some of my questions about what these should contain:
- Report summary data: What do we include? Everything from the summary pages?
- Itemized transaction information: on the page, or just linked to from it?
- PDFs: Linked to from the page, or embedded somehow?
- Earlier, amended versions of the report: Are these linked to from it or contained on the page?
- Other _different_ reports from the same committee: Do we care about linking to these?

**Scoping tasks:**
- [ ] Identify which reports we want to include in the first round
- [ ] Identify what data the report pages should contain (via discussion here and sketching)

**Design tasks:**
_TBD_

**Comment by noahmanger** [comment]
Ok! Updated with much more context about what this is referring to @jenniferthibault.

**Comment by LindsayYoung** [comment]
For the HTML forms we should definitely include all the fields. The purpose of this page is to represent the report data. 

Conceptually, I think this is a great opportunity to move away from the PDFs. Especially for e-filing where the pdfs are processed and generated but are so large that they are not useful as pdfs.

That being said, we will continue to want a page-by page viewer and downloads for PDF for people who want them.
