### ISSUE TITLE
"Search Advisory Opinion" and "Search Regulations" is misaligned

### ISSUE THREAD

**Issue by porta-antiporta** [18F/openFEC-web-app#1555]
<img width="275" alt="screen shot 2016-08-29 at 9 33 04 am" src="https://cloud.githubusercontent.com/assets/16668007/18055561/fa3c602c-6dcd-11e6-823a-11c644cae8f0.png">

<img width="309" alt="screen shot 2016-08-29 at 9 51 03 am" src="https://cloud.githubusercontent.com/assets/16668007/18055604/2b7022e6-6dce-11e6-9539-ddd095f684b0.png">

The above two look awkward from a spacing perspective between the `Title` of the button and the `collapse arrow`

**Comment by jenniferthibault** [comment]
It looks like a slightly tweaked div structure could help here, where the icons are set to vertical centers and the text doesn't wrap around the icons.

Here's one and two line mockups:

<img width="387" alt="screen shot 2016-08-29 at 11 02 04 am" src="https://cloud.githubusercontent.com/assets/11636908/18056023/32a88d14-6dd8-11e6-9e8b-2eb73b49b634.png">

**Comment by noahmanger** [comment]
This was recently resolved.
