### ISSUE TITLE
"Advisory opinions" breadcrumb incorrect on AO canonical page

### ISSUE THREAD

**Issue by porta-antiporta** [18F/openFEC-web-app#1556]
https://fec-stage-proxy.18f.gov/data/legal/advisory-opinions/2005-01/

The `Advisory opinion` breadcrumb goes to the advisory opinion search results page without the search query string, yielding a No Results Found error.

Two options:
1. Return to the search results page with the query string
2. Go to the Advisory opinions landing page

**Comment by porta-antiporta** [comment]
Root cause:

/templates/legal-advisory-opinion.html line 4:
'{% set breadcrumb_links=[(cms_url + '/legal-resources', 'Legal resources'), (url_for('advisory_opinions'), 'Advisory opinions')] %}'

**Comment by porta-antiporta** [comment]
Option 2 fix : `url_for('advisory_opinions_landing')`

**Comment by porta-antiporta** [comment]
Just realized that Option 1 is not a possibility because the user could go to the canonical page directly, so there's no `query` possible; or they came from the universal search page.

Option 2 is the approach we will pursue.

**Comment by noahmanger** [comment]
Looks like the PR didn't automatically close this. Resolved in https://github.com/18F/openFEC-web-app/pull/1559
