### ISSUE TITLE
efiling report summaries not sorting by date

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1562]
On http://localhost:3000/reports/presidential/?data_type=efiling and other report pages, the efiling table isn't sorting correctly on receipt date:

![image](https://cloud.githubusercontent.com/assets/1696495/18070881/28d0ba6a-6e0e-11e6-9c16-efb0a3d1f88b.png)

I'm not sure if this is an API bug or a web app bug, but needs to be fixed before release.

**Comment by noahmanger** [comment]
Can you take a look at this too @jontours ?

**Comment by jontours** [comment]
Yeah this is expected, the code is currently commented out, and also an index needs to be added to `create_dt`, which this column maps to internally on the api.

**Comment by noahmanger** [comment]
Ah ha! Are we blocked on this then, or is it possible to do this for launch?

**Comment by jontours** [comment]
Nope no blockers, I might check with @LindsayYoung just to verify I have the syntax right for the sql statement.  Also may not be a bad idea to ask if it's ok to create the needed indices in the partners channel.

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/openFEC/pull/1921
