### ISSUE TITLE
Consistency of advanced data filters

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/openFEC-web-app#1566]
I noticed a couple places where we could improve the consistency of our data tags.

### Colons
When we have `Transaction period` we follow with a colon, so the tag looks like `Transaction period: 2015–2016`. I think we should probably do the same for "beginning" and "ending" tags, which currently _do not_ have colons.

So, moving from this:
<img width="734" alt="before" src="https://cloud.githubusercontent.com/assets/10552702/18109030/cd0f4a1c-6ed4-11e6-9d1a-bae54bd22934.png">
_current_

To this:
<img width="751" alt="after" src="https://cloud.githubusercontent.com/assets/10552702/18109036/d1b8c426-6ed4-11e6-9565-6fb210338ad5.png">
_proposed new. consistent and (I think) easier to read._

### Quotations
When users enter a name into the `Contributor` field, that name appears in quotes, a lá `"John"`. We don't use that same quotation approach for other free-text fields (`Employer`, `City`, and `Occupation`). It seems to me that logically we should either have all free-text fields appear in quotes or none of them. 

<img width="963" alt="screen shot 2016-08-30 at 5 07 57 pm" src="https://cloud.githubusercontent.com/assets/10552702/18109163/65ce064e-6ed5-11e6-9e7a-9d53fb2d65f7.png">
_current_

Do other designers have thoughts?

cc @noahmanger @xtine @nickykrause @jenniferthibault @onezerojeremy

**Comment by xtine** [comment]
**Date range tags**
Transaction period filters are already changing to this design #1541: 
<img width="244" alt="screen shot 2016-08-31 at 9 42 12 am" src="https://cloud.githubusercontent.com/assets/24054/18122009/4f78036a-6f5f-11e6-854f-84c777fe273f.png">

When only one date filter is specified (just beginning or ending) then it will show the text like it did before. Can add the colon in that instance.

**Removing quotations on names**
I didn't realize the quotes were on certain tags. I would agree to remove the quotations on names to keep it consistent with the other free text filters.

**Comment by jenniferthibault** [comment]
I thought that all free text filters were supposed to have quotes? To show that:
- It's free text, not an option chosen from a typeahead
- We are matching entries based exactly on what the user entered (in the case of a typo, for example)

My vote here then would be for universal consistency by adding the quotes to all free text filters (city, company, contributor name, etc)

**Comment by noahmanger** [comment]
Yeah, +1 to Jen. It's a distinction we deliberately introduced, so should keep it consistent.

**Comment by nickykrause** [comment]
agreed! +1 to all

**Comment by emileighoutlaw** [comment]
Woot! I totally agree that all free text filters should use quotes, for precisely the reasons Jen wrote. 

Moving this out of discussion and into implementation — I can implement, or one of our front end devs can?

**Comment by xtine** [comment]
@emileighoutlaw: Is this issue still relevant? I notice at least on dev, all free text fields I tried use quotes:

<img width="886" alt="screen shot 2016-09-23 at 1 18 52 pm" src="https://cloud.githubusercontent.com/assets/24054/18800166/5bdafee4-8190-11e6-9db7-e716980ce745.png">

**Comment by noahmanger** [comment]
Yeah this looks resolved to me. Closing.
