### ISSUE TITLE
Commissioner feedback: Clarify time periods on data profile pages

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1584]
@fec-issue-bot commented on [Thu Sep 01 2016](https://github.com/18F/FEC/issues/461)

## What were you trying to do and how can we improve it?
I am looking at Hillary Clinton&#39;s summary page.  It shows she has raised $326,859,456 and spent $268,592,357 ... as of what date in time is this data?  July 31, 2016?  The page doesn&#39;t say. 

## Tell us about yourself
Lee Goodman, Commissioner, FEC

## Details
* URL: https://beta.fec.gov/data/candidate/P00003392/
* User Agent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36

**Comment by noahmanger** [comment]
Question: On the [/candidate/totals/](https://fec-stage-api.18f.gov/developers/#!/candidate/get_candidates_totals) endpoint, the only date I see is the `load_date`. What does that refer to? Would displaying a date range that begins with Jan 1 of the current cycle and ending on the load date be accurate?

```
    {
      "district": "00",
      "candidate_inactive": false,
      "has_raised_funds": true,
      "cash_on_hand_end_period": 1574762.1,
      "disbursements": 250660754.75,
      "address_street_2": null,
      "election_districts": [
        "00",
        "00"
      ],
      "candidate_id": "P00003392",
      "name": "CLINTON, HILLARY RODHAM",
      "party": "DEM",
      "address_street_1": "PO BOX 101436",
      "two_year_period": 2008,
      "candidate_status": "C",
      "office": "P",
      "district_number": 0,
      "cycles": [
        2008,
        2010,
        2012,
        2014,
        2016
      ],
      "office_full": "President",
      "address_city": "ARLINGTON",
      "is_election": false,
      "receipts": 252235516.85,
      "election_years": [
        2008,
        2016
      ],
      "debts_owed_by_committee": 5943384.58,
      "cycle": 2008,
      "address_zip": "22210",
      "incumbent_challenge": "O",
      "federal_funds_flag": false,
      "election_year": 2008,
      "address_state": "VA",
      "party_full": "Democratic Party",
      "state": "US",
      "incumbent_challenge_full": "Open seat",
      "load_date": "2007-12-11"
    }
```

**Comment by noahmanger** [comment]
Capturing the results of a Slack conversation: Doing this requires adding `coverage_start_date` and `coverage_end_date` to this endpoint. Since this is a backend task, I'm going to move this to the backlog to be prioritized as such.

**Comment by noahmanger** [comment]
Further details from sprint planning: 
In cases where there's multiple committees included in the totals, the `coverage_start_date` will be the earliest `coverage_start_date` and the `coverage_end_date` will be the most recent `coverage_end_date`. 

This will need to adjust whether you're looking at the entire 4 or 6 year range or just 2 year chunks.

**Comment by jontours** [comment]
Digging into what's needed here.  I don't think it's going to be _too_ hard, some slightly clever sql may be needed.
