### ISSUE TITLE
Unverified Committees and Candidates

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC-web-app#1591]
There is always something new here at the FEC. As you all probably know when we made registering candidates and committees easier by putting it on line, we made it easier for people to create fictitious committees and candidates. In order to deal with this the commission now has a policy to identify and segregate these committees from actual committees. In the current website it will work like this:

If you search for committees or candidates anywhere you can currently search for them you won't find these fictitious ones. At the same time we are creating two new data catalog items: "Unverified Candidates" and "Unverified Committees" where you can find them and look at their filings.

We will need to do the same thing in betFEC.  I've created a table that is a single column and contains just the cand_cmte_id of unverified committees. I suspect it will need to be added to the API and worked into the existing beta code along with providing a search for unverified committees that also shows their filings.

I would think this might be a good project to work on during our shadowing period so our developers could use it to become familiar with the process of adding to the API and front end developing.

Priority is low but not super low.

**Comment by LindsayYoung** [comment]
Thanks Jeff. Improving data quality is A+ in my book!

**Comment by noahmanger** [comment]
Ditto! We're all excited about this.
