### ISSUE TITLE
Help users understand empty fields on Archived MURs

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC-web-app#1598]
Copying this issue out from @adborden's https://github.com/18F/openFEC-web-app/pull/1586#issuecomment-248478811 to think through.

Sometimes fields in a MUR page will be blank, even though the information is available if you open the PDF and read it. Here's an example:

http://localhost:3000/legal/matter-under-review/3584/

<img width="1073" alt="screen shot 2016-09-22 at 5 45 22 pm" src="https://cloud.githubusercontent.com/assets/11636908/18767306/5d5352a2-80ec-11e6-8498-be567c62de78.png">

Context from @adborden and @porta-antiporta 
> There's nothing we can do to get that information out. OCR will not pull out that kind of metadata. So we're just looking for what kind of cues and messaging to present the user in that case. Maybe some content explaining that not all archive MURs have metadata, but you can still search them and view the PDF.

**Steps to completion**

- [x] Search existing patterns for this principle in action
- [ ] Select approach
- [ ] Provide style/layout arrangement of pattern in context of MUR page
- [ ] Messaging review with @emileighoutlaw 
- [ ] Open new issue for implementation

**Comment by jenniferthibault** [comment]
There are two fields where this is relevant on AO pages:

1. **The summary categories:**

<img width="320" alt="screen shot 2016-09-30 at 2 59 59 pm" src="https://cloud.githubusercontent.com/assets/11636908/19003381/86d9180e-871e-11e6-8423-e220280b8fc2.png">

  - Open date
  - Close date
  - Summary
  - @adborden are we able to customize this "None" text that's there now? 
  - @emileighoutlaw if we can, would we want to enter something?

2. **The participants table**

<img width="475" alt="screen shot 2016-09-30 at 3 00 05 pm" src="https://cloud.githubusercontent.com/assets/11636908/19003391/8c8d8eec-871e-11e6-879c-a7b2129fbdda.png">


## Existing patterns
On principle, when data isn't available in templates we have told users: 
- that usually it should be there but in this case it isn't
  - if we know why, we say why
  - if we don't know why, we give them a chance to check it, or leave feedback


Our alert style patterns were set in this issue: https://github.com/18F/fec-style/issues/266#issuecomment-214425298

Based on this, the "RESULTS RETURNED" category seems to be the best fit. We could put this under the participants table:

![screen shot 2016-09-30 at 3 02 51 pm](https://cloud.githubusercontent.com/assets/11636908/19003466/eaf7fb02-871e-11e6-90d6-7c1c68338e69.png)

Copy 👓 from @emileighoutlaw definitely needed!!

**Comment by adborden** [comment]
Yeah, we can customize the text for those. I'm using "Unknown" already for the search results https://beta.fec.gov/data/legal/search/enforcement-matters/?search_type=all&search=vice+president

![screenshot from 2016-10-03 12-58-09](https://cloud.githubusercontent.com/assets/509703/19051781/14b27dcc-8969-11e6-8305-c8c2f2e1d2dd.png)

**Comment by emileighoutlaw** [comment]
Hey @jenniferthibault! Are you suggesting we use the alert pattern styling, so it would _look_ like this:

![screen shot 2016-09-30 at 3 02 51 pm](https://cloud.githubusercontent.com/assets/11636908/19003466/eaf7fb02-871e-11e6-90d6-7c1c68338e69.png)

Or is that alert just a possible content model?

It seems like an alert message might be a little intense for something that seems like an issue with the ability to pull and preview content from a case, right? Unless we want people emailing our team and letting us know? But how would they know if this is a mistake? 

If we're using the alert styling, I'd go with something like this:
> ### Participants
> **No content available**
Sometimes this information exists in case documents but isn’t readable by computers. Open the case for more information.

If we’re just adding a paragraph below the “Participants” header, I’d go with something like:
> ### Participants
> No content available: Sometimes this information exists in case documents but isn’t readable by computers. Open the case for more information.

### Button copy
Last note: I wouldn't say "view case," since people with screen readers won't be “viewing” it. How about “Open case” for the button? 



Let me know if I'm off track here, and we can chat!

**Comment by jenniferthibault** [comment]
@emileighoutlaw thanks for the good questions, and sorry for the gap in getting back to you!

The alert module I showed before was definitely just one option, and I appreciate the push to others for good reasons, I think you're right it does come off as too strong. 

I would like to keep within our existing alert pattern, but I think we can drop the headline and button architecture within it. Something like the style below will let us keep the visual consistency between alerts & commentary, but in a quieter way. 

![screen shot 2016-10-19 at 1 38 54 pm](https://cloud.githubusercontent.com/assets/11636908/19530471/05103d82-9602-11e6-9e19-5dbbe8871a2c.png)

As opposed to something like this, which feels too in-line to me:
<img width="725" alt="screen shot 2016-10-19 at 1 38 03 pm" src="https://cloud.githubusercontent.com/assets/11636908/19530515/2daf2654-9602-11e6-9bae-ac276afb2f8b.png">

On changing button copy from `View case` > `Open case`, it works for me, as long as we're consistent. I can't think of other times we've used `view`  yet, but it doesn't feel outside possibility. Any places we should check that you can think of?

Would you also change the text from Aaron's search results screenshot [above](https://github.com/18F/openFEC-web-app/issues/1598#issuecomment-251209584) to 'Unavailable'  instead of `Unknown` ?

**Comment by emileighoutlaw** [comment]
**Existing text**
Yes! Let's change the text from `Unavailable` to `Unknown`

**Styling of alert**
I like what you have above— I appreciate the pattern consistency but gentler tone

**Open case**
Good thought about consistency. For this, let's go with "open," (both in the alert message and on the button). I'll take on the task of hunting down and eliminating any other "view"s on the site.

**Comment by jenniferthibault** [comment]
Transferring to implementation in https://github.com/18F/openFEC-web-app/issues/1651
