### ISSUE TITLE
Update landing charts to use live data API

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1603]
So that users always see the most up-to-date information, update the data landing page charts to use the new API once https://github.com/18F/openFEC/issues/1953 is complete.

---

**Criteria for completion:**
- [x] The charts use data from the API
- ~~The charts allow users to navigate back to earlier two-year cycles using the arrows~~
- [x] The methodology is updated to acknowledge the data is live
- [x] The disclaimer is removed

**Comment by LindsayYoung** [comment]
Got a version going that returns:
```
{
   "year": 2015,
   "Receipts": -2051.35,
   "month": 1,
   "type": "party",
   "cycle": 2016
},
{
   "year": 2015,
   "Receipts": -1392.96,
   "month": 2,
   "type": "party",
   "cycle": 2016
},
```
If would be easy to add a date if you want it. 
We could try to group them by date but I don't know how I would do it off the top of my head.

**Comment by noahmanger** [comment]
Cool. Yeah, that's close. So does each object represent a monthly total? How do you know which month each applies to?

**Comment by LindsayYoung** [comment]
Yea, the total is the aggregate for that date. The year and month represent the date- I can just add date, to make it more intuitive.

**Comment by noahmanger** [comment]
Oh! I missed the `month` field.

**Comment by LindsayYoung** [comment]
OK, added a date field, I was originally afraid it might be confusing since we need a day, to make it consistent, it is the first of the month, I will try to add documentation so people don't think it applies to that day.

**Comment by noahmanger** [comment]
Could you make it the last of the month? If not, what about just a `MM/YYYY` format?

**Comment by LindsayYoung** [comment]
I can do the last day of the month and if that is in the future I can override it with yesterday's date. I can get rid of the month and year as separate vars.

sound good?

**Comment by LindsayYoung** [comment]
Now it looks like:
```
{
   "cycle": 2016,
   "type": "candidate",
   "receipts": 8252528.86,
   "date": "2015-09-30T00:00:00"
},
{
   "cycle": 2016,
   "type": "candidate",
   "receipts": 66310157.81,
   "date": "2015-12-31T00:00:00"
},
```

**Comment by noahmanger** [comment]
Excellent. Thanks!

**Comment by noahmanger** [comment]
We still need to update the methodology: 

![image](https://cloud.githubusercontent.com/assets/1696495/19581880/449df3a2-96e5-11e6-9cac-17b2024220e3.png)

@emileighoutlaw what language should we use to explain that the data is live? Or maybe nothing?

**Comment by emileighoutlaw** [comment]
Good catch. Explaining what "live" data is could get really complicated, and this is intended for beginning data users, so I'm inclined to say we keep it simple: 

> This data includes Forms 3, 3P, 3X, 5, 7 and 9.

**Comment by noahmanger** [comment]
That sounds right to me.

**Comment by noahmanger** [comment]
Ok, that change is here: https://github.com/18F/openFEC-web-app/pull/1646

With #1644 capturing the work to add pagination back in time, this will be closed once that PR is in.

**Comment by noahmanger** [comment]
Closing now that methodology is done via https://github.com/18F/openFEC-web-app/pull/1646
