### ISSUE TITLE
Design interaction for exporting and paginating aggregate tables

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1607]
So that users can more easily read the data contained in aggregate tables fond on candidate, committee, and election pages, add the ability to (a) change the number of pages and (b) export the data from these tables.

---

This task is just to design the interaction for these two additions, and I'll open a separate issue for implementation.

**Comment by noahmanger** [comment]
So this should be pretty simple as it's just applying functionality that we have elsewhere to a new circumstance. So I think we can basically just apply existing patterns to do something like this:

![image](https://cloud.githubusercontent.com/assets/1696495/18896825/bfda3eea-84d9-11e6-951b-f840929d5454.png)

This:
- Uses the same export button as on data table pages
- Aligns the button with the heading the way we do elsewhere
- Includes the page controls in the footer like we do on data table page

The only question I have is where the "showing X of X entries" should go. That option above includes it in the header next to the export button, which I think is useful so that it's contextually close to the export action and you know how many records you'll get.

The other option would be to put it next to the pagination buttons like so:
![image](https://cloud.githubusercontent.com/assets/1696495/18896861/fe6aff82-84d9-11e6-80d0-52ef4a011069.png)

Once an export is triggered, the interaction would work like exports on data table pages, where the footer banner appears and the export is processed:
![image](https://cloud.githubusercontent.com/assets/1696495/18896867/11c04722-84da-11e6-9e58-763ad0fc14cd.png)

For reference, to see these pages in the wild check out an example like: https://beta.fec.gov/data/committee/C00307314/?tab=receipts

cc @nickykrause and @jenniferthibault

**Comment by nickykrause** [comment]
Thanks @noahmanger!, cc @jenniferthibault 

My TL; DR thoughts on this: 
- Following the patterns we have in place for the placement of the export button and the pagination arrows makes perfect sense to me
- I vote for putting the "showing X of X entries" text at the bottom.

My thoughts on the  "showing X of X entries" text: 

I am sort of on the fence about the placement of the "showing X of X entries" text. I see your point about including it at the top next to the export button, to add context to that action, but I also see an argument for placing it near the pagination button, to give context to _that_ action. 

And, actually, I am thinking that there is conceptual similarity between the "showing X of X entries" text and the other items at the bottom: the "results per page" feature, as well as the arrows. They all collectively communicate to the users about "how many things" they are seeing. Perhaps that is an argument for the footer. 

But, a caveat to the footer idea could be that users will not want to look all the way to the bottom to see how many entries are being displayed (or they might not notice that text). This thought is inspired by the codesign sessions we did last week with legal search, where users pointed out that they wanted to see (at the top) how many search results they had. 

However, I think that feedback from the codesign sessions represents a different use case... Users who are looking at this data table didn't just conduct a "search," for which a primary concern is "How many results did I get?" 

All that is to say: I vote for putting the  "showing X of X entries" text at the bottom.

**Comment by noahmanger** [comment]
That makes sense to me. I like including it at the bottom as well. @jenniferthibault any thoughts?

**Comment by jenniferthibault** [comment]
Oh gosh, sorry to be such a blocker. I agree!

**Comment by noahmanger** [comment]
Not a blocker! All good. Closing. @xtine you're now totally in the clear for implementation.
