### ISSUE TITLE
Implement CSV links on reports and filings tables

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1610]
So that users can view the entire contents of a report as a CSV, provide a link to the new CSV files for reports.

---

Once [the design](https://github.com/18F/openFEC-web-app/issues/1552) has been settled and [the API change](https://github.com/18F/openFEC/issues/1954) has been made, update the filings and reports tables to include links to CSVs in their results.

**Criteria for completion:**
- [x] /filings page includes CSV in processed and efiling data
- [x] Every /reports/*/ page includes CSV link in processed and efiling data

**Comment by jontours** [comment]
@noahmanger @LindsayYoung  how are the csv links defined for the regular processed reports, i.e. resources that don't have a `file_number` aka `rep_id`?

**Comment by noahmanger** [comment]
So here's the design we're going to implement:
![design](https://cloud.githubusercontent.com/assets/11636908/18963518/51011d84-8643-11e6-8c78-d707d3bf0b4c.png)

If you want an example, these are currently implemented on the "add to calendar" component on the calendar page:
![image](https://cloud.githubusercontent.com/assets/1696495/19395451/a9c3968a-920b-11e6-9237-370a674c83b1.png)

**Comment by xtine** [comment]
So it seems columns are getting a bit squished on some of the reports pages:

<img width="1186" alt="screen shot 2016-10-17 at 1 14 40 pm" src="https://cloud.githubusercontent.com/assets/24054/19453858/d0f7af36-946b-11e6-8172-bcb6b96797d1.png">
<img width="1190" alt="screen shot 2016-10-17 at 1 15 05 pm" src="https://cloud.githubusercontent.com/assets/24054/19453859/d0f8b2be-946b-11e6-8396-ea638e671944.png">

I would suggest maybe making the report type text and download icon smaller, but any other ideas?
@noahmanger @jenniferthibault

**Comment by jenniferthibault** [comment]
Hmmm, this is the mini-est button pattern we have right now. 

I wonder if it's feasible to combine the Coverage start date column with the Coverage end date column so that it renders as one range? Coverage period: mm/dd/yyyy–mm/dd/yyyy ? This seems like it's as much a data question as a design question though, and we'd want to look at other data sets it impacts.

I know @noahmanger did some work with column widths and what gets shown in each data set before, so I'm curious to hear his thoughts.

**Comment by xtine** [comment]
I narrowed the Filer / Committee name columns to save some space, but the columns still start to run into each other for Presidental and PAC and party committee reports. I tried to have a word break on the financial columns on the Presidential report page, but not sure if it really works:
<img width="961" alt="screen shot 2016-10-19 at 11 58 38 pm" src="https://cloud.githubusercontent.com/assets/24054/19549323/8c242a94-9658-11e6-8d84-d27046a74df0.png">

/cc @jenniferthibault @noahmanger

**Comment by jenniferthibault** [comment]
What about wrapping the text in each cell to the next line when the cell gets too small, instead of letting it overflow?

**Comment by jenniferthibault** [comment]
Another brief thought on the button positioning: is it possible to center it vertically in each cell, like the text is? Keeping visual alignment will help keep these pages feeling ordered, even though there's a lot going on.

**Comment by xtine** [comment]
@jenniferthibault: do you mean wrapping the dollar amounts like in the image above? I only did it on the first row to demonstrate how it looks compared to the other two rows that are not wrapping. But now that I think about it, it would potentially be a bit confusing because if a dollar amount wraps like this:
$700,000
,000.00
it might look like 700k rather than 700m.

**Comment by xtine** [comment]
@jenniferthibault: good suggestion about vertically centering the buttons, they look better now :)
<img width="225" alt="screen shot 2016-10-20 at 12 31 53 pm" src="https://cloud.githubusercontent.com/assets/24054/19574941/3d858838-96c1-11e6-829e-4f868f7f946c.png">

**Comment by noahmanger** [comment]
Yeah, I think wrapping numbers isn't going to work well. We _could_ remove the `coverage beginning date` column, which as I understand it is less important than the `coverage end date`? @LindsayYoung what do you think about that?

**Comment by jenniferthibault** [comment]
Ah yep, no wrapping on numbers then. Thank you for trying! Hoping Lindsay can guide us to prioritizing columns.

**Comment by noahmanger** [comment]
Resolved by #1635
