### ISSUE TITLE
Implement itemized debts page

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1614]
So that users see the debt obligations owed to or by committees, implement a data table page for itemized schedule D data.

---

[API endpoint.](https://api.open.fec.gov/developers/#!/party-coordinated_expenditures/get_schedules_schedule_d)

**Filters and columns:**
These are what I understand the filters and columns we need to be:
 
- Committee ID (typeahead filter)
- Creditor name (text filter)
- Purpose (column only)
- Date (date range without time-period select) (I think this is the date of the filing it was included on, but not positive)
- Amount paid this period (financial range filter)
- Amount incurred this period (financial range filter)

**Details panel:**
Include all the fields available on the Schedule D form:
![image](https://cloud.githubusercontent.com/assets/1696495/22170969/d7b31c7a-df39-11e6-9dde-e2b4e2e9c8ee.png)

The details panel should also link to the original image, just like receipts and disbursements.

**Completion criteria:**
- [x] Debts page available at `/debts`
- [x] Data is filterable by available filters
- [ ] Details panel contains additional data and links to original image
- [ ] Link to page is included on "Advanced data" page

**Comment by noahmanger** [comment]
Updated the original issue with more details about filters and columns. @jwchumley @PaulClark2 can verify those are right (and @jontours can help with API questions).

**Comment by xtine** [comment]
I have the columns working in a datatable, but currently none of the proposed filters are a parameter so I can't get the filters working right now. @jontours: can the filters be added as parameters?

**Comment by jontours** [comment]
I can take a look.  There should be a couple of filters, but not all of them are implemented.

**Comment by PaulClark2** [comment]
`Date (date range without time-period select) (I think this is the date of the filing it was included on, but not positive)`  -- This is correct. The date in the SD table is the report receipt date. It is not the date the debt or obligation was incurred.
