### ISSUE TITLE
Craft language for independent expenditure "summary" vs. "notice" filter

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1616]
So that users understand the difference between viewing data from Form 3X & 5 vs data from the 24 and 48 hour reports, craft language for the filter that communicates the difference. 

---
The filter in question is this one, which is being implemented in https://github.com/18F/openFEC-web-app/pull/1565

![image](https://cloud.githubusercontent.com/assets/1696495/18965578/a8fff4ee-8632-11e6-8785-33c920e63fbd.png)

There's three parts to this task:
- [x] 1. Identify what to call each type of data (the values on the toggle)
- [x] 2. Create language for an explanatory tooltip
- [x] 3. Decide on the label for the "form type" filter, which is a way to further refine results when the "Summary" option on the toggle is selected

For #1, @PaulClark2 can you explain why we shouldn't use the "notice" language?

For #2, here's a stab at some basic content for a tooltip:
> At certain times before an election, committees are required to report independent expenditures within 24 and 48 hours. Use the 24 and 48 hour notice filter to view this data.
> These expenditures are also reported via summary forms on regular filing dates. Use the summary report filter to view this data. 

cc @emileighoutlaw @PaulClark2 @jwchumley @amykort

**Comment by PaulClark2** [comment]
There's more detail about what triggers the need for all four of the items below. I wanted to keep the first pass fairly clean. I think the primary take away is in our publications and instructions all IEs are sent to us on reports. Calling them notices is technically incorrect and might cause confusion for users. (Yes, "notices" is easy short hand for 24-hour and 48-hour reports of independent expenditures. I use it internally because it's shorter.)

Notices:
24-hour notices disclose electioneering communications (Form 9)

48-hour notices disclose contributions or loans received (Form 6) by principal campaign committees. 

Reports:
24-hour reports of independent expenditures disclose IEs made by registered committees (Form 24) and persons other than political committees (Form 5) between 1 and 19 days before an election.

48-hour reports of independent expenditures disclose IEs made by registered committees (Form 24) and persons other than political committees (Form 5) 20 days or more before an election.

**Comment by PaulClark2** [comment]
Maybe just change "24 and 48 hour notice filter" to "24 and 48 hour report filter." 

"Summary reports" sounds odd to me but maybe it's fine. 

>At certain times before an election, filers are required to report independent expenditures within 24 or 48 hours. Use the 24 and 48 hour report filter to view this data.
>These expenditures are also reported on the filers' next regularly scheduled report. Use the report filter to view this data.

**Comment by emileighoutlaw** [comment]
Summary reports sounds odd to me too, but I don't have anything useful to counter suggest yet. But I'm brainstorming ideas now

**Comment by noahmanger** [comment]
Thanks for explaining @PaulClark2 . Agree that "Summary reports" is off. Other ideas:
- Regular reports
- Standard reports
- Quarterly and monthly reports

(I don't love any of those ideas...just throwing them out there).

**Comment by PaulClark2** [comment]
You're welcome @noahmanger

**Comment by AmyKort** [comment]
One problem with summary reports might be that it makes it sound like the regularly scheduled report is the "extra report" when all IEs should be reported on the regularly scheduled report and only a time-sensitive subset is reported in 24 or 48 hour reports. 

We generally say that information from a 24 hour report, for example, must also be reported on the next regularly scheduled report. Is regularly scheduled report an option?

**Comment by PaulClark2** [comment]
Let's start with "Regularly scheduled reports" and "24 and 48 hour reports."

**Comment by noahmanger** [comment]
I like it. And so this is the tooltip? @emileighoutlaw any edits to language?

> At certain times before an election, filers are required to report independent expenditures within 24 or 48 hours. Use the 24 and 48 hour report filter to view this data.

> These expenditures are also reported on the filers' next regularly scheduled report. Use the report filter to view this data.

**Comment by AmyKort** [comment]
Let's change this up a little. While it's technically true, I think it might give the wrong impression. The rule for 48 hour reports is basically that folks have to report IEs within 48 hours once they aggregate $10,000 or more at any time during a calendar year. The rule for 24 hour reports is basically that folks must report  IEs of $1,000 or more within 24 hours during the 20 days before an election (but not the last 24 hours before the election). This really oversimplifies the rule, but my point is that the 48 hour reports aren't triggered by proximity to the election like the 24 hour reports. So, should we go more specific or more general with the tool tip to avoid giving folks the wrong impression? @emileighoutlaw ?

**Comment by emileighoutlaw** [comment]
This pattern reminds me of the processed vs. eFiling pattern: https://beta.fec.gov/data/filings/?data_type=processed

Once I made that connection (and drawing on language in the registration and reporting section, I came up with this:

<img width="259" alt="screen shot 2016-10-03 at 5 01 59 pm" src="https://cloud.githubusercontent.com/assets/10552702/19055798/64d3f8d6-898b-11e6-9c0d-61f94207703a.png">

> #### Regularly scheduled report type
> [ ] Form 3X 
> [ ] Form 5


Tooltip content: 
> Political committees file regular reports about their financial activity.

> In certain circumstances — in addition to regularly scheduled repots — committees must also report independent expenditures within 24 or 48 hours. 


Thoughts?

**Comment by AmyKort** [comment]
I like it!

**Comment by noahmanger** [comment]
Nice. One last language question. Should these filters be labeled like this?

![image](https://cloud.githubusercontent.com/assets/1696495/19100306/7747aaf2-8a72-11e6-9fc1-8ca44849b155.png)

In the details panel we "Filing type" and "report type":

![image](https://cloud.githubusercontent.com/assets/1696495/19100323/b42d4ecc-8a72-11e6-90db-cb3c17fe57bc.png)

**Comment by emileighoutlaw** [comment]
Great catch, Noah! In general, I've been trying to use "report" as a noun to talk about forms and "file" as a verb to talk about the action of turning in a report. 

So the way you have it is above is great, and we might want to consider adjusting the details panel.

Also, the bottom button should be capitalized, a lá: `24- and 48-Hour Reports`. That's how we have it in Registration and reporting

**Comment by noahmanger** [comment]
Great. Sounds like we solved this. Closing.
