### ISSUE TITLE
Mockup AO filter interactions

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC-web-app#1619]
Based off of criteria decided in https://github.com/18F/fec-eregs/issues/276

cc @nickykrause

**Comment by jenniferthibault** [comment]
Going to start with mockups on which filters to include first from https://github.com/18F/fec-eregs/issues/274#issuecomment-252071794

**Comment by jenniferthibault** [comment]
I know we are still working out some sorting and search functionality questions in https://github.com/18F/fec-eregs/issues/274 , but I thought it was safe to start on what types of patterns we'd use for each filter. Here's what I'm thinking, with notes in pink and questions in red.

![ao-search-desktop-v2 copy 11](https://cloud.githubusercontent.com/assets/11636908/19203476/5d7d3e72-8ca5-11e6-90ff-4bd55c27d454.png)

**Comment by jenniferthibault** [comment]
I should also mention that we would like @emileighoutlaw 's thoughts and review for filter content and consistency. They might involve a check with Cheryl. Specifically:
- `Document issue date` : Is there a better/preferred way to say this? 
- `Entity`: This seems close to what MURs call "Participants". I was wondering if we could use this as a category title, but it may be a legal no-go
- `Status` - This is not an existing category name, but we need a way to separate the pending option. 

I'm indifferent to making this a prerequisite for implementation - it seems like these content design  questions could be happening concurrently, but I think Emileigh should make that call since it's her wheelhouse.

**Comment by jenniferthibault** [comment]
@nickykrause 's outline of open questions for @anthonygarvan to discuss is here: https://docs.google.com/drawings/d/1jFlj2EKWweF1QcVGDH2n4_xsw4_jxz58VIFqaK0cmvQ/edit

This is now the current working issue for resolving those questions and refining content.

**Comment by jenniferthibault** [comment]
@nickykrause from Tony & Porta's thoughts/comments in your document, I see a few things confirmed & a few open questions to get this wrapped up:

**Design changes/confirmations:**
- Remove the "Status" category & "Include pending requests" checkbox
- Confirmed: Use type-ahead pattern that accepts plain text entry for all Entity/Participant search fields. This would look like this interaction: http://recordit.co/IQPF3oRXxA
- Confirmed: Use plain text search for keyword search. This would look like this interaction:
  - 
![e5utl60bwx](https://cloud.githubusercontent.com/assets/11636908/19524785/e48c6dc0-95ec-11e6-83c4-3198b3b3372c.gif)


**Content design**
- @emileighoutlaw Let's check with Amy/Chery about using "Participants" instead of "Entity". Porta seemed to hint this was possible. 
- What should be the wording/phrasing for `Document issue date` ?

**Interaction design question**
- @nickykrause how do you want to deal with sorting? Tony indicated the possibilities were open-ended.

![screen shot 2016-10-19 at 11 14 56 am](https://cloud.githubusercontent.com/assets/11636908/19524912/4b08a8ac-95ed-11e6-9a0d-80acadb0c5c0.png)

**Comment by nickykrause** [comment]
@jenniferthibault: given that the users we did talk to expressed little interest or trust in the relevance sort, I am inclined to say we could start with a default reverse chronological sort and assess the need for other sorting options through testing

**Comment by emileighoutlaw** [comment]
## Entity/Participants

 I agree that "Participants" is better. Let's move forward with that, and I'll confirm with Amy/Chery. So:
> **Entity**

## Search bar
I worry that "Search for" is a little too ambiguous. In data we have things like "Candidate name or ID." Bearing that in mind, how about something like:

> **Keyword or advisory opinion number**

(Term is what we use elsewhere on the website, but I've decided this is confusing because elections have "terms" too, and I want to go back and change that everywhere)


## Document issue date
I agree it's kind of weird, but it makes sense to me, and I'm not coming up with anything better at the moment. I'll keep mulling, but let's leave it as is for now.

> **Document issue date**

**Comment by jenniferthibault** [comment]
Great! Thanks everyone. Here's what that all combined looks like for implementation:

![ao-search-desktop-v2 copy 10](https://cloud.githubusercontent.com/assets/11636908/19569389/8686b956-96c3-11e6-8685-36dec840c6c6.png)


@anthonygarvan is there already an issue for implementation, or should I make a new one?

**Comment by jenniferthibault** [comment]
Status update: the interaction design and visual styling are complete, & it's ready for implementation on the front end.

**Comment by jenniferthibault** [comment]
Closing in favor of implementing in https://github.com/18F/fec-eregs/issues/276
