### ISSUE TITLE
Winnow enforcement content that introduces audits

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/openFEC-web-app#1623]
Once we got our content in the context of the enforcement landing page, it's clear we wrote a lot more about audits than we did about any other enforcement topic. I don't think we need to put any extra emphasis on audits, so I'd like to trim this down some. 

![screencapture-127-0-0-1-3000-legal-enforcement-1475806583662](https://cloud.githubusercontent.com/assets/11636908/19177653/ffaa175c-8c18-11e6-925a-71e0f9b9e6c0.png)

**Current**
> Coming soon: Generally, the Commission may audit a committee when an internal review of the committee’s reports filed meet thresholds of substantial compliance with the Federal Election Campaign Act. Also, the Commission is required to audit all presidential campaigns and convention committees that accept public funds. 

**Proposed new**
> Coming soon: Commission audits of political committees.

It's much shorter but more in line with how we introduce other sections. We can use the old version on the audits page, when we actually want to explain the process to interested readers. 

Tagging in @AmyKort to review this proposed change.

Related to: https://github.com/18F/openFEC-web-app/pull/1622

**Comment by AmyKort** [comment]
I agree. Thank you!

**Comment by emileighoutlaw** [comment]
I see you working on a holiday, Amy! ;)
