### ISSUE TITLE
Figure out methodology sections for top raiser and spender charts

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1647]
So that advanced users understand the different methodological decisions that are used to compute the totals on the top raiser and spender charts, write a methodology section that explains the numbers.

---

For comparison, the methodology on the totals charts includes:
- The forms used
- The time period covered
- The different types of transactions that count towards the total
- An advanced breakdown of the form line numbers that make up each number

This content should also explain that the numbers are for all of a candidate's authorized committees.

**Comment by noahmanger** [comment]
This is the raising chart (the spending one is identical):
![image](https://cloud.githubusercontent.com/assets/1696495/19647779/bd9c9cfa-99cd-11e6-9cbd-ba8c9834fc65.png)

The filter options are:
- Presidential candidats
- Senate candidates
- House candidates
- PACs
- Parties

The API endpoints we use for candidates is `/candidates/totals` . For PACs it's `/totals/pac/` and parties is `/totals/party/`.

Depending on how complicated this is, we may need to simply remove the methodology button for the initial release of the feature, which I think is ok as it's not as complex or potentially confusing as the other charts that use methodology popups.

@emileighoutlaw and @PaulClark2 can I ask you to connect on this?

**Comment by PaulClark2** [comment]
Should we have a question mark after "Who's raising the most?" @emileighoutlaw

**Comment by PaulClark2** [comment]
My first try at the methodology language. 

Raising chart
Total receipts for each committee is the sum of total receipts of each reporting period of a two-year period. The committees are ranked in descending order by total receipts.    
Presidential candidates: sum of total receipts (Form 3P Line 22 Column A)
Senate and House candidates: sum of total receipts (Form 3 Line 16 Column A)
PACs and Parties: sum of total receipts (Form 3X Line 20 Column A)

Spending chart
Total disbursements for each committee is the sum of total disbursements of each reporting period of a two-year period. The committees are ranked in descending order by total disbursements.    
Presidential candidates: sum of total disbursements (Form 3P Line 30 Column A)
Senate and House candidates: sum of total disbursements (Form 3 Line 22 Column A)
PACs and Parties: sum of total disbursements (Form 3X Line 31 Column A)

@emileighoutlaw @noahmanger @amykort

**Comment by emileighoutlaw** [comment]
@PaulClark2 did an awesome job as always 🎉  (cc @amykort)

I tweaked a couple things— I made the total receipts align with our glossary definition a little more and made the form-by-form breakdown closer match what we have on the existing chart methodologies. Edits and notes are still very welcome: 

### For the raising chart
Committees are displayed in descending order of total [receipts]()*(link to glossary). Total receipts are the sum of all contributions and other receipts that each committee reported during a two-year period.

The form and line used to calculate total receipt sums is:
- **Presidential committees**: _Form 3P, Line 22, Column A_
- **Senate and House committees**: _Form 3, Line 16, Column A_
- **PACs and party committees**: _Form 3X, Line 20, Column A_


### For the spending chart
Committees are displayed in descending order of total [disbursements]()*(link to glossary). Total disbursements are the sum of all purchases and payments that each committee reported during a two-year period.

The form and line used to calculate total disbursement sums is:
- **Presidential committees**: _Form 3P, Line 30, Column A_
- **Senate and House committees**: _Form 3, Line 22, Column A_
- **PACs and party committees**: _Form 3X, Line 31, Column A_

**Comment by AmyKort** [comment]
"Total receipts are the sum of all contributions and other receipts that each committee reported during a two-year period." I like the way this is worded from a readability standpoint, but I wanted your opinion on whether we've changed the meaning from what @PaulClark2 suggested. The reporting period is two years. If you're two months into the two-year reporting period, that's two months worth of data. When I read "reported during a two-year period" I think I'm looking at two years worth of information. Maybe this isn't a problem because the chart itself shows the time periods, but I wanted to get your reactions. @emileighoutlaw

**Comment by noahmanger** [comment]
Related question: Do we need to address the date range above the chart? I think we either need to explicitly say in the methodology that the data is only as recent as the last report filed by committees, but that it has been updated as recently as yesterday. Right?

**Comment by emileighoutlaw** [comment]
That's a good question. Paul's original was 

> "Total receipts for each committee is the sum of total receipts of each reporting period of a two-year period" 

It seems like that sentence might lead to the same confusion for partial reporting periods. What if we reconfigure a bit:

### Raising
> Committees are displayed in descending order of total [receipts]()*(link to glossary). Total receipts are the sum of all contributions and other receipts received by a committee. 

> This chart includes data up to and including the most recent report filed by each committee. It's displayed in two-year cycles.

> The form and line used to calculate total receipt sums is:
- **Presidential committees**: _Form 3P, Line 22, Column A_
- **Senate and House committees**: _Form 3, Line 16, Column A_
- **PACs and party committees**: _Form 3X, Line 20, Column A_


### Spending
> Committees are displayed in descending order of total [disbursements]()*(link to glossary). Total disbursements are the sum of all purchases and payments made by a committee.

> This chart includes data up to and including the most recent report filed by each committee. It's displayed in two-year cycles.

> The form and line used to calculate total disbursement sums is:
- **Presidential committees**: _Form 3P, Line 30, Column A_
- **Senate and House committees**: _Form 3, Line 22, Column A_
- **PACs and party committees**: _Form 3X, Line 31, Column A_

**Comment by AmyKort** [comment]
love it. thank you.

**Comment by PaulClark2** [comment]
@emileighoutlaw  should "sums is:" be "sums are:" for both methodology sections?

I like the reconfigured language. I think it reduces confusion about the two-year period and explicitly addresses what reports are included (the coverage date question).

**Comment by emileighoutlaw** [comment]
Oh yeah — @noahmanger, can we make that change? (the "sums are")

**Comment by noahmanger** [comment]
Got it. Thanks!

**Comment by noahmanger** [comment]
Resolved via #1662 . Thanks all!
