### ISSUE TITLE
Design preferred order for participants list on MURs pages

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC-web-app#1654]
Pointed out by the FEC enforcement folks during their review:

When multiple respondents are listed on a case, often the counsel are listed first, with the primary respondents and complainants (the two most interesting and useful participants) listed very last.

Here's an example where this happens: https://fec-stage-proxy.18f.gov/data/legal/matter-under-review/5903/

In grooming the feedback, @anthonygarvan mentioned that we can choose this order, so we should set it!

Steps to completion:
- [x] Review all options for participant relationships
- [x] Order them by relevance / usefulness / priority
  - (maybe we can learn this through a card sort activity with someone at the FEC?)
- [x] Transfer or create issue for implementation

**Comment by jenniferthibault** [comment]
cc @nickykrause — this is an information design task that we might be able to knock out relatively easily. Would you like first crack? Or if you're full with testing wireframes this sprint I don't mind trying.

**Comment by nickykrause** [comment]
@jenniferthibault: I'd like to, but I suspect I will be too busy this week with trying to get more realistic content in the wires and designing/doing the testing on them (assuming people sign up for testing, anyway...). It's hard to know how much time I'll have until we know how recruiting goes

**Comment by jenniferthibault** [comment]
I think I can take this, which would unblock a MUR-focused dev task.

@anthonygarvan or @vrajmohan is it possible to surface a list of all the possible participant relationship categories from the database or code? Or should I attempt to dig this up manually?

**Comment by vrajmohan** [comment]
We can get it from the database. I'll update this ticket with the list over the weekend.

**Comment by vrajmohan** [comment]
1.  Previous Respondent
2.  Representative
3.  Treasurer
4.  Primary Respondent
5.  Respondent
6.  Complainant
7.  Law Firm
8.  Respondent's Counsel
9. Opposing counsel
10.  Previous Treasurer

**Comment by jenniferthibault** [comment]
Thanks Vraj, I've reached out to Cheryl to help guide the order. As soon as I hear back I'll report in!

**Comment by jenniferthibault** [comment]
Cheryl connected me with Stephen and Dawn, who helped clarify many things about MUR participants for me.

For everything MUR-related, we should always list the Respondent before the Complainant, because in the MUR process, the MUR is about the alleged actions of the respondent, not the complainant. For that reason, MURs are routinely referred to by the name of the first respondent of most prominent respondent.

That means we should:

- [ ] On current MUR pages, change the order in the Summary sub-sections to:
  - (1) Respondent
  - (2) Complainant 

    -  Currently: 
![screen shot 2016-11-02 at 1 40 27 pm](https://cloud.githubusercontent.com/assets/11636908/19940151/14a58dfa-a102-11e6-9b5b-6543931f0d95.png)

- [ ] Within this Summary Respondent section: When multiple respondent participants are present, list them in the following order:
  - (1) Primary Respondent
  - (2) Respondent
  - (3) Previous Respondent

    -  [MUR #6231](https://fec-dev-proxy.18f.gov/data/legal/matter-under-review/6261/) is a good example of one with multiple Respondent types. Currently, with no respondent order preference: 
    
    - ![screen shot 2016-11-02 at 1 46 10 pm](https://cloud.githubusercontent.com/assets/11636908/19940424/fa736974-a102-11e6-9e90-c71a38d94d03.png)

    -  Preferred, with respondent order preference:
    - ![screen shot 2016-11-02 at 1 47 28 pm](https://cloud.githubusercontent.com/assets/11636908/19940470/2ace7442-a103-11e6-9f26-1db9f0a89533.png)

- [ ] On current MUR pages, AND  archived MUR pages: Within the Participants table, order Participant Relationships using the following:
 - Primary Respondent
 - Respondent
 - Previous respondent
 - Treasurer
 - Previous Treasurer
 - Complainant 
 - Respondent’s Counsel
 - Opposing Counsel 
 - Representative
 - Law firm
   

@vrajmohan could you take a look and let me know if this is all the information you need to move forward?

**Comment by vrajmohan** [comment]
Clarification on Summary Respondent section when multiple respondent participants are present: Do we order them as requested (i.e. Primary Respondent, Respondent, Previous Respondent) without any indication as to who is what? In other words, when you see the list "Adam, Ben, Charles, Doug, Edgar", there would be no way to know that Doug is a Previous Respondent without looking at the Participants table.

**Comment by jenniferthibault** [comment]
Yes, that's the intention.

It would help (if possible through technical tactics I'm unfamiliar with) if we could have the category label `RESPONDENT` automatically turn to `RESPONDENTS` when there is more than one entity present. 

The converse is that if there is only one entity listed as a Respondent, it would not change to the plural.

What do you think?

**Comment by jenniferthibault** [comment]
Transferring to Vraj for implementation. 🎈 🚀
