### ISSUE TITLE
Advisory opinion title formatting stripped

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC-web-app#1670]
I'm guessing this happened with the heading style update, but it looks like AO titles and paragraph body copy lost their formatting, which makes it really hard to start and follow the reading hierarchy:

https://beta.fec.gov/data/legal/advisory-opinions/1979-32/

![screen shot 2016-10-31 at 11 35 01 am](https://cloud.githubusercontent.com/assets/11636908/19860203/48cafca0-9f5e-11e6-8a00-b092336b9f1a.png)

They should match the styling on MURs:
https://beta.fec.gov/data/legal/matter-under-review/4908/

![screen shot 2016-10-31 at 11 37 51 am](https://cloud.githubusercontent.com/assets/11636908/19860271/7f7296be-9f5e-11e6-837e-f3cfd1455c0e.png)

cc @noahmanger / @xtine because it's a front end 🐛

**Comment by noahmanger** [comment]
Ah, looks like it's just a little markup mistake:
![image](https://cloud.githubusercontent.com/assets/1696495/19861020/2d821ac0-9f48-11e6-9861-e101533d1f30.png)

The errant `"` in the `<h1>` is throwing it off. Also the subtitle should be after the H1, not inside it.

**Comment by jenniferthibault** [comment]
Would that be why the body paragraph style inside the container is too small? it's 1.4rem, but our body style should be 1.6rem. Might be a separate issue, I also see it on the MUR pages.

**Comment by noahmanger** [comment]
No, that's small because it's not in a `p` tag, which it should be.

**Comment by jenniferthibault** [comment]
@vrajmohan addressed the extraneous `"` in https://github.com/18F/openFEC-web-app/pull/1667/files. 

Remaining to-do's that should be checked across AO, archived MUR, and current MUR page templates:

- [ ] Is the subtitle after the H1, not inside it?
  - [ ] AO template
  - [ ] Archived MUR template
  - [ ] Current MUR template

- [ ] Is there a `p` tag surrounding copy in the main container?
  - [ ] AO template
  - [ ] Archived MUR template
  - [ ] Current MUR template

**Comment by jenniferthibault** [comment]
It looked to me like the issue of subtitles being outside the h1's was already fixed before I started in, so I didn't adjust anything there.

**Comment by jenniferthibault** [comment]
Resolved by https://github.com/18F/openFEC-web-app/commit/b42446bd6b6d293d14261068e10538d7879d2160 and #1676
