### ISSUE TITLE
Move openfec-web-app to new cloud.gov

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1684]
We need to move the openfec-web-app to the new cloud.gov, which requires:

- [ ] Use built-in routing feature instead of the proxy app
- [x] Make sure new relic is going
- [ ] Make sure github is reachable by the app for feedback
- [x] Make sure deployment works with the invoke task
- [ ] Make sure deployment works by travis
- [x]  Move dev/staging/prod to cloud.gov url instead of 18F.gov

(updated issue since ethnio is off)

**Comment by LindsayYoung** [comment]
Hi @anthonygarvan, I see you are working on eregs and @ccostino  is working on the cms so I can try and pick this up since my meetings got canceled. Stop me if I am wrong
