### ISSUE TITLE
Add communication filer totals to the overview totals endpoint

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1685]
So that users can get a complete picture of the total amount raised and spent in a cycle, add the numbers for communication filers to the election totals endpoint.

---

This is the lone task left after the work of verifying the entity totals from https://github.com/18F/openFEC/issues/1991 . We removed the communication filers from the endpoint and display, but I believe ultimately want to add them back in if it's feasible.

- [ ] The API returns an accurate number for the amount raised and spent by these groups

---

Update 
- [x] @PaulClark2 finish the SQL
- [x] Turn into endpoint
- [ ] Add it to front-end chart
- [ ] Update methodology modals to include the new info

**Comment by noahmanger** [comment]
@LindsayYoung here's an issue we already had for adding communication filer data to the API. Bumping this into Sprint 4 from the icebox since we need it for the home page.

**Comment by PaulClark2** [comment]
**Form 5 - IEs**

select get_cycle(rpt_yr) as cycle, sum(ttl_indt_contb), sum(ttl_indt_exp)
  from public.fec_vsum_f5_vw where rpt_yr between 2007 and 2016 and most_recent_filing_flag = 'Y' group by cycle order by cycle;

select
get_cycle(rpt_yr) as cycle,
f.rpt_yr,
extract(month from to_date(cast(cvg_end_dt as text), 'YYYY-MM-DD')) as month,
sum(coalesce(ttl_indt_contb ,0)),
sum(coalesce(ttl_indt_exp ,0))
  from public.fec_vsum_f5_vw f
  where rpt_yr >= 2007
  and most_recent_filing_flag = 'Y'
  group by get_cycle(rpt_yr), f.rpt_yr, extract(month from to_date(cast(cvg_end_dt as text), 'YYYY-MM-DD'));

**Form 7 - Communication costs**

select get_cycle(rpt_yr) as cycle, sum(ttl_communication_cost)
  from public.fec_vsum_f7_vw where rpt_yr between 2007 and 2016 and most_recent_filing_flag = 'Y' group by cycle order by cycle;

select
get_cycle(rpt_yr) as cycle,
f.rpt_yr,
extract(month from to_date(cast(cvg_end_dt as text), 'YYYY-MM-DD')) as month,
sum(coalesce(ttl_communication_cost ,0))
  from public.fec_vsum_f7_vw f
  where rpt_yr >= 2007
  and most_recent_filing_flag = 'Y'
  group by get_cycle(rpt_yr), f.rpt_yr, extract(month from to_date(cast(cvg_end_dt as text), 'YYYY-MM-DD'))
  order by f.rpt_yr, extract(month from to_date(cast(cvg_end_dt as text), 'YYYY-MM-DD'));

**Form 9 - Electioneering communications** 

select get_cycle(rpt_yr) as cycle, sum(ttl_dons_this_stmt), sum(ttl_disb_this_stmt)
  from public.fec_vsum_f9_vw where rpt_yr between 2007 and 2016 and most_recent_filing_flag = 'Y' group by cycle order by cycle;


select
get_cycle(rpt_yr) as cycle,
f.rpt_yr,
extract(month from to_date(cast(end_cvg_dt as text), 'YYYY-MM-DD')) as month,
sum(coalesce(ttl_dons_this_stmt ,0)),
sum(coalesce(ttl_disb_this_stmt ,0))
  from public.fec_vsum_f9_vw f
  where rpt_yr >= 2007
  and most_recent_filing_flag = 'Y'
  group by get_cycle(rpt_yr), f.rpt_yr, extract(month from to_date(cast(end_cvg_dt as text), 'YYYY-MM-DD'))
  order by f.rpt_yr, extract(month from to_date(cast(end_cvg_dt as text), 'YYYY-MM-DD'));

**Comment by noahmanger** [comment]
@PaulClark2 in preparation for adding this to the the front-end, can you help out by updating the methodology popups?
