### ISSUE TITLE
Consider adding nav items for raising and spending breakdowns

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1686]
Currently, in the dropdown nav we just have links that go to the top-level raising and spending overviews on beta.fec.gov/data

![image](https://cloud.githubusercontent.com/assets/1696495/20044055/0ad74764-a44a-11e6-970a-072b5ee044d7.png)

I think we should consider either redirecting them to the breakdown pages at beta.fec.gov/data/spending and beta.fec.gov/data/raising or adding links to those pages separately.

**Comment by jenniferthibault** [comment]
We've changed strategy for the items in the menu to now focus on priorities and structure within each section. This issues no longer applies to that strategy, so closing.
