### ISSUE TITLE
Change "Open case" Archive MUR terminology to something else

### ISSUE THREAD

**Issue by adrianwebb** [18F/openFEC-web-app#1689]
See #1651 

We got feedback today that the "Open case" terminology in the above issue was confusing because this has a different meaning inside FEC.  We need to change this to something else.

@emileighoutlaw is supposed to be thinking on the name and coordinate with Amy, so we can update.

**Comment by emileighoutlaw** [comment]
Will be resolved by this PR: https://github.com/18F/openFEC-web-app/pull/1688

**Comment by emileighoutlaw** [comment]
This is resolved. Closing now.
