### ISSUE TITLE
Adding a column to the api rad-analyst endpoint

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC-web-app#1694]
@LindsayYoung  @ccostino  RAD wants to add another column to the rad_analyst endpoint in the API. It is a 3digit analyst ID that we use to link the data capture process and internal reports with the RAD modules.  I'll give Jean the source information. Could you add this to the list please?

**Comment by LindsayYoung** [comment]
If you add it to the table we can easily add that to the API results

**Comment by jwchumley** [comment]
Working on it. It is one of the tables that was just dumped but needs to be scheduled so Jean is going to work on it.

**Comment by ccostino** [comment]
Great, thank you @jwchumley!

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/openFEC/pull/2060
