### ISSUE TITLE
restore new relic

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC-web-app#1701]
it's not reporting

**Comment by ccostino** [comment]
In looking into this issue and pushing a standalone app to test New Relic (by following these instructions), the following output was given:

```
ERROR - A valid account license key cannot be found. Has a license key been specified in the agent configuration file or via the NEW_RELIC_LICENSE_KEY environment variable?

ERROR - Data collector is indicating that an incorrect license key has been supplied by the agent. The value which was used by the agent is 'NO LICENSE KEY WAS SET IN AGENT CONFIGURATION'. Please correct any problem with the license key or report this problem to New Relic support.
```

What I find strange about this is that the license key is set, and the other apps are working just fine with it.

**Comment by ccostino** [comment]
Starting the web app normally in the cloud.gov environment does show that the license key is found, so there's something else not right.

**Comment by ccostino** [comment]
We have still not been able to figure out the cause of this or what might be missing/misconfigured with the New Relic setup in the web app.  I tried one adjustment in #1710 when I noticed a discrepancy, but that didn't resolve the issue.  I also asked in the admins-newrelic Slack channel but didn't receive much help at the time; I can ask again.

@tadhg-ohiggins was able to get the `fec-eregs` app to report, but again, it's unclear why that is now working and the web app continues to be problematic.

Does anyone know who else might have a better sense of this or more experience with New Relic that we could ask for help?

**Comment by adrianwebb** [comment]
Just checking in to see what the status is on this?  cc @ccostino, @tadhg-ohiggins

**Comment by ccostino** [comment]
@adrianwebb I haven't had a chance to revisit this yet between being out and trying to get the content restoration pieces in place.  I'm hoping that once I have that working I can get back to it, especially since @tadhg-ohiggins is transitioning off the project now.
