### ISSUE TITLE
Fix IE only reports page

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1709]
Something's wrong with the data table at https://beta.fec.gov/data/reports/ie-only/

![image](https://cloud.githubusercontent.com/assets/1696495/20572770/b9f16d78-b161-11e6-89b1-7b29615fc866.png)

There must be some mislabeled fields or something. This is a very low traffic page, but it's in production so we should fix it sooner than later.

@xtine this might be a decent thing to use as a learning opportunity?

**Comment by xtine** [comment]
I don't think I've seen this page before, where is it linked in https://beta.fec.gov/data/advanced/?

**Comment by noahmanger** [comment]
Heh, it's totally not linked at all, hence the low traffic.

**Comment by noahmanger** [comment]
I just checked and there's a few problems:
- The `/reports/ie-only/` response doesn't include the committee name or `document_description`
- There's no `/efile/reports/ie-only/` endpoint

We certainly have more important issues going on, but flagging for @jontours . Can you just weigh in on how complicated the fix is? If it's more than an hour or two we should just icebox this.
