### ISSUE TITLE
Clarify that overview chart data is based on latest reports

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1713]
It came up in a stakeholder presentation in DC that the charts here should specify that this is based on the numbers _as reported_ to date, so as to not mislead people in thinking that, say, the number they see for November 1 is the actual amount spent or raised at that date. 

![image](https://cloud.githubusercontent.com/assets/1696495/20695969/c0b11626-b5a4-11e6-8908-c244e7f14a06.png)

I know there's some language trickiness, as saying "reported" might confuse people, but I think we should try to clarify this.

**Comment by emileighoutlaw** [comment]
We didn't talk about this in our meeting today, but I do think we should put it in this sprint because 1) it's content work I have time for/believe I could implement and 2) the outcome of this will also impact how we display raising and spending on the homepage. 

What do you think @noahmanger ? Can I pull it into sprint 2?

**Comment by noahmanger** [comment]
Yeah, if you have time for it, I think it would be good to do. What do you think @AmyKort ?

**Comment by AmyKort** [comment]
I think that's a great idea. Thanks.

**Comment by emileighoutlaw** [comment]
How about something like this:

<img width="931" alt="screen shot 2016-12-07 at 12 36 41 pm" src="https://cloud.githubusercontent.com/assets/10552702/20981335/e352cb44-bc79-11e6-91d0-e3f564e936e1.png">

With a little bit of introductory text, we can introduce the players (candidates, parties, and PACs) as well as pull the glossary links out of the actual chart, which has always felt a little strange to me. It also allows us to explain how reporting works a little and gives us a spot to build a pathway from data to the reporting and compliance section (italicized), if we wanted to do that.

**Comment by AmyKort** [comment]
Works for me. pinging @PaulClark2

**Comment by PaulClark2** [comment]
Looks good to me, too.

**Comment by noahmanger** [comment]
@emileighoutlaw this look right? 
![image](https://cloud.githubusercontent.com/assets/1696495/21151411/4741309a-c117-11e6-8f67-24ed6c2c685a.png)

I made this change in this branch https://github.com/18F/openFEC-web-app/pull/1729

**Comment by emileighoutlaw** [comment]
Beautiful. Made one small note in that PR.
