### ISSUE TITLE
Make utility & footer navigation up to date across site

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC-web-app#1714]
**Legal resources**
<img width="641" alt="screen shot 2016-11-29 at 1 31 22 pm" src="https://cloud.githubusercontent.com/assets/11636908/20723414/742d0ea6-b638-11e6-91e5-ab211d0d8aae.png">
<img width="1278" alt="screen shot 2016-11-29 at 1 31 39 pm" src="https://cloud.githubusercontent.com/assets/11636908/20723415/742d9c68-b638-11e6-98c5-782f2a75ee81.png">

**Data**

<img width="1275" alt="screen shot 2016-11-29 at 1 31 58 pm" src="https://cloud.githubusercontent.com/assets/11636908/20723418/78bddd4c-b638-11e6-8123-c04887ba946b.png">
<img width="1275" alt="screen shot 2016-11-29 at 1 32 06 pm" src="https://cloud.githubusercontent.com/assets/11636908/20723417/78bd9ea4-b638-11e6-9480-4e9daf9950b9.png">

**Reg/reporting**
<img width="1278" alt="screen shot 2016-11-29 at 1 32 15 pm" src="https://cloud.githubusercontent.com/assets/11636908/20723421/7e637680-b638-11e6-8131-69715f72b5a2.png">
<img width="1278" alt="screen shot 2016-11-29 at 1 32 22 pm" src="https://cloud.githubusercontent.com/assets/11636908/20723422/7e64e290-b638-11e6-8a0f-d8ca846621b8.png">

**Regulations**
<img width="1279" alt="screen shot 2016-11-29 at 1 32 41 pm" src="https://cloud.githubusercontent.com/assets/11636908/20723426/841864d2-b638-11e6-852b-4efadd11d3c7.png">

& no footer?

## Steps to correct:

- on Data: 
  - Add "Latest updates" to the footer nav
- on LR: 
  - Remove "Contact" from utility nav
- on R&R: 
  - Remove "Contact" from utility nav
- on Regulations: 
  - Remove "Contact" from utility nav
  - Remove `( )` from around "About" on utility nav
  - Add footer

**Comment by noahmanger** [comment]
Ok, I've made all these changes in PRs.

Except the footer on eregs. I tried to do this, and see because of the way the page layout is set up there that it's more complicated than we should do right now. I'm going to make an icebox issue for adding the site footer to eregs so we can close this once the existing changes are merged in.

**Comment by jenniferthibault** [comment]
Thanks! Yeah eregs is basically living on another style planet of its own right now, it's very out of sync with the rest of the site's styles (and here, functionality).

**Comment by noahmanger** [comment]
Resolved.
