### ISSUE TITLE
Implement improved raw vs. processed UI

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1734]
So that users can better understand the difference between raw, electronic filing data and processed data, implement the new interface for toggling between data types.

---

🖌 [Designs](https://cloud.githubusercontent.com/assets/11636908/21067286/1ec15564-be38-11e6-9516-7ca533c4d3bf.png) | 🗣 [Discussion](https://github.com/18F/openFEC-web-app/issues/1716)

This redesign is addresses several issues that arose in usability testing when studying the way people toggled between data types on the [filings page](https://beta.fec.gov/data/filings) in preparation for extending this pattern to receipts, disbursements and independent expenditures. This issue is just for changing the interface on filings and reports pages.

**Behavior:**
When the user toggles between the two types of data: 
- Explanatory text should be visible below the toggle explaining the data set
- A green success message displays notifying of the data type switch
- The filters area below changes to only display filters that are allowed for the type of data set
- Hidden filters should be removed from the query
- Upon toggling _back_ to the other form, any filters that were previously set should still be set

**Copy:**
_UPDATED: 12/21/16 by Em_
> **Electronic filings**
> - This data **has not** yet been categorized and coded by the FEC. It's pulled directly from a committee's raw, electronic reports. It doesn't include paper filings.

> **Processed data**
> - This data **has been** categorized and coded by the FEC. The FEC's multi-step process can take days (for electronic filings) or weeks (for paper filings).

**Completion criteria:**
- [x] Change the toggle labels to the new labels
- [x] Refactor toggles to horizontal layout
- [x] Display explanatory text upon toggle change
- [x] Display success message upon toggle change
- [x] Hide all non-efiling filters when viewing raw data
- [x] Clear value of filters for the opposite data type
- [x] Preserve non-efiling filter values (if set) when toggling back to processed data

**Comment by emileighoutlaw** [comment]
I updated the content in this issue description to reflect our newly approved content, which is ready for implementation. :)
