### ISSUE TITLE
Update filings and reports tables with new amendment information 

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1738]
So that users can always understand the version status of a filing, show the amendment status and history in the filings and reports tables.  

---

🖌  [Panel design](https://cloud.githubusercontent.com/assets/11636908/21234683/a22ce0c0-c2c1-11e6-9484-8786a018672b.png), [table design](https://cloud.githubusercontent.com/assets/11636908/21234682/a2257574-c2c1-11e6-8d99-794d26c9d7df.png) | 🗣  [Discussion](https://github.com/18F/openFEC-web-app/issues/1715#issuecomment-267388367)

**Completion criteria:**
- [x] Add "Version" column to the /filings page table
- [x] Add "Original" or "Version [#]" to the document description on /filings page table 
- [x] Update the reports details panel to reflect the designs, including proper date formats
- [x] Update filters on `/filings` and `/reports/**` pages to include a filter for "Version" and "Document status" (per comment below)
- [x] Add the table and panel info on the /reports/ pages as well
- [x] Update all links to the `/reports/**/` pages to not include `?is_amended=false` (this is a frequent request from RAD)
- [x] Show default value when version status is unknown (per https://github.com/18F/openFEC-web-app/issues/1806)

**Comment by noahmanger** [comment]
Circling back on the open question here. 

**Reports pages:** I think we need to include the same version column and "original" vs. "amendment" word in the report title. 

**Filters:** I think we should replace the current amendment-y filters on both filings and reports with the same two filters:

> **Version**
> [ ] Most recent version 
> [ ] Past version

> **Document status**
> [ ] Original
> [ ] Amendment 

This would replace both this filter on the reports pages:
![image](https://cloud.githubusercontent.com/assets/1696495/21703252/95427a78-d365-11e6-9450-2dc52d369eda.png)

And this one on filings:
![image](https://cloud.githubusercontent.com/assets/1696495/21703267/b37c0770-d365-11e6-9ae8-cc2eee61da35.png)

Additionally, we've gotten a lot of feedback from folks requesting that the links to reports pages default to showing all reports (whereas now it defaults to `is_amended=false`).

cc @emileighoutlaw for language and @jontours to make sure the logic makes sense for the filter.

**Comment by noahmanger** [comment]
One last change here. I'm adding another criteria for completion which is to ensure that this all shows up when viewing raw data as well, which depends on https://github.com/18F/openFEC/issues/2147

**Comment by noahmanger** [comment]
I just updated the original completion criteria to rank the remaining items in order of importance. I think once the basic details are included in the panel, adding the appropriate filters on the filings and reports pages is the next most important thing given that it's something that people have asked us for repeatedly.

**Comment by emileighoutlaw** [comment]
For the content, we'd like to try going forward with:

> Past version
Current version
Version unknown

**Comment by xtine** [comment]
@jenniferthibault: Should the text have an icon like Past/Current versions?

**Comment by jenniferthibault** [comment]
@xtine I'd prefer to begin without an icon for Unknown. Fewer icons, less to decode, less clutter. 

If possible though, we should keep the text aligned as if there were an empty placeholder where the icon would have been. This is a scrappy way to show it, but:

**Like this:**
🔵  Past version
⚪️  Current version
 ___ Version unknown

**Not like this:**
🔵  Past version
⚪️  Current version
Version unknown

**Comment by noahmanger** [comment]
@xtine do you think it'd be possible to get the rest of the tasks above complete for this release, maybe saving the amendment chain display for the next round?

**Comment by xtine** [comment]
Filters working:
<img width="300" alt="screen shot 2017-01-30 at 4 12 56 pm" src="https://cloud.githubusercontent.com/assets/24054/22445986/83d561a0-e707-11e6-8b8c-1495c6197bd4.png">

**Comment by xtine** [comment]
@noahmanger: I've updated https://github.com/18F/openFEC-web-app/pull/1796 to pull into next release.

**Comment by xtine** [comment]
@noahmanger: ideally the new filters should be radio buttons, but the radio input style is overwritten for the raw/processed data type. what do you think?

**Comment by noahmanger** [comment]
Well I think there's times when we want to be able to view all filings, not just one or the other. A radio would always require you to pick.

**Comment by noahmanger** [comment]
I pulled out a couple of the bigger separate tasks into new issues in #1815 and #1816 and updated the completion criteria accordingly.

**Comment by noahmanger** [comment]
It looks like the API work for this has been merged in, so we can finish this up whenever anyone has time.

**Comment by noahmanger** [comment]
I finished up the remaining work for this in https://github.com/18F/openFEC-web-app/pull/1847

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/openFEC-web-app/pull/1847
