### ISSUE TITLE
Provide way to view pending AOs

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1747]
So that legal researchers can see what AOs have been requested but not yet resolved, provide a way for users to find pending AOs.

---

Once the pending AO flag has been set on the API, there's a few places where we need to tie them into the UX:

1. On the AO Landing page, we show all pending AOs:
![image](https://cloud.githubusercontent.com/assets/1696495/21246477/e6ad6b18-c2dd-11e6-8cc1-8b4824b94441.png)

2. On the AO process page, the side bar provides a link to the AO search page filtered down to pending AOs

**Completion criteria:**
- [x] Show pending AOs on landing page
- [x] Add the "pending AO" icon to pending AOs in search results
- [x] Denote pending AOs on individual AO pages

**Comment by jenniferthibault** [comment]
In sprint planning, @anthonygarvan raised a question about how we get the data for the commenting deadline.

From the Advisory Opinion process page: https://beta.fec.gov/legal/advisory-opinions/process/
> Submit comments on a request in writing to the Office of General Counsel within ten days after the advisory opinion request is made public.

After the advisory opinion request is made public = Pending AO. The comment period may not be in the API, but can it be calculated based on the 10 day commenting period = first 10 days of the AO becoming public?

**Comment by AmyKort** [comment]
There's a date associated with the request in the pending AO section of the legacy site (in parentheses). I think this marks the start of the 10 days. I will double check that.

**Comment by AmyKort** [comment]
Here is the formula we use to determine the comment period for AORs (which gets manually added to our legacy calendar):

For AORs, use ten calendar days after the date the AO was made public. If that day falls on a weekend or holiday, use the next Monday or if a weekday holiday, the next working day. Select “Unspecified time” and use the calendar provided to select the due date.
