### ISSUE TITLE
Refine content for efiling data interface

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/openFEC-web-app#1751]
### Background
Basically, the "electronic filings" data and "processed data" is mutually exclusive and serves different purposes, so we need to make sure users understand this difference.

### Content right now
Here's how the content looks right now:

<img width="280" alt="screen shot 2016-12-19 at 3 05 30 pm" src="https://cloud.githubusercontent.com/assets/10552702/21330247/34289c9c-c602-11e6-99e6-ee33977d1e5c.png">

<img width="275" alt="screen shot 2016-12-19 at 3 04 53 pm" src="https://cloud.githubusercontent.com/assets/10552702/21330253/373cf568-c602-11e6-92bc-95b187e696f4.png">

Tagging in @AmyKort and @PaulClark2 to help us think about the content here because they're our geniuses, and I know they'll have ideas 😀 

Related: https://github.com/18F/openFEC-web-app/issues/1716

**Comment by AmyKort** [comment]
The current explanation says: 1) Data has been filed electronically, but has not been reviewed by the FEC. 2) It's our most recent data, but excludes paper filings. 

My concern was that folks might read that as saying that the difference between this data and processed data is that it doesn't include paper filings. My understanding is that's true, but not entirely true. There's also value-add with the processing of data.

But, I'm not having a lot of luck coming up with an alternative. I'm trying to say that the reason to look at this is that it's very current, but it's also raw data. How do folks feel about actually calling it raw data or raw electronic filings? Thoughts, @emileighoutlaw and @PaulClark2 ?

(One suggestion)
Search the most recent electronic filings. These filings have not yet been reviewed by the FEC. Search Processed Data to find data from electronic and paper filings that have been reviewed by the FEC.

**Comment by jwchumley** [comment]
I don't mind "Raw". You could also use "unprocessed".


"Includes only unprocessed electronically filed data"?


"Includes only raw electronically filed data"?

________________________________

**Comment by AmyKort** [comment]
@jwchumley  I had the sense that "raw" was the way press folks talked about it. Does that sound right? Maybe calling it unprocessed is better, though, because the other option is processed.

**Comment by AmyKort** [comment]
Or, y'all can say I was way off in my initial comment, and the language is fine as it is. :8ball:

**Comment by PaulClark2** [comment]
Here are the blurbs the Press Office uses:

**Electronically filed reports** can be viewed via the “Filings” tab as soon as committees upload their reports to the Commission’s server.  The “Two-Year Summary” and “Report Summary” sections of the Viewer will be updated with summary-level data the morning after the committee submits its report to the agency. While the summary-level data will be updated to include the most recent report filing, the associated, itemized transactions may take up to several weeks to be incorporated into the database.

**.FEC data**
.FEC files are available to the public immediately after a committee files a report electronically with the Commission. The information available in these files comes directly from the committee's report in a raw data format. The .FEC files of reports filed on paper are made available to the public after the data from the filing been entered into the agency's database. Use processed data to access more comprehensive search options and all years of data.

**Reports filed on paper (including Senate candidates and Senate party committees)** will be added within 48 hours of receipt and viewable as PDF documents or HTML.  Summary-level data will be updated in the Viewer within the same 48-hour receipt window.  Itemized transactions may take up to several weeks to be entered into the database.

**Processed data**
Processed data has been reviewed by the FEC using a multi-step process. This process can take days (for electronic filings) or weeks (for paper filings). Use processed data to comprehensively search all FEC data, which includes eFilings, once they're processed. Use eFiling data to access the most recent, raw information.

**Comment by PaulClark2** [comment]
Here's my attempt:

Electronic filings: These data are available to the public shortly after a committee files a report electronically with the Commission. The information available in these files comes directly from the committee's report in a raw data format.

Processed data: Processed data has been categorized by the FEC using a multi-step process. This process can take days (for electronic filings) or weeks (for paper filings). Use processed data to comprehensively search all FEC data.

@emileighoutlaw @AmyKort

**Comment by emileighoutlaw** [comment]
Thanks for giving me some time to think about this and helping brainstorm some great ideas! 

I like where @PaulClark2 is going with this, and I think @AmyKort's right that we need to be clear about the complex differences between the two types of data. 

For our users, I do think there's value in being clear that paper filings aren't included in the electronic filings tab (but I hear that we don't want it to seem like that's the main difference between the two). How about something like:

> **Electronic filings**
This data **has not** yet been reviewed by the FEC. It's pulled directly from a committee's raw, electronic reports. It does not include paper filings. 

> **Processed data**
This data **has been** reviewed by the FEC. The FEC's multi-step review process can take days (for electronic filings) or weeks (for paper filings). 

That keeps the review piece front and center for both types of data (i.e., most important) but still lets users know they can't find paper filings in the electronic filings tab.

**Comment by jwchumley** [comment]
"Reviewed" isn't the correct word here I don't think. It is reviewed by Rad later. It is "Processed"  perhaps. Or "Coded" but that his to fecspeaky.

________________________________

**Comment by jwchumley** [comment]
I mean, Reviewed might be OK but it has a specific meaning inside the building and perhaps outside with certain constituencies.

________________________________

**Comment by amypike** [comment]
@jwchumley  I agree that "reviewed" generally refers to the RAD reviewing process. FWIW, a quick document round-up: we use the term "processed" in the legislative recommendation for electronic filing of Senate reports/EC reports.  "Processed" is also used in the most recent budget document.  I like "coded" but agree with you that might be too fecspeaky.

**Comment by PaulClark2** [comment]
I agree, "reviewed" is the wrong word. I prefer "categorized." Essentially, the coding and entry staff input value added data.  They add committee and candidate IDs and they add transaction types.

**Comment by amypike** [comment]
@PaulClark2 Hmmmm.  If "coded" is too techy, is "categorized" not techy enough?  I don't know if "categorizing" alone captures the value-added part of the process.  "Categorizing and coding?"  I'm out of ideas (that was fast!).

**Comment by emileighoutlaw** [comment]
Oooo. I think that could be interesting:

> **Electronic filings**
> - This data **has not** yet been categorized and coded by the FEC. It's pulled directly from a committee's raw, electronic reports. It doesn't include paper filings.

> **Processed data**
> - This data **has been** categorized and coded by the FEC. The FEC's multi-step process can take days (for electronic filings) or weeks (for paper filings).

**Comment by PaulClark2** [comment]
I like it, @emileighoutlaw .

**Comment by AmyKort** [comment]
I'm happy with that. It's nice and short, and it does a whole lot of work. What do other folks think?

**Comment by jwchumley** [comment]
[👍]

________________________________

**Comment by emileighoutlaw** [comment]
Woohoo! Marking this as ready for implementation :)

**Comment by noahmanger** [comment]
Sorry to swoop in late, but I just started working on implementing this and found a snag. First of all, the labels "processed data" and "electronic filings" are too long to fit in a side-by-side toggle. Second, I remember the usability research finding these labels were confusing. @nickykrause was originally looking to change "Electronic filings" to something more like "Raw data". 

Is there a better (and shorter) name we can come up with that also more clearly communicates the nature of the data? I'd vote for something along the lines of "Raw data", "Unprocessed" or "Real-time":
![image](https://cloud.githubusercontent.com/assets/1696495/21411133/d6371164-c79a-11e6-90a7-a1e3f2faaf26.png)

**Comment by PaulClark2** [comment]
Let's go with "Raw data" or "Unprocessed."  I like "raw Data" better but "unprocessed" provides more direct contrast. My preference for "raw data" over "unprocessed" is not strong.

**Comment by nickykrause** [comment]
I'm still a fan of "raw data" - something about the "raw" conveys not only "unprocessed-ness" but also immediacy, or new-ness, and it seems like we want to convey both things. 

That's my two cents, anyway :smile:

**Comment by jwchumley** [comment]
Raw works for me. If I'm not too late chiming in...

________________________________

**Comment by noahmanger** [comment]
We've gone with "raw" data for now. Can modify in the future.
