### ISSUE TITLE
Processed vs raw data on committee pages - exporting data

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#1755]
Hey all,

Just wanted to follow up on the question Christian and Amy raised around the processed vs raw data on committee pages. 

Can you tell me more about what you're looking for? I'm not sure I understand.

Noah

@noahmanger @ChristianHilland @AmyKort @LindsayYoung @jwchumley

**Comment by PaulClark2** [comment]
Christian, were you talking about the export buttons here?

![image](https://cloud.githubusercontent.com/assets/11817734/21389835/ac9fdca8-c751-11e6-85cf-fafe85bbac00.png)

**Comment by PaulClark2** [comment]
No, he was talking about downloading transactions. Viewer (I searched for C00213512) -- Two-year summary tab -- Itemized individual contributions (or any hyperlinked category).

Currently users are only able to download as-amended, processed data (two-year period-to-date).


I'm pretty sure what Christian is asking for is the ability to download both download as-amended, processed data (two-year period-to-date) and the as-amended, raw data (two-year period-to-date) from the Committee pages, https://beta.fec.gov/data/committee/C00213512/?cycle=2016&tab=summary, (new feature) or from here https://beta.fec.gov/data/receipts/?two_year_transaction_period=2016&committee_id=C00213512&min_date=01%2F01%2F2015&max_date=12%2F20%2F2016&is_individual=true or any of the transaction level search pages. 

![image](https://cloud.githubusercontent.com/assets/11817734/21389844/be49cfcc-c751-11e6-947c-210dcc4f9ec4.png)

**Comment by PaulClark2** [comment]
That's great! Do those have structured links?

**Comment by PaulClark2** [comment]
Thanks, Paul.  Yes, I was just curious as to where the itemized processed and raw data would be presented on the site. I assume that data will be accessible through a section of a committee's page.

**Comment by PaulClark2** [comment]
@LindsayYoung No, they do not have structured links. The web app makes a database call when you click on one of the links on the two-year summary page.

**Comment by PaulClark2** [comment]
To be clear, Christian is asking for the ability to download transaction level data, processed and raw efiling, from a committee page like, https://beta.fec.gov/data/committee/C00213512/?cycle=2016&tab=summary, as well as from from the SA, SB, SE, etc. pages.

**Comment by noahmanger** [comment]
I see! Thanks for clarifying. We don't currently have a place for downloading transaction-level data from these pages, but it's one of the themes that has emerged and we'll look at it when we move on to redesigning these pages later this quarter. I'm adding this issue to that epic.
