### ISSUE TITLE
Fix transaction period date filter

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1770]
We need to come up with a better solution for generating the list of transaction period filters. This PR introduced a temporary fix https://github.com/18F/openFEC-web-app/pull/1769

The first task is to figure out what we want our approach to be.

---

## Update
Per the discussion below, we've decided that:
- We want a global constant for the default cycle
- This cycle should be the default for 1-2 months into the odd year of a new cycle, and then be manually changed to the new cycle
- Even though for a couple months we default to the previous cycle, the new cycle (e.g. `2017-2018`) should be an option on all cycle selects

So to do this, we need to:
- [x] Set a global `DEFAULT_CYCLE` constant
- [x] Update the `transaction_period` filter to default to `DEFAULT_CYCLE` and also include the next cycle as an option (this shouldn't be hard-coded)

**Comment by ccostino** [comment]
@noahmanger I'll tag team this with you to help!

**Comment by noahmanger** [comment]
@ccostino for next week: The code for this lives here https://github.com/18F/openFEC-web-app/blob/develop/openfecwebapp/templates/macros/filters/date.html#L35

As a temporary fix, I hard-coded the max-value in that range as 2016 (it was previously using the current year). 

The bigger question for me is when we should change the default time period across the site. Right now people are still doing research on 2015-2016 transactions, but I'm not sure when we should change it. Either way, I doubt it would make sense to ever make it the first of the year, and so I wonder if instead we should set a global config constant for `DEFAULT_CYCLE` or something that we can use to set the default view everywhere?

I'm curious what @PaulClark2 and @jwchumley think about the question of when the default should switch over.

**Comment by ccostino** [comment]
Thanks, @noahmanger!  I like the idea of setting a `DEFAULT_CYCLE` of sorts, but I am also curious what @PaulClark2 and @jwchumley think about this as well.  Do either of you have any additional thoughts or preferences around how we should approach this?

**Comment by ccostino** [comment]
One other thing to note: we couldn't make it start on an odd year because of the way election cycles are set (they start and end on even years).  We already account for all of this in the API.  Starting on [line 9 in `config.py`](https://github.com/18F/openFEC/blob/develop/webservices/config.py#L9), we have two methods defined for calculating the start and end of a cycle for any given year, then have a few default values set.

Should we consider implementing the same logic in the web app side, create a new API endpoint that exposes this information, or stick with this simple implementation but with the understanding that it can only ever be even number years and it'll require a (very small) manual change every so often to adjust which cycles are present on the site?

**Comment by PaulClark2** [comment]
We tend to "activate" the next cycle quickly after January 1 of the odd year. For our bulk data files, this happens the first Sunday after January 1. For the Data Catalog and other data files, this usually happens mid-January. Users are often interested in new Statements of Organization (F1s) and Statements of Candidacy (F2s). However, folks interested in financial data are still looking at the previous cycle (right now they'd be looking at 2015-2016 data). 

I'm not sure anything I've written here helps solve our problem.

**Comment by ccostino** [comment]
Thanks, @PaulClark2, this is still helpful to know!  Based on this information and the expanded discussion yesterday in our grooming session, it sounds like we should account for these two things:

* Setting a default cycle to start on when first visiting the page.
* Allowing for newer cycles to still be selected, even if the default is one cycle older, but potentially accounting for the fact that they shouldn't be available until 1 or 2 months into a new odd number year.

Does this sound right?  If so, I think we're in good shape to move forward with figuring out an appropriate implementation. :-)

**Comment by noahmanger** [comment]
Sounds like a good plan to me. Let's move forward with that. I'll update the original issue.
