### ISSUE TITLE
Canonical URL metadata is incorrect

### ISSUE THREAD

**Issue by dogweather** [18F/openFEC-web-app#1772]
It seems to be set to `https://beta.fec.gov/data` in every page. E.g.:

![screen shot 2017-01-03 at 6 55 17 pm](https://cloud.githubusercontent.com/assets/150670/21630477/6c446fa8-d1e6-11e6-9e5b-608c38f2e1b6.png)

**Comment by noahmanger** [comment]
Very late chiming in here, but we discussed in PI planning that these SEO enhancements are something we want to do before the flip. @dogweather do you want to take these on?

**Comment by dogweather** [comment]
Sure, you got it.

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/fec-cms/pull/987 (with changes to web app also coming soon).
