### ISSUE TITLE
Implement breadcrumb structured data

### ISSUE THREAD

**Issue by dogweather** [18F/openFEC-web-app#1773]
I believe this would have a positive impact on usability and findability, and is not hard. E.g:

![breadcrumb-url-example](https://cloud.githubusercontent.com/assets/150670/21630576/783b09ec-d1e7-11e6-917d-afce788d538a.png)

[Docs by Google](https://developers.google.com/search/docs/data-types/breadcrumbs)

**Comment by noahmanger** [comment]
This is another one to work on before site flip.

**Comment by dogweather** [comment]
I'm taking it on.
