### ISSUE TITLE
Redesign financial summary component

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1783]
So that users can best understand a candidate or committee's two-year financial totals, design an improved financial summary component that is easier to read and comprehend.

---

Coming out of the [research synthesis](https://github.com/18F/openFEC-web-app/issues/1765), one of the first tasks is to design a new financial summary component for committee pages and candidate pages that addresses the user needs:

- Show sub (and sub-sub) totals in a clear way for easy scanning
- Include links to itemized transactions when relevant
- Show the coverage periods for the data and date the last report was received
- Include a link to all of the reports that constitute the totals

**Completion criteria:**
- [x] Design for committee pages ready for implementation
- [x] Design for candidate pages ready for implementation

**Comment by nickykrause** [comment]
Financial summary idea that I passed to Jen for her thoughts 💭  and her magic 🌟 

![image](https://cloud.githubusercontent.com/assets/1450173/22381593/cef94142-e487-11e6-8a4d-82df875812eb.png)

More to come from Jen

**Comment by jenniferthibault** [comment]
🖌  [Full Candidate profile redesign mockups](https://gsa.invisionapp.com/share/ESA8FN046#/216609962_Candidate_-_Financial_Summary)

## Preview of financial summary redesign:

### GOALS and updates for this page:

#### GOAL 2: Offer a more thorough and usable "report-style" financial summary

- We designed a new "report-style" presentation of the Financial Summary info for Candidates, which offers the level of detail originally presented on fec.gov

#### GOAL 3: Show more totals and subtotals on Candidate pages

- On the Financial Summary, we have designed a detailed report that contains totals & subtotals across a variety of data points for a Candidate

![candidate - financial summary](https://cloud.githubusercontent.com/assets/11636908/22428415/e3dc768e-e6d4-11e6-903c-10abe79742a0.png)

We're going to be walking through this in detail in today's demo.

**Comment by jenniferthibault** [comment]
So that we can re-use this issue for committee page redesign work, which will likely be almost entirely similar, I'm moving this into sprint 6 and the "Ready" column.
