### ISSUE TITLE
Pending AO filter doesn't seem to work

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1794]
When checking the "Show only pending requests" on the [AO search page](https://fec-stage-proxy.18f.gov/data/legal/search/advisory-opinions/?search_type=advisory_opinions&search=&ao_name=&ao_no=&ao_min_date=04%2F01%2F1975&ao_max_date=01%2F16%2F2017&ao_is_pending=true&ao_requestor=&ao_requestor_type=0) no results are shown, even though [fec.gov](http://saos.fec.gov/saos/searchao;jsessionid=62A38F841122B93F69FD9E37A33B7990?SUBMIT=pending) shows three pending AOs.

Is this an issue with our data or with the functionality of the filter? cc @anthonygarvan

**Comment by anthonygarvan** [comment]
This works fine. Note that pending AOs do not yet have final opinions. Shows [4 pending AOs](https://fec-stage-proxy.18f.gov/data/legal/search/advisory-opinions/?search_type=advisory_opinions&search=&ao_name=&ao_no=&ao_min_date=04%2F01%2F1975&ao_max_date=01%2F16%2F2017&ao_category=R&ao_is_pending=true&ao_requestor=&ao_requestor_type=0) on staging. If we think this will be a gotcha for a lot of people it might require some UX attention. cc @nickykrause .

**Comment by noahmanger** [comment]
Oh I see. And if no document type is shown Final Opinion gets set as a default. I think this is ok to release as-is but we should think about this.

**Comment by noahmanger** [comment]
We have an answer for this in the new designs here https://github.com/18F/fec-eregs/issues/329 so I'm closing.
