### ISSUE TITLE
Implement citation filter for AOs

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC-web-app#1810]
So that users can quickly find relevant AOs , allow them to search by citation using typeahead inputs for regulations and statutes.

---

🖌  [Design](https://cloud.githubusercontent.com/assets/1450173/22312632/537afbc4-e31e-11e6-912f-b320d4e44348.png) | 🗣 [Discussion](https://github.com/18F/openFEC-web-app/issues/1735) + [More discussion](https://github.com/18F/openFEC-web-app/issues/1764#issuecomment-275255186)

**Dependency:** [Back-end support](https://github.com/18F/openFEC/issues/2164)
**Parallel workstreams:** 
- [Implement citation filter for MURs](https://github.com/18F/openFEC-web-app/issues/1764)
- [Implement citation filter for ADRs](https://github.com/18F/openFEC-web-app/issues/1813)

**Completion criteria:**
_Needed._

**Comment by noahmanger** [comment]
Closing in favor of https://github.com/18F/openFEC-web-app/issues/1857
