### ISSUE TITLE
Implement citation filter for ADRs

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC-web-app#1813]
So that users can quickly find relevant ADRs , allow them to search by citation using typeahead inputs for regulations and statutes.

---

🖌  [Design](https://cloud.githubusercontent.com/assets/1450173/22312632/537afbc4-e31e-11e6-912f-b320d4e44348.png) | 🗣 [Discussion](https://github.com/18F/openFEC-web-app/issues/1735) + [More discussion](https://github.com/18F/openFEC-web-app/issues/1764#issuecomment-275255186)

**Dependency:** Back-end support: ?
**Parallel workstreams:** 
- [Implement citation filter for MURs](https://github.com/18F/openFEC-web-app/issues/1764)
- [Implement citation filter for AOs](https://github.com/18F/openFEC-web-app/issues/1810)

**Completion criteria:**
_Needed._

**Comment by noahmanger** [comment]
We're still a ways out on ADR data, so I'm moving this out of Sprint 6.
