### ISSUE TITLE
Review content for ADR and AF filters

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/openFEC-web-app#1814]
This is a continuation of: https://github.com/18F/openFEC-web-app/issues/1797#issuecomment-275701188

The filters, as they are today:
![mur_filters_v3](https://cloud.githubusercontent.com/assets/1450173/22376670/8de60c52-e474-11e6-8276-8fef449efd76.png)

![adr_filters_v3](https://cloud.githubusercontent.com/assets/1450173/22376643/731e37a0-e474-11e6-97ff-9ada6dc9c1b3.png)

![af_filters_v3](https://cloud.githubusercontent.com/assets/1450173/22377375/43176790-e477-11e6-8c40-88c2ed7b2a2b.png)

Content notes to follow 🌞

**Comment by jenniferthibault** [comment]
If it's helpful to see these big & leave comments in-line, I made an [InVision](https://gsa.invisionapp.com/share/BHA8KHWME#/216649562_ADR-Filters) with these mockups for today's demo.

**Comment by emileighoutlaw** [comment]
Thanks, Jen!

**Comment by AmyKort** [comment]
Issue moved to [18F/fec-cms #1560](https://github.com/18F/fec-cms/issues/1560) via [**ZenHub**](https://www.zenhub.com/)
