### ISSUE TITLE
Add amendment chain to reports panels

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1815]
So that users can understand the complete history of a filing, show the amendment chain in the details panel of all reports.

---

This is pulling the amendment chain work into its own story out of https://github.com/18F/openFEC-web-app/issues/1738 . 

[The design](https://cloud.githubusercontent.com/assets/11636908/21234683/a22ce0c0-c2c1-11e6-9484-8786a018672b.png)

**Criteria for completion:**
- [ ] All reports (candidate, PAC, and party) show the amendment chain, both on the /filings/ page and /reports/ pages
- [ ] The amendment chain section includes a blurb explaining what it is (need copy from @emileighoutlaw )
- [ ] The latest version shows the latest version icon
- [ ] Previous versions show the previous version icon
- [ ] All amendments include links to their downloads and the date they were filed
- [ ] The current version you're looking on should show `(Selected)` and have a bold title

**Comment by xtine** [comment]
The panels started out as generic templates, but now we have more cases for specialization depending on the type of datatable it's on. As the templates are starting to get more complex, I think there will be value in stepping back and refactoring how datatable templates are set up to make this and future panel tasks easier and more comprehensible in the future.
