### ISSUE TITLE
Create new page layout for candidate pages

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1819]
So that candidate pages are easier to navigate, create a new layout for candidate pages that switches from tabs to a sidebar. 

---

[Designs](https://gsa.invisionapp.com/share/ESA8FN046#/216609962_Candidate_-_Financial_Summary)

This is one of several tasks to redesign candidate pages. The purpose of this is just to replace the page navigation tabs with a sidebar. This should work exactly like the tabs currently do, where clicking on one shows a new panel and updates the URL accordingly. This issue does not entail re-arranging other components, as that will happen in a separate issue.

**Completion criteria:**
- [x] Make a new base template behind a feature flag
- [x] On large screens, tabs are arranged in a sidebar next to main content area
- [x] On small screens, tabs are full-width and below the main content area
- [x] Clicking on a tab shows the related section
- [x] Clicking on a tab updates the URL
- [x] A11y check: All tabs can be tabbed through and operated with a keyboard

**Comment by noahmanger** [comment]
@xtine what do you think about including all of these changes in a new template file that we include only when a feature flag is turned on? I'm worried about breaking things apart in the current templates and then having things in a state of disrepair, depending on how the various features go.

**Comment by xtine** [comment]
@noahmanger: I agree, I think it's probably worthwhile to make a new template so both pages are accessible until the new layout is complete.

**Comment by noahmanger** [comment]
Cool. Let's do this issue first then. I updated the completion criteria to include the feature flag.

**Comment by xtine** [comment]
Where do the links on the side nav for "Elections and Committees," "Individual Contributions," "Disbursements," and "Filings" go to?
