### ISSUE TITLE
Add links to new data pages on Advanced Data

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1838]
So that users can find the pages for loans, debts and party expenditure, add links to the Advanced Data page.

---

Party expenditures should go under "Spending" but I'm not sure about loans and debts. Maybe we need a new section for these? If so, we will need @emileighoutlaw to add a blurb of content perhaps.

---

## Update
Party expenditures is added, so we just need a section for loans and debts.
- [ ] Write content for section
- [ ] Add to page

**Comment by emileighoutlaw** [comment]
In our content, we've been separating loans, debts, and advances out as its own thing, separate from raising and spending. So that would be nicely consistent with the content, if we went in this direction.

**Comment by noahmanger** [comment]
I'll add these links in this work (https://github.com/18F/openFEC-web-app/issues/1877) but we still need content explaining what loans and debts are. Is there a working definition we've used elsewhere?

**Comment by emileighoutlaw** [comment]
We have content on the `loans, debts and advances` landing page, but I don't think we can reuse it for this (it doesn't quite translate between contexts). 

@AmyKort — do you think this is something you and I could pair on together? Ask someone from the content managers or data team to help us write?

**Comment by AmyKort** [comment]
Yes!

**Comment by noahmanger** [comment]
This work is now included in [this issue](https://github.com/18F/openFEC-web-app/issues/1885) here. We'll deal with all of the content for this page in one fell swoop.
