### ISSUE TITLE
[ATO] Address IE-specific issue with cross-site scripting

### ISSUE THREAD

**Issue by ccostino** [18F/openFEC-web-app#1840]
In addition to the other cross-site scripting issue (#1839), there was another one found specifically with IE, where you could put anything after the root URL (e.g., https://fec-dev-proxy.app.cloud.gov/whatever_here) and it would process.

It is possible we'll need to take a look at the https://github.com/18F/fec-proxy app as well for this one.

**NOTE:** This is intended for GovCloud, but needs to be fixed across the board.

**Comment by xtine** [comment]
In researching this particular issue, I realized that this might be the result of IE specific XSS filters that prevents a page from being loaded if it thinks it detects a XSS attack. There is a HTTP header that controls this filter, `X-XSS-Protection` (more detail here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection) and it seems to be active only in IE.

At first I thought about turning this filter off, but I think we should look if we can have a nginx specific rewrite of any suspicious strings in the URL (like `<script>`) to forward to 404.

**Comment by ccostino** [comment]
Awesome, thanks for looking into this, @xtine!  Forwarding to a 404 or just a 400 (Bad Request) makes sense to me.  I suggest 400 since the root URL/path is likely okay, it's the data being passed along with it in the query parameters that are bad/malformed.
