### ISSUE TITLE
Data Broken Links

### ISSUE THREAD

**Issue by patphongs** [18F/openFEC-web-app#1845]
After running a link crawler, there were many data broken links. We'll want to investigate whether these are programatic issues that can be solved.

https://docs.google.com/spreadsheets/d/1VwzkBC1PtXfqMIoCHC_nGE6wyU9n0D_ZQ5AjK1mAbrw/edit#gid=852590192

**Comment by jwchumley** [comment]
I looked at the first 24 or so broken committee links. In each case the url uses a cycle that the committee wasn't or isn't yet active. For example:
https://beta.fec.gov/data/committee/C00027193/?cycle=1986&

THis committee terminated in 1984 so there should be no link to it in the 1986 cycle.

This one is a little different as it is still an active committee:
https://beta.fec.gov/data/committee/C00091892/?cycle=2020&

The candidate has filed a 2020 form 2 and exists as a 2020 candidate but the committee hasn't filed anything yet beyond 2016. 

I think we need to how these urls are being created to see if it is a data issue or a logic issue. It may be both.



@patphongs @noahmanger @PaulClark2 @LindsayYoung @ccostino

**Comment by patphongs** [comment]
@jwchumley The terminated committee is interesting because even though it terminated in 1984, it shows up when you are viewing the full election cycle https://beta.fec.gov/data/candidate/S4UT00027/?cycle=1986&election_full=true. The committee even says that it was from 1976–1984. Maybe some logic needs to be added that if a committee is terminated, make the link only to the year that it was terminated when viewing the full cycle?

**Comment by jwchumley** [comment]
@pat Yep. I think Lindsay or Carlo will pretty easily see if it is a logic issue on their end (I think so) or an underlying data issue. I don't see the issue on our end but it could be there.

**Comment by patphongs** [comment]
I moved the committee cycle problem noted here in a new issue here #1852

**Comment by noahmanger** [comment]
So I'm hoping the broken committee links will be addressed with the fix I described in #1852 . As for the one broken candidate link here, the issue seems to be that she ran for a special election in 2013. I'm not sure what the solution is, but hopefully that helps narrow the problem.

**Comment by noahmanger** [comment]
The broken committee link issue was resolved in the last release, and the special election candidate issue is tracked elsewhere. Closing.
