### ISSUE TITLE
Candidate 404 page

### ISSUE THREAD

**Issue by patphongs** [18F/openFEC-web-app#1850]
Candidate HALVORSON, DEBORAH is showing a 2013 cycle in the drop down rather than a 2014. Therefore, going to that candidate's page yields a 404 due to the fact it is trying to pull up a non-existent 2013 cycle slice

https://beta.fec.gov/data/candidate/H8IL11113/

**Comment by noahmanger** [comment]
I believe this is the same issue as #1929, so I referenced this there, but will close to cut down on open threads.
