### ISSUE TITLE
election pages -- invalid election years for President and Senate

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#1863]
...data/elections/president/ allows users to enter invalid presidential election years. 

We should not allow a 2018 presidential election page. The dates displayed on the page, as it exists now, are confusing. 

https://beta.fec.gov/data/elections/president/2018/
![president-election-page](https://cloud.githubusercontent.com/assets/11817734/23460331/e07c10c2-fe52-11e6-8f1c-4ca7e9707d2a.png)

**Comment by PaulClark2** [comment]
...data/elections/senate/[STATE]/ allows users to enter invalid Senate election years. 

https://beta.fec.gov/data/elections/senate/MO/2020/ MO does not have a Class 2 (2020) Senate election.

The dates displayed on the page are confusing.

![senate-class2-invalid-election-2020-page](https://cloud.githubusercontent.com/assets/11817734/23460504/bd462d30-fe53-11e6-9070-8255a1b3dc4c.png)

**Comment by PaulClark2** [comment]
Also see https://github.com/18F/openFEC-web-app/issues/1864

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/openFEC-web-app/pull/1865
