### ISSUE TITLE
election pages - future Senate electons

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#1864]
Senate Class 1 is up for election in 2018. The election pages for classes 2 and 3 are confusing.

Class 2: https://beta.fec.gov/data/elections/senate/IL/2020/
Class 3: https://beta.fec.gov/data/elections/senate/AZ/2022/

![senate-class2-2020-election-page](https://cloud.githubusercontent.com/assets/11817734/23460807/255e532e-fe55-11e6-8fe0-5ac4f6e6168b.png)

![senate-class3-2022-election-page](https://cloud.githubusercontent.com/assets/11817734/23460811/29b2f966-fe55-11e6-92bc-0e59ff6d2c13.png)

Also see https://github.com/18F/openFEC-web-app/issues/1863

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/openFEC-web-app/pull/1865
