### ISSUE TITLE
Improve ability for users to get to the larger data set from relevant sub-sections on candidate & committee profile pages

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC-web-app#1869]
On candidate pages, such as https://beta.fec.gov/data/committee/C00004473/?tab=summary&cycle=2016

We currently provide links to the full data set for Receipts from the Financial summary tab

<img width="997" alt="screen shot 2017-03-03 at 11 53 22 am" src="https://cloud.githubusercontent.com/assets/11636908/23561177/1fc3c41e-000b-11e7-8f59-fa284e51ff66.png">

and for disbursements:

<img width="993" alt="screen shot 2017-03-03 at 12 15 49 pm" src="https://cloud.githubusercontent.com/assets/11636908/23561191/3010b2b4-000b-11e7-806f-a5fcae998328.png">

On the disbursements tab, we change the language of this button to `Filter this data` - but at least one user ( 👋 @PaulClark2 ) reported that they couldn't get to the full disbursement data from this page.

![screen shot 2017-03-03 at 12 16 56 pm](https://cloud.githubusercontent.com/assets/11636908/23561241/6f9be3d6-000b-11e7-9ea2-33bd50c4f42d.png)

We don't currently have a separate "Receipts" category—instead we surface a sub-category of receipts, "Individual contributions". This decision was made because it's the most commonly requested information. On this page, users can access the whole IE data table through the `Filter this data` button, but the user reported looking there for the ability to get to "All receipts" data.

![screen shot 2017-03-03 at 12 19 15 pm](https://cloud.githubusercontent.com/assets/11636908/23561382/026e1a58-000c-11e7-9ef7-3f2e940189ab.png)

_______
**Transcript of original feedback:**
> *Paul:* "this is probably a user error (mine). When I'm on a committee profile page, how do I get to all receipts?  I see how to get to individual contributions and all disbursements. I don't see how to get to all receipts."

> *Jen:* "Right now we don’t have a separate tab for receipts, but we do have them summarized (with a button link to the data table that’s labeled “Browse receipts") on the financial summary tab. Can you say more about what you were expecting to see? and does that button bring you to what you were looking for?"

> *Paul:* "Yes. I see that button now. It's only available from the financial summary tab. It disappears if I select the individual contributions tab.  I expected it to be an option or at least to have an easy path to all receipts. The same is true about disbursements. The button to browse all disbursements disappears if I select the disbursements tab."

_______

**Design questions to pursue**
- How should we adjust the language on the buttons to be consistent across all tabs, and to better hint at what data set they link to?
- How should we provide access to the full data set of the parent data category?
- If we are surfacing "Disbursements" as its own tab, should it's sibling, "Receipts" be at the same level and also have its own tab for parity in information modeling?

cc @nickykrause / @emileighoutlaw / @onezerojeremy

**Comment by PaulClark2** [comment]
Thanks, Jen.

One tweak to your description, independent expenditures is a sub-category of spending. 

This is rough. I wonder if the left nav should have categories like this
Financial summary
About this committee
Receipts
   All receipts
   Individual contributions
   [other categories of contributions -- future feature]
Disbursements
   All disbursements
   current disbursement link [needs a name]
Between committees
Independent expenditures
Filings

**Comment by jenniferthibault** [comment]
Ack, I said "independent expenditures" but meant "individual contributions". At least I got the screenshot right to prove it! Thanks for pointing that out @PaulClark2 I'm going to edit the post to correct it for future readers

**Comment by PaulClark2** [comment]
Suggestion following our discussion about using "raising" and "spending."

    Financial summary
    About this committee
    Raising
        All receipts
        Individual contributions
        [other categories of contributions -- future feature]
    Spending
        Disbursements [transactions]
        Disbursement aggregations [current disbursements page]
        Between committees [need to confirm this only includes SB transactions reported by the committee the users is viewing]
        Independent expenditures
    Filings

**Comment by jenniferthibault** [comment]
We've pulled out the structure design questions into https://github.com/18F/openFEC-web-app/issues/2019

**Updated design questions to pursue in this issue**
- Where do users expect to be taken if there is a data table link near each section? (see testing issue https://github.com/18F/fec-testing/issues/36) 
- If relevant, what sections need them, what sections don't?
- How should we adjust the language on the buttons to be consistent across all tabs, and to better hint at where they will take you?

**Comment by jenniferthibault** [comment]
This issue was integrated into the design and thinking of #2019 , so closing in favor of discussion happening there
