### ISSUE TITLE
candidate profile page - elections

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#1874]
I'm generally not a fan of the elections list at the top of the candidate profile pages. 

Strom Thurmond participated in these elections: 1954, 1956 (special), 1960, 1966, 1972, 1978, 1984, 1990, 1996
![image](https://cloud.githubusercontent.com/assets/11817734/23662287/12e75124-031d-11e7-89c9-e35013da135f.png)

This list is accurate. But, I'm not sure what value it adds.
![image](https://cloud.githubusercontent.com/assets/11817734/23662792/a45c0f54-031e-11e7-995e-c2acc21003b1.png)

**Comment by noahmanger** [comment]
This is all changing with the [new candidate pages](https://gsa.invisionapp.com/share/ESA8FN046#/218195097_Candidate_-_Financial_Summary) which should be shipping with the next release next week. So I'm going to close this.
