### ISSUE TITLE
Implement improved results display for AO search

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1882]
So that users can better understand the results returned by different filters when browsing AOs, implement an improved results display that shows more information as well as case and document views.

---

[Case view](https://gsa.invisionapp.com/share/K4A5SHNFJ#/215798709_AO-Case_View) | [Document view](https://gsa.invisionapp.com/share/K4A5SHNFJ#/215798710_AO-Document_View)

Dependency: https://github.com/18F/openFEC/issues/2242

The expected behavior is that if a user has entered a text query, the results should be presented in the document view. If they did not, the results should only be presented in the case view, which gives a condensed presentation of the information and doesn't show text matches within documents (because there's no text to show).

**Completion criteria:**
Case view includes:
- [x] Case number and title and link to canonical page
- [x] Date issued
- [x] Summary
- [x] Links to later AOs that cite this AO
- [x] Pending AOs show "Pending request" with icon

Document view includes:
- [x] All of the case info above
- [x] Nested documents that contain matching text
- [x] Document category with a link to the PDF
- [x] Matching text excerpt with matches highlighted

**Comment by anthonygarvan** [comment]
@noahmanger can we break the tag implementation into a separate story? It's not mentioned here but it's in the design, I think it makes sense to get this in and track that separately.

**Comment by noahmanger** [comment]
For sure. https://github.com/18F/openFEC-web-app/issues/1965
