### ISSUE TITLE
Do load testing

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1886]
We want to do load testing on our various apps so we're sure that they can handle the increased load that we expect from being the main fec.gov. We should do this for all of the apps:

- API
- Web app
- CMS
- eRegs (though probably much less necessary here)

**Comment by AmyKort** [comment]
@vrajmohan  Is this issue still relevant?

**Comment by AmyKort** [comment]
Issue moved to [18F/fec-cms #1611](https://github.com/18F/fec-cms/issues/1611) via [**ZenHub**](https://www.zenhub.com/)
