### ISSUE TITLE
Build Liger prototype

### ISSUE THREAD

**Issue by nickykrause** [18F/openFEC-web-app#1887]
Coming out of https://github.com/18F/fec-cms/issues/835, we have decided to set aside a few days at the beginning of the upcoming sprint to build a prototype of the "Liger" approach to the two-site experience. 

To reiterate what the Liger approach is:

> **Liger.** For content that we know needs to be migrated but has not yet been redesigned, create "transitional" pages on the new site (fec.gov), where the body of the page contains legacy content and the "frame" of the page contains the new navigation. Also create an "archive" version of the legacy site, which will be a snapshot of the site in its full form, but which will not continue to be updated (it is for reference only).

If we are able to make sufficient progress on a Liger prototype without encountering significant blockers, then we will proceed to test Liger with both internal and external users. If Liger does not work well for any reason, we can switch to our alternative two-site experience approach, known as **Mirror**.

The Liger experience is available via in [this InVision](https://gsa.invisionapp.com/share/KMAR2WZSF#/222566350_Rd2-Home-Alert) on screens 15-21. 

**Completion criteria**
- [x] A Liger prototype that can be used for testing with internal / external users

OR

- [x] An understanding of the difficulties of implementing Liger and a recommendation to switch to Mirror

**Comment by noahmanger** [comment]
We're past the stage of prototyping, so closing this.
