### ISSUE TITLE
Update "no data" messages

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1888]
Once we do the site flip, we will likely want to update these messages that appear when no data has been reported by a candidate or committee for a certain time period:

![image](https://cloud.githubusercontent.com/assets/1696495/24025005/e0035730-0a74-11e7-8d1f-398f45510546.png)

**Comment by emileighoutlaw** [comment]
Bringing this more in line with our other error messages (issue: https://github.com/18F/fec-cms/issues/881), how about this:

> ## No results
> Sorry, we didn’t find any documents filed for **XXXX** in **XXXX**.

> [Try a different search]

> Think this was a mistake? Send us an _email_ or file a _GitHub issue_. 

cc @AmyKort

**Comment by noahmanger** [comment]
My $.02: I'd move away from the "Sorry, we didn't find any" language. This message is used when there's just no reports filed for a committee, so I think it would be good to separate it from any sense of there being something wrong. I think we had this more cautious language up at first when there was more of a risk, but now I think we can assert a little more confidence. Does that make sense?

**Comment by emileighoutlaw** [comment]
Yep — that makes sense. Do I remember correctly that there sometimes be a decent amount of lag-time between a filing deadline and when documents show up in our search?

What I'm wondering is if we should take a step back from "sorry" but still be gentle:

> ## No results
> We didn’t find any documents filed for **XXXX** in **XXXX**.

or if we can/should be more firm about the documents not existing:

> ## No results
> No documents have been filed for **XXXX** in **XXXX**.

**Comment by emileighoutlaw** [comment]
> ## No results
> We don’t have any financial data for **XXXX** in **XXXX**. 

> Sometimes no results are returned when:
> - There hasn't been a filing deadline yet
> - A filing deadline has passed, but the FEC hasn’t finished processing the financial data

> To find the most recent activity for this candidate, try changing the election cycle. 

> [ Search another year ] 

> Think this was a mistake? Send us an _email_ or file a _GitHub issue_.



?

**Comment by noahmanger** [comment]
What about:

> We don’t have any financial data for **XXXX** in **XXXX**. 

> This can either be because:
> - There hasn't been a filing deadline yet, or
> - A filing deadline has passed, but the FEC hasn’t finished processing the financial data

> To find the most recent activity for this candidate [or committee], try changing the election cycle. 

> Think this was a mistake? Send us an _email_ or file a _GitHub issue_.

Is it against our pattern to not include a title? The "No results" seems heavy in this situation, and "results" feels like a weird word to use because it's this is showing up in a situation where there wasn't really a "search" initiated.

**Comment by emileighoutlaw** [comment]
Ooo, I like it much better without the"No results" title.

The content inconsistency with other messages doesn't set off any alarms (it _is_ a unique interaction) but @jenniferthibault might have a different visual style perspective.

**Comment by jenniferthibault** [comment]
No title 👍 ! It's not a strict template, it's one we can use pieces of but leave fields blank when they aren't necessary.

**Comment by noahmanger** [comment]
Working on implementing this and I found another case that might warrant a different message: the other spending tables on candidate pages:

![image](https://cloud.githubusercontent.com/assets/1696495/25151111/4d9d7ca2-2452-11e7-9165-7f47f911c6ac.png)

In these cases, it may be because nobody has made any of these expenditures or that none have been reported yet.

**Comment by emileighoutlaw** [comment]
Would it be something more like this? 

> We don’t have any itemized financial data for **NAME** in **YYYY-YYYY**. 

> Sometimes this happens when a candidate [or committee]:
> - Hasn't made any expenditures
> - Has made expenditures, but there hasn't been a deadline to report them

> To find the most recent activity for this candidate [or committee], try changing the election cycle. 

> Think this was a mistake? Send us an _email_ or file a _GitHub issue_.

**Comment by emileighoutlaw** [comment]
We also need a no results message for our new :tada: search :tada:

<img width="993" alt="screen shot 2017-04-21 at 4 35 15 pm" src="https://cloud.githubusercontent.com/assets/10552702/25297002/c0743904-26b0-11e7-8d86-b2b3b10d65a7.png">

_(header is optional depending on what design we use)_

> **No results** 
> We didn’t find any pages matching **XXXX**. 

> FEC.gov is in the middle of a redesign, and some pages aren’t included in search results yet. Please try another search. Or, [search an archive](classic.fec.gov) of the old FEC.gov design.

> If you’d like to contact our team, we’re available by [email](url) or [GitHub](url). 


What I wanted to offer folks was:
- A not-too-complicated explanation that this isn't 100% inclusive
- A pathway to search on the old site if they want
- A pathway to contact our team

**Comment by jenniferthibault** [comment]
@emileighoutlaw is this what you're thinking?

![screen shot 2017-04-21 at 7 28 51 pm](https://cloud.githubusercontent.com/assets/11636908/25299007/c87803de-26c8-11e7-89e9-5456736b815e.png)

**Comment by emileighoutlaw** [comment]
Yep! It didn't feel like we needed any buttons like we do on the other messages, since the option to re-do a search is right there above it on the page.

**Comment by emileighoutlaw** [comment]
A last thought for the week: Google offers more suggestions of what people might do differently, which is one thing we don't do: 

![digg-not-found-in-google](https://cloud.githubusercontent.com/assets/10552702/25299093/3766e092-26c1-11e7-816e-39d32032a586.jpg)

I was worried the content was getting pretty verbose. But if we thought adding that kind of prompt would be helpful, I'd be down for trying to tighten things up.

**Comment by noahmanger** [comment]
I think that for no results on the site search we might also want to re-highlight the additional searches. Not sure if that means we duplicate the links that are in the sidebar or just mention them, but I could imagine queries that yield no results here but could in another system.

**Comment by noahmanger** [comment]
I just added one line, what do you think?

> Try changing your search term or using one of the other specialized search tools.

![image](https://cloud.githubusercontent.com/assets/1696495/25358489/7e8bb0c4-28f6-11e7-8d7f-a51c587bce95.png)

**Comment by emileighoutlaw** [comment]
Love what you did, Noah! When we point folks to the other search tools, I think we should adjust the note that follows. So:

> **No results**

> We didn't find any pages matching **XXXXX**.

> Try changing your search term or using one of our other specialized search tools. 

> _____________________________________________________________________________

> FEC.gov is in the middle of a redesign, and some pages aren't included in search results yet. You can still _search an archive_ of the old FEC.gov design.

> If you'd like to contact our team, we're available by _email_ or _GitHub_

**Comment by noahmanger** [comment]
After wrestling with this for a while, I think I have a good solution for the "no data" messages on itemized tables, which is to offer a more specific explanation (rather than vague, general language):

![image](https://cloud.githubusercontent.com/assets/1696495/25412696/7de0c478-29d9-11e7-8789-20bb33688a36.png)

![image](https://cloud.githubusercontent.com/assets/1696495/25412680/6c2a6b44-29d9-11e7-8d82-e2344de47b0e.png)

![image](https://cloud.githubusercontent.com/assets/1696495/25412683/71f9fabc-29d9-11e7-9725-fc315b3e25bc.png)

![image](https://cloud.githubusercontent.com/assets/1696495/25412690/75ceac8c-29d9-11e7-82e2-437162f6c72a.png)

![image](https://cloud.githubusercontent.com/assets/1696495/25412725/c2b42356-29d9-11e7-8142-d679d4323f98.png)

**Comment by jenniferthibault** [comment]
@noahmanger a content suggestion to the communication costs language:
Instead of saying: 
> No communication costs have been made in opposition or support of this candidate


Could we instead say: 
> No transactions have been made in support or opposition of this candidate 

or

> No spending has occurred in support or opposition of this candidate 

?

On the candidate profile pages, we use the phrase "spending to support or oppose" so we should keep the order and language the same if it makes sense, https://fec-dev-proxy.app.cloud.gov/data/candidate/P80003338/?cycle=2012&election_full=True

**Comment by jenniferthibault** [comment]
and also i love these improvements! 💟

**Comment by noahmanger** [comment]
Well, on the "Other spending" tab, all three of those tables are visible, and it often happens where there's data for one or two out of the three, so I think the more general "No transactions" or "No spending" options are a little confusing because there may well be transactions, just not that specific kind.

Good catch on the ordering of "support" and "opposition" though. I'll make that fix.

**Comment by jenniferthibault** [comment]
Great, I knew you would know if it made sense or not 😄 

👍

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/openFEC-web-app/pull/1958
