### ISSUE TITLE
Strategy for combining openFEC-web-app + fec-cms + fec-style

### ISSUE THREAD

**Issue by xtine** [18F/openFEC-web-app#1891]
A long term goal for the ease of future maintenance and development of beta.fec.gov (and soon fec.gov) would be to combine `openFEC-web-app`, `fec-cms`, and `fec-style` into one repo. This would speed up and make development easier as there would just be one place to look for web app changes, and compilation of static assets (CSS, JS, etc) would be executed and managed from one directory. Deployment would also be simplified and there wouldn't be management of a global npm package.

A proposed way to go about this:
* Convert `openFEC-web-app` from Flask to Django app
* Connect converted `openFEC-web-app` Django app into `fec-cms` project
* Migrate `fec-style` assets and build process into `fec-cms`

**Comment by noahmanger** [comment]
👏  Thanks for thinking about this! One big thing we'd need to solve for is the fact that the two use different templating languages (Jinja2 vs. Django). And if we want to be able to share more templates (like a standard base template that includes header and footer) we'd need to get both to be the same, right?

**Comment by xtine** [comment]
The porting process for `openFEC-web-app` would have to be done file by file (for both Python and html files). Shared base templates would also have to be integrated at time of adding the converted `openFEC-web-app` Django app.

I estimate this to be like 90% straightforward and simple, but the 10% will be the snag that we couldn't predict that might take a bit of time. I do think the time invested will be more than worth the effort in the time/headache savings from managing three separate repos all deployed differently.

**Comment by AmyKort** [comment]
@xtine  Is this issue still relevant?

**Comment by xtine** [comment]
This issue isn't relevant anymore, this was done in the Great Merge a while back.

**Comment by AmyKort** [comment]
Thanks!
