### ISSUE TITLE
Make data landing page resilient to API failures

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1894]
Currently, if an API endpoint that the data landing page relies on is down, the page throws a key error and crashes. We should update the view logic to be more resilient to prevent these issues from crashing the page in the future.

**Comment by LindsayYoung** [comment]
I *think* we want to change the line in api_caller.py:
https://github.com/18F/openFEC-web-app/blob/develop/openfecwebapp/api_caller.py#L35
```
    return results.json() if results.ok else {}
```
to 
```
    return results.json() if results.ok else {'results': []}
```
I think that will make it a bit more graceful of a fail if an endpoint is misbehaving.
