### ISSUE TITLE
Add links to SAOS and EQS from new pages

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1900]
So that researchers understand the benefits and limitations of the new systems and how to get to the legacy systems, add the messages and links to SAOS and EQS.

---

[Design issue](https://github.com/18F/fec-cms/issues/840) | [Content](https://docs.google.com/document/d/1_c-zQyPUdNJ5LROl3BxpD71c5RKhLA5jvlb_oGh_6P8/edit#)

**Completion criteria:**
- [x] Link to EQS and MUR archive on [Enforcement](https://beta.fec.gov/legal-resources/enforcement/)
- [x] Link to SAOS and EQS from the main legal search results page [[design](https://cloud.githubusercontent.com/assets/11636908/23970589/a776ce6c-09a0-11e7-86f2-4fc1314a50f5.png)]
- [x] Link to SAOS on https://beta.fec.gov/data/legal/advisory-opinions [[design](https://cloud.githubusercontent.com/assets/11636908/23970457/3999898e-09a0-11e7-9e30-6173a7e7dd10.png)]
- [x] Link to SAOS on https://beta.fec.gov/data/legal/search/advisory-opinions/
- [x] Link to EQS on [ADR page](https://beta.fec.gov/legal-resources/enforcement/alternative-dispute-resolution/) [[design] (https://cloud.githubusercontent.com/assets/1696495/24121166/81a24586-0d74-11e7-9fe0-74c25f292a0a.png)] (Note this is a CMS page that just needs to be edited)
- [x] Link to EQS on [AF page](https://beta.fec.gov/legal-resources/enforcement/administrative-fines/) [[design](https://cloud.githubusercontent.com/assets/1696495/24121166/81a24586-0d74-11e7-9fe0-74c25f292a0a.png)] (Note this is a CMS page that just needs to be edited)
- [x] Link to EQS and MUR archive from the MURs search results page [[design - expanded](https://cloud.githubusercontent.com/assets/11636908/24118496/6aeec778-0d84-11e7-8bf9-28bfad018399.png)] [design - collapsed](https://cloud.githubusercontent.com/assets/11636908/24118497/6af01286-0d84-11e7-803f-2af6a559b3f8.png)
- [ ] The messages on the data browsing pages are collapsible

**Comment by jenniferthibault** [comment]
Links for linking:
- EQS: http://eqs.fec.gov/eqs/searcheqs
- MUR Archive: http://www.fec.gov/MUR/
- SAOS: http://saos.fec.gov/saos/searchao

**Comment by noahmanger** [comment]
FYI I dealt with a couple of these checkboxes in 

- https://github.com/18F/openFEC-web-app/pull/1920
- https://github.com/18F/fec-cms/pull/950

So I checked them off the list.

**Comment by noahmanger** [comment]
Content is now finalized https://docs.google.com/document/d/1_c-zQyPUdNJ5LROl3BxpD71c5RKhLA5jvlb_oGh_6P8/edit# 🔒

**Comment by noahmanger** [comment]
Links are all added and the final step of making the messages collapsible is here https://github.com/18F/openFEC-web-app/issues/1971
