### ISSUE TITLE
Usability test new candidate pages

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1903]
**Completion criteria:**
- [ ] Test new candidate and committee pages with 4-5 people
- [ ] Synthesize results

**Comment by nickykrause** [comment]
Finished testing last week.

- A few observations and issues have been logged in the testing repo, here: https://github.com/18F/fec-testing/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20created%3A%3E%3D2017-04-07%20label%3Adata

- More detailed, question-by-question observations are available here: https://docs.google.com/spreadsheets/d/1oUZJRdCOo5quMkh3q7CEYW0CNh37jjh5Cl66QD63Bo8/edit#gid=0

**Comment by nickykrause** [comment]
The candidate page testing results have been synthesized in [this spreadhseet](https://docs.google.com/spreadsheets/d/1C-ur70Ksv7ibiGyzpodiZAAngy33SPU_uzXv1YVoK7Y/edit#gid=0) 🔒 

GitHub issues have yet to be logged in the testing repo, but they will be based off of those observations.

**Comment by noahmanger** [comment]
Nice work! Good stuff in there. I'm going to close this issue now that it's all been synthesized.
