### ISSUE TITLE
Browser and device test

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1936]
We should look through a variety of desktop browsers and mobile devices (iOS and Android) to make sure there's no glaring issues. 

Include transition.fec.gov as well.

**Comment by ccostino** [comment]
It'd be good to do this especially after these 3 PRs are merged:

* https://github.com/18F/openFEC-web-app/pull/1986
* https://github.com/18F/fec-cms/pull/1021 (tests are still broken at the moment)
* https://github.com/18F/fec-style/pull/686

I'll post a quite note here once they're all in!
