### ISSUE TITLE
Revisit special election candidate logic

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1953]
In order to ensure that all special election edge cases show up, we should revisit the logic used for displaying candidate pages which https://github.com/18F/openFEC-web-app/pull/1945 patched just to make sure we're not forgetting anything.

**Comment by AmyKort** [comment]
@lbeaufort  Is this issue still relevant?

**Comment by AmyKort** [comment]
Issue moved to [18F/fec-cms #1612](https://github.com/18F/fec-cms/issues/1612) via [**ZenHub**](https://www.zenhub.com/)
