### ISSUE TITLE
No typeahead for 'Obama' in campaign finance data candidate search bar

### ISSUE THREAD

**Issue by nickykrause** [18F/openFEC-web-app#1960]
On the [campaign finance data landing page](https://beta.fec.gov/data/), I entered 'Obama' into the search bar, and there were "no matches" -- Obama's candidate page did not appear in the typeahead. 

<img width="977" alt="screen shot 2017-04-19 at 10 41 50 am" src="https://cloud.githubusercontent.com/assets/1450173/25186116/2cbc92d4-24ed-11e7-8e66-831320cc48f1.png">

The same issue happened for `Barack`

I can only get the typeahead to appear by typing _exactly_ the term `oba` (no more, no less): 

<img width="968" alt="screen shot 2017-04-19 at 10 45 50 am" src="https://cloud.githubusercontent.com/assets/1450173/25186178/6fc8b706-24ed-11e7-96c6-1e6a58e77e08.png">

cc: @noahmanger -- maybe this isn't an issue in the new, combined search?

**Comment by noahmanger** [comment]
Ah yeah this is a weird bug I've noticed before. I'm not sure what the issue is.

**Comment by jenniferthibault** [comment]
Same!

**Comment by noahmanger** [comment]
Consolidating this and other similar bugs in https://github.com/18F/fec-style/issues/714
