### ISSUE TITLE
implement collapsible info message for legal pages

### ISSUE THREAD

**Issue by anthonygarvan** [18F/openFEC-web-app#1971]
- to get legal info messages out, we punted on making the messages collapsible, since that was dependent on work by @xtine . I think that work has been merged now and info messages should adopt the proper styles / js.

**Comment by AmyKort** [comment]
Issue moved to [18F/fec-cms #1585](https://github.com/18F/fec-cms/issues/1585) via [**ZenHub**](https://www.zenhub.com/)
