### ISSUE TITLE
Broken links to various AO searches

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1975]
Caught by Jason: the varios links on the [Advisory Opinion Process page](https://beta.fec.gov/legal-resources/advisory-opinions-process/) to search AO requests, comments and draft answers don't work. They take you to the AO search page with the correct filter selected, but no results.

@anthonygarvan do you know what's up here?

**Comment by anthonygarvan** [comment]
These links had gone out of date with the react upgrade. Paired with @LindsayYoung to get these updated in wagtail.

**Comment by noahmanger** [comment]
Thanks!

**Comment by noahmanger** [comment]
Just curious: what's the link difference?
