### ISSUE TITLE
add 2017-2018 to filings and reports filters

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#1976]
![image](https://cloud.githubusercontent.com/assets/11817734/25340149/d6827ed0-28d2-11e7-9561-cb10d2001a6d.png)

https://beta.fec.gov/data/filings/?data_type=processed
https://beta.fec.gov/data/reports/presidential/?is_amended=false&data_type=processed
https://beta.fec.gov/data/reports/house-senate/?is_amended=false&data_type=processed
https://beta.fec.gov/data/reports/house-senate/?is_amended=false&data_type=processed

**Comment by noahmanger** [comment]
This will be fixed by https://github.com/18F/openFEC-web-app/pull/1966.

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/openFEC-web-app/pull/1966
