### ISSUE TITLE
Levin funds appears twice on pac committee profiel

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC-web-app#1987]
https://beta.fec.gov/data/committee/C00000422/

Look near the bottom of the "raising" block:

Levin Funds
Non-Federal Transfers
Levin Funds

**Comment by noahmanger** [comment]
Oh! The first one should actually be labeled "Total transfers". Fixing.

**Comment by noahmanger** [comment]
Should it be like this? 

![image](https://cloud.githubusercontent.com/assets/1696495/25448007/021499bc-2a6c-11e7-8628-ff73789e6470.png)

**Comment by jwchumley** [comment]
Good. Thanks

**Comment by noahmanger** [comment]
Resolved by #1966
