### ISSUE TITLE
Passing in citation in AO search URL fails

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1989]
I noticed that when trying to go to an AO search with a citation in the URL, the page fails:

https://fec-stage-proxy.app.cloud.gov/data/legal/search/advisory-opinions/?api_key=5yyI90SU3Xb73TVlv4wrEhQxYcCwMWCywQiGdYbJ&type=advisory_opinions&ao_regulatory_citation=17+CFR+%C2%A71.20

This has the effect of not being able to go back to these pages if you click into an AO from it.

**Comment by anthonygarvan** [comment]
I included this fix in keyboard shortcut PR.
