### ISSUE TITLE
Legal search results - Search button is misaligned and incorrectly sized

### ISSUE THREAD

**Issue by porta-antiporta** [18F/openFEC-web-app#1999]
https://beta.fec.gov/data/legal/search/?search_type=all&search=gore

<img width="1267" alt="screen shot 2017-04-28 at 1 33 06 pm" src="https://cloud.githubusercontent.com/assets/16668007/25542497/7a931262-2c18-11e7-9783-c7089c86cff9.png">

**Comment by noahmanger** [comment]
On it.
