### ISSUE TITLE
Re-order legal search results to match order of landing page resources

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC-web-app#2005]
We changed the items on the legal resources landing page to flow by popularity of access, but left the search results ordered by document authority. The guiding principle is that the models should be consistent in both places.

Since the order of access is the most recent thinking, that's the hypothesis we are going with for now.

**Completion criteria**

- [ ] Change order of legal search results to:
 - AOs
 - MURs
 - Regulations
 - Statutes

The logic that we initially set up around moving items with zero results to the bottom of the list should be retained. 
![screen shot 2017-05-02 at 1 36 42 pm](https://cloud.githubusercontent.com/assets/11636908/25630830/72a9784e-2f3c-11e7-948b-6b6c6eac8a8c.png)

created from legal grooming session today, cc @noahmanger

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/openFEC-web-app/pull/2027
