### ISSUE TITLE
Side nav on legal resources landing page does not highlight or scroll

### ISSUE THREAD

**Issue by nickykrause** [18F/openFEC-web-app#2006]
I was just on the [legal resources landing page](https://beta.fec.gov/legal-resources/) and noticed that the side nav doesn't follow me down the page when I scroll, as it does on other pages (e.g., [Help for candidates & committees](https://beta.fec.gov/help-candidates-and-committees/))

The topics within the navigation also aren't highlighting to denote which section I'm scrolled to
<img width="229" alt="screen shot 2017-05-02 at 2 29 36 pm" src="https://cloud.githubusercontent.com/assets/1450173/25635466/d50e18bc-2f43-11e7-8cbf-d9de55576415.png">

cc @noahmanger and maybe @anthonygarvan

**Comment by noahmanger** [comment]
Oh oops. Easy fix so I just rolled it into https://github.com/18F/fec-cms/pull/1032/commits/b6e86f16a69e3b56042fc795c324eda46fdc3a8d

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/fec-cms/pull/1032/
