### ISSUE TITLE
Complete UX improvements to AO canonical page

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC-web-app#2007]
These are the remaining tasks to reconcile the intended designs with what's on production for the AO canonical pages [except for the story about embedding FEC Record articles in the Summary text, which I can't find, but am nearly positive it exists....will continue hunting]

**Documents table:**
- [x] Add document icon to each doc in the `Name` column
- [x] Sort reverse chronologically

![screen shot 2017-05-02 at 5 44 23 pm](https://cloud.githubusercontent.com/assets/11636908/25640835/4148906e-2f5f-11e7-834c-02ad1f536aeb.png)

**Entities table:**
- [x] Display Entity `Type`column
(The logic already established for the order in which Entities are listed should not change)
![screen shot 2017-05-02 at 5 46 52 pm](https://cloud.githubusercontent.com/assets/11636908/25640906/88cee8d4-2f5f-11e7-9a4b-493a1df18b18.png)

🖌 🖥  **[Designs in InVision](https://gsa.invisionapp.com/share/QCA404INT#/229485601_AO_Canonical-Collapsed-Demo)**

cc @nickykrause and @anthonygarvan for a double-check

**Comment by noahmanger** [comment]
Question for @jenniferthibault : we're now sorting the documents reverse chronologically, but we decided we wouldn't allow re-sorting in the opposite direction or sorting by other headers. Should we still show the sorted state on the date header then? We can show it but not show a click cursor, but it might still seem like you can sort other things.

**Comment by noahmanger** [comment]
Also noting that adding the entity type column requires https://github.com/18F/openFEC/issues/2478

**Comment by jenniferthibault** [comment]
Sorry to have missed this the first-time, @noahmanger — can you add a little documentation about why we aren't allowing re-sorting in the opposite direction, or sorting by other headers? I'm not sure I understand those constraints.

**Comment by noahmanger** [comment]
It was a cost-benefit decision. Adding dynamic sorting by each column header requires a not-insignificant dev lift,  and the document list is unlikely to ever be long enough that sorting is really critical. It's useful to have it sorted in some logical order, which we decided makes sense to be date so that you can see the flow of documents, but not necessary to be able to change the parameter.

**Comment by jenniferthibault** [comment]
Got it, thank you!

I think then we'd want to remove the sort arrows altogether then, since they indicate functionality. If someone is looking for order, the date order _should_ be easy to recognize, especially in the first-position column.

**Comment by noahmanger** [comment]
My thought exactly. 👍
