### ISSUE TITLE
Smite the stray bracket in the metadata preview text

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC-web-app#2012]
![screen shot 2017-05-05 at 8 46 28 am](https://cloud.githubusercontent.com/assets/11636908/25746011/7a755824-316f-11e7-9672-f19fa0e2abad.png)
This appears on every preview instance of all beta site links.

![screen shot 2017-05-05 at 8 49 22 am](https://cloud.githubusercontent.com/assets/11636908/25746072/c5a2726e-316f-11e7-91a3-d84e7ab33387.png)

1. find it.
2. smite it. (with 🔥 , optional) 

@noahmanger , might pair well with the meta image work you're on?

**Comment by noahmanger** [comment]
Ah finally found it. Removed in the upcoming social images PR.

**Comment by noahmanger** [comment]
Resolved.
