### ISSUE TITLE
Add app-side caching

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#2020]
Not sure what else to say about this other than that we want to add more aggressive caching to the web-app.

**Comment by ccostino** [comment]
We have a meeting setup with @cmc333333 this afternoon to review caching in our apps and things we might need to be aware of.  At the moment, I have the following:

* General things to bear in mind with caching
* Anything specific we should bear in mind for cloud.gov apps
* Memcached is not available to us, correct?  So... Redis?  And if so, use our existing service or create a new one specific for caching?
* Preferred Django and Flask cache packages/plugins?

Documentation I've come across so far:
* [Caching in Flask](http://flask.pocoo.org/docs/0.12/patterns/caching/)
* [Werkzeug's Redis Cache Support](http://werkzeug.pocoo.org/docs/0.12/contrib/cache/#werkzeug.contrib.cache.RedisCache)
* [Caching in Django](https://docs.djangoproject.com/en/1.11/topics/cache/)
* [django-redis caching package](https://github.com/niwinz/django-redis)
*[Caching in Django with Redis](https://realpython.com/blog/python/caching-in-django-with-redis/)
*[SO: Caching SQLAlchemy calls with Flask and Redis](http://stackoverflow.com/questions/24589123/how-to-cache-sql-alchemy-calls-with-flask-cache-and-redis)

This is partially related to https://github.com/18F/openFEC/issues/2371; there might be something we can leverage in our findings here with the SQLAlchemy side of things in the API.

**Comment by ccostino** [comment]
We had a great conversation with you @cmc333333, thank you for your help!  These are the notes I've taken from the meeting:

* Put Caching in front of the API
* Leverage CloudFront and set it to cache for an hour (would have to account pages that display real time data)
* Add headers in nginx (proxy app) for specific endpoint
* api.data.gov - pop into Slack channel and double check if we just need to add headers and/or what is required for setup (unsure of cap, or if the functionality is available)
* If caching needed directly in the application level, go with Redis:
   * Setup a separate Redis service just for caching in cloud.gov
   * Flask has a RedisCache built-in via Werkzeug
   * Django does not have a built-in Redis cache as of 1.11.x - [django-redis](https://github.com/niwinz/django-redis) seems like a worthy addition (but verify with others; Jacob mentioned always using [django-redis-cache](https://github.com/sebleier/django-redis-cache))

Additional strategies:

* Create a custom logger specific to queries and include that logger in areas making queries; leverage that to parse logs for query performance
* Connection pool setup might be worth looking into as well

If there's anything I missed or recorded incorrectly, please let me know!

/cc @LindsayYoung, @jontours, @vrajmohan, @anthonygarvan

**Comment by LindsayYoung** [comment]
Added 10 minute API caching on stage and prod

**Comment by cmc333333** [comment]
@gui verified that api.data.gov caching for you if given the right headers. Instructions at https://api-umbrella.readthedocs.io/en/latest/admin/api-backends/caching.html

**Comment by noahmanger** [comment]
Anything more to add on this, or can we close?

**Comment by ccostino** [comment]
I think we have a few more adjustments we'd like to make at the app level to account for the following things:

* Downloads not being cached (they have their own caching as it is; once they're generated they live for up to a day and are then cleared out with the nightly refresh)
* Adjustments for the real time data (e.g., e-filings)

I believe that's it though; @LindsayYoung if I missed anything feel free to add/correct!

**Comment by noahmanger** [comment]
Are either of those pre-flip musts? Or should this go to the backlog?

**Comment by ccostino** [comment]
I don't think they're pre-flip, so should be okay to put back in the backlog.

**Comment by AmyKort** [comment]
@ccostino  Is this issue still relevant?

**Comment by ccostino** [comment]
I'm leaning toward no, at least not as this currently stands; @LindsayYoung do you agree or should we copy this over to `fec-cms`?
