### ISSUE TITLE
April quarterly for candidate ID C00634543

### ISSUE THREAD

**Issue by patphongs** [18F/openFEC-web-app#2032]
The April quarterly report for this candidate - Kathryn Allen MD for Congress (ID C00634543) indicates that it is 116 pages long, yet when I click to view the report, the PDF only contains 12 pages. I have tried from multiple computers and multiple internet sources and I can never get more than 12 pages. Is this a problem with the document or is the report still being process?

Webmanager's Inbox

**Comment by noahmanger** [comment]
I see a 116 page PDF for that here: http://docquery.fec.gov/pdf/985/201704149052245985/201704149052245985.pdf

Can someone double check that I'm not crazy?
