### ISSUE TITLE
Improvement Suggestions from User

### ISSUE THREAD

**Issue by patphongs** [18F/openFEC-web-app#2033]
**What were you trying to do and how can we improve it?**

- I was attempting find individuals' overall political contributions in the Individual Contributions part of the site. I find it very burdensome to have to refresh the page for each two-year period, and then exporting files for each period instead of all at once, as I was able to do before. Please change this for the official launch. I also recommend making the exported files .csv or .xls files instead of .zip files.

- I was also trying to find individuals' in the database, but it is more complicated this time around. I would highly recommend bringing back the last name and first name fields (or something similar) instead of having to enter in [last name, first name], [last name, nickname], and other complicated combinations to get everything that I need to pop up.

Webmanager's Inbox

**Comment by noahmanger** [comment]
This is a known issue that we're tracking elsewhere, so I'm going to close.
