### ISSUE TITLE
minify assets 

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC-web-app#2037]

**Comment by noahmanger** [comment]
All the code is in place for this to work correctly, but it seems that the `prod` environment is not being [picked up here](https://github.com/18F/openFEC-web-app/blob/develop/gulpfile.js#L25).

@xtine can you look into this?

**Comment by noahmanger** [comment]
Does this variable need to be set for Travis specifically?

**Comment by ccostino** [comment]
Oh good question - it is being set here in the [production manifest](https://github.com/18F/openFEC-web-app/blob/develop/manifest_prod.yml#L10), but it's not set anywhere in [`.travis.yml`](https://github.com/18F/openFEC-web-app/blob/develop/.travis.yml).  I imagine it has to be set either in the `env` section toward the top or exported explicitly in the `before_deploy` section (like the `PATH` environment variable is) in order for Travis to know to minify things before deploying.

**Comment by noahmanger** [comment]
Cool. Could you add this so we can take advantage with the next hotfix deploy?

**Comment by ccostino** [comment]
Added to your hotfix for the coverage dates, @noahmanger!

One thing though, this will affect all deploys through Travis, so the assets may also be minified in dev.

**Comment by AmyKort** [comment]
Issue moved to [18F/fec-cms #1558](https://github.com/18F/fec-cms/issues/1558) via [**ZenHub**](https://www.zenhub.com/)
