### ISSUE TITLE
load by state profile information only if user requests it

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC-web-app#2039]
It also looks like we load the individual contribution by state information on the initial page load before people have clicked on the tab. For better performance, we will want to load that client side and only if the user clicks on the tab. 

I was watching the network on this page load on a candidate and committee page

https://beta.fec.gov/data/candidate/H8CA05035/?tab=summary
https://beta.fec.gov/data/committee/C00213512/?cycle=2018&tab=summary

**Comment by noahmanger** [comment]
Ah! Good catch. This is a fix we can make.

**Comment by noahmanger** [comment]
Grabbed this fix in #2113
