### ISSUE TITLE
AO filter panel is missing the open/close icons

### ISSUE THREAD

**Issue by nickykrause** [18F/openFEC-web-app#2043]
(cc @jenniferthibault who can maybe provide the missing icons, if needed; cc @manger as FYI)

I was browsing the AOs today and saw that some icons we use in the filter panel seem to be missing.

On the data side, we have icons to open and close the filter panel:
![data-1](https://cloud.githubusercontent.com/assets/1450173/26122816/6acac72e-3a3e-11e7-8705-57296cd4c0b8.png)
![data-2](https://cloud.githubusercontent.com/assets/1450173/26122821/6e43d4e0-3a3e-11e7-8109-0c882de2a9d6.png)

but they are missing on the AO panel:
![ao-panel-1](https://cloud.githubusercontent.com/assets/1450173/26122832/7601b724-3a3e-11e7-9408-92d84c944767.png)
![ao-panel](https://cloud.githubusercontent.com/assets/1450173/26122840/79bf0010-3a3e-11e7-93db-8c4dbf77a0a0.png)

**Comment by jenniferthibault** [comment]
Good :eyes @nickykrause

**Comment by noahmanger** [comment]
Resolved by https://fec-prod-eregs.app.cloud.gov/regulations/api/
