### ISSUE TITLE
change name 'unique only' to 'unique individuals only'

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC-web-app#2044]
Change name 'unique only' to 'unique individuals only'

https://beta.fec.gov/data/receipts

<img width="250" alt="screen shot 2017-05-16 at 4 42 56 pm" src="https://cloud.githubusercontent.com/assets/4406333/26127268/c19de4c4-3a56-11e7-95f3-94f528a060cd.png">

Also since we have a view for individuals, we probably should not set it true by default. that is  how the link starts off here 

https://beta.fec.gov/data/advanced/

Here is the explanation from the API documentation if you want to reference https://api.open.fec.gov/developers/#!/receipts/get_schedules_schedule_a

**Comment by PaulClark2** [comment]
I agree. For the `All receipts` page `unique individuals only` should _not_ be selected by default.

**Comment by jwchumley** [comment]
Agreed.
