### ISSUE TITLE
Events deleted from FEC calendar still displaying on beta calendar

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC-web-app#2046]
<img width="1067" alt="screen shot 2017-05-17 at 9 45 34 am" src="https://cloud.githubusercontent.com/assets/11636908/26156886/b12de186-3ae5-11e7-9431-258edf8c47ec.png">

Reported by @FECHoosier
cc @AmyKort

**Comment by noahmanger** [comment]
The issue with the duplicate May 11 headings is because the open meeting has a time set and the others don't, so it's not being grouped together. Fixing this now.

As for the deleted data, I'm not sure. @jwchumley should deleted calendar events not be showing up on our data any more?

**Comment by noahmanger** [comment]
Pinging on this. @jwchumley did this meeting get deleted from the source tables for the new calendar?
