### ISSUE TITLE
Consider classification scheme and menu microcopy for Latest Updates filters

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC-web-app#2047]
![screen shot 2017-05-17 at 9 47 32 am](https://cloud.githubusercontent.com/assets/11636908/26156980/ea7707f6-3ae5-11e7-91bc-de8391c51c63.png)

As reported by @FECHoosier
cc @AmyKort

**Comment by AmyKort** [comment]
Under discussion over here https://github.com/18F/fec-cms/issues/1063#issuecomment-301957029

**Comment by noahmanger** [comment]
Closing this as with the transition to a new meeting page it's irrelevant.
