### ISSUE TITLE
Tasks for Site Flip Day

### ISSUE THREAD

**Issue by patphongs** [18F/openFEC-web-app#2049]
This issue is to catch all the activities and communications that need to happen on the day of the site flip. If you feel something needs to be added, please feel free:

- [x] Change name servers for www.fec.gov
- [x] Change IP for fec.gov to new web server
- [x] Change banners
- [ ] Change redirects from beta.fec.gov to www.fec.gov and redeploy proxy
- [x] Change environmental variable for hostname
- [x] Update the search indexes https://github.com/18F/fec-cms/issues/1025
- [x] Change any references to beta.fec.gov in the manifests
- [x] Set `CANONICAL_BASE` env var to `https://www.fec.gov`

**Comment by LindsayYoung** [comment]
# Site flip rundown

The classic.fec.gov domain is already running

## Friday, May 19 
- Testing forwarding app. This will send traffic from fec.gov with a permanent redirect to www.fec.gov  
- Public Release cut and on staging 

## Monday, May 22
- Forwarding app running in production
- Code freeze 
- CenturyLink will shorten TTL from hour to 15 minutes

##Tuesday, May 23
- Push release to production, starting 12:00 pm Eastern (trying to guarantee finishing by 6)
- DNS propagation 7:30 pm Eastern for www.fec.gov

@noahmanger Can we reschedule sprint planning and maybe the demo to for post flip and replace it with a site flip rundown meeting?

**Comment by noahmanger** [comment]
@LindsayYoung yeah I think we should move the meetings.
