### ISSUE TITLE
update 11 CFR publication date

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#2052]
https://beta.fec.gov/legal-resources/#regulations

We need to update `This archive contains a full-text version of 11 CFR, as published January 1, 2016.` to `This archive contains a full-text version of 11 CFR, as published January 1, 2017.`

My understanding is we can't make this change in Wagtail.

@AmyKort 
@llienfec

**Comment by noahmanger** [comment]
Ah right. This is simple, so I just rolled it into an open PR I have.

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/fec-cms/pull/1065/
