### ISSUE TITLE
Image number search for statements and reports and specific pages with a document

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#2054]
Request from FEC staff member: `My suggestion was adding the image number search to the main search on the “Campaign finance data” page.  We don’t need to actually put in wording that states you can search using the image number, but could we enable that functionality since it is so vital to internal staff?`

This image number search would be different from the image number search on the transaction pages. This search would allow users to enter an image number and return a document. The Viewer allows users to search for any image number. The docquery call look like this: http://docquery.fec.gov/cgi-bin/fecimg/?IMAGE_NUMBER

![image](https://cloud.githubusercontent.com/assets/11817734/26246289/40012568-3c66-11e7-8051-54b21b9ca7f5.png)

**Comment by noahmanger** [comment]
I was just playing around with this and it's easy enough to do a regex check for an 11 or 16 digit number and then redirect to the page-by-page PDF view. It's just a question of UX.

If we're going to add it, we should expose it for everyone. I could see a couple ways.

We could call it out as a separate field, similar to the AO number:
![image](https://user-images.githubusercontent.com/1696495/27307851-b670877c-5500-11e7-9fcb-25385ebc2e95.png)

Or add it as secondary help text:
![image](https://user-images.githubusercontent.com/1696495/27307860-c44f9540-5500-11e7-9ce7-09ae0c80cad4.png)

**Comment by PaulClark2** [comment]
I like option #2 with the secondary text better. @jwchumley @AmyKort do either of you have a preference?

**Comment by AmyKort** [comment]
I also like option 2.

**Comment by jwchumley** [comment]
Option #2 for me as well.


________________________________

**Comment by noahmanger** [comment]
Not urgent, but I'd like to know what @jenniferthibault or @nickykrause think.

**Comment by nickykrause** [comment]
@noahmanger I also prefer option 2 (the helptext). Could it be simpler, like this?: 

`Examples: Obama for America; C00431445; Bush, George W.; P00003335; or enter an image number for a filing`

Just wondering if it needs to be on a second line and contain all the detail it contains, or if an abbreviated version would suffice.

**Comment by noahmanger** [comment]
Works for me. Yeah, the second line felt a little clunky.

**Comment by jenniferthibault** [comment]
I don't have anything substantive to add, just +1'ing @nickykrause 's suggestion :)
