### ISSUE TITLE
Add image number to main filings page table

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#2055]
Request from FEC staff: `any chance we can add the image number in a new column on the filings page for a committee`

Being about to see the image number on this page https://beta.fec.gov/data/filings/?data_type=processed would be helpful to staff.

**Comment by noahmanger** [comment]
Just going through the backlog. This isn't a hard thing to add:
![image](https://user-images.githubusercontent.com/1696495/27307605-533959e6-54ff-11e7-8072-b41afc177614.png)

But I wonder if this information makes more sense in the panel? Is it useful to see the image number for a lot of filings all at once?

**Comment by PaulClark2** [comment]
Having the image number available without needing to open the panel makes it easier for many staff to do their jobs more quickly. 

I think there is another issue requesting coverage dates (or at least coverage end date). This is also about helping staff access information more quickly.

**Comment by noahmanger** [comment]
That makes sense to me. I separately have a PR adding those coverage dates to filing tables on committee pages: https://github.com/18F/openFEC-web-app/pull/2139
