### ISSUE TITLE
Preliminary design work around election summary page

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#2070]
This is a discovery / early design task for the upcoming election summary / compliancy / mappy / page. We know there's a set of interrelated needs in this general vicinity, so we need to refine our understanding of what those needs are and start to get some ideas out.

cc @nickykrause @jameshupp

**Comment by nickykrause** [comment]
@noahmanger - Is there any old research on this, or are we starting fresh? I think I asked you this before but can't remember what you said. Just wondering if this is like the C&C profile updates, where we had logged away a bunch of feedback that we were able to aggregate to inform those designs. I assume that the current `Elections` section came out of a data-driven hypothesis that organizing the data by elections was useful, so I am wondering if I could look at that data.

Also, personally, I am not fully clear on how our `election` summaries relate to what is known as the `compliance map` on the old site, and if those things are truly related in some way (synonymous? near-synonymous?), or if they were actually intended to meet very different needs. So, at least for me, I'll be 🤔 about that briefly before jumping in.

BUT, aside from that initial exercise in getting up to speed and checking out any old data, it seems like we could do some or all of the following things:

- Short interviews with some of the FEC staff about the original goals of the map, its perceived utility (what user needs do they see it meeting?), and their recollection of the kinds of comments/concerns that users have expressed to them about it. 
    - Some of the project team members, perhaps some folks in InfoDiv? I recall hearing commentary that this area of the data was of particular interest to some of the commissioners as well, which I am interested to understand more about.
  
- Usability testing of the current map to get a sense of what is or isn't working with it
    - We could do this with any users, in order to get at least _some_ insight, but it'd be best with the "target" users, whoever we think those people are.
 
- Short user interviews about what interests them about election-related information and how they use that information.
    - The goal of this would be to get a sense of what the user need actually is with this data, and to acknowledge that a map may or may not be the best solution.
    - E.g., The limited exposure I have had to this area in usability testing has shown that some journalists want to be able to follow (and get updates about) the data related to a given election that they are tracking -- they want to see the progress of that race "at a glance". (There is so much to dig into on that, so it'd be nice to have a semi-structured conversation about it)

I'm just throwing this out there to get the ball rolling, so I'm happy to hear other thoughts on this. Whatever we end up doing in this research phase, I'd like to empower the FEC team to drive it

**Comment by noahmanger** [comment]
This all sounds right on. I'm also happy to do a brain dump over video if you want.

IIRC, we don't have research *specifically* on this issue, but I'm sure there's findings in the overall data research that would be relevant.

**Comment by nickykrause** [comment]
I was looking back through some of the research this morning, and I came across this affinity mapping exercise that I thought I'd drop here, since it is relevant to the work on elections:

![image](https://cloud.githubusercontent.com/assets/1450173/26591058/13209348-4522-11e7-85e5-7f619e3a8cc8.png)

I didn't find much else that was specific to `elections`(yet), but I will add more if I do.

**Comment by nickykrause** [comment]
@patphongs: 

We'd like to involve some FEC team members in some initial research activities to inform the design of the revised `Elections` section. I'm wondering who you think should be involved in working on some of the following activities:

- Designing and conducting short interviews with some of the FEC staff about the original goals of the old compliance map, its perceived utility (what user needs do they see it meeting?), and their recollection of the kinds of comments/concerns that users have expressed to them about it.

- Designing and conducting some usability tests (with people who don't work for the FEC) of the old compliance map to get a sense of what is or isn't working with it

- Designing and conducting some short user interviews (with people who don't work for the FEC) about what interests people about election-related campaign finance information, and how they use that information

Of course, I will be available to work alongside and to help whoever from the FEC is involved, but we'd like to take this opportunity to have some FEC folks in the driver's seat on some research! 🎉

**Comment by nickykrause** [comment]
Update here: Sounds like @llienfec will be helping out! 🎉

**Comment by llienfec** [comment]
Very excited and will be working on getting up to speed on this.

**Comment by nickykrause** [comment]
I have broken this issue out into smaller issues that Lauren can drive:

Research plan development/participant recruiting:
https://github.com/18F/openFEC-web-app/issues/2099

User interviews:
https://github.com/18F/openFEC-web-app/issues/2100

Stakeholder interviews:
https://github.com/18F/openFEC-web-app/issues/2101
