### ISSUE TITLE
Search box type ahead weirdness

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC-web-app#2076]
If you are searching for candidates and put in Paul Ryan, the type ahead will only offer you the Romney/Ryan option. His current Senate committee isn't even there. "Ryan, Paul" does the same thing.  If you do partial names it works but still puts the older presidential committee first.  Other folks who have run for President and are also in Congress also aren’t showing their most recent committees in the drop down (McCain, Kaine, etc.)

"Ryan" or "Paul" show other options even "ryan Pa" but "Ryan Pau" only shows the romney'paul option.

**Comment by noahmanger** [comment]
Consolidating this with similar reports in https://github.com/18F/fec-style/issues/714
