### ISSUE TITLE
Easier path to Commission meeting pages

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#2079]
We need to make it easier for folks to find Commission meeting pages. Neither path seems obvious or intuitive. 

Path 1: Press-->Resources for journalists-->Lean more-->Commission meetings-->Archive of open meeting agendas

Path 2: All latest updates-->Publication type-->Commission meetings

@rhoughfec

**Comment by nickykrause** [comment]
@PaulClark2 what was the old path? 😬 I am having trouble finding them

**Comment by nickykrause** [comment]
whoop scratch that -- found it on the side nav

**Comment by PaulClark2** [comment]
left nav: Meetings and hearings-->Commission meetings

**Comment by noahmanger** [comment]
We've implemented a solution for this with the new home page and menu.
