### ISSUE TITLE
Add Ethnio to new site

### ISSUE THREAD

**Issue by nickykrause** [18F/openFEC-web-app#2080]
Now that we've finished the site flip, we can add Ethnio to the new fec.gov and remove it from classic.fec.gov (if it is still appearing there).

@patphongs I have sent you the code snippet via Slack, but here are the instructions from Ethnio:

> Insert the code as close to the closing body tag as possible - it works as SSL or regular HTTP. This ensures that ethnio never interferes with any of the content loading on your site.

**Comment by noahmanger** [comment]
@LindsayYoung are we allowed to add Ethnio back now?

**Comment by nickykrause** [comment]
ooo good point. Thanks for tagging in Lindsay, @noahmanger !

**Comment by patphongs** [comment]
Just to fill in this issue, this has been approved by use from the FEC
