### ISSUE TITLE
Change default election year to most recent only

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#2084]
This seems to be causing some confusion. Let's change this to default to the most recent election year. I don't think that surprises folks. 

![image](https://cloud.githubusercontent.com/assets/11817734/26495294/15b48d96-41f1-11e7-9c08-ed0ef317d656.png)

: https://www.fec.gov/data/candidates/?election_year=2014&election_year=2016&election_year=2018&has_raised_funds=true

**Comment by jwchumley** [comment]
I think we should throw it over to Nicky. My thought is to remove the default year entirely since this is the advanced search. Without the defaults the current behavior would be that it would find everybody and when you click on one you automatically get the most recent activity year for that committee.

**Comment by rhoughfec** [comment]
I think this will be a common issue for enforcement attorneys and commission offices since a lot of their cases are 4-6 years behind the current election cycle. I agree Jeff, I think if we can remove the default entirely that would be great. Thanks guys!

**Comment by nickykrause** [comment]
Sure! I probably won't be able to 🤔 on it until later today, after usability testing/retro, but I am happy to look at it.

**Comment by noahmanger** [comment]
Easy enough fix. Removing the default probably does make sense in this case.

**Comment by rhoughfec** [comment]
Thanks @noahmanger !

**Comment by nickykrause** [comment]
@noahmanger - I just looked at it, and I agree. I wondered if there was a reason that we decided to have a default? Did it have anything to do with trying to add _some_ limit to the number of results right up front? If so, is that something we actually need to be concerned about, or are we cool with removing the default and letting all the results appear (paginated, of course)

**Comment by noahmanger** [comment]
IIRC (and this was _very_ long ago) it was an attempt to just limit the universe to a more relevant set of results be default, but that feels less important now.

**Comment by noahmanger** [comment]
I assume we want to do the same for `/committees`?

**Comment by noahmanger** [comment]
Will be fixed in https://github.com/18F/openFEC-web-app/pull/2083

**Comment by nickykrause** [comment]
Makes sense to me
