### ISSUE TITLE
Create an easier path for users to view AOs by year number

### ISSUE THREAD

**Issue by AmyKort** [18F/openFEC-web-app#2085]
On the old AO search page there is an option to bypass the search function and view AOs by series, so that a user could view a list of all AOs labeled 2015 (even if some of them crossed over the end of the year and were issued during 2016). Can we retain some aspect of this one-click browse functionality?

cc @rhoughfec

**Comment by rhoughfec** [comment]
Do we want to close this? I think this was a learning curve users experienced right after the site flip. I haven't heard this as a big problem recently.
