### ISSUE TITLE
Allow users to more easily navigate through documents in an AO file

### ISSUE THREAD

**Issue by AmyKort** [18F/openFEC-web-app#2086]
The new system does not have the split screen display that the old system has.  So once you’ve clicked on a  document, if you need to look at other documents from the same AO, you have to go back a page. Users would like to be able to navigate through the AO file without having to go back to a previous page.

**Comment by noahmanger** [comment]
Closing in favor of https://github.com/18F/openFEC-web-app/issues/2123
