### ISSUE TITLE
remove download button on candidate by state and by size

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC-web-app#2089]
These were not downloadable before and I think the buttons got added when we rearranged things.

For example this shouldn't have a export link:

https://beta.fec.gov/data/candidate/P80003338/?cycle=2012&election_full=True&tab=individual-contributions
<img width="904" alt="screen shot 2017-05-30 at 4 00 00 pm" src="https://cloud.githubusercontent.com/assets/4406333/26608583/36f096a4-4551-11e7-9232-58a104873b19.png">

This isn't a hard backend fix but it is more than we want to do in a hotfix because we need to re-write some views. 

When people try to download these it looks like takes forever but really there is an error, which is another good reason to get an error message going on downloads:  https://github.com/18F/openFEC-web-app/issues/2038

**Comment by noahmanger** [comment]
Resolved by #2096
