### ISSUE TITLE
Committee profiles: Coverage date tag displays end as "none" on Financial summary

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC-web-app#2103]
<img width="1254" alt="screen shot 2017-06-02 at 2 53 09 pm" src="https://cloud.githubusercontent.com/assets/11636908/26740388/52719ce4-47a3-11e7-926f-a82e9a164cd6.png">

**Comment by noahmanger** [comment]
@jontours is currently working on fixing the weird coverage dates.

**Comment by jenniferthibault** [comment]
This should be resolved by https://github.com/18F/openFEC/pull/2454 soon

**Comment by noahmanger** [comment]
Resolved on staging and will be deployed with our next release:
![image](https://user-images.githubusercontent.com/1696495/26992768-f7764e12-4d14-11e7-9b83-0daf0ca904b6.png)
