### ISSUE TITLE
AO pages not showing any/all regulatory and statutory citations from final opinion

### ISSUE THREAD

**Issue by AmyKort** [18F/openFEC-web-app#2105]
https://www.fec.gov/data/legal/advisory-opinions/2016-26/
https://www.fec.gov/data/legal/advisory-opinions/2001-13/
https://www.fec.gov/data/legal/advisory-opinions/2002-01/
https://www.fec.gov/data/legal/advisory-opinions/2000-06/

We seem to be missing a lot of statutory and regulatory citations in the Legal Citations box. Is this unexpected?

**Comment by noahmanger** [comment]
@AmyKort are there any pages that are showing citations? Or does this seem like an intermittent issue? cc @vrajmohan and @anthonygarvan

**Comment by vrajmohan** [comment]
I will investigate. If you remember there were no citations for AOs published since 2014 as the OCRs were empty. This was fixed last week. Perhaps there are some stragglers.

**Comment by AmyKort** [comment]
It seems like an intermittent issue. I noted that a lot of canonical pages show regulations and no statutes, which would be highly unusual in an AO. Just browsing around, it looks like we pick up more regulatory citations than statutory citations, but we're also not picking up all of the regulatory citations. I didn't notice that 2014 to present AOs were worse off, but I can look again with that in mind.

**Comment by vrajmohan** [comment]
In all the 4 cases that you have listed, the poor quality of the OCR is the reason for the failure to identify statutory citations. " 26 U.S.C. §9008" is being OCR'd as "26 U.S.C. Â§9008". The extra character before the section symbol "§" is throwing off the parser. We could make the parser more sophisticated but that may yield some false positives.

**Comment by AmyKort** [comment]
Thank you for tracking that down!

**Comment by noahmanger** [comment]
Is there any further action needed on this?

**Comment by AmyKort** [comment]
resolved by https://github.com/18F/fec-cms/issues/1425
