### ISSUE TITLE
Candidate loans -wrong on committee profile summary page

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC-web-app#2109]
It looks like instead of displaying the Loans made by the candidate, it is displaying the Total loan repayments.

https://www.fec.gov/data/committee/C00610113/?cycle=2016

Candidate loans in this case should be the same as total loans: $8,192,850.00

Displaying:$34,334.00  which is also displaying correctly as the candidate loan repayments and the total loan repayments.

**Comment by jwchumley** [comment]
This is also wrong on the candidate profile page:
https://www.fec.gov/data/candidate/S6FL00426/?cycle=2016&election_full=false

**Comment by noahmanger** [comment]
@jontours can you roll this into your totals fixes?

Verified that this value is coming from the API:
`"loans_made_by_candidate": 34334`

**Comment by jontours** [comment]
Yup!

**Comment by noahmanger** [comment]
Did this get included in your PR @jontours ?

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/openFEC/pull/2470
