### ISSUE TITLE
Adding some fuzzy logic to the individual search

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC-web-app#2111]
This comes from @amypike and originates from people trying to vet presidential appointees by checking their contribution histories. In the old individual search it actually looks like it is doing a "contains" search. Joe Smith finds Joel Coopersmith.

Seems seeing all the extra possible returns makes them feel better about the thoroughness of the search. I'm not sure how I feel about it but we should probably put it in front of some users and see what they think

**Comment by noahmanger** [comment]
Interesting idea and I can definitely see the utility; though could also see it leading to a frustrating amount of false positives. So yes, testing would be good.

Curious from the technical standpoint how tricky this is to enable for a test.

**Comment by jwchumley** [comment]
Judging from the behavior on the old site It is simply taking the first name and last name (separate fields) and finding results with either of them anywhere in the resulting name. Of course we can reach out and get the code from Salient if you need it.


I agree about the possible frustration and was thinking maybe it could be a choice between the current approach and a fuzzier approach with a "feeling lucky" type check box.  Just a thought.


________________________________

**Comment by AmyKort** [comment]
Issue moved to [18F/fec-cms #1568](https://github.com/18F/fec-cms/issues/1568) via [**ZenHub**](https://www.zenhub.com/)
