### ISSUE TITLE
Selecting to only see primary or general campaign donations

### ISSUE THREAD

**Issue by shanac** [18F/openFEC-web-app#2120]
Hi Everyone!

I've been recently poking around the FEC site a lot.  I'm super-impressed how much it has improved from the previous version.

That said, I would like two changes in the search functionality.  I'm opening an issue for each one to make it easier for you to prioritize if and how you want to implement said changes.

So the first change:

I see in the advanced data that people give for either a primary or general election.  I can't manage to figure out how to only see donations for only a primary.  Is there a way to add a selection tool of some sort so I can filter by primary vs general election.

Thanks!

Shana

**Comment by noahmanger** [comment]
Thanks for writing in, Shana! This makes a lot of sense. There's not currently a filter for primary/general elections, but I know that would be useful. I'll add this to our backlog.

**Comment by shanac** [comment]
Thank you! I thought it would be an obvious(er) tweak and I was surprised it wasn't there.  Thought you might want the feedback

**Comment by AmyKort** [comment]
Issue moved to [18F/fec-cms #1590](https://github.com/18F/fec-cms/issues/1590) via [**ZenHub**](https://www.zenhub.com/)
