### ISSUE TITLE
Default cycle for committee profile - suggested change

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC-web-app#2126]
I've had three or four people that couldn't find reports in the last week because they were looking for a recent form 1 or a form 99 for a committee that has not campaign finance reports after 2016. The profile uses the latest campaign finance report to establish the default coverage period. I think it should use the latest filing instead. 

This is not the way we have always done it but I think it makes sense now to switch to letting the data set the default.

**Comment by noahmanger** [comment]
This makes sense to me. I want to play around with it and make sure there's no unintended consequences, but should be an easy fix.

**Comment by noahmanger** [comment]
Duplicate issue from #2205
