### ISSUE TITLE
Complete consistent table header styling for AOs

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC-web-app#2141]
Since we're inching closer to having the tags for AOs in place, these styling tweaks should help make the patterns line up closer to 1:1.

**Pattern from data tables and attributes present**
- Title is h1 class
- Underline under title is grey and meets the edge of the filter panel and edge of the screen
- Page title is the data set, without verbiage ("Receipts" instead of "Searching receipts")
- Table headers have a 2px border top that meets the edge of the filter panel and edge of the screen
- Vertical lines between columns extend into header area
- Line height of column headers is tighter (check that we're using the same classes)
- The first row has a white background instead of grey

<img width="1277" alt="screen shot 2017-06-19 at 4 10 10 pm" src="https://user-images.githubusercontent.com/11636908/27303788-e83d35e4-5509-11e7-9d48-97108c998f22.png">

**Current status of AO tables**
- (missing the attributes listed above)
<img width="1277" alt="screen shot 2017-06-19 at 4 21 26 pm" src="https://user-images.githubusercontent.com/11636908/27304233-6763eaa6-550b-11e7-96b4-0a05b73937e1.png">

**Comment by noahmanger** [comment]
Resolved by #2144
