### ISSUE TITLE
Bug: Line number filters don't show tag when loading from URL

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#2155]
I noticed that if you go to a URL with the line number filter applied ([example](https://fec-stage-proxy.app.cloud.gov/data/receipts/?two_year_transaction_period=2016&data_type=processed&min_date=01%2F01%2F2015&max_date=12%2F31%2F2016&line_number=F3P-17D)) the filter is applied but there's not a tag generated. 

Can you look into this @xtine ?

**Comment by xtine** [comment]
Ah, I think somehow, the function to do a line number check upon load was accidentally removed https://github.com/18F/openFEC-web-app/blob/release/public-20170629/static/js/modules/filters-event.js#L12

**Comment by noahmanger** [comment]
This was fixed a while ago.
