### ISSUE TITLE
Test design of version two of homepage

### ISSUE THREAD

**Issue by AmyKort** [18F/openFEC-web-app#2160]
Need to test design of version 2 of homepage

**Comment by jenniferthibault** [comment]
Design from #2159 ready for first round of testing. Interview script in progress here: https://github.com/18F/fec-testing/blob/master/Testing-Scripts/Test-Script_2017-07-13.md

**Comment by patphongs** [comment]
Testing for the homepage has been completed in this script: https://github.com/18F/fec-testing/blob/master/Testing-Scripts/Test-Script_2017-08-03.md

There may be follow-up testing for homepage. @jenniferthibault What do you think? If not, we can probably mark this as done?

**Comment by jenniferthibault** [comment]
Since we have another interview next week, and will synthesize and file issues in the testing repo after, I wouldn't call it done until then.

**Comment by AmyKort** [comment]
Are we ready to close this one?
