### ISSUE TITLE
Design/dev pairing for AO boolean search

### ISSUE THREAD

**Issue by AmyKort** [18F/openFEC-web-app#2162]
Yep. Need to set that up.

Related to https://github.com/18F/openFEC-web-app/issues/2069

**Comment by nickykrause** [comment]
Meeting scheduled for Monday

**Comment by nickykrause** [comment]
Met with @anthonygarvan today and shared the [designs](https://gsa.invisionapp.com/share/9XC6RNVW5#/239213570_Legal-Home-Modal-Default) with him. He didn't express any immediate concerns with the approach we have outlined for boolean keyword search. 

I have created an implementation issue for this here: https://github.com/18F/openFEC-web-app/issues/2170. 

I am closing this issue; we can use the implementation issue for further discussion
