### ISSUE TITLE
Elections work-stream: Early design brainstorming & sketching

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#2164]
Clarification on this issue for @patphongs:

When we do decide to tackle the actual design process for the election map and the compliance map, the purpose of this issue is to remind us to generate a variety of ideas at the beginning, rather than getting stuck on one concept and developing it in so much detail that we can't pivot to something else. 

Basically, this issue will remind us to set aside time for rapid idea generation or "brainstorming." 

The design firm [IDEO has distilled their brainstorming advice](https://www.ideou.com/pages/brainstorming) into a series of seven principles: 1) Defer judgement, 2) Encourage wild ideas, 3) Build on the ideas of others, 4) Stay focused on the topic, 5) One conversation at a time, 6) Be visual, and 7) Go for quantity. 

Jumping straight into a design program like Sketch can make it difficult to "encourage wild ideas" or "go for quantity," because the digital format is not quite as quick or as flexible as just sketching with markers on paper. Paper-sketched ideas don't need to feel "perfect," and they are easy to discard as we think of new things, since they aren't labors of love that have taken hours to produce (like a complex, digital wireframe might be). 

A concrete way to get people sketching on paper -- and rapidly! -- is to conduct a design studio. When the time comes to brainstorm some ideas to meet the user needs outlined in our user stories, we could schedule a design studio to get ideas flowing and to get more people involved in the process. 

[Here](https://methods.18f.gov/#design-studio) is some information about how to conduct a design studio, from 18F's methods cards. Note that this link also contains a link over to [an example of a real design studio conducted by 18F](https://18f.gsa.gov/2014/09/25/design-studio-onrr/). 

If you choose not to do a design studio, that's also fine. One or two designers could still start some sketching on paper and share those early sketches with the team, perhaps in the Friday design sync meeting, before moving on to digital wires. That process would have different strengths/weaknesses compared to a design studio, and the choice is up to you!

Also, note: It is not _always_ necessary to sketch on paper. But, it can be very helpful!

We can talk more about this, and the possible timing of it, in our sync today.

**Comment by nickykrause** [comment]
Quick update here: We held a design studio today to sketch some initial concepts based on the research. We have scheduled a second design studio for tomorrow and will reconnect on Monday to incorporate these sketches into the research readouts and to communicate the idea of our "quick wins" more clearly

cc @patphongs @noahmanger @llienfec

**Comment by nickykrause** [comment]
Having completed the design studios, we are suggesting some quick wins and mid-to-long-term wins for the elections workstream: https://github.com/18F/openFEC-web-app/issues/2167

**Comment by nickykrause** [comment]
Closing this because the early brainstorming and sketching was completed in the design studio.
