### ISSUE TITLE
Elections work-stream: Identify quick wins and mid-to-long-term wins

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#2167]
From Nicky, clarification on this for @patphongs:

Although we have pushed the full design work for the elections stuff out into the future, we'd like to take a look at the user needs coming out of the research and decide if there are any "quick wins" (or small changes) that we could make to our existing designs that might meet some basic needs between now and whenever we do a larger design effort. 

This issue can capture our ideas about what those quick wins might be and which ones we want to take on.

This might include back-end or API work. We'll need to make separate issues for that work once our "quick wins" are identified.

**Comment by nickykrause** [comment]
Per the demo meeting today, and per the outcome of our [design studios](https://github.com/18F/openFEC-web-app/issues/2164), we have identified some "quick wins" and more "long term wins" for the elections work, including the following, with _rough_ sketches, to clarify what we mean.

## Quick wins
### 1. Surface elections and individual contributor searches on data landing page.
<img width="518" alt="screen shot 2017-07-17 at 1 28 39 pm" src="https://user-images.githubusercontent.com/1450173/28283623-dfc118a4-6af3-11e7-813c-cec07e1fbba7.png">

### 2. Emphasize link to election pages from candidate pages.
<img width="716" alt="screen shot 2017-07-17 at 1 28 56 pm" src="https://user-images.githubusercontent.com/1450173/28283639-ecdddae0-6af3-11e7-9881-4f7638b985ce.png">

### 3. Redesign election pages to use new layout templates.
<img width="598" alt="screen shot 2017-07-17 at 1 29 17 pm" src="https://user-images.githubusercontent.com/1450173/28283654-f71f9ffc-6af3-11e7-9a33-43626032a4e9.png">

---

## Mid-to-long-term wins

### 1. Start developing API endpoints for top-level totals: 
- Contest totals:
    - Receipts
    - Disbursements
    - Cash
    - Debt
    - IEs
    - Party expenditures
    - Total by all, republicans, democrats and other

- Summary totals:
    - Total contributions by state
    - Total receipts by size
    - Total IEs per state and district

### 2. Develop previously designed overview visualizations
<img width="778" alt="screen shot 2017-07-17 at 1 31 53 pm" src="https://user-images.githubusercontent.com/1450173/28283748-5b2c6598-6af4-11e7-8f4f-92d48877bc3b.png">

### 3. Consider what additional data visualizations we can build to meet our user needs (see the research in the [slide deck](https://docs.google.com/presentation/d/1otz-6RhaGJF1azldHGoyXnVcTVTveNSEeUjqiqRS68k/edit#slide=id.g248efa252a_0_78) and the [mural](https://app.mural.ly/t/gsa6/m/gsa6/1498162687846/96f9de4d4959e2b08f1553b6c8f3f10e1cdc10a4)), using some of the end-points developed for top-level totals (in point 1). 

### 4. Consider how to improve the "window-shopping" experience and improve the findability / discoverability of the old and new visualizations

**Comment by nickykrause** [comment]
@noahmanger @PaulClark2 @jwchumley @patphongs :

With today's demo and the above update about our short-term and longer-term work plans, it seems like we'll need to break down this work into issues for sprint planning. 

Would you like me to try to chunk out this work, or is this one of those moments where it's a useful exercise for Paul/Jeff/Pat someone at the FEC to practice writing out design issues and completion criteria (i.e., practice structuring design work for agile sprints GitHub)?

Happy to do whatever -- just thought I'd ask :smile:

**Comment by nickykrause** [comment]
Per Slack, it sounds like @patphongs would like to pair a bit on this. More to come.

**Comment by patphongs** [comment]
@nickykrause We can take this on. But it would be useful if we could do a sample design issue just to get us going? Something that we could template or learn from. If you've had something that has been helpful for you when creating those design issues, we would greatly appreciate some insights.

**Comment by noahmanger** [comment]
We've made issues for all of the next steps, so I'm closing this.
