### ISSUE TITLE
Move all ftp.fec.gov file to S3

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#2171]
Move zipped Disbursements to S3.

**Completion criteria:**
- [x] All zipped files automatically uploaded to S3
- [ ] Set-up any necessary redirects

Follow up tasks (future sprints):
- Set up redirects
- Update the front-end
- Notify users once change is in effect

**Comment by PaulClark2** [comment]
Need to get Joseph set up to sync files to S3. These files will go into the legal and data bucket

**Comment by patphongs** [comment]
Joseph has done a successful sync of test file in dev database to dev bucket in cloud.gov. Next step is to update the API code to prevent deletion of files in `bulk-downloads` directory before attempting to sync all files

**Comment by patphongs** [comment]
Additional functionality to list contents of bucket in web browser needs to be done. Issue has been made here #2211

**Comment by patphongs** [comment]
Dependency: Need the release to go out before we can start syncing bulk downloads to the downloads bucket on stage and production

**Comment by patphongs** [comment]
Release has gone out. Joseph has everything he needs to sync content over to the production bucket. Syncing can now happen in 3.5.

Electronic filing team also needs to sync content over to the bulk-downloads directory on S3.

**Comment by patphongs** [comment]
Waiting for efiling group to confirm that they can upload successfully to dev. Then they will try to upload to prod. Once that is confirmed, this will be done.

**Comment by patphongs** [comment]
*Update:* Within the next 24 hours, the efiling team will finish their tests and automated scripts to ensure that they can upload to dev and production successfully. Once we receive confirmation, this ticket will be closed.

**Comment by PaulClark2** [comment]
We'll need to ask Joseph to push any files from in the gap between his one-time upload and the day EFO turns on their daily update.

**Comment by patphongs** [comment]
Files have been moved successfully. Closing this ticket and moving redirect portion here: https://github.com/18F/fec-proxy/issues/56
