### ISSUE TITLE
Ethnio replacement

### ISSUE THREAD

**Issue by nickykrause** [18F/openFEC-web-app#2173]
@patphongs - I'm adding this issue to figure out how else we can recruit users for usability testing, given that we can't use Ethnio. 

A few ideas:
- Reach out to people who are already in Ethnio
    - I am happy to do this, but we have already reached out to those people several times over. I am concerned about the perception that we are "spamming" them (which may or may not be an issue because many have said they are happy to keep participating), as well as the effect on our findings of talking to the same people multiple times. It would be nice to diversify our data more, with new people.
- FEC mailing lists
    - Does the FEC have mailing lists that we could use to recruit? I am not sure what these mailing lists would be for, or who would know about them. I imagine that if they do exist, they might be specific to certain user groups (journalists, committee staff, etc.), which could be helpful. Do you know?
- 18F's recruiter MVP
    - Ever since 18F could no longer use Ethnio, we have been working on a replacement tool using Google Sheets. More information about that is visible in the recruiter MVP's repo: https://github.com/GSA/recruiter. I am not sure yet how close this is to completion because the people working on it said they are still going through approval processes. It might be a while before this could be a realistic option, but I wanted to show it to you anyway.

In the short-term, I think I'd like to try reaching out to some mailing lists, if they exist, but I'd love to hear your thoughts as well, @patphongs 🤔

**Comment by patphongs** [comment]
Thanks @nickykrause for listing all of these options. The best thing is if we could use 18F's recruiter MVP code on our website. But I do see it's still pending GSA IT security review. That kind of puts us in the same boat with Ethnio right now. But if that pans out soon, it would be a great option. 

As for reaching out to FEC mailing lists, as @llienfec mentioned, we would have to look into our policies regarding reaching out to an entire list. 

Utilizing current Ethnio users is a nice temporary option, but we agree with you that the list will exhaust itself soon.

**Comment by nickykrause** [comment]
@patphongs I think that your conversation with Lauren was promising, and I hope Recruiter MVP works out! 

I am un-assigning myself and assigning you to follow this through

**Comment by patphongs** [comment]
Recruiter app may have already been cleared by GSA IT Security. Waiting for final confirmation before moving on to implementation phase.

**Comment by patphongs** [comment]
I would like to visit possible implementation and design for this tool. Linking to the design issue here: https://github.com/18F/fec-cms/issues/1190

**Comment by laurenancona** [comment]
Recruiter has been approved by GSA IT, FYI.

**Comment by patphongs** [comment]
Closing in favor of implementation issue: https://github.com/18F/fec-cms/issues/1222
