### ISSUE TITLE
election front end tasks

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC-web-app#2178]
Current election look-up feature

The elections API work https://github.com/18F/openFEC/pull/2485 might need some front end tweaks. I am noting that here and will flesh out the ticket when we know more 

- [x] look at incumbent data for future elections
- [] Info Div quality checks

**Comment by noahmanger** [comment]
I forgot, but we removed the part that showed incumbents with https://github.com/18F/openFEC-web-app/commit/3f60bb1bd5b0071c3b10d21f52f2b2544f0efdba . Checking on dev, and I'm seeing the Alabama special election correctlyu: https://fec-dev-proxy.app.cloud.gov/data/elections/?cycle=2018&state=AL

However, there's some other bugs this is introducing, which I filed an issue for here https://github.com/18F/openFEC/issues/2544

Closing.
