### ISSUE TITLE
Extend "late filing" retention on filings pages from 2 to 3 days

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC-web-app#2179]
A few sprints back we added the ability to display reports from the real_efile tables if they were too late to make the overnight process. I believe we set them to be displayed for 2 days assuming they would be in the processed data by then. That was a work around because the classic process that displays them for 3 days or until they show up in the processed data was too complicated to implement in the short time frame. 

I think we need to either extend the time to 3 days or implement the more complex -Display until the report shows up in the processed data because we had a report that did this:

Jul 9: Filed late in the evening
Jul 9: It was probably displaying correctly
Jul 10: it was probably displaying correctly
Jul 10 overnight process failed
Jul 11: It fell off the public record because the two days had passed.
Jul 12: It should be fine because the overnight process the previous night should load it.

@noahmanger

**Comment by noahmanger** [comment]
So in this case, the issue is that the committee record is not in the API. The earlier change to display efiled reports for two days was _only_ on the web app side. So I don't think extending from 2 to 3 days will actually solve the issue.

cc @LindsayYoung

**Comment by jwchumley** [comment]
I'll have to check and find out how the classic viewer handles it. It displayed there when it wasn't displaying on the new site. It may be that the viewer creates a virtual row for the committee from the efiling data.


________________________________

**Comment by AmyKort** [comment]
Is this ready to close?

**Comment by AmyKort** [comment]
Issue moved to [18F/fec-cms #1539](https://github.com/18F/fec-cms/issues/1539) via [**ZenHub**](https://www.zenhub.com/)
