### ISSUE TITLE
To better serve user groups with overlapping needs, improve paths between sections of the website.

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC-web-app#2185]
**Criteria for completion**
- Collect relevant issues filed by public, testing, and FEC
- Assess role of home page, nav bar, menu, landing pages, footer (and others?) in findability & path selecting
- Consider if we've labeled navigation items in the most helpful way
- Propose goals for improvement
- Propose design changes toward these goals through prototypes
- Test prototypes & measure improvements

Although they certainly relate, so that we could take them on in stages, we separated the home page changes from the bigger, more cross-page issue of navigating around the site. It's expected that the work in #2159 may need to adjust based on this work.

**Comment by jenniferthibault** [comment]
Starting by collecting existing issues, here is a list of what we have so far:

- The H4CC menu may alienate users who are not candidates/committees, but who could benefit from info there. [testing-#70](https://github.com/18F/fec-testing/issues/70) 
- A few users who open H4CC menu seem to think that all it has are forms, deadlines, trainings. [testing-#67 ](https://github.com/18F/fec-testing/issues/67)
- Users struggle to find information on nearby elections via the campaign finance data menu. [testing-#57](https://github.com/18F/fec-testing/issues/57)
- Improve findability of meeting agendas and information [openFEC-web-app-#2158](https://github.com/18F/openFEC-web-app/issues/2158)
- Difficulty finding information on meetings [fec-#4279](https://github.com/18F/FEC/issues/4279)
- Make it easier to find lists of candidates by election year and office [fec-#4316](https://github.com/18F/FEC/issues/4316)
- Make it easier for users who aren't candidates/committees to find contribution limit chart [fec-#4099](https://github.com/18F/FEC/issues/4099)
- As an average citizen or student, I want to be able to find what law guides the FEC more easily [fec-#4133](https://github.com/18F/FEC/issues/4133)
- User would like "Latest updates" to be more prominent [fec-#4083](https://github.com/18F/FEC/issues/4083)
- Difficulty navigating/using Help for candidates and committees resources [fec-#4220](https://github.com/18F/FEC/issues/4220)
- Difficulty finding electronic filing information [openFEC-web-app-#2132](https://github.com/18F/openFEC-web-app/issues/2132)
- When seeking filing deadlines, users routinely go first to Registration & Reporting [openFEC-web-app-#1721](https://github.com/18F/openFEC/issues/1721)


I'll come back to pick this up & organize/group by theme (if relevant) next

**Comment by patphongs** [comment]
Some follow-up testing can be added for this to see if users understood that they needed to go to Help for candidates and committees to access campaign guidance. After synthesis of our testing results, we might know more. cc @jenniferthibault @llienfec 

https://github.com/18F/fec-testing/issues/73

**Comment by jenniferthibault** [comment]
One way to help scope this down is to focus on known instances of incorrect navigation—times when we know something lives in one place on the site, but users are routinely trying an incorrect navigation path first—and connecting those trails.

That narrows things down to:
- How might we reroute people who look for campaign guidance in "Legal resources"? 
  - [Some users with "rules tasks" seem drawn to legal resources, though candidate resources may be more helpful #19](https://github.com/18F/fec-testing/issues/19)
  - Some hints in here, but not a specific:  [Mixed reviews about how to find troubleshooting information in compliance content #31](https://github.com/18F/fec-testing/issues/31)

- How might we guide users who seek upcoming filing deadlines to the calendar instead of the long list for now? What might a better long-term solution be?
  - When this issue was created, I don't think "Dates and deadlines" was a section on the new site, but we can still likely offer improvements that help people find the calendar: [When seeking filing deadlines, users routinely go first to Registration & Reporting](https://github.com/18F/openFEC/issues/1721) 
- How might we engage or redirect users who are not candidate or committee representatives, but would find information in that section useful?
- The same might be asked of Legal resources—- How might we engage or redirect users who are not lawyers or legal researchers, but would find information in that section useful?

This might seem like a lot, but I'm imagining this issue is not to completely solve all the problems, but rather to identify a system of improvements we could make, and determine what would be the achievable in the near term.

Since I'll be OOO for the rest of the week, I'll move this issue out of "In progress" to keep stand ups moving fluidly, but thoughts are welcome from anyone who wants to lend their brain! 
cc folks who expressed interest in the issue: @dorothyyeager @jameshupp @rhoughfec @patphongs @llienfec

**Comment by jenniferthibault** [comment]
I've updated the designs based on great feedback in last week's design pairing, including:
- Better focus the visual hierarchy (through typography and weighting visual interested assigned to each element)
- Use the card pattern for guide categories, keep them high in the information hierarchy of the page
  - And call them Guides! Which is what they are, in HTML or PDF form. It's a word users recognize and come seeking
- Embed mini feeds of publications and news items that surface recent changes, developments, or reminders so that people can get a quick view of what's newest
  - in Legal resources, this feed includes press releases and record articles in the legal topic categories
  - in Help for candidates and committees, this is Tips for Treasurers, which is an entryway to record articles and other publications that might be useful, but keeps the feed focused.

The independent guide pages would bee the same as outlined above in https://github.com/18F/openFEC-web-app/issues/2185#issuecomment-324472620

### Help for candidates and committees landing revised:
(for comparison, here is [another version](https://user-images.githubusercontent.com/11636908/29935196-ec68e39a-8e4b-11e7-8c55-5d8e0bfd9733.png) that was left on the cutting room floor that reduces the competition between the popular topics and the guides, but feels less visually restful) 

![screen shot 2017-08-31 at 12 53 32 pm](https://user-images.githubusercontent.com/11636908/29935053-7b0f3348-8e4b-11e7-92e1-902d96b62dc1.png)

### Legal resources revised
![screen shot 2017-08-31 at 12 50 59 pm](https://user-images.githubusercontent.com/11636908/29935241-1647c596-8e4c-11e7-9252-730cf3db27ee.png)

Would love if @llienfec @rhoughfec @noahmanger @jameshupp @patphongs could take a look to see if this feels like an improvement based on what we discussed last week, and if I have the right examples in place, especially in the "You might also like" sections

**Comment by jenniferthibault** [comment]
After a great design pairing today we made some further refinements, and have the set that's ready for demoing with the rest of the team in order to move toward implementation and testing:

### New strategy for browsing the _Help for candidates and committees_ landing page
- Surfaces frequently accessed topics that are universally relevant to different entities
- Adds a mini preview feed of specifically relevant publications that will also lead users to more (FEC record, etc)
- Suggests other relevant areas of interest outside this section
- Creates a strong link to getting help for authorized committee representatives seeking it (and promotes new RAD tools!)

![screen shot 2017-09-01 at 5 22 18 pm](https://user-images.githubusercontent.com/11636908/29988602-55a31cb8-8f3c-11e7-88ee-11296be5b54a.png)

___

### Guides as their own page
To make more room on the _Help for candidates and committees_ landing page for giving an overview to the section and most-sought information

![screen shot 2017-09-01 at 5 04 16 pm](https://user-images.githubusercontent.com/11636908/29988601-55a171b0-8f3c-11e7-8ecc-e4a711e30067.png)

___

### New strategy for browsing the _Legal resources_ landing page
- Adds most recent FEC Record and Press releases with legal tags
- Lists all available advanced resource searches
- Makes full resource list more concise and uses a consistent pattern to the model in other sections
- Adds highly visual redirects to Guides and contribution limits for people who have come to this section mistakenly

![screen shot 2017-09-01 at 5 38 35 pm](https://user-images.githubusercontent.com/11636908/29988612-65d84fcc-8f3c-11e7-9dda-30f7e88a95c7.png)

___

I've started placeholder implementation issues in #2286, #2287, and #2288 for each of the above, which we can groom into readiness once we get 👍  from our broader team/product owners

**Comment by AmyKort** [comment]
This looks completely awesome to me! Thank  you for all of the time, thought and care. I think we're ready to move forward with these issues.

**Comment by jenniferthibault** [comment]
Closing in favor of #2286 , #2287 , and #2288 which will implement these. Once implemented, testing should happen on staging/dev before the concepts are moved to production.
