### ISSUE TITLE
Only display Senate candidates on by-location election pages that are up for election

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#2195]
We are currently displaying Senate candidates that are not up for election.  Markey is not up for election in 2018, https://www.fec.gov/data/elections/senate/MA/2018/

![image](https://user-images.githubusercontent.com/11817734/28266740-905eae40-6ac4-11e7-9fda-63e3aefcd43e.png)

**Comment by AmyKort** [comment]
Issue moved to [18F/fec-cms #1577](https://github.com/18F/fec-cms/issues/1577) via [**ZenHub**](https://www.zenhub.com/)
