### ISSUE TITLE
Design UX of election and individual contribution search on data landing page

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#2197]
So that users can more easily locate candidate comparison tools and the individual contributor search, surface those items on the data landing page. 

---

Follow up from https://github.com/18F/openFEC-web-app/issues/2167

Concept:
![concept](https://user-images.githubusercontent.com/1450173/28283623-dfc118a4-6af3-11e7-813c-cec07e1fbba7.png)

**Completion criteria:**
- [ ] Design screens for including the district search and figure out what the flows are
- [ ] How do we link to advanced data pages?
- [ ] Do we include links to frequently sought races? What do we call them?

**Comment by jenniferthibault** [comment]
Had a great pairing session with Noah and a quick checkin with the other designers on Friday.

### Quick wins:
- Integrating base functionality for our prioritized features, and introduce examples through trending searches or possible uses of the data
- Updating the menu to match this and drive traffic to the landing page more

![screen shot 2017-07-25 at 1 43 48 pm](https://user-images.githubusercontent.com/11636908/28585772-57c83994-713f-11e7-98b1-d6f2f96a1a71.png)


![screen shot 2017-07-25 at 1 35 23 pm](https://user-images.githubusercontent.com/11636908/28585745-31986050-713f-11e7-92c7-9ebe4d03e76e.png)



### Longer term view
- Moving the interactive data (charts etc) into context of viewing/comparing election trends based on nation-wide, state-wide, and district-wide races.
@noahmanger has been working on an InVision prototype that fleshes this out: https://gsa.invisionapp.com/d/main#/console/11594801/244852362/preview

**Comment by jenniferthibault** [comment]
**Notes on the new menu items:**

- Campaign finance data overview: `data/`
- Look up candidate and committee records: `data/?search=search` :: It would be helpful if this had it's own stable URL so that we could get to it without entering a search term.
- Find contributions from specific individuals: `data/receipts/individual-contributions`
- Compare candidates in an election: `data/elections`
- Browse full data sets: `data/advanced`

**Comment by jenniferthibault** [comment]
Moved to implementation in https://github.com/18F/openFEC-web-app/issues/2232
