### ISSUE TITLE
Design UX around high-level summary data

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#2199]
This is a broad open-ended design issue around figuring out the components we're going to design to address the user needs around browsing high-level summary data, as identified in https://github.com/18F/openFEC-web-app/issues/2167 . 

Some things to consider:
- Figure out how previously designed visualizations and figures fit into the experience: where do they live? Does anything need to change from their old designs?
- Design the experience around election summary information. How do users find the race with the most spending? What is the best way to visualize this information? How do users see how much a given race has raised/spent? How do users view data for all races / candidates in a state?
- What does this all mean for the "discover" experience more broadly? 

This issue will be done when we can break out smaller design and/or development tasks. 

- [ ] document high-level flows and rationale

**Comment by noahmanger** [comment]
Synced with @jenniferthibault today and we agreed that the concept outlined in [these InVision screens](https://gsa.invisionapp.com/share/JWCOSM7YG#/244852362_USA_-_Raising) is largely answers these questions. The idea is to set up a series of comparison pages:

- US nation-wide
- State-level
- Contest (individual Senate, House or Presidential races, i.e. what we have now)

These pages will incorporate the old visualizations we designed as well as the ones we've implemented and give users a way to compare contests and view state- and contest-level totals, and be the primary way of providing a "discover" experience.

The next step is for Jen to refine these designs a little bit more and answer a few lingering UX questions. The goal is to have well spec'd designs for the next PI planning so that we can break out discreet dev tasks. 

Towards that end, my last contribution on this is noting a few areas where I _know_ we need new API endpoints, with the caveat that these designs aren't full complete, but I wanted get this out somewhere.

### 1. Totals by contest/state/nation-wide
This endpoint should provide total raising, spending and IE totals by cycle per senate,  house and presidential contest. Additionally, whether separate endpoints or all part of the same one, I don't know, but we'll need a way to see the total raising across all House races or all Senate races nationwide or in a particular state. This should give totals as well as subtotals by party (D, R and other). 

There's currently an implementation issue for this here: https://github.com/18F/openFEC/issues/2534

This will feed these figures:
![image](https://user-images.githubusercontent.com/1696495/29898002-7122e662-8d98-11e7-8373-5efd5c75f788.png)

![image](https://user-images.githubusercontent.com/1696495/29898020-7d04a222-8d98-11e7-924c-552c5fdb1b64.png)

![image](https://user-images.githubusercontent.com/1696495/29898057-b0b055ee-8d98-11e7-967c-cf2de3d4250b.png)

![image](https://user-images.githubusercontent.com/1696495/29898062-b88d9dee-8d98-11e7-86aa-d92c0b129a4a.png)

### 2. Nation-wide contributions by state
One figure we definitely want to show is the total contributions per state, perhaps filterable by different committee types:
![image](https://user-images.githubusercontent.com/1696495/29898184-3d359d08-8d99-11e7-9d4b-decc1324031e.png)

There's an old implementation issue for this here: https://github.com/18F/openFEC/issues/1973

### 3. Nation-wide contributions by size
Another figure we'll likely want is total contributions by size, perhaps filterable by different committee types:
![image](https://user-images.githubusercontent.com/1696495/29898197-58a839d8-8d99-11e7-8e1b-90080d5f439b.png)

There's an ungroomed issue for this here: https://github.com/18F/openFEC/issues/2536

There will be more, but that's what we know for now.

**Comment by jenniferthibault** [comment]
Status remains the same from Noah's comment above:

> The next step is for Jen to refine these designs a little bit more and answer a few lingering UX questions. The goal is to have well spec'd designs for the next PI planning so that we can break out discreet dev tasks.

Since I'm OOO the remainder of this sprint, this could get bumped to Sprint 3.6 for completion

**Comment by jenniferthibault** [comment]
This work will continue into the next sprint, and I've upgraded it from a 3 to a 5 in size.

Here's an idea of the work going on:
- Completing the interaction designs for the data visualizations around Senate & House race pages
  - for each state
  - for nation-wide summaries
- Identifying overlapping compliance information
- Integrating the compliance information in design and navigation flows
- Creating an IA prototype for demonstrating the logic
- Creating an InVision prototype for demonstrating the designs

**Comment by jenniferthibault** [comment]
Transferred to the `fec-cms` repo in https://github.com/18F/fec-cms/issues/1531 and will continue work there, so closing.
