### ISSUE TITLE
Update page tour points for home page v2

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC-web-app#2201]
Since the layout and design of the homepage will be changing, we also need to move/reconsider the tour points on that page so that they still make sense.

**Dependencies**
Implement homepage v2: https://github.com/18F/fec-cms/issues/1137

**Criteria for completion**
- [ ] Re-position points 
- [ ] Write new points (if needed)
- [ ] Update copy of existing points (if needed)
- [ ] Implement changes in code

**Comment by jenniferthibault** [comment]
@AmyKort @noahmanger I just remembered this adjustment we'd need to make for the home page. If we're testing the home page next week and decide to make changes based on what we learn, we may not need to implement the tour changes until we know the home page is ready for release. 

Should we move it into this sprint, or hold it until the next?

**Comment by noahmanger** [comment]
Good catch! If we're doing the home page now, we'll need to do this as part of it. So let's keep it in.

**Comment by noahmanger** [comment]
This was resolved with the new home page.
