### ISSUE TITLE
Improve default time period logic for committee pages

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#2205]
Currently, we redirect committee page URLs to the time period with their latest financial information. But in some cases, this means that we default to an earlier time period even though they may have filed a non-financial filing more recently.

**Tasks:**
- [ ] Figure out desired logic

Related:
- https://github.com/18F/FEC/issues/4389
- https://github.com/18f/fec/issues/4366

**Comment by AmyKort** [comment]
Issue moved to [18F/fec-cms #1576](https://github.com/18F/fec-cms/issues/1576) via [**ZenHub**](https://www.zenhub.com/)
