### ISSUE TITLE
Set up Selenium and more front-end testing

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC-web-app#2206]
Set up Selenium browser testing automation tool and more front-end testing

@xtine  can you add anything to this?

If you are wondering what Selenium is: http://www.seleniumhq.org/docs/01_introducing_selenium.jsp

Completion Criteria: Selenium setup and ready for use.

**Comment by AmyKort** [comment]
@xtine Is this issue still relevant?

**Comment by xtine** [comment]
I don't think Selenium is a good choice for front-end testing on our project at this moment. We could always use more tests but it should be groomed issues on what features need more robust testing.

**Comment by AmyKort** [comment]
Thanks! I'll close this.
