### ISSUE TITLE
Simplify front-end build tool workflow

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC-web-app#2208]
integrate FEC style without using node modules? (@xtine)
Maybe extra tasks too
run build icons is broken (only works for Noah and xtine right now)

related to https://github.com/18F/fec-transition/issues/104

Will need clean up after merge.

**Comment by xtine** [comment]
To clarify this issue, this involves updating the front end build tools from gulp+browserify to webpack on both openfec-web-app and fec-cms. Node modules will always be used, but the other issue about combining webapp and cms it will mean the css/js in fec-style will be integrated to the unified app and fec-style itself wont need to be a node module.

**Comment by xtine** [comment]
Also, the build icons wont work for me and currently only work for noah. I havent done icon compiling in webpack yet, but that might solve the compiling issue for everyone else.
