### ISSUE TITLE
Candidate form 2 does not display latest raw filing

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC-web-app#2223]
We added the latest raw efiling section to committee filings but when you go to the candidate profile: https://fec-stage-proxy.app.cloud.gov/data/candidate/H8TX07090/?tab=about-candidate

It only displays processed filings. This should function the same way as the committee's filings to display form 2 filings until they are processed.

**Comment by noahmanger** [comment]
Added this as a step in https://github.com/18F/openFEC-web-app/issues/2193
