### ISSUE TITLE
Alabama Senate election candidates

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#2227]
I'm not sure what's happening here. Both of these pages provide incorrect results.  There are 19 candidate who have files F2s for the AL Senate special election. 

https://www.fec.gov/data/elections/senate/AL/2018/ displays 14 candidates

https://www.fec.gov/data/candidates/senate/?election_year=2018&cycle=2018&election_full=true&state=AL displays 1 candidate. 

CAND_ID	|	CAND_NM	|	CAND_ELECTION_YR	|	CYCLE	|	TTL_RECEIPTS	|	TTL_DISB
---	|	---	|	---	|	---	|	---	|	---
S8AL00431	|	BERETTA, JAMES P	|	2017	|	2018	|	0	|	0
S8AL00407	|	BOYD JR, WILLIE "WILL"  EUGENE	|	2017	|	2018	|	6684	|	6625
S8AL00449	|	BREAULT, JOSEPH F.	|	2017	|	2018	|	0	|	0
S8AL00316	|	BRINSON, R RANDOLPH RANDY MD	|	2017	|	2018	|	180545	|	138073
S8AL00381	|	BROOKS, MO	|	2017	|	2018	|	314812.94	|	110247.19
S8AL00423	|	CALDWELL, VANN	|	2017	|	2018	|	0	|	0
S8AL00357	|	FISHER, JASON E	|	2017	|	2018	|	15562	|	13719
S8AL00332	|	GENTILE, DOMINIC	|	2017	|	2018	|	23231	|	12106
S8AL00373	|	HANSEN, LEWIS MICHAEL JR	|	2017	|	2018	|	13742	|	12125
S8AL00324	|	HENRY, WILLIAM ED	|	2017	|	2018	|	6933	|	0
S0AL00156	|	JONES, DOUG	|	2017	|	2018	|	158418	|	57228
S8AL00365	|	KENNEDY, ROBERT JR	|	2017	|	2018	|	11600	|	398
S8AL00456	|	MAXWELL, MARY	|	2017	|	2018	|	0	|	0
S8AL00399	|	MCGEE, BRIAN JAMES	|	2017	|	2018	|	0	|	0
S8AL00340	|	MOORE, ROY JUDGE	|	2017	|	2018	|	308747	|	47407
S6AL00369	|	NANA, CHARLES	|	2017	|	2018	|	0	|	0
S8AL00464	|	PEEPLES, BRYAN	|	2017	|	2018	|	0	|	0
S8AL00415	|	PITTMAN, LEE DAVIDSON MARBURY	|	2017	|	2018	|	302545	|	31447
S8AL00308	|	STRANGE, LUTHER J III	|	2017	|	2018	|	2524170	|	1481488

**Comment by noahmanger** [comment]
Closing in favor of a consolidated issue in https://github.com/18F/openFEC/issues/2590
