### ISSUE TITLE
Implement changes to data landing page and data menu that incorporate election & individual search

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC-web-app#2232]
Implementing preliminary designs from https://github.com/18F/openFEC-web-app/issues/2197

- [ ] Review & refine microcopy & section titles @jameshupp 
- [x] Adjust landing page
  - [x] Change format of candidate/committee search, add trending search modules (that are set manually)
  - [x] Add individual contributor search
  - [x] Add election search: If a district is entered, "View results" go straight to election page. If no district is entered, "View results" navigates to election search results page
  - [x] Add trending election module (that are set manually)
  - [x] Add cards for advanced data
       - [x] Add new icon for loans @jenniferthibault
       - [x] Add new icon for bulk data @jenniferthibault
  - [ ] Add slab with link to API

**Designs**

![28585745-31986050-713f-11e7-92c7-9ebe4d03e76e](https://user-images.githubusercontent.com/11636908/28780510-f37192e8-75d4-11e7-9604-5f1dd981af8a.png)

**Comment by jenniferthibault** [comment]
@noahmanger could you review the completion criteria above ?

**Comment by noahmanger** [comment]
Updated completion criteria to reflect my last conversation with @jenniferthibault . We agreed that the nav updates aren't necessary for this first version.

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/openFEC-web-app/pull/2243
