### ISSUE TITLE
Upgrade minimatch

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC-web-app#2237]
update to minimatch 3.0.2 or higher

- [ ] after Christine's cms/web-app merge
- [ ] install instructions can run without any high-level warnings

**Comment by xtine** [comment]
I did a search in `node_modules` and also `package-lock.json` and majority of the dependencies on minimatch are `3.0.4`. Also, `npm install` doesn't give this error anymore and we don't currently have npm dependency errors, so I am closing this for now.
