### ISSUE TITLE
Bug: "Home" breadcrumb link in Data and Legal sections broken

### ISSUE THREAD

**Issue by patphongs** [18F/openFEC-web-app#2244]
In user testing today, we uncovered that the home breadcrumb link is broken in the data and legal sections of the website. The `href` seems to be empty.

**Comment by jenniferthibault** [comment]
Thanks for filing this @patphongs !

As seen:

https://www.fec.gov/data/advanced/

![screen shot 2017-08-04 at 4 58 29 pm](https://user-images.githubusercontent.com/11636908/28986726-283cd69a-7936-11e7-8064-13cd93532b03.png)
