### ISSUE TITLE
Bug: Alaska House link appears twice

### ISSUE THREAD

**Issue by patphongs** [18F/openFEC-web-app#2245]
On the elections search page, the House link appears twice for the state of Alaska. The first one is broken and goes to this `https://www.fec.gov/data/elections/house/AK//2018/`. The second one is correct and goes to the right page.

![screen shot 2017-08-04 at 4 26 21 pm](https://user-images.githubusercontent.com/12799132/28985689-b47f9066-7931-11e7-9d9f-083373c41100.png)

**Comment by jontours** [comment]
Fixed with the upcoming code.
