### ISSUE TITLE
Create banner and message for the switch of bulk downloads Content

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC-web-app#2246]
- [x] Paul - work on messaging

- [ ] Classic site banner  - John
- [x] Identify pages for banner - Paul

- [x] Also message on current site

@lbeaufort 
@Cptechiegal

**Comment by johnnyporkchops** [comment]
@paul, I says can you point me in the right direction  to identify pages needed banner as it says in the checklist above?

**Comment by PaulClark2** [comment]
- [x] http://classic.fec.gov/portal/download.shtml

- [x] http://classic.fec.gov/finance/disclosure/ftp_download.shtml
- [x] http://classic.fec.gov/finance/disclosure/ftpdet.shtml
- [x] http://classic.fec.gov/finance/disclosure/ftpsum.shtml
- [x] http://classic.fec.gov/finance/disclosure/ftpefile.shtml
- [x] http://classic.fec.gov/finance/disclosure/ftppaper.shtml


- [x] http://classic.fec.gov/data/DataCatalog.do
- [x] http://classic.fec.gov/data/LobbyistBundle.do?format=html
- [x] http://classic.fec.gov/data/CampaignAndCommitteeSummary.do?format=html
- [x] http://classic.fec.gov/data/CandidateSummary.do?format=html
- [x] http://classic.fec.gov/data/CommitteeSummary.do?format=html
- [x] http://classic.fec.gov/data/CommunicationCosts.do?format=html
- [x] http://classic.fec.gov/data/EnhancedElectioneeringCommunications.do?format=html
- [x] http://classic.fec.gov/data/IndependentExpenditure.do?format=html
- [x] http://classic.fec.gov/data/Leadership.do?format=html
- [x] http://classic.fec.gov/data/Lobbyist.do?format=html
- [x] http://classic.fec.gov/data/Form1Filer.do?format=html
- [x] http://classic.fec.gov/data/Form2Filer.do?format=html
- [x] http://classic.fec.gov/data/UnverifiedCommittees.do?format=html

- [x] http://classic.fec.gov/disclosurep/PDownload.do

**Comment by PaulClark2** [comment]
@jameshupp @rhoughfec @llienfec 

Do one of these options work as the message alerting users that our FTP files are moving? Do you have suggestions or thoughts about a better message? 

Banner message:

_Option 1_: 
The Commission will shut down its file transfer protocol (FTP). We will move the FTP files to a simple storage service (S3) bucket. The new location is, https://www.fec.gov/files/bulk-downloads/index.html. The folder structure is the same as on the FTP. 

_Option 2_: 
The Commission’s FTP server is moving to a new location, https://www.fec.gov/files/bulk-downloads/index.html.

_Option 3_: 
The Commission’s FTP server is moving to an S3 bucket, https://www.fec.gov/files/bulk-downloads/index.html.

**Comment by llienfec** [comment]
I like how streamlined #2 is.  Would these data users need the extra information regarding the S3 buckets before they're on the actual site?

**Comment by PaulClark2** [comment]
I don't think general users need the information about the change from FTP to S3 protocols. I assume most occasional users of these data use a browser to download the file of interest. Any browser will handle the download for them.

I plan to draft a longer message to send by email to FEC staff and our institutional data users. The email will include information about the switch from FTP to S3.

**Comment by rhoughfec** [comment]
I really like #2 as well. The "shut down" language in the first one sounds a little to scary for someone who doesn't understand what's going on.

**Comment by AmyKort** [comment]
Let's go with number 2.

**Comment by AmyKort** [comment]
@PaulClark2  Could you clarify the messaging that needs to go on the site? We need body copy of what needs to go on. A google doc with the specific wording and a note where it should go would be great.

**Comment by AmyKort** [comment]
@PaulClark2  Trying again. We've decided on this language:

The Commission’s FTP server is moving to a new location, https://www.fec.gov/files/bulk-downloads/index.html.

Does this banner go with each of the links identified above?

**Comment by PaulClark2** [comment]
@AmyKort yes `The Commission’s FTP server is moving to a new location, https://www.fec.gov/files/bulk-downloads/index.html.` should be on each page listed above

**Comment by AmyKort** [comment]
Thanks!

**Comment by johnnyporkchops** [comment]
Banner has been added 
![nov-01-2017 20-22-20](https://user-images.githubusercontent.com/5572856/32303984-7642640c-bf42-11e7-91af-9911d3bddfa1.gif)
