### ISSUE TITLE
Add more redirects

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC-web-app#2254]
These addresses are going to 404s- these were the top results in the log data and some sample periods I looked at. We should be redirect them for a better user experience and fewer errors.  

CommitteeDetailFilings
https://github.com/18F/fec-proxy/issues/54

/404error.shtml to our 404

Not sure where these go:
/DisclosreSearch/MapAppRefreshTran.do (probably classic)
/law/recentdevelopments.shtml
autodisclover/autodiscover.xml

Update:
In addition,
There are 404 errors for Committee Filing details. We need to redirect to the appropriate filings tab on the new site.

Example:
http://www.fec.gov/fecviewer/CommitteeDetailFilings.do?tabIndex=3&candidateCommitteeId=C00327239&electionYr=2010

Redirect to

https://www.fec.gov/data/committee/C00327239/?tab=filings

**Comment by johnnyporkchops** [comment]
@dorothyyeager asks, in deciding about where to redirect:
"Is there a way to tell what someone was searching for before they clicked on Recent Developments and got the 404?" cc @LindsayYoung

**Comment by johnnyporkchops** [comment]
Per Dorothy:
/law/recentdevelopments.shtml >> https://www.fec.gov/legal-resources/
More to come...

**Comment by johnnyporkchops** [comment]
1) Any URLS starting with http://www.fec.gov/fecviewer/CommitteeDetailFilings.do? **have been redirected to** /data/ search=$arg_candidateCommitteeId **which preserves the query**
2) /law/recentdevelopments.shtml **has been redirected to**  https://www.fec.gov/legal-resources/
3) autodisclover/autodiscover.xml is either Outlook looking for a configuration file to help it discover an Exchange server or it could point to a [hacking attempt](https://f5.com/labs/articles/threat-intelligence/identity-threats/how-three-low-risk-vulnerabilities-become-one-high-24995). Also notice that autodiscover is misspelled once in the URL which might mean that someone with legitimate intentions simple misspelled it, thus throwing a recurring 404.  cc: LRibeiro@fec.gov
