### ISSUE TITLE
Election results page does not list all districts

### ISSUE THREAD

**Issue by patphongs** [18F/openFEC-web-app#2256]
When searching an entire state, it does not list all of the districts in the search results. This has not been tested on every state, but this also seems to be a problem with Texas too. So possibly other large states might have this issue.

## Example from production:
California has 53 districts. But when searching for California, the search results only display 19 districts for the 2017-2018 cycle. Number of districts also change when you select a different 2 year period. It should list all 53 districts. 

![election-results-bug](https://user-images.githubusercontent.com/12799132/29182244-2e9f840c-7dcc-11e7-8425-6f08885f5a58.gif)

The dropdown district list when selecting California does show 53 districts, which is correct.

![screen shot 2017-08-10 at 12 26 58 pm](https://user-images.githubusercontent.com/12799132/29180895-3bd6298c-7dc7-11e7-9bcf-a22d3b8ecd0b.png)

**Comment by noahmanger** [comment]
This is a front-end issue. We need to pass `per_page=100` to the API call.

**Comment by noahmanger** [comment]
Including this fix in https://github.com/18F/openFEC-web-app/pull/2260

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/openFEC-web-app/pull/2260
