### ISSUE TITLE
Candidate Profiles need to display more than just form 2

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC-web-app#2257]
On this candidates page you can only see his form 2:
https://www.fec.gov/data/candidate/P00005686/?cycle=2020&election_full=true&tab=about-candidate

This candidate also has an RFAI   which you can see if you search in Filings and reports:
https://www.fec.gov/data/filings/?data_type=processed&candidate_id=P00005686

The candidate profile page needs to show form 2, FRQ(RFAI)  AND any form in the form_99_misc table regardless of to_from_indicator.

**Comment by noahmanger** [comment]
Closing in favor of https://github.com/18F/openFEC-web-app/issues/2193
