### ISSUE TITLE
Design page for data downloads

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC-web-app#2265]
**User need:** So that advanced users can locate bulk datasets, design an interface for navigating data from the old data catalog, press historical data summaries and FTP/S3 data.  

**Business need:** In order to shutdown Waltham, we need to expose these datasets on the new site.

---

- [x] Organize the various download files into an information architecture 
- [x] Explore different patterns for displaying the datasets 
- [x] Create front-end implementation issues once we land on a pattern

**Comment by jenniferthibault** [comment]
🔏   [Document](https://docs.google.com/document/d/1gU5qXc4jDyVhe98jCi4vbtzWIo37IcLX4SbrJ7TaKz8/edit#heading=h.c1mr531a9w3) with list of data sources reliant on Waltham

**Comment by jenniferthibault** [comment]
Status: @PaulClark2  sent Christian some card sorting exercises for the possible information architectures we could pursue and we are awaiting the results.
Design has not started, but can once we have architecture(s) to model. Since I'm OOO the remainder of this sprint, this will likely get bumped to 3.6

**Comment by jenniferthibault** [comment]
On Friday, @PaulClark2 @ChristianHilland @jwchumley  @JonellaCulmer and I talked though options that included:
 - Grouping the bulk data into its own separate tab
 - Creating a distinction between searchable data and data to download, then distributing the bulk data into it's own part of each of the existing categories in Advanced Data

We got great feedback that mixing the downloadable files from the data catalog with the former FTP files would have the potential to mislead intermediate users who are comfortable with downloadable data (data catalog) into the gigantic, database-oriented files from the FTP, and it would be helpful to create a distinction here.

We sketched out a concept together that mixed the second approach above with a further breakdown of the data catalog files to position them more closely with the searchable view of the same data.

**Data downloads**  |  [View prototype](https://gsa.invisionapp.com/share/QCDMN3I3D#/254874863_Advanced-Data_Candidates_Copy_2)
This prototype that shows how we might distribute the different (but seemingly similar) data sets through the Candidate data case study. The accordions are clickable and indicate how we might label and group data by year, as well as how we can create the space to describe the data within the it. For describing the bulk data, I've dropped in a placeholder paragraph to mark out the space we could use.
 
Would love to see if the team feels good about moving forward with this approach for building and testing.

cc  @jbucelato , sorry we missed you on Friday!

**Comment by jenniferthibault** [comment]
Implementation issue created in : #2330
Info architecture work will be completed in #2318 
Content design work needed is being tracked in #2321

Since we've decided on a design pattern that's extensible as a template, closing this issue in favor of the three above.

**Comment by jenniferthibault** [comment]
While mapping the data in #2318 , there we had some realizations about the data use that resulted in design changes. Circling back here to make sure the most updated designs are attached to this issue for future GitHub archeologists:

🎨 Updated [InVision prototype](https://gsa.invisionapp.com/share/K5DYFESA8#/258343763_Advanced-Data_Raising)
