### ISSUE TITLE
[Release Bug] Incumbent listed repeatedly in previous election cycles

### ISSUE THREAD

**Issue by patphongs** [18F/openFEC-web-app#2277]
In the election profile page view, noticed that the incumbent is listed multiple times when you select previous election cycles. This looks to be across the board and is a data related issue as seen in this API call https://api-stage.open.fec.gov/v1/elections/?api_key=oXyFx4md0kTkxxq9JNfIRlrOPorXc60dqOVEs4GE&cycle=2012&office=house&state=VA&stateFull=Virginia&district=11&per_page=0&sort_hide_null=true. See below for example:

![multiple-incumbent-bug](https://user-images.githubusercontent.com/12799132/29646591-6363b3c6-8852-11e7-8cde-2892cf9f3b73.gif)

**Comment by PaulClark2** [comment]
Fixed in the 8/24 release

**Comment by patphongs** [comment]
Resolved by this PR https://github.com/18F/openFEC/pull/2622
