### ISSUE TITLE
Important documents not showing up in committee and candidate profile filing lists

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC-web-app#2278]
I'm pretty sure this exists somewhere as an issue because I remember creating it but I can't find it so here we go.
On the candidate landing page filings tab and the committee landing page filings tab there are some reports/forms/documents that are missing. On the candidate page it only shows form 2 but it should cover things like RFAIs and Disavowel notices and probably miscellaneous documents. I think the rule should be:

Don't even consider form type when selecting forms to display. In the candidate section if the candidate filed it, show it. (Form 2s together and everything else in "Other")

Same for committees. If a committee files it, show it. If it it isn't already a separate category, show it under "Other"

this is the case that is causing heartburn right now. If you go to the committee's page and look at filings the RFAI is missing but if you search in filings and reports it is there.

https://fec-dev-proxy.app.cloud.gov/data/committee/C00649996/?tab=filings

**Comment by noahmanger** [comment]
This looks related to this issue: https://github.com/18F/openFEC/issues/2574 which has an in-progress PR in https://github.com/18F/openFEC/pull/2581.
