### ISSUE TITLE
Move "Guides" content its own page under "Help for candidates and committees"

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC-web-app#2286]
So that the _Help for candidates and committees_ landing page can more easily accommodate content that meets different users' needs, move the embedded guide content onto its own child page/section.

Discussion and history in https://github.com/18F/openFEC-web-app/issues/2185 

### Designs
![screen shot 2017-09-01 at 5 03 01 pm](https://user-images.githubusercontent.com/11636908/29987693-770513a2-8f37-11e7-89df-62a5ef848fa3.png)

### Notes
- Use the template established in _[Advanced data](https://www.fec.gov/data/advanced/?tab=raising)_
- The content should be the exact same as it is currently on the [landing page](https://www.fec.gov/help-candidates-and-committees/), just re-organized into tabbed sections instead of a single-page list.
- Since this is an early concept that will likely continue to have structural/design changes, it should be a static (not Wagtail) page

**This issue will be finished when:**
- [ ] Content from the _Help for candidates and committees_ landing page has been moved to a section of a new child page
- [ ] The text in the site menu is changed from `Campaign guidance` to `Guides`
- [ ] The link in the site menu directs people to this section instead of the landing page.

**Dependencies**
- [x] Finalize design and language with stakeholders
- [x] Content in accessible doc
- [x] Wait for CMS and web app merger
- [ ] Implement new strategy for _Help for candidates and committees_ landing page #2287

**Comment by AmyKort** [comment]
@dorothyyeager and @gsmaragdis -- just flagging this one for you.

**Comment by dorothyyeager** [comment]
Thanks @AmyKort - seems like a good concept and like everything will just shift around, but will still have the link to the PDF Guide where appropriate (Guide PDFs are now available in documents)

**Comment by patphongs** [comment]
URL for the guides @johnnyporkchops 

Congressional candidates and committees campaign guide
https://www.fec.gov/resources/cms-content/documents/candgui.pdf

Political party committees campaign guide
https://www.fec.gov/resources/cms-content/documents/partygui.pdf

Corporations and labor organizations campaign guide
https://transition.fec.gov/pdf/colagui.pdf

Nonconnected committees campaign guide
https://www.fec.gov/resources/cms-content/documents/nongui.pdf

**Comment by JonellaCulmer** [comment]
@johnnyporkchops @dorothyyeager In addition to the H4CC landing page, will these pages also be done in time for the DC Conference next week? Or do we have a temporary solution? Such as linking to the documents.

**Comment by dorothyyeager** [comment]
For @JonellaCulmer All of those various committee pages are done and active now (linked from https://www.fec.gov/help-candidates-and-committees/) with the exception of the SSF pages on receipts, disbursements, debts etc.. So my understanding is that those pages that are active now will still be active and this is just a redesign of the landing page that leads to all of them. It will be good to test that people can find them via the new landing page. Looks like the guides will be linked directly too on that page too.

p.s. If I am off on this, someone please let me know. :)

**Comment by patphongs** [comment]
This has been completed in this PR: https://github.com/18F/fec-cms/pull/1291
