### ISSUE TITLE
Legal resources "Edit filters" styles are incorrect

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC-web-app#2290]
Not sure when this bug was introduced, but there's a small styling bug happening in the legal resources filter panel that should get squashed before it spreads:

In the [Statutes](https://www.fec.gov/data/legal/search/statutes/?search_type=statutes&search=), [MUR,](https://www.fec.gov/data/legal/search/enforcement/?search_type=murs&search=&mur_no=&mur_respondents=) and [AO](https://www.fec.gov/data/legal/search/advisory-opinions/?type=advisory_opinions&ao_category=F) advanced search page, the "Edit filters" text is incorrectly styled using the sans serif font. It should have the serif styling, like the rest of the data tables. Below is the correct styling on the left Individual contributions table, and the incorrect AO/MUR styling on the right. 

<img width="1089" alt="screen shot 2017-09-01 at 10 17 21 am" src="https://user-images.githubusercontent.com/11636908/30114026-8c1bede6-92e4-11e7-983f-9405d47705e5.png">

I tried the inspector, but it's not immediately clear ot me what's causing it to inherit these styles. 

cc @xtine (not urgent, just flagging for you)

**Comment by cptechiegal** [comment]
please include/pair with cristl @cptechiegal

**Comment by lbeaufort** [comment]
@jenniferthibault when I went to look into this, it looks like the fonts all match. Do you mind taking a look? I'm on my Mac, in Chrome. Version 61.0.3163.100 (Official Build) (64-bit)

[Statutes](https://www.fec.gov/data/legal/search/statutes/?search_type=statutes&search=), 
![image.png](https://images.zenhubusercontent.com/59a579f28f62dc7798c47359/2dc13c77-4d9a-40ef-8e3b-0d30d82c4835)


[MUR,](https://www.fec.gov/data/legal/search/enforcement/?search_type=murs&search=&mur_no=&mur_respondents=) 
![image.png](https://images.zenhubusercontent.com/59a579f28f62dc7798c47359/b36fe5bb-5980-4b4c-9ad0-7bbe676c79bc)


and [AO](https://www.fec.gov/data/legal/search/advisory-opinions/?type=advisory_opinions&ao_category=F) advanced search page
![image.png](https://images.zenhubusercontent.com/59a579f28f62dc7798c47359/bdf6b909-0156-49b5-b642-5f4578f3384a)

[Individual Contributors](https://www.fec.gov/data/receipts/individual-contributions/)
![image.png](https://images.zenhubusercontent.com/59a579f28f62dc7798c47359/615be7c7-eb4e-423a-8f6d-b9f808d3e63b)

**Comment by jenniferthibault** [comment]
I'm also not seeing the style discrepancies anymore. My favorite issues are the ones that resolve themselves! Feel free to close.

**Comment by lbeaufort** [comment]
Closed - resolved itself. Verified w/@jenniferthibault, thanks!
