### ISSUE TITLE
Quickly access electronic filing password page and FECfile resources

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC-web-app#2296]
@fec-issue-bot commented on [Wed Aug 30 2017](https://github.com/18F/FEC/issues/4487)

## What were you trying to do and how can we improve it?
Quickly access the electronic password page and FECFile resources.

## General feedback?
Could a link to the “Electronic Filing Overview” page (https://www.fec.gov/help-candidates-and-committees/filing-reports/electronic-filing/) be added to the “Help for Candidates and Committees” drop down menu? Some of the most common questions that we receive in RAD are related to FECFile (downloading and using the software) and electronic filing passwords.  Currently from the homepage, it takes four clicks to reach this page.  If this link can’t be added to the drop down menu, could it be added to the top of the “Help for Candidates and Committees” page (https://www.fec.gov/help-candidates-and-committees/) along with the “Dates and Deadlines” and “Forms” links?

## Tell us about yourself
Ryan, RAD Analyst

## Details
* URL: https://www.fec.gov/
* User Agent: Amazon CloudFront

**Comment by PaulClark2** [comment]
Closed in favor of https://github.com/18F/openFEC-web-app/issues/2297
