### ISSUE TITLE
Hard to fine efiling password information

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC-web-app#2297]
@fec-issue-bot commented on [Wed Aug 30 2017](https://github.com/18F/FEC/issues/4487)

## What were you trying to do and how can we improve it?
Quickly access the electronic password page and FECFile resources.

## General feedback?
Could a link to the “Electronic Filing Overview” page (https://www.fec.gov/help-candidates-and-committees/filing-reports/electronic-filing/) be added to the “Help for Candidates and Committees” drop down menu? Some of the most common questions that we receive in RAD are related to FECFile (downloading and using the software) and electronic filing passwords.  Currently from the homepage, it takes four clicks to reach this page.  If this link can’t be added to the drop down menu, could it be added to the top of the “Help for Candidates and Committees” page (https://www.fec.gov/help-candidates-and-committees/) along with the “Dates and Deadlines” and “Forms” links?

## Tell us about yourself
Ryan, RAD Analyst

## Details
* URL: https://www.fec.gov/
* User Agent: Amazon CloudFront

**Comment by AmyKort** [comment]
Our new H4CC landing page has a card for Electronic Filing at the bottom of the page 
( https://www.fec.gov/help-candidates-and-committees/ ) which helps to surface E-Filing information. We'll keep an eye on the success of that layout. Closing for now.
