### ISSUE TITLE
Add more election cycles to spending page

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC-web-app#2298]
@fec-issue-bot commented on [Thu Aug 31 2017](https://github.com/18F/FEC/issues/4492)

## What were you trying to do and how can we improve it?
For all five selections on this page, the only time periods available are 2011-2012 and 2015-2016.

## General feedback?
Please include the current cycle and 2013-2014.  If possible, previous election cycles.

## Tell us about yourself
Jason (Public Records)

## Details
* URL: https://www.fec.gov/data/spending/
* User Agent: Amazon CloudFront

---

@jwchumley commented on [Thu Sep 14 2017](https://github.com/18F/FEC/issues/4492#issuecomment-329507746)

Looking at this it is confusing. It is presidential so should not actually include 2013-2014 but it should probably be broken into 4 year instead of 2 year cycles.

**Comment by PaulClark2** [comment]
Closed in favor of https://github.com/18F/openFEC-web-app/issues/2299
