### ISSUE TITLE
Update header on MUR search that links to EQS from search results page

### ISSUE THREAD

**Issue by AmyKort** [18F/openFEC-web-app#2303]
Now that we've added archived MURs to the MUR search, we should update the "feature in progress" alert that shows above search results. Currently, if a user were to search for an 1977 MUR, the feature in progress alert would still provide a link to EQS as an alternative search option. See for example, https://www.fec.gov/data/legal/search/enforcement/?search_type=murs&search=&mur_no=400&mur_respondents=

![image](https://user-images.githubusercontent.com/13237823/30440751-72d32d06-9945-11e7-9ef6-f93164c04967.png)

**Comment by dorothyyeager** [comment]
We are going to update the AO search in progress boxes along the same lines as well.

Completion criteria:
- [x] Draft language for updating AO and MUR search in progress boxes
- [x] Update the MUR and AO "work in progress" banners on specific pages (work with @patphongs)

**Comment by dorothyyeager** [comment]
The wording agreed upon is here: https://docs.google.com/document/d/1k9DVgHSoYv8voP0uDSX-EwniFSGyP-caCPAUbtwjPmI/edit?usp=sharing for both the AO and MUR search banner pages listed.
