### ISSUE TITLE
Re-evaluate "feature still in progress" alerts for legal resources

### ISSUE THREAD

**Issue by AmyKort** [18F/openFEC-web-app#2304]
We're hearing from some users that the "feature still in progress" language for legal searches could lead users to believe that the new search is incomplete with regards to the documents it contains, rather than that it may not have all of the filters and features that will eventually become available. Improvements to the feature in progress language for AO and MUR search could help.

In addition, with the archived MURs now included in the MUR search, it's time to take down the link to the Archived MUR search on classic.

![image](https://user-images.githubusercontent.com/13237823/30441189-a769e3ec-9946-11e7-96e6-ee7857f3b43c.png)

**Comment by rhoughfec** [comment]
Talked with @AmyKort and @dorothyyeager . Updated language for all legal searches has been sent forward and is tracked in #2303 .

**Comment by PaulClark2** [comment]
Closed in favor of https://github.com/18F/openFEC-web-app/issues/2303
