### ISSUE TITLE
Improve findability of search by MUR number feature

### ISSUE THREAD

**Issue by AmyKort** [18F/openFEC-web-app#2305]
The search by MUR number feature is fantastic, but users are having a hard time finding it. From the main Enforcement page, users only have access to the keyword search box. Users are finding the advanced search functions, such as search by MUR number and search by respondent, by going through the keyword search and then using the filters on that results page. A quick way to improve user experience might be to provide an "advanced search" button under the main keyword search:

![image](https://user-images.githubusercontent.com/13237823/30443465-9afdc496-994d-11e7-8f7d-b93a7ea450e7.png)

Or (or additionally) we might surface the MUR number search on the Enforcement landing page.

**Comment by AmyKort** [comment]
@jenniferthibault  Should I close this in favor of the work you did yesterday?

**Comment by jenniferthibault** [comment]
Almost, but not quite yet! The work is in a pull request, but hasn't been merged yet (and could get hung up on who knows what). Let's move this to "Done" and close it when the PR is merged. 

Will be closable when https://github.com/18F/fec-cms/pull/1276 is merged.

**Comment by jenniferthibault** [comment]
Resolved by https://github.com/18F/fec-cms/pull/1276
