### ISSUE TITLE
Display problem for some paper reports

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC-web-app#2311]
There are some paper reports (24 and 48 hour notices) that are keyed in by FEC staff using the online efiling interface. The process creates an electronic image but the paper is also scanned and stored in a separate folder within the docquery system. I've asked Salient to look at the logic and confirm it for me but I think it is simply "always look in the paper folder for a pdf first. If you find it display it. If not then display the regular image"

Here is an example:
Original paper image:  http://docquery.fec.gov/pdf/PAPER/201706059055303214.pdf#navpanes=0

Generated electronic image: http://docquery.fec.gov/pdf/214/201706059055303214/201706059055303214.pdf

More to come but this is an important issue in production.

@LindsayYoung

**Comment by jwchumley** [comment]
I confirmed the logic.

if the image number exists here: http://docquery.fec.gov/pdf/PAPER/
then display it.
else display it as per usual.

**Comment by AmyKort** [comment]
Issue moved to [18F/fec-cms #1549](https://github.com/18F/fec-cms/issues/1549) via [**ZenHub**](https://www.zenhub.com/)
