### ISSUE TITLE
Build audit search page

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#2324]
Build detailed datatable page for the audit listings

- [ ] Build datable page, Front-end
  - [ ] URLs.py
  - [ ] page to link from
  - [ ] make API run locally

**Comment by jenniferthibault** [comment]
🎨 [Designs & notes](https://github.com/18F/openFEC-web-app/issues/2261#issuecomment-330275144) for table and filters

**Comment by PaulClark2** [comment]
Closed in favor of https://github.com/18F/fec-cms/issues/1304
