### ISSUE TITLE
Spending breakdown coverage periods are confusing and limited

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC-web-app#2340]
The time period pull downs on this page are confusing and lacking in coverage.  only 2011-2012 and 2015-2016 are on the list. It should be all 2-year periods back to 2007-2008 (as far back as the data supports this kind of breakdown for all the listed committee types). Also it doesn't include the current cycle.

- [ ] make the pulldowns for all candidate and committee options 2-year periods. Include all 2 year periods even for presidential and Senate candidates.
- [ ] add 2017-2018 and make it the default.

**Comment by AmyKort** [comment]
Issue moved to [18F/fec-cms #1550](https://github.com/18F/fec-cms/issues/1550) via [**ZenHub**](https://www.zenhub.com/)
