### ISSUE TITLE
Investigate slow queries

### ISSUE THREAD

**Issue by AmyKort** [18F/openFEC-web-app#2343]
We experienced API outages on 11/15/17, and undertook a series of mitigation steps. https://github.com/18F/openFEC/issues/2756

One outstanding issue is to investigate slow queries, which we'll be undertaking now.

**Comment by AmyKort** [comment]
@patphongs  Could you tack on the post-mortem doc? Thanks!

**Comment by patphongs** [comment]
Post mortem document started by @LindsayYoung is [here](https://docs.google.com/document/d/1tizrfTK0o7j2CrptDvXX_7MqopL7LoSlt3sy2gsDj1A/edit#) :lock:

**Comment by AmyKort** [comment]
Moving this issue to https://github.com/18F/fec-cms/issues/1534 Thanks!
