### ISSUE TITLE
Revisit design of Sched. A + B data on committee pages

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#284]
**Goal:** Need to decide how we're going to show Schedule A and B data on the committee pages. 

**Criteria:** FEC give the :+1: to static comps.

**Steps:**
- [x] Review old designs
- [x] Make revisions
- [ ] Test with users
- [ ] Show FEC
- [ ] Maker revisions if necessary

**Comment by noahmanger** [comment]
So the original concept around this was to show a visual breakdown of the amount of money raised in the form of different sizes of contributions, like so:

![committee - schedule a](https://cloud.githubusercontent.com/assets/1696495/8322857/cd6c823e-19f0-11e5-9758-1dea30240154.png)

But keeping in mind that the goals of many users is to see which people, organizations and companies are tied to a particular candidate I'm wondering if we want to show anything else in this regard? Or even a chart of the contributions over time or by geography?

**Comment by noahmanger** [comment]
Also, I'm thinking this makes sense as a separate tab both to keep the Two-Year Summary tab from being overcrowded and to make it easily discoverable.

**Comment by jmcarp** [comment]
Any aggregates we show will need to be precomputed--I'll verify, but I'm pretty sure these will be too expensive to build dynamically. I filed a separate issue at https://github.com/18F/openFEC/issues/1006 to talk about which aggregates we'll need on the API side.

**Comment by noahmanger** [comment]
Cool. I like Lindsay's sub-totals: 
> $200 and Under
$200.01 - $499
$500 - $999
$1000 - $1999
$2000 and Over

**Comment by noahmanger** [comment]
Ok, here's an update with showing Top Committees and Top Individuals. The idea Lindsay and I discussed is that for committees that have max contribution limits, we just show every transaction that has a YTD aggregate amount at the max, explaining that there may be duplicates. On the interface I think this works by making the entire mini-table scrollable. 

If the committee does *not* have limits, we can just show the top transactions, sorted by aggregate amount.

![committee - schedule a](https://cloud.githubusercontent.com/assets/1696495/8339210/ba691ca4-1a6a-11e5-9b7e-657866c8d802.png)

**Comment by jmcarp** [comment]
Maybe I'm misunderstanding, but why allow duplicates at all? I just did a quick check, and the top 20 contributors to Obama for American in 2012 are all the Obama Victory Fund 2012. In any case, we might want to use our own aggregates here anyway, since these queries (like basically all aggregates on the itemized reports) will often be too slow to run dynamically.

**Comment by noahmanger** [comment]
Yeah, I mean if we can avoid duplicates all the better.

**Comment by noahmanger** [comment]
Thinking through other visualization options on the first distribution chart:

Not sure exactly how the data would be for this sort of area chart. Presumably we could do this without aggregates, right?

![committee - schedule a - 2](https://cloud.githubusercontent.com/assets/1696495/8421868/e38b63b8-1e88-11e5-9432-dddd6e370b28.png)

Here's basically the same chart as earlier, but vertical.
![committee - schedule a - 3](https://cloud.githubusercontent.com/assets/1696495/8421869/e38d30a8-1e88-11e5-9164-3e8a451114bf.png)

**Comment by noahmanger** [comment]
Also I think it better to use pagination for the list of individuals instead of scroll, but not positive.

**Comment by noahmanger** [comment]
@jenniferthibault and @LindsayYoung could you both weigh in on this?

**Comment by jenniferthibault** [comment]
+1 for pagination.

It took me a few times of looking at each graph/chart design option to realize that is was showing the number of people who had donated in each contribution range. 

Especially with this one, I'm not sure what the columns represent. (Ex: What does $100,000 mean?) 
![screen shot 2015-06-30 at 10 24 42 pm](https://cloud.githubusercontent.com/assets/11636908/8446342/fbcbf8b8-1f76-11e5-8415-f63f608b17be.png)
If we go for this layout, definitely add column labels, and add the total number of people who donated within that range to the right-hand side of the graph bar, or inside the graph bar.

On this layout, I think there would need to be some interaction when you mouse over the graph that shows you the number of contributions at that price, or within a certain range of the graph.
![screen shot 2015-06-30 at 10 26 38 pm](https://cloud.githubusercontent.com/assets/11636908/8446355/1d4164b0-1f77-11e5-87c7-79d85a6ac7aa.png)

Glad to help mock this up Noah, let me know if that would be helpful!

**Comment by noahmanger** [comment]
Totally right on column labels. And yeah, I think the horizontal one isn't working and also +1 to a hover on the other chart. To clarify: the only thing we can visualize is the amount of money given in different amounts, *not* the number of contributors (we have no way of de-duping individual contributors, so just have the transaction as the unit of measurement). 

I'd love some help on the mocks! Let me know if you want the Sketch file otherwise you can go to town (sketching or high fidelity is fine).

**Comment by jenniferthibault** [comment]
A couple alternatives:

![screen shot 2015-07-01 at 11 51 51 am](https://cloud.githubusercontent.com/assets/11636908/8458905/beefda9c-1fe7-11e5-8052-c3d8b93cc37f.png)
![screen shot 2015-07-01 at 11 52 04 am](https://cloud.githubusercontent.com/assets/11636908/8458906/bef10e44-1fe7-11e5-82e2-0b030b300249.png)

**Comment by noahmanger** [comment]
Nice, yeah this helps. I think I prefer the second version in this case, for a couple reasons:

1. I like not having to hover in order to see the numbers
2. I think working in aggretates for ranges as oppoesd to discreet numbers gives a better picture of whether or not someone is drawing their support in the form of small, medium or large contributions.

I think I'd make the labels look more different from the chart title (both in terms of font style and border), but other than that I think it looks good.

Also, we already have the template for those types of charts, so it'll be easy to implement

**Comment by jmcarp** [comment]
I would also prefer the bar chart to the smoothed histogram. Histograms make more sense with many uniform bins (e.g. 100-199, 200-299, etc.), but we're using a small number of non-uniform bins, such that the smoothing gives the illusion of more precision than we actually have. The bar chart is a simple and accurate representation of the data.

**Comment by noahmanger** [comment]
:+1: I'll post the mock in #fec-partners to get reactions from stakeholders.

**Comment by LindsayYoung** [comment]
+1 to the histogram being more precise 

Going back to the duplicate conversation. For looking for individual donors, can show a list of schedule As sorted contb_aggregate_ytd- We will need to explain that that it is reported by committee and just for the year, unlike our normalized data. 

The problem comes for super-pacs so if Sheldon Adelson makes a two, one-million  dollar contributions the list would look like

| contributor | donation | yearly_total |
|---------------|-------------|----------------|
| S. Adelson | $1,000,000 |  $2,000,000 |
| Sheldon Adelson | $1,000,000 |  $1,000,000 |

People don't have identifiers and we can't perfectly deal with duplicates, so we are stuck showing the data as is.

**Comment by LindsayYoung** [comment]
I am thinking that instead of having the top lists, it would be much easier to show the a schedule A query-able view where it defaults to sorting by the year to date totals, that way you are seeing top donors, but we are not making any calculations or doing any modifications that would be hard to defend.  I do think that the top contributor lists would be better for for non-experts, so there is a trade-off.

**Comment by noahmanger** [comment]
I'd really prefer to keep things to a simple list if possible. What if instead of showing YTD totals, we just make the individuals list a list of the "Top Contributions from Individuals", showing Name, Amount and Date, and maybe a link to the image?

We're providing a link to the query view of schedule A so I'd rather not duplicate the data on this page.

**Comment by noahmanger** [comment]
Current iteration:

![committee - schedule a](https://cloud.githubusercontent.com/assets/1696495/8529271/bbb73606-23cd-11e5-88e0-a4d4b373a22f.png)

**Comment by jenniferthibault** [comment]
This may be too early for design-oriented feedback, but I'm still having a hard time visually associating the bar chart and the number value. Could they be moved closer to one another, and possibly put "View" into the column on the farthest right? (I tried this out in my last mockup above, curious to hear others' thoughts)

**Comment by noahmanger** [comment]
@jenniferthibault oops! I missed that. Yes, I like that idea more, too. I'm moving the remaining tasks in this issue to a new one ( #316 ) to keep things clean.
