### ISSUE TITLE
Improve filter toggle button 

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#293]
Doesn't make sense in the light blue box. I'm playing with it.

**Comment by noahmanger** [comment]
Something like this...

![](https://s3.amazonaws.com/f.cl.ly/items/0e1j1A0n3x1C2T1j1618/Screen%20Recording%202015-06-24%20at%2006.02%20PM.gif)

**Comment by noahmanger** [comment]
And then on mobile it will slide down from the top.

**Comment by noahmanger** [comment]
@jenniferthibault thoughts?

**Comment by jenniferthibault** [comment]
The arrow directions are great! We may still need supporting text (show filters, hide filters), as I'm not sure it's obvious what will be happening. Is sideways text a bad idea?

Sorry for the hold-up for such a simple comment. Now that the meeting is done I'll be more on point

**Comment by noahmanger** [comment]
Yeah I was wondering about that too. I don't know how I feel about sideways text. I don't mind it when I see it places. Two other ideas:

Include this sort of filter icon next to the arrow:
![](https://cdn0.iconfinder.com/data/icons/pixon-1/24/filter_list_order_sequence_sort_sorting_outline-512.png)

Or on hover, the tab could slide out a little and say "Filters".

**Comment by jenniferthibault** [comment]
Oh yes! The slide out to say "Filter" on hover/tab focus (for 508) seems the most direct to me. I read that icon as "graphs," or "charts," more than filter.
