### ISSUE TITLE
Finish design of filing table on committee pages

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#296]
**Goal:** Design a view for all filings within a two year period on a committee page that includes a way to view an HTML preview of the filing.

**Steps:** 
- [x] Review current design
- [ ] Decide which columns to show
- [ ] Decide the options under the "view" toggle
- [x] Figure out how to show the preview
- [ ] Finished comps

**Comment by noahmanger** [comment]
So here's what we currently have:

![committee - reports](https://cloud.githubusercontent.com/assets/1696495/8362425/929e1724-1b2d-11e5-9d87-3e4abbeff4e8.png)

![committee - reports - open](https://cloud.githubusercontent.com/assets/1696495/8362426/956b32d4-1b2d-11e5-8dd9-b24dfbafce01.png)

**Key features**
- Each column should be sortable
- Can filter by the type of filing you want to view
- Show Receipts and Disbursements (and other top level figures?) in the table
- Link to raw Schedule A and B data (probably should re-label to something better), which pulls it up in a browse table
- Shows which reports are amended. The most recent report is on top, with the previous versions nested below
- The "View" button is a dropdown that presents different options for viewing it. Not sure if these are the right ones or not, but that's the idea
- Upper right-hand shows the last and next filing deadlines... not necessary for now, but this can be added whenever we get that data together

**Still to figure out**
- Each filing should be able to pull up an HTML preview on the same page. I'm still working on this interaction and will post ideas here.
- Need to settle on what options are in the "View" dropdown

**Comment by noahmanger** [comment]
Credit to @jenniferthibault for cleaning up the preview view. 

Click on a report name...
![committee reports](https://cloud.githubusercontent.com/assets/1696495/8468071/a3729f96-201b-11e5-9d82-30a20c5da47c.png)

... and the preview pane slides out with more details on that report:
![committee reports - details](https://cloud.githubusercontent.com/assets/1696495/8468070/a3726832-201b-11e5-8414-57376a6707df.png)

This moves the "View" button into the preview, and also (recent edition), I added Beginning Cash and Ending Cash to the table view.

**Comment by noahmanger** [comment]
Just need to settle on columns and view options to close this out. @LindsayYoung do you have thoughts?

**Comment by jenniferthibault** [comment]
@noahmanger Looking at the first designs in #311 helped me figure out what wasn't working with the close button! This changes that by grounding it with a dark border, and moves the "Filed on" text closer in the header of the details panel. (it was floaty :) )

![3 2 committee report preview 6 copy](https://cloud.githubusercontent.com/assets/11636908/8479860/675d0eaa-20a8-11e5-94bc-aa6ee0b70da4.png)

**Comment by noahmanger** [comment]
Oh nice! Yeah that definitely helps.

**Comment by noahmanger** [comment]
Ok. Columns are good, plus potentially showing independent expenditures for those committees that have them.

View options:
- Page-by-page
- PDF
- (Maybe FECFile)
- Contributions
- Expenditures

Closing out.
