### ISSUE TITLE
Design transaction detail view UI

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#311]
When on browsing contributions or expenditures, you need to be able to open a detailed view of the transaction. We got some ideas started in #283 

![](https://cloud.githubusercontent.com/assets/1696495/8312555/14bd2c4c-1992-11e5-80dc-123d82ca51be.png)

![](https://cloud.githubusercontent.com/assets/1696495/8312555/14bd2c4c-1992-11e5-80dc-123d82ca51be.png)

Most likely it should resemble the pattern being developed to show detailed previews of filings on committee pages:

![](https://cloud.githubusercontent.com/assets/1696495/8468070/a3726832-201b-11e5-8414-57376a6707df.png)

**Comment by noahmanger** [comment]
@jenniferthibault assigning this to me but if you have time Thursday and want to jump on it, be my guest!

**Comment by jenniferthibault** [comment]
On it! Here's the first pass of reconciling the two elements with the same styling. I added a permalink, but does this section also need the "View" as PDF, FECfile, HTML, etc drop-down list?
![contribution view - alt copy](https://cloud.githubusercontent.com/assets/11636908/8480400/6299552e-20ab-11e5-99b0-56942054792f.png)

**Comment by noahmanger** [comment]
Nice! Nope, doesn't need the same view options.

**Comment by noahmanger** [comment]
To talk it through a bit more: the idea is that this is "above" the table, right? And the table can scroll below. A few more design questions to consider:

- Is the detail pane a fixed width or flexible based on the width of the table? 
- How does it work on mobile? Maybe then we go to a modal view?

Anything else we need to think through before we can close this out?

**Comment by noahmanger** [comment]
- Re: width, just be sure to not cover important columns
- On mobile it will be a modal
- Lindsay will mock up how to differentiate totals
