### ISSUE TITLE
Design UX for location look up tool

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#313]
**Goal:** Design the interface for looking up candidates and elections by address.

**Criteria:** Static comps of a tool that allows users to input an address to find relevant content.

**Steps:** 
- [x] Determine which flow model we're using (main search bar vs. separate tool)
- [x] Design comps
- [ ] Review with 18F
- [ ] Review with FEC

**Comment by noahmanger** [comment]
Question on this: is there a reason we couldn't do street address lookup for this? My suspicion is that that's a more natural interaction for people and then we won't need to worry about showing multiple districts in the results. There's APIs out there for this.

**Comment by LindsayYoung** [comment]
I know how to do a look-up by zip code, we would need to got a geocoding service to look up by address. Other people have done it and I have heard of tools that do this. Sometimes they will be wrong, especially the free ones. 

Also, will all users feel comfortable giving the government their address?

**Comment by noahmanger** [comment]
I can't speak to the comfort without doing some testing. My thought was just that for people who *are* comfortable it would be a good option. Is using a service out of the question? Do we not need to use one if it's just zip code?

**Comment by noahmanger** [comment]
Also, will it be an option to at least show a map of the districts so that users can try to pin point where they live?

**Comment by LindsayYoung** [comment]
I can point to the shape files, implementing that is beyond my front-end abilities.

**Comment by LindsayYoung** [comment]
https://www.census.gov/geo/maps-data/data/cbf/cbf_cds.html

**Comment by noahmanger** [comment]
Forgot to upload this sketch earlier. 
![img_2621](https://cloud.githubusercontent.com/assets/1696495/8712148/83d54862-2b0d-11e5-9773-0c356012e294.JPG)

Maybe helpful maybe not, @jenniferthibault . The idea is you put in a zip code and it returns all of the districts that match (which could be several) and you can either click to view the district or click through to individual candidates.

**Comment by jenniferthibault** [comment]
@noahmanger + others:

Search begins: 
![district 1 copy](https://cloud.githubusercontent.com/assets/11636908/8757375/ac0815b2-2ca7-11e5-8438-a3583f612768.png)

All results:
![district 1 copy 2](https://cloud.githubusercontent.com/assets/11636908/8757386/c87f9ac6-2ca7-11e5-97ff-2bf3e0715456.png)

Refined results:
![district 1 copy 3](https://cloud.githubusercontent.com/assets/11636908/8757391/d6e9aa8e-2ca7-11e5-9735-b9357386e805.png)

One thing bugging me: where should the search tags be positioned? I have them nearest the new search field, but they could also go under the "results" headline.

**Comment by noahmanger** [comment]
I like this layout a lot. 

For simplicity sake, I think we shouldn't worry about the ZIP+4 option. Even with +4 I believe it can still be fuzzy. 

If we don't have the +4 I think we don't actually need the search tags. We can just display the curent zipcode in that input.

Other than that, I think this is looking great.

**Comment by jenniferthibault** [comment]
Removed the Zip +4: Thoughts? Also sending to the slack channel for review on 7/21.

![district 1 copy 4](https://cloud.githubusercontent.com/assets/11636908/8790400/9f356eb8-2f1b-11e5-8334-c52ef45f3f50.png)
![district 1 copy 5](https://cloud.githubusercontent.com/assets/11636908/8790401/9f6f2f4a-2f1b-11e5-836c-7fe41167a42d.png)

**Comment by noahmanger** [comment]
I just have one question, which is how we handle the senate seats. I know
Lindsay and I talked about it, but I can't remember where we landed. Is it
possible to break them out? Or will we always just have one senate district
page / result?

Other than that, the UX here looks great to me.

On Mon, Jul 20, 2015 at 5:13 PM, Jennifer Thibault <notifications@github.com
> wrote:

> Removed the Zip +4: Thoughts? Also sending to the slack channel for review
> on 7/21.
>
> [image: district 1 copy 4]
> <https://cloud.githubusercontent.com/assets/11636908/8790400/9f356eb8-2f1b-11e5-8334-c52ef45f3f50.png>
> [image: district 1 copy 5]
> <https://cloud.githubusercontent.com/assets/11636908/8790401/9f6f2f4a-2f1b-11e5-836c-7fe41167a42d.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC-web-app/issues/313#issuecomment-123102687>
> .
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146

**Comment by PaulClark2** [comment]
Agreed the UX looks great.

1-a) I'm generally uncomfortable including street addresses for individual contributors.  It gives very easy access to individuals' home addresses.  The bulk files include name, city, state, Zip Code, employer and occupation.  That's already alot of information about the contributor.  I understand the street addresses are available in the .fec files but it takes some work to get those addresses.  

1-b) Perhaps I misunderstood, are you thinking the user types in a complete address then the web app displays a Congressional District?   Then, when displaying contribution data we'd exclude the street address?  

2) Will president be displayed for all Zip Codes?

3) What about Alaska, Hawaii, American Samoa, Guam, Northern Mariana Islands, Puerto Rico and Virgin Islands?

@akort may have additional comments

**Comment by noahmanger** [comment]
To be clear, this view has nothing to do with "Contribution" info. This is purely for looking up candidates and elections by zip code.

**Comment by LindsayYoung** [comment]
Zip codes are a popular way to find a member of Congress, which many people don't know. 

- We don't have street address in the API. I think it would be cool to have a hash of the street address, so you wouldn't know what it was, but you could compare records to see if they were the same. (That's not a priority, but it would be cool)

Zip codes for the following- 
American Samoa: 
  96799
Guam:
  96910 - 96952
Puerto Rico:
  00900 - 00999
Virgin Islands:
  008xx

**Comment by jenniferthibault** [comment]
Thanks everyone, I'm moving this over to implementation.
