### ISSUE TITLE
Design Schedule B tab on committee page

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#315]
**Goal:** Design how Schedule B summary data will be displayed on the committee pages

**Criteria:** Static comps demonstrating the design.

**Steps:** 
- [x] Identify what information will be shown and how it varies by committee
- [ ] Design comps
- [ ] Review with 18F
- [ ] Review with FEC

**Comment by noahmanger** [comment]
Trying to figure out what makes sense to show here, given the lack of normalization in the data. The two main things that I understand users to be looking for that would be found in this data are: 
- Other committees they've given money to
- Vendors the committee has spent money with

I'm having a hard time imagining a useful way of showing vendor data, though. Any ideas?

Anything else this is missing?

**Comment by LindsayYoung** [comment]
The codes are kind of useful I have used them to explore what committees are spending money on.

**Comment by noahmanger** [comment]
Can you point me towards the list of codes?

**Comment by PaulClark2** [comment]
The transaction codes can help with contributions to other committees.  The committee of interest's disbursements.  But, operating expenditures, payments to vendors, are not coded.   A complete list of transaction codes is here:  www.fec.gov/finance/disclosure/metadata/DataDictionaryTransactionTypeCodes.shtml

**Comment by PaulClark2** [comment]
The list of transaction codes is extensive.  Jeff and I can help with pulling out the committee-to-committee transactions if you think you want to go that way,

**Comment by jwchumley** [comment]
Along with where the money is spent, the purpose of disbursement is important for knowing what they are spending their money on. Unfortunately it is free form text so it is hard to work with but if you could do anything that makes good use of that it would be a winner I think.

**Comment by AmyKort** [comment]
I agree that the purpose of disbursement is interesting to users, so if there's a way to make that work, that would be great. Thanks!

**Comment by PaulClark2** [comment]
Comment from Christian:  "I agree with the other comments about it being difficult to analyze disbursements because there isn't a uniform method of reporting the purposes. I wonder if we could somehow lump purposes into particular categories and allow public users to modify their own search criteria. For example, any disbursements with: consultant, staff, director, salary, payroll would be lumped under the category of Staff Expenses.  Users could somehow modify the keywords."

**Comment by noahmanger** [comment]
Hmmm. This is interesting. So, if people have the ability to edit the search or keyword terms, that should happen on the query view. But we could present sort of "recommended shortcut" groupings that could then be edited. 

Easier to explain with a picture...
![disbursement purpose](https://cloud.githubusercontent.com/assets/1696495/8578150/ebcb3eec-2561-11e5-9675-0e18c5427849.png)

This definitely entails making editorial decisions about what terms to include and we'll want to be transparent about those decisions and provide the necessary disclaimers. But if you think this is both permissable and doable I'm very interested.

**Comment by PaulClark2** [comment]
@noahmanger this is nice.  I think with proper disclaimers this could be interesting and useful to people.

**Comment by noahmanger** [comment]
Cool! A few more questions:

1. What's the lift like, implementation-wise?
2. How many of these sub-totals do you think we'll have and how often will they change? Can we try sketching out what they would be?
3. Maybe a stretch, but would we be worried about people gaming the system by using different words in purpose descriptions?

**Comment by jmcarp** [comment]
We have a reasonably performant mechanism in place for updating summaries incrementally, and what you're describing seems similar enough to what we're already doing with the Schedule A receipts that this shouldn't be a huge implementation task for the API.

**Comment by PaulClark2** [comment]
@noahmanger This is the purpose of disbursement list Amy mentioned in the meeting:    http://www.fec.gov/rad/pacs/documents/ExamplesofAdequatePurposes.pdf    This is a starting place.

**Comment by noahmanger** [comment]
Oh great! This is a great place to start. Could I ask your team to take a
swipe at grouping them?

On Mon, Jul 13, 2015 at 2:49 PM, Paul Clark <notifications@github.com>
wrote:

> @noahmanger <https://github.com/noahmanger> This is the purpose of
> disbursement list Amy mentioned in the meeting:
> http://www.fec.gov/rad/pacs/documents/ExamplesofAdequatePurposes.pdf This
> is a starting place.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC-web-app/issues/315#issuecomment-121071712>
> .
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146

**Comment by PaulClark2** [comment]
Yup .... I'll ask FEC folks to take a swipe at grouping these.

**Comment by noahmanger** [comment]
Just to be clear, is this "Purpose of Disbursement" table the only one we're showing on this page, or did we also want to show something based on transaction codes?

**Comment by noahmanger** [comment]
@PaulClark2 just to try to close the loop on this. 

I see this tab as having two tables: 1) Aggregate totals by Purpose and 3)  2) Aggregate totals by committee that received disbursement (to easily see how much was transferred to which committees). 

Do we also want to aggregate by payee? (Like you have [here](http://docquery.fec.gov/pres/2015/Q1/C00574624.html)?)
