### ISSUE TITLE
Styling for Schedule A and B data tables

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC-web-app#317]
Data tables for Schedules A and B are implemented in #302 but need styling work before they can be released, especially for the detail sidebar (which is currently still a modal).

**Comment by noahmanger** [comment]
Here's a view at the detail sidebar:

![contribution view - alt](https://cloud.githubusercontent.com/assets/1696495/8657424/5da8c284-2952-11e5-9895-429bc30c9f3c.png)

**Comment by noahmanger** [comment]
So starting with a full table like this:

![table](https://cloud.githubusercontent.com/assets/1696495/8687184/77df5492-2a42-11e5-9911-d277ad04a7df.png)

Hovering over a row highlights it blue

![table hover](https://cloud.githubusercontent.com/assets/1696495/8687193/835a47a0-2a42-11e5-9ec8-c9489de147a8.png)

Clicking anywhere other than the link to the committee name then converts it to a two panel layout, similar to how a two-panel email app works (like Mail on iPad). 

![table click](https://cloud.githubusercontent.com/assets/1696495/8687203/a0412e6a-2a42-11e5-9f1f-e53b5ae79146.png)

In this view you just see the three left-most columns of the table. Clicking "Close" in the upper right closes the right panel and returns to a full table view. Clicking on any other row pulls up that preview.

**Comment by noahmanger** [comment]
And then on mobile, sticking with the Mail app paradigm, you just this view at first:

![mobile 1](https://cloud.githubusercontent.com/assets/1696495/8687238/05536070-2a43-11e5-8426-a258bcdef6b8.png)

And clicking on a row switch the whole thing to the details pane, with the option to go back: 

![mobile 2](https://cloud.githubusercontent.com/assets/1696495/8687239/055613c4-2a43-11e5-8efa-69c8c5259632.png)
