### ISSUE TITLE
Implement election pages

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC-web-app#321]
Implementation of #297.

**Comment by jenniferthibault** [comment]
Mockups ready for implementation per conversation in #297 . Anything in pink is a note, or shows where the break between an alternate view (like the single vs double maps) not meant for the actual design. Holler with questions!

![election - candidate location - map](https://cloud.githubusercontent.com/assets/11636908/8852850/93d0f400-3125-11e5-81c6-8b82f6a9ecee.png)

____________  


![election - candidate location - table](https://cloud.githubusercontent.com/assets/11636908/8852831/7c2573ee-3125-11e5-8fdb-419455f82c61.png)

____________  

![election - contribution size](https://cloud.githubusercontent.com/assets/11636908/8852914/e787c8e4-3125-11e5-9736-d739f90d085a.png)


____________  

![election - candidate comparison - contributor type](https://cloud.githubusercontent.com/assets/11636908/8852882/b346069a-3125-11e5-95d5-5c431724ddf6.png)

____________  

![election - other spending](https://cloud.githubusercontent.com/assets/11636908/8852916/edcac54e-3125-11e5-8aa4-843719137c1c.png)

**Comment by noahmanger** [comment]
Old
