### ISSUE TITLE
To give users confidence that the data is recent, add "last updated" text to the site

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#326]
Random thought I just had, but we should give some thought to where and when we want to add "last updated" text on the site. For example, if a committee page is updated after a filing, do we say so?

**Comment by leahbannon** [comment]
Need to be careful not to confuse with when the candidate or committee last filed updates.

**Comment by noahmanger** [comment]
I know that there's some trickiness to the wording of this, but I still think it would be valuable.

**Comment by emileighoutlaw** [comment]
Agree that this could be helpful, especially for power users who want to know — for example — if the last quarterly report is included yet. I'm also worrying about candidates and committees whose last update was a long time ago, but the data is the most recent. Do we have concerns about that?

**Comment by noahmanger** [comment]
We can change it, but it seemed right to add a new yellow card for "Understand the timeliness of data" under the blue card "Have confidence in the data you're looking at". Right now this is the only white card:

https://18f.storiesonboard.com/m/fec/!card/kXgi7AIYizmLeDnUEM13oA

But I could see having more.
