### ISSUE TITLE
Style Contributions tab

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#339]
Once the functionality is implemented, make sure the tab is styled correctly.

**Comment by noahmanger** [comment]
So there's a couple small things here: #359 and #361 

And then there's a couple bigger questions / thoughts I've got:

### 1. Redesign Contribution Size table?
The first question I have is if we should switch the Contribution Size table from this style:

![screen shot 2015-07-27 at 3 59 23 pm](https://cloud.githubusercontent.com/assets/1696495/8919980/e2c0060e-3478-11e5-865e-0086ca2dbe3e.png)

To the typical Datatables syle we're using elsewhere (including for Contribution Size on the election page):

![screen shot 2015-07-27 at 3 59 28 pm](https://cloud.githubusercontent.com/assets/1696495/8919985/f2cce27e-3478-11e5-8e1c-915982bb8a12.png)

It made more sense to have a different style in the early stages of design, but I didn't notice the inconsistency until we started using Datatables for the other comparisons.

### 2. Separate Individual Contributions from Committee Contributions?
The second question is a little bigger: should we separate out the contributions from individuals from those from committees? By analyzing them all together, I think it gives a distorted view. For instance, it looks like they got a ton of money from DC if they made a big transfer from a joint fundraising committee. And similarly, committee contributions won't have employers or occupations. 

I _think_ the best way to go would be to have a table showing the contributions from committees on top and then the four tabs for contributions from individuals below (or vice versa): State, Size, Employer, Occupation.

This making sense?

**Comment by PaulClark2** [comment]
#2 -- I agree with Noah they should be separated.  From a subject matter point of view, individual contributions, PAC contributions, party contributions, candidate contributions and transfers from JFRs or other affiliated committees are all significantly different.

**Comment by jwchumley** [comment]
Yes. Combining pac and individual contributions is confusing. National PACs are concentrated in DC and VA with a bunch also in CA. 

Using Steny Hoyer (Dem - MD) as an example, including PACs
DC is first with $333,000 
VA at $116,000 
CA with $111,000 
Maryland at $68,000

If you remove PACs it changes to this:

CA $71,000
MD $57,000

and DC and VA are 6th and 8th on the list.

**Comment by noahmanger** [comment]
Great. My thoughts exactly. I'll work on this.

**Comment by noahmanger** [comment]
So how does this look?

![screen shot 2015-07-30 at 1 46 38 pm](https://cloud.githubusercontent.com/assets/1696495/8994625/8417b1ec-36c1-11e5-90d5-1868a066eb78.png)

@jmcarp or @LindsayYoung : will we need to add the a paremeter on the API side to pull aggregates just of individual contributions?

**Comment by jmcarp** [comment]
@noahmanger for that, we'll need to change the way the aggregates are built. Right now, aggregates are grouped by committee, election cycle, and some category (state, zip code, occupation, etc.). Two options for updating the API:
* Restrict all aggregates to individual contributions only.
* Group all aggregates by committee, cycle, contributor type (individual vs committee), and category (state, zip, etc.); only expose individual aggregates on the webapp.

Thoughts @LindsayYoung @noahmanger?

**Comment by noahmanger** [comment]
Hmmm. It seems like the more future proof option is the second one. While we may only need individual aggregates now, i could see aggregates by committee being useful in the future? But if it's a lot more work then I'd be fine with #1.

**Comment by LindsayYoung** [comment]
Initially, I found the second option more appealing, because I like more data. That being said, I think we will be covered if we just have aggregates for state, contribution size, employer and occupation only for individual donors. Committee contributions by state or size breakdown is not really valuable and people could compute that themselves if they really wanted to.

We would still want aggregates by committee in the receipts from committees section.
