### ISSUE TITLE
Add disclaimer for free text aggregates

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#344]
For the aggregates on the Disbursements tab we need to add language that explains they are the result of aggregating free text fields, so stuff may not be included.

**Comment by jmcarp** [comment]
Likewise for Schedule A aggregates by employer and occupation.

**Comment by noahmanger** [comment]
@emileighoutlaw can you weigh in on how this language looks?
> Note: these totals are calculated based on data collected via free text input as reported by this committee in their filings. These totals do not take into account misspellings or variations.

It would show up here: 
![screen shot 2015-07-23 at 4 58 40 pm](https://cloud.githubusercontent.com/assets/1696495/8864887/3e831cb2-315c-11e5-8ccd-2cf15cf6e6f3.png)

**Comment by emileighoutlaw** [comment]
Does this seem more clear to you? 

"Note: These totals are calculated from filing data that the committee reported with free text input. As such, totals don't take into account misspellings or variations."

**Comment by PaulClark2** [comment]
I'm not crazy about calling a committee or treasurer out on their spelling.  How about something like this:

"Note:  The totals by purpose are summed based on free text input as reported by this committee.  Variations in spelling or abbreviation will produce multiple totals for the same purpose of disbursement." 

The note could go on the suggest to the user to scan the entire list to guarantee they are getting all the information they want.

**Comment by noahmanger** [comment]
Oh that's a good catch. I'd like to keep it more general so that the same language can be used for aggregating purpose / employer / occupation, etc. What about:

> Note: These totals are summed based on free text input as reported by this committee. Variations in spelling or abbreviation will produce multiple totals for the same category. For the most accurate information, [click here to view the list of itemized transactions. »](link)

**Comment by PaulClark2** [comment]
@noahmanger   I like that  :thumbsup:

**Comment by emileighoutlaw** [comment]
Me too!

**Comment by PaulClark2** [comment]
This is a little nit-picky but I'll suggest changing "For the most accurate information" to "For the most complete information"   The aggregations are necessarily inaccurate but they may be incomplete because of the nature of the free text data entry.

**Comment by noahmanger** [comment]
+1
