### ISSUE TITLE
Persistent URLs for sub-pages

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC-web-app#347]
Pages with multiple tabs currently don't have persistent URLs for each tab. So, for example, if a user browses to a committee detail page, clicks on the Filings tab, and then refreshes, she won't return to the Filings tab automatically. I propose to add per-tab URLs using `pushState`, like we're currently doing for the data table URLs (e.g. `/committees?party=REP`).

**Comment by noahmanger** [comment]
+1

On Tue, Jul 21, 2015 at 9:15 AM, Joshua Carp <notifications@github.com>
wrote:

> Pages with multiple tabs currently don't have persistent URLs for each
> tab. So, for example, if a user browses to a committee detail page, clicks
> on the Filings tab, and then refreshes, she won't return to the Filings tab
> automatically. I propose to add per-tab URLs using pushState, like we're
> currently doing for the data table URLs (e.g. /committees?party=REP).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC-web-app/issues/347>.
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146
