### ISSUE TITLE
Committee search from homepage doesn't work

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#358]
From the homepage, if you change the search dropdown to "Committees" and then search, you get no results. It looks like there's a bug in the way we're building the url where it's not replacing the `search_type=candidates` parameter:

`?search_type=candidates&search_type=committees&search=michigan`

**Comment by jmcarp** [comment]
Good catch. Looks like the issue comes up because we have two inputs for choosing search type: a select for desktop views, and a pair of radio buttons for small screens. Even though only one input is displayed at a time, both get submitted with the search form. The simplest fix would be to use the same inputs for different screen sizes, if possible. Otherwise, we can add a few change listeners to keep the two inputs in sync. Both options are simple enough--what's your preference @noahmanger?

**Comment by noahmanger** [comment]
Aaaaah. So this is a little tricky because of the different places the search bar lives. I could use some help thinking through this ( @jenniferthibault ) so here's a list with explanation:

**Desktop:**
- Hero: Enough space for dropdown or radios
![screen shot 2015-07-23 at 10 57 30 am](https://cloud.githubusercontent.com/assets/1696495/8857959/a4194b74-3129-11e5-9b39-a47e966354de.png)

- Header: Only enough space for dropdown
![screenshot-1](https://cloud.githubusercontent.com/assets/1696495/8857963/a83fc250-3129-11e5-8db6-77981bcde405.png)

- Search results: Enough space for dropdown or radios
![screenshot-2](https://cloud.githubusercontent.com/assets/1696495/8857973/b11f6c04-3129-11e5-8e7b-68fc0afe5e8f.png)

**Small screen: Only space for radios**
- Hero:
![screenshot-2 copy](https://cloud.githubusercontent.com/assets/1696495/8858000/d495db46-3129-11e5-9836-2e5302e1a3a8.png)

- Nav pop up menu (instead of header):
![screenshot-3 copy](https://cloud.githubusercontent.com/assets/1696495/8857988/c6143572-3129-11e5-9ef6-6b885d94d3fb.png)

- Search results:
![screen shot 2015-07-23 at 10 55 25 am](https://cloud.githubusercontent.com/assets/1696495/8858011/dd19b5a8-3129-11e5-91e8-0cece27ed832.png)

**Comment by noahmanger** [comment]
So I guess i could see moving to radios throughout, except with the header search on desktop it wouldn't work. Maybe that's ok to have it be different, but that seems like a potentially confusing inconsistency?

**Comment by jmcarp** [comment]
To be more specific, the issue is related to having multiple inputs of the same name *in the same form*. So it's no problem to use radio buttons in one form and selects in another. The problem comes up when a single form includes both.

**Comment by noahmanger** [comment]
Oh totally. I'm just trying to think through if it makes sense to just say we're only using radio buttons all the time.

**Comment by jenniferthibault** [comment]
@noahmanger I think it might make even more sense to move to toggle throughout instead of radios (remember the Luke W article I sent you yesterday?). That would also work to the left of the type field on the desktop version, AND we use toggles frequently elsewhere, radio buttons less so.

**Comment by noahmanger** [comment]
Word. Yeah I was thinking the same thing. I still think it might be a
little tricky in the header, but I bet we can make it work.

On Thu, Jul 23, 2015 at 11:18 AM, Jennifer Thibault <
notifications@github.com> wrote:

> @noahmanger <https://github.com/noahmanger> I think it might make even
> more sense to move to toggle throughout instead of radios (remember the
> Luke W article I sent you yesterday?). That would also work to the left of
> the type field on the desktop version, AND we use toggles frequently
> elsewhere, radio buttons less so.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC-web-app/issues/358#issuecomment-124193136>
> .
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146

**Comment by noahmanger** [comment]
I'll take this on.

**Comment by noahmanger** [comment]
Fixed in #363
