### ISSUE TITLE
Show "null" message if a schedule A field is blank

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#369]
In this example, the top total by employer is blank. We should show some sort of message explaining what this means.

![screen shot 2015-07-27 at 10 03 20 am](https://cloud.githubusercontent.com/assets/1696495/8912326/f21e970a-3446-11e5-8752-3d0928444bf8.png)

**Comment by LindsayYoung** [comment]
We could say, something along the lines of "occupation not reported" when it is null.

**Comment by noahmanger** [comment]
This was implemented a while ago.
