### ISSUE TITLE
To illustrate that charts with limited data will eventually have more, add an empty state to bar charts

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#372]
Right now, if the current cycle only has a couple reports in, the charts are conspicuously empty. 

![screen shot 2015-07-27 at 10 57 10 am](https://cloud.githubusercontent.com/assets/1696495/8913774/f4fa28be-344f-11e5-91e3-338fbca58490.png)

So I was wondering if there's a way we could make the presentation clearer that there are more reports on the way? Here's a couple concepts I sketched out:

![empty charts](https://cloud.githubusercontent.com/assets/1696495/8913795/1b9da70c-3450-11e5-9a36-291be2e79907.png)

Fine if we want to bump this to the backlog, but if anyone has ideas, this has been nagging at me for a while.

cc @jenniferthibault

**Comment by LindsayYoung** [comment]
That's a good idea. I really like option A, it seems very clear.

**Comment by jenniferthibault** [comment]
Nice! I love the texture of the lines on B, but A is definitely the most clear. The text helped me understand it best.

**Comment by noahmanger** [comment]
Cool. Maybe the texture of B but the text of A?

**Comment by jenniferthibault** [comment]
If the text doesn't get lost in the background :+1: !

**Comment by noahmanger** [comment]
Cool. @LindsayYoung is there any reason to not include end date as December 31 of the second year (e.g. 12/31/2016)?
