### ISSUE TITLE
Add DAP google analytics code

### ISSUE THREAD

**Issue by leahbannon** [18F/openFEC-web-app#373]
1. [Implementation Instructions & Code](http://www.digitalgov.gov/services/dap/analytics-tool-instructions/)
2. [DAP FAQs](http://www.digitalgov.gov/services/dap/common-questions-about-dap-faq/)

**Comment by konklone** [comment]
A  note that the implementation is simpler now, and can use a central hosting location. See https://github.com/18F/18f.gsa.gov/pull/1111 for an example PR for 18f.gsa.gov.

**Comment by leahbannon** [comment]
Also make sure https://api.open.fec.gov  is covered.

**Comment by leahbannon** [comment]
Josh did this.
