### ISSUE TITLE
Disbursements Tab: Add Purpose aggregates

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#375]
The "Compare by Purpose" table needs to be completed.

**Comment by jmcarp** [comment]
Yep. The code is written here: https://github.com/18F/openFEC/pull/1067. We're just waiting on the finished list of purpose categories.

**Comment by PaulClark2** [comment]
@jmcarp @LindsayYoung 

Below is first try at a purpose of disbursement list.  I'll ask Jeff, Amy K, Amy P and Christian to talk a look, too.  


Administrative (non-exhaustive list of examples)
Salary
Overhead
Rent
Postage
Office supplies
Office equipment
Furniture
Ballot access fees
Petition drives
Party fees
Legal fees
Accounting fees

Travel (non-exhaustive list of examples)
	Travel reimbursement
	Commercial carrier tickets
	Reimbursement for use of private vehicles
	Advance payments for corporate aircraft
	Lodging
	Meals

Fundraising and Solicitation (non-exhaustive list of examples)
	Direct mail
	Fundraising events
	Mailing lists
	Consultant fees
	Call lists
	Invitations including printing
	Catering
	Event space rental

Advertising (non-exhaustive list of examples)
	General public advertising
	Radio
	Television (broadcast, cable, satellite) 
	Print
	Related production costs
	Media

Polling (non-exhaustive list of examples)
	Opinion polling

Campaign Materials (non-exhaustive list of examples)
	Buttons
	Bumper stickers
	Brochures
	Mass mailings
	Pens
	Posters
	Balloons

Campaign Event Expenses (non-exhaustive list of examples)
	Candidate appearances
	Campaign rallies
	Town meetings
	Phone banks
	Catering
	Door-to-door get-out-the-vote
	Canvassing
	Driving voters to polls

Transfers (non-exhaustive list of examples)
	(these transactions generally have a transaction code:  "24G"

Loan Repayments (non-exhaustive list of examples)
(these transactions generally have a transaction code: "20C," "20F," "20G," "20R," "22J," "22K," "22L," "22U"

Refunds (non-exhaustive list of examples)
	Contribution refunds
(these transactions generally have a transaction code:  "17R," "20Y," "21Y," "22R," "22Y," "22Z," "23Y," "28L," "40T," "40Y," "40Z," "41T," "41Y," "41Z," "42T," "42Y," "42Z"

Political Contributions
	Contributions to federal candidates
	Contributions to federal political committees
 (contributions to other federal candidates or committees generally have a transaction code:  "24K")
	Donations to nonfederal candidates
	Donations to nonfederal committees

Donations (non-exhaustive list of examples)
	Donations to charitable or civic organizations

Non-allocable Expenses (non-exhaustive list of examples)

**Comment by jwchumley** [comment]
That is a pretty good list for starters. I don't have anything to add right now.

**Comment by PaulClark2** [comment]
Suggestion #1 from Christian:  rename "Travel"
Travel and Staff Reimbursements (non-exhaustive list of examples)
*Travel reimbursement
*General reimbursements
*Commercial carrier tickets
*Reimbursement for use of private vehicles
*Advance payments for corporate aircraft
*Lodging
*Meals

lll

**Comment by PaulClark2** [comment]
Suggestion #2 from Christian:  Add an "Other" or "Miscellaneous" category to catch everything that doesn't fit into the predefined categories
