### ISSUE TITLE
Fix "Recipient Committee" filter on /receipts

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#381]
Not working at all right now.

**Comment by LindsayYoung** [comment]
This is the call I think it would be using and that looks fine to me
http://fec-dev-api.cf.18f.us/v1/schedules/schedule_b?per_page=20&recipient_committee_id=C00492348

**Comment by noahmanger** [comment]
Ah, I think I figured out what the problem is. The typeahead search isn't setting the committee_id anywhere. It's just setting the committee name in the field.

**Comment by jmcarp** [comment]
Yep, looks like we ran into a number of regressions related to field names changing in some places but not others. Longer term, we need tests for all the new filters, but for now there are some fixes in 386.
