### ISSUE TITLE
Disbursements "City" filter doesn't work

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#383]

**Comment by LindsayYoung** [comment]
Problem is with the API-

Count and pages are correct but no results are returned

http://fec-dev-api.cf.18f.us/v1/schedules/schedule_a?per_page=20&contributor_city=Washington

```
{
 "results": [],
"api_version": "1.0",
"pagination": {
"pages": 916,
"last_indexes": null,
"per_page": 20,
"count": 18312
}
}
``

**Comment by LindsayYoung** [comment]
(I posted sched A instead of B) 

Schedule B has a 502 error

http://fec-dev-api.cf.18f.us/v1/schedules/schedule_b?per_page=20&recipient_city=Washington

**Comment by LindsayYoung** [comment]
@jmcarp do you think it might be missing an underlying view?

**Comment by jmcarp** [comment]
This is a casing issue. The raw data use all upper-case text for cities. I'll make those terms case-insensitive.

**Comment by LindsayYoung** [comment]
thanks!

**Comment by LindsayYoung** [comment]
Do you think it is the same problem on schedule_a cities?

**Comment by jmcarp** [comment]
Sure is. I'll submit patches for these in a few.

**Comment by LindsayYoung** [comment]
Thanks!
