### ISSUE TITLE
graceful breakage when pages with a lot of resources error

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC-web-app#393]
This has come up in candidate committee profiles a few times. if one of the many resources is down, the whole page doesn't work.  I think it would be ideal to render the rest of the page and have some notification and or logging for the failure.

**Comment by jmcarp** [comment]
Mostly applies to content that's loaded server-side; data that we load client-side (maps, data tables, election results) doesn't crash the page if it fails to load for some reason.

**Comment by jmcarp** [comment]
Replacing this with a couple of more specific issues / proposals in #729 and #730.
