### ISSUE TITLE
Implement frontend for "Outside Spending" tab

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC-web-app#394]
Depends on https://github.com/18F/openFEC/issues/1097, https://github.com/18F/openFEC/issues/1098, and https://github.com/18F/openFEC/issues/1099.

**Comment by LindsayYoung** [comment]
The mock up of the outside spending election tab is at the bottom of #297

**Comment by jmcarp** [comment]
This is done.

**Comment by LindsayYoung** [comment]
:dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers:
