### ISSUE TITLE
Use Datatables for contribution size aggregate table

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#398]
Any objections to re-implementing this table...

![screen shot 2015-08-03 at 2 52 29 pm](https://cloud.githubusercontent.com/assets/1696495/9048664/a9e38d70-39ef-11e5-9186-7cfd4a8f27d6.png)

...to use Datatables (like so):
![screen shot 2015-08-03 at 2 56 56 pm](https://cloud.githubusercontent.com/assets/1696495/9048695/f84a73c0-39ef-11e5-869b-724da7492f7b.png)

This is the way it is rendered on election pages, and I think it makes sense to have all of our aggregate tables use the same component. (My apologies for giving it a different style in the first place. It was a style holdover before we started using Datatables for everything).

**Comment by jmcarp** [comment]
:+1:
