### ISSUE TITLE
Start applying new styles

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#402]
Break this issue out into more concrete and smaller tasks once discussed with @jenniferthibault .

(Assigning me to keep track of it for now)

**Comment by jenniferthibault** [comment]
@noahmanger when you have a chance, can you send over the latest you have on the site map?

Maybe we can make a checklist of all the screens here, then move each category (and it's sub-screens) into it's own issue.

**Comment by noahmanger** [comment]
I took a swipe at applying the new styles (which were just living in the styleguide) to the data site. Not much to look at yet and still lots more to do.

<img width="1499" alt="screen shot 2015-08-13 at 11 44 42 pm" src="https://cloud.githubusercontent.com/assets/1696495/9268605/9a83afa8-4215-11e5-894d-900f90618132.png">

**Comment by jenniferthibault** [comment]
It's aliiiiiiiiiiiiiive!

Really liking that #fffff9 background. Has a nice sunny lumnescnce to it

**Comment by LindsayYoung** [comment]
Progress!

**Comment by noahmanger** [comment]
Agreed! We'll need to keep an eye on it on other monitors. At times it
catches my eye in a way that just looks ...off. But all in all I like the
sunny vibes.

On Fri, Aug 14, 2015 at 7:08 AM, Lindsay Young <notifications@github.com>
wrote:

> Progress!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC-web-app/issues/402#issuecomment-131115594>
> .
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146
