### ISSUE TITLE
Fix probabilistic test failures

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC-web-app#414]
Some of our Selenium tests have been failing probabilistically on Sauce Labs (although typically not when I run them locally). We should get the tests back into shape, such that they pass reliably when they should be passing. Assigning this to myself, but if anybody has thoughts on what might be behind this behavior, suggestions appreciated! This means you @msecret and @noahmanger.

**Comment by noahmanger** [comment]
Noooo idea but this makes me happy.

**Comment by jmcarp** [comment]
Tests are fixed for now, and future testing will be mostly focused on lighter-weight unit tests that should be easier to maintain. I'll close this for now, and will try to do a better job staying on top of the Selenium tests.
