### ISSUE TITLE
Fix filtering on committee filings tab

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#423]
None of the filters are currently working on the filings tab.

**Comment by leahbannon** [comment]
Related to https://github.com/18F/openFEC/issues/1028

**Comment by LindsayYoung** [comment]
They are working
https://fec-dev-web.cf.18f.us/filings?committee_id=C00005561&report_year=1991&amendment_indicator=N&primary_general_indicator=P&report_type=CA

**Comment by leahbannon** [comment]
Ok, so looks like they are working for browse, just not on the committee page tab

**Comment by leahbannon** [comment]
Fixed
