### ISSUE TITLE
Enable cycle select to filter filings on filings tab

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#424]

**Comment by leahbannon** [comment]
Is this just related to filtering not working right now? https://github.com/18F/openFEC/issues/1028

**Comment by LindsayYoung** [comment]
Nope, we are still using report year for date filtering instead of election cycle

**Comment by noahmanger** [comment]
Update from discussion:

- We will simplify the Committee Page filings table to just show filings in the current selected cycle (requires backend update)
- Include a "View all" button that takes you to the filings browse page filtered down to all filings by that committee
