### ISSUE TITLE
Design solution to candidate comparison maps

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#429]
This is something that needs some design work: 

![screen shot 2015-08-05 at 1 01 19 pm](https://cloud.githubusercontent.com/assets/1696495/9096474/27026500-3b72-11e5-8a18-12dc9daf468e.png)

If you're on an election page and have selected a smaller subset of candidates to compare, but select menu on the map tool below still lists all potential candidates. I'm not sure what the expected behavior would be, but I tend to think that the the list should default to the first candidate that's selected above and the rest of the options should be limited to the candidates selected? This would make building presidential comparisons a lot easier.

What do others think?

**Comment by jenniferthibault** [comment]
On the latest, I have a combination of drop-down list, checkboxes, and "apply selection" button.

The idea being that you can select multiple candidates from the drop-down (much like the browse/filter data page) and when you've selected all the ones you'd like, you hit apply.

On the map view, I'd assume that you view the candidates in the drop-down in alphabetical order

**Comment by noahmanger** [comment]
Right, but what about the secondary select associated with each map? Should the only options available there be the options that you've selected in this candidate list?

(Also, we won't need the "Apply Selection" button. We can just update when you change the selection).

**Comment by leahbannon** [comment]
Done
