### ISSUE TITLE
Update labels on "Contributor type" table to be more descriptive

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#430]
On election pages, the "Compare by contributor type" table headers should probably be "Received from individuals" and "Received from committees". Thoughts, @emileighoutlaw ?
![screen shot 2015-08-05 at 1 04 39 pm](https://cloud.githubusercontent.com/assets/1696495/9096538/94492e14-3b72-11e5-8e67-ff8a9ed2fc0a.png)

UPDATE: This language needs to be consistent on election pages as well.

**Comment by emileighoutlaw** [comment]
In that case, individuals are exactly what they sound like, and committees are congressional committees, nonconnected committees, and political party committees?

If so, where do corporations and labor organizations fit in?

**Comment by noahmanger** [comment]
Not sure. @LindsayYoung ?

**Comment by emileighoutlaw** [comment]
@LindsayYoung to the rescue?

**Comment by noahmanger** [comment]
Ping. What should we do about this?

**Comment by emileighoutlaw** [comment]
Thinking about this now! I'll get you an idea today.

**Comment by LindsayYoung** [comment]
I am confused by the current receipts tab. [example](https://fec-dev-web.18f.gov/committee/C00431445?tab=receipts&cycle=2014)

The breakdown of committee giving is underneath every tab. Is it supposed to be its own tab?

Back to Emileigh's question- committee v. non-committee is a different category than what type of organization is the donor.

**Comment by noahmanger** [comment]
Re: the receipts tab, it still needs some design help, but the idea is that the toggle buttons are just showing different presentations of Individual Contributions, so we wanted to break out the committee contributions into a separate section.

But I think we can do more to clearly associate / differentiate everything into the appropriate groupings.

**Comment by LindsayYoung** [comment]
If I am understanding correctly, @jmcarp correct me if I am wrong, we are showing individual donations vs non-individual donations on the `schedules/schedule_a/by_contributor_type/by_candidate` endpoint.

Spending that is not from individuals includes offsets, party money, refunds loans, transfers and other receipts.

**Comment by emileighoutlaw** [comment]
If it's broken out as received from either individual or non-individuals, my thinking is the language might be clearest as "Received from individuals" and "Received from groups" 

?

**Comment by LindsayYoung** [comment]
That is better, but it is not 100% correct since there are candidate loan repayments and offsets, which aren't really groups.

**Comment by emileighoutlaw** [comment]
Arg! 

"Individuals"        "Groups and other" 

?

I *hate* the word other.

**Comment by emileighoutlaw** [comment]
Circling back around to this:

The best way I can think to differentiate these two groups is `Individuals` and `Non-individuals`. Not very sexy content. I keep getting stuck, because the non-individuals group encompasses _so many_ different types of things. Thoughts on this @LindsayYoung @jmcarp @noahmanger

**Comment by noahmanger** [comment]
That works for me. I could see adding a tooltip similar to the one we're adding to the "show unique only" filter that explains more?

**Comment by noahmanger** [comment]
We axed this whole thing, so closing.
