### ISSUE TITLE
Inconsistent address updating

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#438]
Perhaps related to the recent fixes to the browser history stuff, but I'm seeing inconsistent behavior when changing filters. Sometimes the params in the address bar change and sometimes they don't, but in both cases the filters seem to work as expected.

**Comment by jmcarp** [comment]
I'm wondering if this was related to one of the fixes that was deployed recently. Is it still happening? Can you give an example?

**Comment by noahmanger** [comment]
Simple example:

- Start at https://fec-dev-web.18f.gov/candidates?cycle=2012&cycle=2014&cycle=2016
- Removing the year filters updates the URL as expected
- Now add President --> adds `office=P`
- Add Senate --> adds `office=S`
- Remove Senate --> removes `office=S`
- Remove President --> `office=P` remains

**Comment by jmcarp** [comment]
Thanks, will take a look.
