### ISSUE TITLE
Design & style search results page and for dealing with "no results" on search

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#444]
We need a way to better handling "no results" cases on search results. This could happen because of spelling mistakes or searching for the wrong type. This needs some UX thinking.

**Comment by jenniferthibault** [comment]
### UX solution
by @onezerojeremy 

![sidebar](https://cloud.githubusercontent.com/assets/11636908/9531749/a64414a2-4cd5-11e5-8c71-e4a1fe1c495e.png)


### Styled 

![search results](https://cloud.githubusercontent.com/assets/11636908/9531779/b9f19f92-4cd5-11e5-8f7f-d820bcea41ad.png)
