### ISSUE TITLE
Explore consistency and logic of which data lives where

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#447]
This is an ambiguous and kind of gnarly issue, and will need more research and testing, but we're noticing a theme of a lack of clarity around where financial data lives between candidate, committee and election pages. It will be easier to explain in person.

**Comment by jenniferthibault** [comment]
@noahmanger— still true? or addressed by other issues?

**Comment by noahmanger** [comment]
Hmmm. Not really sure. It's vague enough that we can probably close it for now but I just wanted to make sure we stayed open to the possibility that we may need to change things to meet user expectations.
