### ISSUE TITLE
Election page aggregates should link to itemized transactions

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#449]
However, I know this is a little tricky because we're using totals from all of a candidate's authorized committees. So flagging this for discussion.

**Comment by jmcarp** [comment]
I proposed a small change to the API that includes a list of committee IDs in the elections endpoint, which gives the webapp the information it needs to fetch transactions for all of a candidate's principal and authorized committees. The receipts and disbursements API endpoints also accept multiple values for `committee_id`, so we can get that data. The tricky part is handling this in the filter interface: we don't currently allow users to filter by multiple committees, even though the API can handle those queries.

**Comment by noahmanger** [comment]
We have everything in place (or about to be in place) in order to implement this now, right? This will be valuable to link to these views from the candidate pages as well.
