### ISSUE TITLE
Text in detail panel appears offscreen for bottom rows

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC-web-app#455]
When a user clicks on a table row to pull up the detail panel, the detail text appears at the top of the table. This looks good for rows toward the top of the table, but for rows toward the bottom, the detail text is offscreen, and the user has to scroll away from the highlighted row to see the text. To reproduce, go to the receipts page, scroll to the bottom, and click the last row in the table.
<img width="1094" alt="screen shot 2015-08-10 at 8 54 56 pm" src="https://cloud.githubusercontent.com/assets/1633460/9187776/5e2fd25e-3fa2-11e5-903f-ae1fa80fa15d.png">

Not sure how to resolve this--maybe the detail text should be anchored to the highlighted row somehow. What do you think @noahmanger @msecret @jenniferthibault?

**Comment by noahmanger** [comment]
I've been wrestling with this and still can't figure it out. The way similar "master-detail" layouts like this work is that the master list on the left scrolls within its own container. So we'd set a max-height on the table with `overflow-y: scroll` that way the details panel on the right would always be visible. 

The alternative would be to try something along the lines of having the details panel stick once it reaches the top of the screen, but that feels clunky to me.

**Comment by noahmanger** [comment]
In a recent patch we made it so that when you open a panel, focus is set on the close icon. This has the side-effect of scrolling to the top of the page so you can see it. I think that works for now.
