### ISSUE TITLE
Use color bars consistently for aggregate data tables

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC-web-app#460]
Right now, some of the aggregate data tables use color bars to indicate contribution totals, and some don't. I think all the aggregate tables should use bars.

With:
<img width="987" alt="screen shot 2015-08-11 at 6 17 48 pm" src="https://cloud.githubusercontent.com/assets/1633460/9212216/5435f2e8-4055-11e5-8a1d-185e07377d93.png">

Without:
<img width="976" alt="screen shot 2015-07-15 at 11 15 54 am" src="https://cloud.githubusercontent.com/assets/1633460/9212223/59d27dfc-4055-11e5-8d98-da4a3ca4e104.png">

Does that sound right @noahmanger? If so, I can knock this out in a few minutes.

**Comment by noahmanger** [comment]
I like it. @jenniferthibault ?

**Comment by jenniferthibault** [comment]
All for consistency! Thanks @jmcarp. 
On desktop view, in places where there may only be few columns of data, is there a way to limit how wide it would span? It might be weird to have a bar that spans half a page just because a table only had two columns of data.

**Comment by jmcarp** [comment]
@jenniferthibault sounds good re. limiting width; will address in a separate patch.
