### ISSUE TITLE
Consolidate filings columns

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC-web-app#470]
Filings are filed by a committee or a candidate, not both. This means that for every row in the browse filings view, at least one of "Filer Name" and "Candidate Name" is blank. Since only one column can ever be populated for a given row, could we consolidate the two columns into one, and call it something "Filer Name"?

What do you think @LindsayYoung @noahmanger?

**Comment by LindsayYoung** [comment]
Sounds good, it would be good to make the search look for both candidate and committee, since those would not be 2 separate categories anymore.

**Comment by noahmanger** [comment]
Or would it better to just have a separate search for candidates? That way we could make use of the typeahead in both cases.
