### ISSUE TITLE
Implement design for more prominent place for cycle select

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#483]
*Background:* Usability testing uncovered that some people have a hard time noticing the cycle select and understanding how it affects the page. Separate (but related), if the user changes the select on one page (e.g. a candidate, committee or election) and then goes to a related page, should the cycle stay consistent? If so, should it be in a more universal place, such as the page header?

*Goal:* Design a new iteration of the cycle select that tries to address these problems.

*Tasks*:
- [x] @jenniferthibault design alternate placement for the cycle select
- [ ] Implement one version for usability testing this week.

**Comment by jenniferthibault** [comment]
On both candidates and committee pages, i turned the button a solid color, which gives it more contrast. @onezerojeremy 's text changes also seem like they'll be a bit help.

![screen shot 2015-08-21 at 12 44 03 am](https://cloud.githubusercontent.com/assets/11636908/9401461/be8e9736-479d-11e5-9641-f2dcfe4137b7.png)

___________________________________________ 

![screen shot 2015-08-21 at 12 44 14 am](https://cloud.githubusercontent.com/assets/11636908/9401462/be91a0a2-479d-11e5-8e61-ad6f78a6c547.png)

**Comment by noahmanger** [comment]
Cool. Works for me. I can restyle those.

**Comment by jenniferthibault** [comment]
Great! transferring over to you for styling/implementation @noahmanger
