### ISSUE TITLE
Preview Pane not displaying correctly for single candidate

### ISSUE THREAD

**Issue by onezerojeremy** [18F/openFEC-web-app#518]
URL: https://fec-dev-web.18f.gov/candidates?name=huffman&cycle=2016&cycle=2014&cycle=2012

Upon name searching and finding one candidate on the candidate browse page, clicking on the candidates row triggers a preview pane that does not appear correctly. 

![preview pane display bug](https://cloud.githubusercontent.com/assets/474916/9473534/4d43a2bc-4b29-11e5-8b82-cf249f1e6a9a.gif)

**Comment by noahmanger** [comment]
Ah yep. Known bug. I'm on it!

**Comment by jmcarp** [comment]
Duplicate of #428.
