### ISSUE TITLE
Browse Receipts "This Month" and "This Quarter" options

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC-web-app#530]
https://fec-dev-web.18f.gov/receipts?min_date=08%2F01%2F2015&max_date=08%2F31%2F2015

"This Month" is not a valid option. We should almost never have data for this month. If you browse "this month" now you get six transactions. Five of them are data entry errors (8 in the month should actually be 6) and one of them is an anomaly. A committee filed their October quarterly 65 days early.

"This Quarter" is iffy. For the first fifty days of each quarter there should be no transactions available for "this quarter". Then you get the first month's transactions of monthly filing committees.   Quarterly filing committees will never show up under "this quarter" except for data entry errors and a few anomalies. 

I think "This year" is OK. It technically has the same issues as the others and it will never have the last quarterly filing or the last monthly filing but it doesn't seem to imply completeness like Month and Quarter do.

**Comment by leahbannon** [comment]
If we wanted to keep something that was shorter than a year, is there a more recent option with good data? Is "last quarter" an option?

**Comment by jwchumley** [comment]
As in "most recently completed?" I agree that it would be nice to have 
something smaller than year.

**Comment by noahmanger** [comment]
What if we show:

- Last quarter (Q1 2015)
- This year (2015)
- This cycle (2015 - 2016)

**Comment by leahbannon** [comment]
Sounds good to me. @jwchumley thoughts?

**Comment by AmyKort** [comment]
I like Noah's idea. 

@jwchumley

**Comment by noahmanger** [comment]
Passing to @LindsayYoung
