### ISSUE TITLE
Candidate Page - Filings - Form 2

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#544]
Form 2 filings are labeled as "Document YYYY" instead of "Statement of Candidacy" or "Form 2."  

![untitled](https://cloud.githubusercontent.com/assets/11817734/9582418/40fce0a0-4fd3-11e5-96f0-58d95c75f5a2.png)

**Comment by LindsayYoung** [comment]
For the names, We are looking at vw_filing_history and use report_type and get the full name by joining with dim. If there is no reporttype  report_type, and if there is nothing there, we use document_type. If there is nothing entered for either, we use "Document" and the year. That way, there is always something to click on and view the PDF. 

If you can get us more document names, that would be great.

**Comment by PaulClark2** [comment]
Form Type	Description
F1		Statement of organization
F1M		Notification Of Multicandidate Status
F2		Statement of candidacy
F9		24-hour notice of disbursements for electioneering communications
F10		24-hour notice of expenditure of personal funds
F11		24-hour notice of opposition personal funds amount
F12		24-hour notice of suspension of increased limits
F99		Miscellaneous Document
RFAI		RFAI or Request for additional information should be pre-pended to any report type

**Comment by LindsayYoung** [comment]
Thanks!
@PaulClark2 is that in the data somewhere or do should I just hardcode those?

**Comment by PaulClark2** [comment]
As you discussed earlier, you'll need to hardcode these
