### ISSUE TITLE
Campaign Finance Data Menu - Search by ZIP code

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#545]
![untitled](https://cloud.githubusercontent.com/assets/11817734/9582506/bd7f6706-4fd3-11e5-989a-c1f98cdcf6d3.png)

"Search by ZIP code" is unclear.  Can I only search for candidates or can I search for candidates and committees?

**Comment by noahmanger** [comment]
Yeah, I've never been happy with the microcopy for this piece. This sends you to the election search page, which I think we need a better name for. @emileighoutlaw do you have thoughts?

**Comment by emileighoutlaw** [comment]
@noahmanger How about "Search by location" ?

**Comment by jenniferthibault** [comment]
Closing this issue in favor of https://github.com/18F/openFEC/issues/1184 which tracks the user story and need
