### ISSUE TITLE
Mobile - receipts

### ISSUE THREAD

**Issue by davidgoldschmidt** [18F/openFEC-web-app#547]
see the filters and contributor names  looks good ... like the candidate
however,  I am not able to click on the contributor name for additional information (like the candidate)
fyi - disbursements is fine
iphone 5c and note4

**Comment by LindsayYoung** [comment]
Hello,

We don't have additional information about donors, like we do for candidates. What we know about donors is in the receipts search. Candidates have IDs, so the information around them is easy to group information from different forms together. Contributions are reported by the various campaigns and do not have ids assigned by the FEC.  Names are actually bad identifiers and supporting information like address can change, so creating profiles is actually pretty challenging. Center for Responsive Politics, and other groups do a lot of additional research to create donor profiles. That isn't planned for this project. 

We do hope to offer useful search options, so you can find the records and resources we do have. 

We would like to continue hearing your ideas of how we can continue to improve the searches and site.

Thanks for writing in!
