### ISSUE TITLE
State or Territory Filter - "National"

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#548]
![untitled](https://cloud.githubusercontent.com/assets/11817734/9582658/c3530e84-4fd4-11e5-8704-2b269bc1eb9f.png)

"National" is an option in the "State or Territory" filer for both Browse Candidates and Browse Committees.   If you select "National," while browsing candidates the web app returns no results.   I assume for candidates this should return presidential candidates.   "National" doesn't make sense for committees.

**Comment by leahbannon** [comment]
Just remove it.
