### ISSUE TITLE
Receipts - column sort

### ISSUE THREAD

**Issue by davidgoldschmidt** [18F/openFEC-web-app#550]
can you sort the first 4 columns to the left?
the cursor changes,but there are no "triangles" like the sortable columns to the right

**Comment by leahbannon** [comment]
For now, if we offer sorting, this will affect performance too greatly. We will fix this for now so that the cursor doesn't change when hovering over the headers.

We will research adding this feature later. David - is there a type of sorting that you would need here?

**Comment by noahmanger** [comment]
Thanks for pointing this out, David. The cursor no longer changes when hovering over these column headers so I'm going to close.
