### ISSUE TITLE
Missing Employer and Occupation columns

### ISSUE THREAD

**Issue by wluoFEC** [18F/openFEC-web-app#551]
![image](https://cloud.githubusercontent.com/assets/7440932/9586215/6e8cba2a-4fe9-11e5-9f87-b5d9c9f4e7a6.png)

**Comment by leahbannon** [comment]
I believe this has been fixed (see screenshot). Comment here and let me know if you're still seeing it. Thanks!

<img width="704" alt="screen shot 2015-09-08 at 4 54 41 pm" src="https://cloud.githubusercontent.com/assets/4323988/9750280/6cac68ec-564a-11e5-9a2d-275ff5032224.png">
