### ISSUE TITLE
Receipts - filter

### ISSUE THREAD

**Issue by davidgoldschmidt** [18F/openFEC-web-app#553]
how do you apply the filter?
I entered retired in occupation...no change
not sure it is related?  when I took a screenshot  I noticed http://fec-dev-web.cf.18f was added after retired

![receiptfilter](https://cloud.githubusercontent.com/assets/14056918/9587117/c1f17a7a-4fee-11e5-9693-18a0e9d8bd5d.JPG)

**Comment by leahbannon** [comment]
Good question - right now, you apply by clicking outside of the field. But we agree that this is unclear, so we're addressing it here: https://github.com/18F/openFEC/issues/1170 Thanks!
