### ISSUE TITLE
Add glossary links throughout

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#555]
Go through all content on app and CMS and add links to glossary terms.

**Comment by noahmanger** [comment]
We need to add a way to do this to terms on the CMS pages. @jmcarp any idea how best to do this? Elsewhere we just wrap them in a span with special data attributes.

**Comment by jmcarp** [comment]
One option would be adding a custom button to the wagtail rich text editor, e.g. next to the "Links" button. You'd select some text, click the "glossary" button, and specify a glossary term. Example of custom buttons here: https://jossingram.wordpress.com/2014/07/24/add-some-blockquote-buttons-to-wagtail-cms-wysiwyg-editor/

**Comment by noahmanger** [comment]
Oh yeah, that sounds like a great solution. Also, I love that that site is a Wordpress :)

**Comment by noahmanger** [comment]
@emileighoutlaw can we coordinate on this tomorrow? I think it makes more sense for you to do (if you've got the time).

**Comment by emileighoutlaw** [comment]
Yes. I can definitely do this. Let's chat today so I know I'm doing the CMS pages right.

**Comment by noahmanger** [comment]
Note: these need to be added to the table headers on the "Other spending" tabs.
