### ISSUE TITLE
Add explanation text for outside spending tables

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC-web-app#573]
The election outside spending tab shows aggregated data for independent expenditures, communication costs, and electioneering, but needs text explaining what those things mean (tbh, I'm not sure myself!). You can see the page in question at https://fec-dev-web.18f.gov/elections/president/2012/?tab=spending, with some placeholder text at https://github.com/18f/openfec-web-app/issues/297#issuecomment-123865324.

Pinging @LindsayYoung and @emileighoutlaw.

**Comment by noahmanger** [comment]
+1.

**Comment by LindsayYoung** [comment]
So, I predict this is going to be hard to get approved. @paulclark2, @amykort and @jwchumley will most definitely need to chime in. 

I would say:

Outside spending represents the groups and individuals that report spending money on their own campaign targeting a particular candidate or race. 

These figures are a reflection of the forms reported to the FEC. Different groups and types of spending have different reporting requirements.

**Comment by jmcarp** [comment]
In the simplest case, we can literally copy and paste definitions of independent expenditures, communication costs, and electioneering costs from the current FEC site, since all language there has already been approved. Or we can add those terms to the glossary and make each table header a glossary link. In any case, it would be great to get some text out relatively soon, since the page gives very little context right now.

**Comment by emileighoutlaw** [comment]
I think they should be in the glossary. I would be curious to hear your thoughts on this language (esp. @amykort). It's basically straight from the campaign guide. Is it clear what these are?

Independent expenditure: "an expenditure for any communication that expressly advocates the
election or defeat of a clearly identified candidate and that isn't made in coordination with any
candidate or his or her campaign or political party."

"Communications costs: "an expenditure for any communication — including ones that expressly advocate the election or defeat of of a federal candidate — made by:
 - A corporation to its stockholders, executive or administrative personnel or their families.
- A labor organization to its members and their families."

Electioneering: "Any broadcast, cable or satellite communication that's publicly distributed within 30 days of a primary or 60 days of a general election, refers to a clearly identified federal candidate and is receivable by 50,000 or more persons in the candidate’s district or state."

**Comment by LindsayYoung** [comment]
I just mean I don't think there is a definition of "outside spending" that the FEC currently uses. 

I like the idea of using already approved copy for the sections!

**Comment by PaulClark2** [comment]
I like the Emileigh's idea of using language from the Guides.  

Perhaps just a very simple sentence on the page, "Outside spending is comprised on independent expenditures, communication costs and electioneering communications and is reported by political parties, political action committees and persons other than political committees.", with glossary links for  "independent expenditures," "communication costs" and "electioneering communications."   @amykort

**Comment by PaulClark2** [comment]
@LindsayYoung you are correct we don't have a definition of "outside spending."  I can see someone arguing that all money except candidate campaign money is "outside."   I'll wait for Amy to chime in with her thoughts.  I'll also ask Christian, in Press, if he has any idea.

**Comment by emileighoutlaw** [comment]
Maybe a tweak of 

"Outside spending is independent expenditures*, communication costs* and electioneering communications*. Political parties, political action committees and people other than political committees report outside spending."

**Comment by PaulClark2** [comment]
Yes that's better!  I've been kind of an English language nightmare the past few days.

**Comment by AmyKort** [comment]
I'm doing a little research on our "outside spending" history. And eating a sandwich. But, I'm on it. Thanks!

**Comment by emileighoutlaw** [comment]
:sandwich: :bread: ! :)

**Comment by emileighoutlaw** [comment]
Hey there! Let's keep talking about this "Other spending" tab!

1. The section `Given by` could easily be misinterpreted as money given to a candidate. Can we change it to `Spent by` ?
 
2. I know we don't want to start giving legal definitions, but can we add some explanatory text to the "Independent expenditures" section? I was thinking something like

"Independent expenditures[glossary link]. This section shows money spent about a candidate, not by a candidate."

That way we aren't defining IE, which is problematic. But we are seeing some sort of explanatory text.

 @AmyKort @PaulClark2: thoughts?







An independent expenditure

: "money spent about a candidate, not by candidate" 



"an expenditure for any communication that expressly advocates the
election or defeat of a clearly identified candidate and that isn't made in coordination with any
candidate or his or her campaign or political party."

**Comment by LindsayYoung** [comment]
+100

I really like "Spent by" to emphasize that the candidates are not directly receiving this money. 

I also like a clear explanation in that section that the candidates are not spending or receiving this money.  The phrase "isn't made in coordination" has a legal definition, but we need something to quickly explain the chart.

**Comment by PaulClark2** [comment]
+1  I like "Spent by," too.  I think it's clearer.  Amy may have thoughts about the bigger explanation.

**Comment by AmyKort** [comment]
I think the language we usually use is "made by" rather than "spent by." http://www.fec.gov/press/press2015/news_releases/20150128release.shtml
What if we just link "independent expenditure" to the glossary definition for now, and work up explanatory text later. IE's are a sticky issue, so we'll want to get the language just right.

**Comment by AmyKort** [comment]
For the label, I think spent by is fine

**Comment by LindsayYoung** [comment]
Sounds great, we will use "spent by" in the tab and I am adding official definition to glossary for now.

**Comment by noahmanger** [comment]
Just flagging that whatever explanation we write needs to account for the logic that we settled on in this patch https://github.com/18F/openFEC/pull/1227

**Comment by noahmanger** [comment]
What's the status on this? Should this be before launch?

**Comment by AmyKort** [comment]
I think that the glossary definitions we already have should be sufficient for launch. We can make the explanation a fast follow. @PaulClark2 ?

**Comment by noahmanger** [comment]
Ok. The only thing that definition doesn't cover though is our decision to not include 24 / 48 hour reports, right? I think we need to make clear that these aren't included in our totals.

**Comment by LindsayYoung** [comment]
We can say that totals are from quarterly reports. 

We are including the quarterly form 5, so all the groups are accounted for.  I think we need some more methodology explanations in general.

**Comment by PaulClark2** [comment]
We'll need to say "quarterly, monthly and semi-annual reports" because many PACs (Form 3X filers) report monthly and in non-election year many PAC quarterly filers file semi-annually.

**Comment by noahmanger** [comment]
So how does this sound? 

```
These totals are drawn from quarterly, monthly and semi-annual reports. They do not include independent expenditures reported through 24 or 48 hour notices.
```

@emileighoutlaw ?

**Comment by PaulClark2** [comment]
Maybe, "These totals are drawn from quarterly, monthly and semi-annual reports.  24-hour and 48-hour independent expenditures reports are not included."

@emileighoutlaw @noahmanger

**Comment by emileighoutlaw** [comment]
I think @PaulClark2's suggested language is okay with me if it's okay with @AmyKort

**Comment by amypike** [comment]
You've got one Amy vote, sounds good to me.

**Comment by AmyKort** [comment]
Sounds good!
