### ISSUE TITLE
"view all" links not working on elections page

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC-web-app#579]
https://fec-dev-web.cf.18f.us/elections/

The function to build them is [here](https://github.com/18F/openFEC-web-app/blob/develop/static/js/modules/election-lookup.js#L77-L87), but it isn't called. 

I tried adding it to the url to the resource but that adds /elections to every link on the page.

You can see that [here](https://github.com/18F/openFEC-web-app/pull/576).

**Comment by jmcarp** [comment]
Fixed in #576.
