### ISSUE TITLE
Deal with re-districting

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#587]
Using Pelosi as an example: https://fec-dev-web.18f.gov/candidate/H8CA05035

It looks like her district had a different number until 2012, because clicking on any election year link in the header takes you to an election page without her, presumably because the 2010 re-districting drew her district different / with a new number.

I know we've talked about this in the past, but we should fix it here.

**Comment by jmcarp** [comment]
This issue just refers to the candidate detail page, right? I can fix this one.

**Comment by noahmanger** [comment]
Yep.
