### ISSUE TITLE
Add election lookup to Data Home

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#591]
[Full mock here](https://invis.io/SE3ZFQF8Y). Specifically this part:

![screen shot 2015-09-04 at 1 03 40 pm](https://cloud.githubusercontent.com/assets/1696495/9694116/ad8f5740-530a-11e5-8537-55548a574aef.png)

If @jmcarp gets the basic functionality there, I can style.

**Comment by jmcarp** [comment]
For the right-hand panel, I can hard-code this to look up the 2016 presidential election for now, but what should this do after the election next year? If we switch to the 2020 presidential election after the 2016 election, this widget will be pretty empty for a few years.

Thoughts @noahmanger?

**Comment by noahmanger** [comment]
Good question. Curious what @jenniferthibault thinks, but I think in the future it could disappear, or be a sort of retrospective. There's always a lot of reporting around the total numbers post-election, so I think that could go on for a while.

**Comment by jmcarp** [comment]
In any case, sounds like we can hard-code to the 2016 Presidential election for now. I'll do that next unless folks want to discuss more--let's just remember to make a decision about the long-term behavior before the election.

**Comment by noahmanger** [comment]
:+1: I've got the placeholder markup for it here: https://github.com/18F/openFEC-web-app/pull/605

**Comment by jenniferthibault** [comment]
Nice! I love the idea of a retrospective for a certain amount of time after the election, (maybe a year, even?) which will be relevant to people researching. 

@amykort @jwchumley @paulclark2 Any thoughts on what you'd like to be able to show users here in the future that would be similarly useful and interesting? Feel free to pitch a few ideas!

**Comment by PaulClark2** [comment]
One option would be to switch to house or senate candidates and numbers for 2017-2018.  A natural time switch would be following the 2017 April Quarterly reports.  They are due 4/15/2017. These reports will be the first financial reports for house and senate candidates for the 2017-2018 two-year period.

**Comment by jmcarp** [comment]
Agree with @PaulClark2 about switching to Congressional candidates in 2017, but not sure we want to implement that piece now. Thoughts @noahmanger?

**Comment by noahmanger** [comment]
Yeah, I agree that can wait.

On Fri, Sep 11, 2015 at 9:33 AM, Joshua Carp <notifications@github.com>
wrote:

> Agree with @PaulClark2 <https://github.com/PaulClark2> about switching to
> Congressional candidates in 2017, but not sure we want to implement that
> piece now. Thoughts @noahmanger <https://github.com/noahmanger>?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC-web-app/issues/591#issuecomment-139592790>
> .
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146
