### ISSUE TITLE
Add Ethnio javascript to home page of Beta

### ISSUE THREAD

**Issue by onezerojeremy** [18F/openFEC-web-app#601]
Assuming we'll want to use the same one on both it and the FEC main site. 
```
<!-- Ethnio Activation Code -->
<script type="text/javascript" language="javascript" src="//ethn.io/70862.js" async="true" charset="utf-8"></script>
```
http://help.ethn.io/hc/en-us/articles/200202455-Placing-Ethnio-Javascript-The-Details

If we want to do something different, I'm totally down to switch it up. Ideas?

**Comment by noahmanger** [comment]
Oh good call. Yeah let's do it.

On Tue, Sep 8, 2015 at 4:44 PM, Jeremy Canfield <notifications@github.com>
wrote:

> Assuming we'll want to use the same one on both it and the FEC main site.
>
>
> http://help.ethn.io/hc/en-us/articles/200202455-Placing-Ethnio-Javascript-The-Details
>
> If we want to do something different, I'm totally down to switch it up.
> Ideas?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC-web-app/issues/601>.
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146
