### ISSUE TITLE
Move web app and cms to beta.fec.gov

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC-web-app#609]
We have the subdomain, we need to move the webapp and cms.

**Comment by jmcarp** [comment]
Have we decided what's going to live at each url? Sounds like the CMS lives at beta.fec.gov, but what about the data site? Is the API staying where it is at api.open.fec.gov?

**Comment by LindsayYoung** [comment]
If I remember correctly, we talked about moving the cms site and the data site to beta.fec.gov and keeping the API at the same url until we wanted to announce it was out of beta.

**Comment by jmcarp** [comment]
Right, but the CMS and data site can't live at exactly the same URL. The URL for the CMS will be `beta.fec.gov`. What URL will represent the root of the data app?

**Comment by leahbannon** [comment]
I say /data

**Comment by PaulClark2** [comment]
makes to use /data.   I'm tagging Wei and Amy as they will need this information for our press office @wluoFEC @amykort

**Comment by jmcarp** [comment]
Done.
