### ISSUE TITLE
Deal with Cycle select on committee filings tab

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC-web-app#612]
The cycle filter changes the url and is not connected to the form. I have only thought of hacky ways to deal with this. Any ideas?

The last remaining issue on 18F/openFEC#1028

**Comment by noahmanger** [comment]
This currently works for me. Updating the cycle updates the reports and URL. Am I missing something?

**Comment by jmcarp** [comment]
@noahmanger the issue is the page refresh. Changing inputs inside the filter form (amendment indicator, election type, etc.) loads new filings data without refreshing the page. Changing the cycle select refreshes the page. So yes, changing the cycle select gives the expected data, but it's kind of clunky.

**Comment by noahmanger** [comment]
Ah. Gotcha. Considering that we're likely to move to rendering more data
client side on these pages, would it make sense to wait to do a universal
cycle select update then? I'd like to at least keep the behavior of the
cycle select the same for now.

On Thu, Sep 10, 2015 at 6:41 AM, Joshua Carp <notifications@github.com>
wrote:

> @noahmanger <https://github.com/noahmanger> the issue is the page
> refresh. Changing inputs inside the filter form (amendment indicator,
> election type, etc.) loads new filings data without refreshing the page.
> Changing the cycle select refreshes the page. So yes, changing the cycle
> select gives the expected data, but it's kind of clunky.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC-web-app/issues/612#issuecomment-139237531>
> .
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146
