### ISSUE TITLE
"www" prefix are needed for any links back to fec.gov old site.

### ISSUE THREAD

**Issue by wluoFEC** [18F/openFEC-web-app#621]
Please add "www" prefix to any links back to fec.gov pages. The links without "www" prefix will be broken for FEC internal users. 

![image](https://cloud.githubusercontent.com/assets/7440932/9796215/fa4a2ef4-57c2-11e5-9b7d-6c29dc1b7b20.png)

![image](https://cloud.githubusercontent.com/assets/7440932/9796202/de781a88-57c2-11e5-8fde-b4e413c78b37.png)

**Comment by noahmanger** [comment]
Ah oops. Fix coming.

On Thu, Sep 10, 2015 at 10:51 AM, Wei Luo <notifications@github.com> wrote:

> Please add "www" prefix to any links back to fec.gov pages. The links
> without "www" prefix will be broken for FEC internal users.
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/7440932/9796215/fa4a2ef4-57c2-11e5-9b7d-6c29dc1b7b20.png>
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/7440932/9796202/de781a88-57c2-11e5-8fde-b4e413c78b37.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC-web-app/issues/621>.
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146
