### ISSUE TITLE
Explain which itemized transactions and aggregates we're showing

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#622]
We currently don't show itemized transactions and aggregates for anything before 2011. Wherever we end up drawing the line, we need to explain that to the user. So if you're looking at an old election or old committee page, we should have a way of explaining why the receipts and disbursements tabs are empty.

Tasks:
- [x] @jmcarp Identify where the cutoffs are
- [ ] @jenniferthibault and I work on the design

**Comment by noahmanger** [comment]
I think this makes sense to try to get for launch, but could be ok to wait.

**Comment by noahmanger** [comment]
We've added this to /receipts and /disbursements, but should still figure out a way to handle this on the committee page tabs.

**Comment by jmcarp** [comment]
It'a actually pretty straightforward to extend the aggregates back in time--maybe to 1979, like the rest of the data. It's just the transactions that are complicated. If users wouldn't find it too confusing to show aggregates but not transactions pre-2011, we could make this change anytime.

**Comment by jenniferthibault** [comment]
@noahmanger glad to work this up today if you'd like

**Comment by noahmanger** [comment]
@jmcarp oh yeah that would definitely be better I think. Better to show the aggregates, but not have them link to the transactions. Maybe we include an "info warning" explaining why that is.

**Comment by noahmanger** [comment]
It would be nice because looking at any committee page pre-2011 is just really sparse.

**Comment by noahmanger** [comment]
We're fixing this by running one-time aggregates for pre-2011 transactions.
