### ISSUE TITLE
Inconsistent "Campaign finance data" drop down menus

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#630]
The left menu - cms
The center menu  - openFEC
Right menu - beta Home Page

![untitled](https://cloud.githubusercontent.com/assets/11817734/9814487/8240365c-585c-11e5-994a-807ee435df37.png)

**Comment by noahmanger** [comment]
Good catch. This has been fixed but is just waiting to be deployed.

On Fri, Sep 11, 2015 at 5:10 AM, Paul Clark <notifications@github.com>
wrote:

> The left menu - cms
> The center menu - openFEC
> Right menu - beta Home Page
>
> [image: untitled]
> <https://cloud.githubusercontent.com/assets/11817734/9814487/8240365c-585c-11e5-994a-807ee435df37.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC-web-app/issues/630>.
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146
