### ISSUE TITLE
Formatting on Terminate your Committee Page

### ISSUE THREAD

**Issue by AmyKort** [18F/openFEC-web-app#632]
On the Terminate your committee page (https://fec-dev-cms.18f.gov/registration-and-reporting/terminate-your-committee/) there are two spots that should be bullet lists (or something).

You can file a termination report when your committee meets all of these criteria:

   [Bullet] You no longer intend to take in contributions.

   [Bullet]  You no longer intend to make expenditures.

    [Bullet] You no longer intend to disburse money that could qualify you as a political committee.

   [Bullet]  You have resolved all outstanding debts and obligations (and no other committee authorized by your candidate has any outstanding debts or obligations).

Then again:

For example, you can combine your termination report with an already scheduled filing by checking the “Termination Report” box on your July Quarterly report. However, your termination report must include the following information:

   [Bullet]  All receipts and disbursements not previously reported. This includes your accounting of debt retirement.

   [Bullet]  How you will use any remaining committee funds and assets.

**Comment by jenniferthibault** [comment]
This is happening on a few pages that stem from the checklist. We need to take a pass at formatting them all—I believe they are all unstyled right now.

**Comment by noahmanger** [comment]
List styles are now working!
https://fec-dev-cms.18f.gov/registration-and-reporting/get-treasurer/

On Fri, Sep 11, 2015 at 5:32 PM, Jennifer Thibault <notifications@github.com
> wrote:

> This is happening on a few pages that stem from the checklist. We need to
> take a pass at formatting them all—I believe they are all unstyled right
> now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC-web-app/issues/632#issuecomment-139692371>
> .
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146

**Comment by AmyKort** [comment]
Thanks!
