### ISSUE TITLE
Text change in alert link on search for candidates and election by location

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC-web-app#633]
Detail patrol:

On Search for candidates and election by location:
In the alert for a zip code that has multiple district, change link styling to keep it short, hide the `http://www.`, and capitalize "House"

Current:
Find your district on [https://www.house.gov](https://www.house.gov).

Change to:
Find your district on [House.gov](https://www.house.gov).
@emileighoutlaw is the capitalization of "House" correct here?

<img width="496" alt="screen shot 2015-09-11 at 10 11 06 am" src="https://cloud.githubusercontent.com/assets/11636908/9817008/6e1ebc7c-586e-11e5-894c-2b7d39f639e9.png">

**Comment by emileighoutlaw** [comment]
@jenniferthibault There's shockingly little guidance out there on capitalizing URLs.  There's a lot of story here, but tl;dr 18F style is: `Find your district on house.gov`

And "Zip code" should be "ZIP code."
