### ISSUE TITLE
Fix pagination on outside spending tab

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC-web-app#635]
The left/right buttons are loading and working, but the page numbers (1, 2, 3, 4) are not. See bottom right of screenshot below

https://fec-dev-web.18f.gov/elections/president/2016/?tab=spending

![screen shot 2015-09-11 at 10 27 15 am](https://cloud.githubusercontent.com/assets/11636908/9817251/bf10c034-586f-11e5-9f8b-a749b0898a24.png)

**Comment by jmcarp** [comment]
This seems to be intentional (we're specifying `pagingType: 'simple'` on those tables), but I'm not sure why we're doing it. @noahmanger, is it better to hide page number buttons on the "other spending" tables?

**Comment by noahmanger** [comment]
I don't remember making a conscious decision to do that, but if I did it
would've just been to reduce clutter. I'm fine with either approach.

On Fri, Sep 11, 2015 at 9:13 AM, Joshua Carp <notifications@github.com>
wrote:

> This seems to be intentional (we're specifying pagingType: 'simple' on
> those tables), but I'm not sure why we're doing it. @noahmanger
> <https://github.com/noahmanger>, is it better to hide page number buttons
> on the "other spending" tables?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC-web-app/issues/635#issuecomment-139588527>
> .
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146

**Comment by jmcarp** [comment]
Ambien paging™

**Comment by jmcarp** [comment]
More seriously, we need to use simple paging (back and forward, but no page numbers) for the very large tables (itemized receipts and disbursements), since the database doesn't support arbitrary page selection in those cases. I'm wondering whether we copied that setting from the itemized tables to other tables that do support paging by number. Maybe we should allow paging by number for all tables that support it on the backend. What do you think @jenniferthibault?

**Comment by jenniferthibault** [comment]
To recap our convo and make sure I understand it right, we're going to:
 - Only offer paging by number on browse data tables. Else, they'll just have the forward page/backward page button. 

Is that right @jmcarp ? or do i have that reversed?

**Comment by jmcarp** [comment]
That's my understanding @jenniferthibault. Just filed these changes in #660.
