### ISSUE TITLE
Need bullets on Mandatory electronic filing page

### ISSUE THREAD

**Issue by AmyKort** [18F/openFEC-web-app#636]
For all other filers, electronic filing is required if you meet any of the following criteria:

   [Bullet] You’ve raised or spent more than $50,000 this calendar year.

  [Bullet]  You raised or spent more than $50,000 in either of the last two calendar years.

    [Bullet] You’re a new committee, and at the end of the first quarter you’ve raised or spent more than $12,500.

   [Bullet]  You’re a new committee, and halfway through the calendar year you’ve raised or spent more than $25,000.

And again:

There is an exception to the mandatory e-filing requirement for filers that meet all three requirements below:

   [Bullet]  The committee anticipates terminating before the next election year,

   [Bullet]  The committee’s candidate hasn’t qualified (and doesn’t intend to qualify) as a candidate in the next election, and

   [Bullet]  The committee has $50,000 or less in net debts by January 1, the year after an election.

**Comment by emileighoutlaw** [comment]
done
