### ISSUE TITLE
Language Change on File by Paper page

### ISSUE THREAD

**Issue by AmyKort** [18F/openFEC-web-app#637]
On the file by paper page, the address for House candidates should be changed to delete "Electronic Filing Office."

"House candidate committees submit reports to:

Electronic Filing Office [Delete this line from the address]

Federal Election Commission

999 E Street, NW

Washington, DC 20463"

**Comment by amypike** [comment]
I think @emileighoutlaw made this language change on Tuesday afternoon, after the presentation run-through.

**Comment by emileighoutlaw** [comment]
Indeed!
