### ISSUE TITLE
Missing word and chart on Learn More about Quaterly Reporting Page

### ISSUE THREAD

**Issue by AmyKort** [18F/openFEC-web-app#639]
Last paragraph needs a "the":

You’ll file quarterly reports even if your candidate retires, withdraws, loses the primary or otherwise drops out of [the] race before the general election.

Also--for me, the formatting on this page doesn't work. I think the list of reports/dates was supposed to be a chart, not a list

**Comment by noahmanger** [comment]
Oh yep. The problem is that the CMS doesn't currently support doing table layouts, but we're going to add it. Thanks for reminding!

**Comment by AmyKort** [comment]
Thanks--I'll stop flagging those.

**Comment by noahmanger** [comment]
Please do keep flagging anything with spelling issues though!

On Fri, Sep 11, 2015 at 9:22 AM, AmyKort <notifications@github.com> wrote:

> Thanks--I'll stop flagging those.
>
>
>
> From: Noah Manger <notifications@github.com>
> To: 18F/openFEC-web-app <openFEC-web-app@noreply.github.com>,
> Cc: AmyKort <akort@fec.gov>
> Date: 09/11/2015 12:21 PM
> Subject: Re: [openFEC-web-app] Missing word and chart on Learn More
> about Quaterly Reporting Page (#639)
>
>
>
> Oh yep. The problem is that the CMS doesn't currently support doing table
> layouts, but we're going to add it. Thanks for reminding!
> ?
>
> Reply to this email directly or view it on GitHub.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC-web-app/issues/639#issuecomment-139590484>
> .
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146

**Comment by emileighoutlaw** [comment]
Seconding what Noah said about missing words and spelling issues @AmyKort ! I'll go in and fix them wherever you find them!

**Comment by emileighoutlaw** [comment]
Actually, since this page is in Wagtail, can you fix the missing `the` @noahmanger ?

**Comment by emileighoutlaw** [comment]
(or let me know how to get in for edits?)

**Comment by noahmanger** [comment]
Oh yeah! I'll show you tomorrow.

On Mon, Sep 14, 2015 at 8:26 AM, Emileigh Barnes <notifications@github.com>
wrote:

> (or let me know how to get in for edits?)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC-web-app/issues/639#issuecomment-140115572>
> .
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146

**Comment by emileighoutlaw** [comment]
Added the word in!
