### ISSUE TITLE
Fundraising Comparison for Presidential Election

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#648]
The list of Candidates to Compare is ordered according to top receipts. It looks like it is in columns, so you want to read down the columns. Clinton first, then Bush.  But, the right order is when you read across. We found this confusing. Also, on the presidential map, we put the dollar amount next to each name so people understand why candidates are presented in a particular order. We think this would help to clarify the order in the Candidates to Compare list as well

![pres-compare](https://cloud.githubusercontent.com/assets/11817734/9828446/6fa9a4d8-58bb-11e5-8229-a6be88609ccb.png)

**Comment by jenniferthibault** [comment]
Ohhh interesting. Do we want to list them here in order of receipt amount, or alphabetical?

**Comment by AmyKort** [comment]
Either is fine. I think we want to be consistent and make it readily clear what the logic is. If we do order them by receipt amount, I think it really helps to have the $ total next to the candidate.
