### ISSUE TITLE
So users understand the elections page Fundraising Comparison Map, alter the way candidates are added to comparison

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#650]
We found the map options confusing. It defaults to Clinton, and if you just press the “add candidate” button and don’t do the drop down, it adds Sanders. It isn’t at all clear that the logic for these choices is based on fundraising totals.  Even if I deselect Clinton the map of her financial activity is the first to appear.  

https://fec-dev-web.18f.gov/elections/president/2016/

![map-compare](https://cloud.githubusercontent.com/assets/11817734/9828527/a7e2bcc6-58bc-11e5-9780-c7d1ec6c5c8a.png)

**Comment by noahmanger** [comment]
Cool. We were just talking about this today. @jenniferthibault has some new suggestions here: #645

**Comment by jenniferthibault** [comment]
Yes! :+1:

**Comment by noahmanger** [comment]
Duplicate issue.
