### ISSUE TITLE
To accurately label the contributor location table, rework the "state" column

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#651]
Contributor Table—Location
If the label is “State,” then the things listed underneath that table need to be states (or DC). This list includes military postal codes and U.S. Territories—confusing, especially if these codes come up first. On the Candidate Viewer, we sum all of those and classify them as other. Additionally, we found the sort function confusing. The up arrow for the states organizes them A-Z (top to bottom) but the top arrow for the dollar amounts organizes them $0 to $1,000,000 (bottom to top). I don’t think this is intuitive for the way people think of how to put things in order. I’d have the top arrow arrange dollar amounts from highest to lowest. In any case, when you put the alphabetical list next to the dollar amount list, the arrows become confusing.

https://fec-dev-web.18f.gov/elections/president/2016/

![states](https://cloud.githubusercontent.com/assets/11817734/9828559/459a6608-58bd-11e5-9bf2-e6c2d1556b39.png)

**Comment by noahmanger** [comment]
Changed the title to reflect the need to clean up the language for the state column, either by:
- Changing the label to something other than "State"
- Or combining / removing territories and non-state geographies

As for the sort arrow question, in both cases the up arrow signifies "ascending" (lowest value to highest). It's kind of weird, but I don't believe we've heard from other users that it poses a significant challenge. But if we want to redesign we can make a separate issue.
