### ISSUE TITLE
Change Tab Name - Outside Spending

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#652]
If we are including this in the demo the tab name needs to be changed from "Outside Spending" to "Other Spending."  

https://fec-dev-web.18f.gov/elections/president/2016/

![other-spend](https://cloud.githubusercontent.com/assets/11817734/9828597/bb428b38-58bd-11e5-9f46-4725e8a64866.png)

**Comment by noahmanger** [comment]
Ah, thanks. This is addressed in an upcoming PR.

**Comment by PaulClark2** [comment]
:thumbsup:

**Comment by jmcarp** [comment]
Done in #662.
