### ISSUE TITLE
File by Paper page Fixes

### ISSUE THREAD

**Issue by AmyKort** [18F/openFEC-web-app#656]
https://fec-dev-cms.18f.gov/registration-and-reporting/file-paper/

"Always retain proof of mailing and delivery." (insert "of")

Paper copies for House and Presidential candidates are not submitted to the t E-file office and do not need to be addressed to any specific office.

There are two addresses for Senate candidate - one for hand delivery and the other for courier/express delivery (e.g., Fed Ex).  See Candidate Guide, p. 80 and 11 CFR 105.2

Mail in their original Forms 1 and 2 to
the Secretary of the Senate, Office of Public Records,
P.O. Box 77578, Washington, DC 20013-7578.

The address for courier or express delivery
is 232 Hart Senate Office Building, Washington, DC
20510-7116.

Also, "FEC staff convert each paper-filed form (3, 3L, 3X, 5, 6, 7 and 24-hour and 48-hour independent expenditure reports) to a .fec file."  What about form 9s? 

@emileighoutlaw

**Comment by emileighoutlaw** [comment]
Addressed
