### ISSUE TITLE
"Electronic Filing" Page Fix

### ISSUE THREAD

**Issue by AmyKort** [18F/openFEC-web-app#657]
https://fec-dev-cms.18f.gov/registration-and-reporting/file-electronically/

"You should expect to receive this within a few minutes of submission — contact our Electronic Filing Office if you don’t. "  Let's insert the e-file office telephone number here.  (202) 694-1307.

@emileighoutlaw

**Comment by emileighoutlaw** [comment]
I think we're trying to keep contact info only on the Contact Us page. How about if we hyperlink "Electronic Filing Office" to our "Contact Us" page? @noahmanger

**Comment by emileighoutlaw** [comment]
Added hyperlink.
