### ISSUE TITLE
Add Comma Administrative Fine Page

### ISSUE THREAD

**Issue by AmyKort** [18F/openFEC-web-app#658]
https://fec-dev-cms.18f.gov/registration-and-reporting/administrative-fines/

The committee couldn’t file because of unforeseen circumstances beyond its control and, when those circumstances ended, the committee filed the late report within 24 hours. This is also called the “best efforts” defense. (insert comma after ended)

@emileighoutlaw

**Comment by emileighoutlaw** [comment]
added.
