### ISSUE TITLE
As a person navigating the site, I would like the icons to be linked buttons as well as the text

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC-web-app#663]
This bug came from last week's usability tests, where a user clicked repeatedly on the circle illustration expecting it to act as a linking button. When the icon did not respond to a click, the user thought that the page wasn't working.

<img width="168" alt="screen shot 2015-09-14 at 2 29 54 pm" src="https://cloud.githubusercontent.com/assets/11636908/9858193/52df382a-5aed-11e5-95d2-d27b80439bdb.png">

Linking both the text and the icon will allow a larger click surface area, and bring the interaction more in line with users' mental models of how these icons work.

cc @onezerojeremy to make sure I've expressed this correctly, and @noahmanger for imlpementation

**Comment by onezerojeremy** [comment]
Yes! Thank you for filing it for me. There's some question if they are
viewing the whole crimson card as a button or just the icon and text. I
think we can try either way, and probably resolve it with hover effects.

**Comment by noahmanger** [comment]
Makes sense! I'll fix it. I've had the same question about whether or not we should have the card be a button or not.
