### ISSUE TITLE
Fix or remove cycle select for electioneering and communication cost committees

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC-web-app#664]
While discussing #653, we noticed that the cycle select dropdown isn't right for electioneering and communication cost committees. We currently identify the relevant election cycles for a committee using F1 and F3 filings, but these committees may rarely file F1 forms and never file F3 forms. I see two non-exclusive fixes here:

* Fix election cycles for electioneering and communication committees in the API
* Remove the cycle select for the committees, since they rarely include a large enough number of filings for filters to be useful.

Seems like we should definitely do the first part, but I'd like to get feedback on the second. Pinging @noahmanger @LindsayYoung.

**Comment by LindsayYoung** [comment]
Would it simply things for committee drop-downs if we only look to see if anything comes up in the filings table for that cycle? Would that work for candidates too?

That would also fix the random F1z adding weird years such as 1988 to Trump's page http://localhost:3000/candidate/P80001571

**Comment by noahmanger** [comment]
Would that solve the above problem? Either way it makes sense to me.
