### ISSUE TITLE
As a user with opinions about your code, I'd like to visit your repo from the home page and make my opinions known. 

### ISSUE THREAD

**Issue by onezerojeremy** [18F/openFEC-web-app#668]
Currently, we mention that we're listening on Github, but provide no link to it from the "What's next" box. 
URL: https://fec-dev-cms.18f.gov/
<img width="1076" alt="screen shot 2015-09-14 at 10 29 56 pm" src="https://cloud.githubusercontent.com/assets/474916/9866437/448722a4-5b30-11e5-8afa-711af7c08a9f.png">

**Comment by noahmanger** [comment]
Fixed.
