### ISSUE TITLE
Post beta release design consideration: big picture presentation of the current Campaign Finance activities

### ISSUE THREAD

**Issue by wluoFEC** [18F/openFEC-web-app#670]
The open.fec.gov lacks the big picture presentation/Visualization of the current Campaign Finance activities, such as presential and House/Senate Maps and Charts FEC.gov currently has. 
![image](https://cloud.githubusercontent.com/assets/7440932/9881811/9dc94fb2-5b9f-11e5-85da-4741efabb1d6.png)

![image](https://cloud.githubusercontent.com/assets/7440932/9881829/aa31042a-5b9f-11e5-8c3d-65c94eff0149.png)

![image](https://cloud.githubusercontent.com/assets/7440932/9881850/c73e33a8-5b9f-11e5-96f8-55d5f4c10c6f.png)

**Comment by noahmanger** [comment]
This is captured in the story map so I'm closing out here.
