### ISSUE TITLE
Review casing on candidate pages

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC-web-app#672]
While looking at an unrelated issue, I noticed that lots of text on the candidate detail page Capitalizes Every Word ("Combined Financial Totals", "Ending Cash on Hand", etc.). This doesn't seem to be consistent with newer text. Should these be lower-cased @emileighoutlaw?

<img width="994" alt="screen shot 2015-09-15 at 4 13 45 pm" src="https://cloud.githubusercontent.com/assets/1633460/9888801/105390c2-5bc5-11e5-8637-7860d1876920.png">

**Comment by emileighoutlaw** [comment]
It should be! I'm on it. Good catch. :)
