### ISSUE TITLE
Consider removing occupation and employer columns

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#680]
We can't sort by occupation or employer on /receipts and they're being squished severely, so I think we may as well just remove them. Thoughts?

**Comment by wluoFEC** [comment]
This is one of features people really want.  we should consider to keep it if we can.

**Comment by LindsayYoung** [comment]
We needed to modify it for the presentation, We can always change things back, We do still have full text search on both fields. We could also try out different things, like displaying them together--  employer, occupation (in cases were they are not blank or repeated.)

**Comment by noahmanger** [comment]
I'm going to consider this a sub-issue of #815 and close it out.
