### ISSUE TITLE
Link to Definition of Candidate on Registration and Reporting Page

### ISSUE THREAD

**Issue by AmyKort** [18F/openFEC-web-app#687]
Can you link to the glossary definition of candidate on the Registration and Reporting page when"

*Candidates* are people running for elected federal office. Federal office is the House of Representatives, the Senate, or the office of the president.

*Candidates* must designate at least one campaign committee. These authorized groups are called candidate committees.

@emileighoutlaw

**Comment by emileighoutlaw** [comment]
Done!
