### ISSUE TITLE
Figure out a "messy data warning" pattern

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#689]
We need a way to warn users when data may be messy or inconsistent, and provide an explanation for why that may be.

**Comment by jmcarp** [comment]
For example, computed versus reported fundraising aggregates are likely to be a least a little different. Related to this, we may want to add notes on methodology for interested users--e.g., how exactly do we compute aggregates?

**Comment by noahmanger** [comment]
Depending on how long those notes on methodology are, it could really be a set of pages on the website. Kind of an in-depth data glossary.

**Comment by noahmanger** [comment]
Thinking more about this I like the idea of some sort of icon + tooltip pattern. The meaning we're trying to convey, as I understand it, includes:

- Warn users of any time when we make complicated judgement calls (e.g. the Unique Only filter on receipts)
- Warn users when aggregates are based on free-text or otherwise ambiguous data (e.g. the disclaimer at the bottom of the aggregate Disbursements By Purpose table on committee pages)

I think in cases where we have the real estate, such as the By Purpose table, we can simply display the text, but I think it would be good to have it accompanied by the icon. In other cases, such as with a filter, it's good to display it with a tooltip, but again, might be helpful to have an icon in the filter label.

I'm not sure if the what we're going for is more "warning" or more "methodology explanation", so not certain on the right approach to iconography, but would love @jenniferthibault thoughts on this.

**Comment by noahmanger** [comment]
Usability note: in the case of the "Show Unique" filter, it would be nice to have the tooltip show when an icon is focused / hovered, rather than the field or label itself, so that it doesn't obscure other filters. (See discussion here https://github.com/18F/fec-style/pull/101)

**Comment by jenniferthibault** [comment]
@noahmanger, what about this icon with this tooltip implementation?

![screen shot 2015-09-23 at 1 45 32 pm](https://cloud.githubusercontent.com/assets/11636908/10053316/63070170-61f9-11e5-824f-cfa09d5cd145.png)

![screen shot 2015-09-23 at 1 44 19 pm](https://cloud.githubusercontent.com/assets/11636908/10053294/44087240-61f9-11e5-8103-d1207e524fa7.png)

**Comment by noahmanger** [comment]
I like the icon. But would we want to use the same one in the alerts that we're using elsewhere on the filters (where we currently use the exclamation point icon)?

**Comment by jenniferthibault** [comment]
I was thinking that "alert" and "more information" were different kinds of info, and should have different icons. The interactions are also a little different, where here you interact with the icon, and an alert is presented to you without your interaction.
I may be misunderstanding though, do you mean the exact same icon should be used, or a more similar icon style?

**Comment by noahmanger** [comment]
Hmm. Just to think this through out loud here: 

The "alerts" here aren't actually alerting to something "new" or a difference in state. It's not that something has changed or that you stumbled on a particular edge case (unlike the "No data" messages when you go to a committee that hasn't filed reports or if there's an error in loading data for a table).

In this case, the messages are more about providing additional information and context to what you're looking at. And because it's the same type of contextual info that the tooltips offer, it makes me think that we should make the two feel like the same thing.

Does that make sense? Certainly open to args for the contrary.

**Comment by jenniferthibault** [comment]
I think it makes sense. What I'm hearing is that instead of using the "alert" pattern in the disclaimers in #736 (which is what the latest mockup shows), we should possibly be using this tooltip pattern for the disclaimers. Is that right?

Glad to talk this one out in a video chat, I think we're close @noahmanger .

**Comment by jenniferthibault** [comment]
A quick call figured this out! Solution: what's happening here is ok and great, but what needed to happen was just switching the exclamation point mark in #736 with a matching "i" info mark so that the cue was the same.
