### ISSUE TITLE
So that users can more easily explore different districts from the elections page, make districts in map clickable

### ISSUE THREAD

**Issue by wluoFEC** [18F/openFEC-web-app#691]
1) the highlighted district shows as clickable, however, nothing happened when I clicked on it. (screen shot).  
2) It would be nice for users to be able to click on the other districts to view the elections for the selected districts.
![image](https://cloud.githubusercontent.com/assets/7440932/9909383/f7d1a542-5c65-11e5-8999-d716141df852.png)

**Comment by noahmanger** [comment]
Storymap card: https://18f.storiesonboard.com/m/fec/!card/5958-T-XbVEZKznUD8RvAQ
