### ISSUE TITLE
In order to show users where the data is coming from, link to the details from the summary number on the 2016 presidential election

### ISSUE THREAD

**Issue by wluoFEC** [18F/openFEC-web-app#697]
I really like the summary number on the 2016 presidential election. Can we link the summary number to the detail data page?

![image](https://cloud.githubusercontent.com/assets/7440932/9910630/0fbf2d68-5c6c-11e5-8400-b61b4e771191.png)

**Comment by jenniferthibault** [comment]
To do: figure out where each number should link to (form type) then where each should direct. @lindsayyoung to maybe think about it if she has time

**Comment by LindsayYoung** [comment]
The disbursements and expenditures for the presidential race should link to new presidential reports:

https://fec-proxy.18f.gov/data/filings/?min_receipt_date=01-01-2015&max_receipt_date=12-31-2016&amendment_indicator=N&form_type=F3P

IEs link is trickier. We need to incorporate all the places where the IE summaries can be reported, so it should be limited to the new F5 and 3x forms.

https://fec-proxy.18f.gov/data/filings/?min_receipt_date=01-01-2015&max_receipt_date=12-31-2016&amendment_indicator=N&form_type=F3X&form_type=F5

Does that sound right to you, @PaulClark2?

**Comment by PaulClark2** [comment]
The F3P link seems right to me.   I'm not sure the IE link is helpful because it doesn't take you to IEs made for or against presidential candidates.  It takes you to F3X an F5 filings.
