### ISSUE TITLE
Implement "other spending" tab on candidate pages

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#700]
In order for users to see which other groups are making IEs for or against a candidate, we should show them on the candidate's page.

Question for @jenniferthibault and @onezerojeremy : do you think this should just be on a separate tab? We had previously tried to remove tabs from candidate pages but this might be a fine reason to bring them back.

**Comment by LindsayYoung** [comment]
I think that is important to separate out, since this is spending affecting a candidate and not spending the candidate is legally responsible for.

**Comment by AmyKort** [comment]
I agree with Lindsay that, however we do this, we need to strongly separate IE spending from the candidate's funds--lots of markers to make that distinction. Thanks!

**Comment by noahmanger** [comment]
+1

**Comment by jenniferthibault** [comment]
+1 as well

**Comment by onezerojeremy** [comment]
Agree on the separation. I also want to call out that usability testing has
indicated the candidate page is the second place people look, after trying
in committee browse first.

(But that should be a separate issue)

**Comment by jenniferthibault** [comment]
To do: Just adding independent expenditures in a table on a new tab with all the same columns except for candidate.

**Comment by onezerojeremy** [comment]
Usability testing is indicating that users aren't associating "Other Spending" with the data that will be available on that tab, and therefore aren't clicking. They also don't reliably associate "Independent Expenditures" with Super Pacs. 

Task: 
How would you find which Super PACs are supporting or opposing Hillary Clinton?
User 1, relatively new to campaign finance:
>"I don’t know, but that’s actually the kind of stuff I want to find."
[on the candidate's page, scrolling around for Super PACs]
>"Okay so how would I find Super PACs? I guess this is just the one committee? Hillary for America is the Super PAC? It’d be nice to see like something that designates the key, like if Hillary for America is the Super PAC or if it’s a 501C or a different type of PAC? I still have no idea. Oh that’s her principal campaign committee. I don’t know if that means Super PAC."
User 2, campaign finance professional:
>“Other spending? It’s not very intuitive. You would think that means because you’re on the Hillary Clinton page you’d think that’s other spending by the candidate or the candidate’s committee."

Don't have good instincts on what to call it (that will pass legal muster); recommend we keep gathering data for now, but it's strikes me that our language isn't matching user expectations yet.

**Comment by AmyKort** [comment]
That's really interesting feedback, I'll get with the FEC team and start coming up with some options to test in the future. Thank you.

**Comment by noahmanger** [comment]
I think the solution is in both redesigning the places where this "other spending" data shows up (like the committee browse page and committee pages, as you reference in other issues), as well as coming up with a better label for the tab. I'm going to break the tab issue out into its own issue and copy your comment there.
