### ISSUE TITLE
There is an expectation that the committee information will be on the committee profile page. We need to figure out a solution for showing "Other spending" aggregates on committee pages

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#701]
In order for users to have a comprehensive understanding of the IEs, ECs or communication costs that name a committees make, we should show those "Other spending" categories aggregated by the candidate they name and if it's in support of or opposition to that candidate. 

This allows the user to see an "other spending" aggregate on an election or candidate page, and then click through to that committee to see who all they've been supporting or opposing. 

This needs some design work to figure out how this piece lives on these pages and what the rules are.

**Comment by jmcarp** [comment]
Was this issue referring to the other spending tab on the candidate page or the committee page? We added the first but not the second.

**Comment by noahmanger** [comment]
Oops! I misread.

**Comment by noahmanger** [comment]
Card: https://18f.storiesonboard.com/m/fec/!card/vfBqyymmLoMAzznTwluFuw

**Comment by noahmanger** [comment]
Duplicate of https://github.com/18F/openFEC-web-app/issues/978
