### ISSUE TITLE
betaFEC feedback email

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#709]
We need to change the contact / feedback email address currently on betaFEC from info@fec.gov to betafeedback@fec.gov

**Comment by noahmanger** [comment]
To be clear: are we replacing all of the 18f-fec@gsa.gov email addresses with this as well? Seems like there should be a consistent email address for feedback.

**Comment by PaulClark2** [comment]
This might be a @wluoFEC and @leahbannon question but I agree we should be consistent.

**Comment by leahbannon** [comment]
That's fine by me
