### ISSUE TITLE
Make it easy to pass multiple args for the same filter in url_for()

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#714]
On the data landing page we want to link to /committees filtered down to all PACs and all IE committees. But the `url_for()` function doesn't currently accept multiple instances of the same filter argument. 

![screen shot 2015-09-18 at 10 36 11 am](https://cloud.githubusercontent.com/assets/1696495/9966724/4c2528c4-5df3-11e5-893c-d0e768d56d04.png)

**Comment by jmcarp** [comment]
That's because `url_for` is a Python function, and Python doesn't let you repeat function arguments. Try passing a list instead:
`url_for(candidate_id=['C001', 'C002', ...])`

**Comment by noahmanger** [comment]
Oops. That works. Thanks.
