### ISSUE TITLE
beta.fec.gov bookmark icon on iPhone's homescreen 

### ISSUE THREAD

**Issue by wluoFEC** [18F/openFEC-web-app#721]
Design an FEC bookmark icon for beta.fec.gov on iPhone's homescreen.  

![image](https://cloud.githubusercontent.com/assets/7440932/9993832/ee738246-6047-11e5-90de-4e74f20a6a2b.png)

**Comment by noahmanger** [comment]
Thanks for the reminder! This will actually be captured here: https://github.com/18F/openFEC-web-app/issues/718. I'll add a note to make sure we get it, but then closing this issue.
