### ISSUE TITLE
add link to pdf for receipts and disbursements

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC-web-app#726]
In the panel view it would be great to have a link view the source.

Here is an example pattern for lining to a particular page:
http://docquery.fec.gov/pdf/718/201507159000204718/201507159000204718_000002.pdf

**Comment by PaulClark2** [comment]
You can also use this pattern:  http://docquery.fec.gov/cgi-bin/fecimg/?201507159000204719

I'll ask EFO which is better and if there are any pitfalls for either pattern.
