### ISSUE TITLE
Content: beta content warning

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/openFEC-web-app#727]
Warning that content is in beta.

Document here: https://docs.google.com/document/d/1-mOlrfxv5vM2fuVSk6jk7OAk4vdtQ5uxKQHjG-GuLrI/edit
 * [x] Draft content
 * [x] Amy review

**Comment by noahmanger** [comment]
Is this still relevant?

**Comment by emileighoutlaw** [comment]
Yeah — depending on how they want to launch the registration and reporting side. This has been drafted. I'll link to it here in a sec.

**Comment by emileighoutlaw** [comment]
@amypike @amykort: Are we still needing to put this up with our OGC-approved `Registration and reporting` pages? If so, is the text we reviewed in October good to go? I can re-email it to y'all if you want to look again.

Next steps:
 * [ ] Determine if this necessary to launch content 
 * [ ] Final Amy approval
 * [ ] Talk to @jenniferthibault and @noahmanger about the best way to design and implement this

**Comment by emileighoutlaw** [comment]
Closing in favor of https://github.com/18F/fec-cms/issues/155
