### ISSUE TITLE
To simplify code and make for a speedier user experience, load candidate detail data client-side

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC-web-app#729]
We're now loading most data from the browser, but the candidate detail page is still loaded server-side. We should refactor this page to fetch data directly from the API via AJAX.

Part of #393.

**Comment by noahmanger** [comment]
Card: https://18f.storiesonboard.com/m/fec/!card/9vuPRVIC47rHnDnUEHzR2Q
