### ISSUE TITLE
Filings panels missing data

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#734]
On http://localhost:3000/committee/C00370007?tab=filings : the first three reports do not have data in their panels. The others do. This happens on other pages as well, but this is a good example. Despite having numbers for those fields on the reports, this data is consistently missing when trying to view the panel for these.

**Comment by jmcarp** [comment]
I found a few different things going on here. @noahmanger: after we merge 18F/openFEC#1224 and #734, can you verify that this is working as expected?

**Comment by noahmanger** [comment]
Fixed!
