### ISSUE TITLE
Bad receipt + disbursement date data

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#735]
On both receipts and disbursements, if you clear the date filters and sort by date (both ascending and descending) you're shown transactions both very far in the future (2100s) and very far in the past (as far back as 1800s).

**Comment by jmcarp** [comment]
This issue comes up for lots of data types here (remember the kid who filed for President in 2044?). Seems like we have a choice between showing all the data (which includes the fake stuff), and all the plausible data. If possible, it would be good to take a consistence stance on this--if we hide implausible disbursements, we should probably also hide implausible candidates.

**Comment by PaulClark2** [comment]
I put this Slack to but it might be useful here, too.  Also we can look at other schedules and form tables.

Looking at the SA table in goldengate.open.fec it looks like we only have 133 transactions that are either before 1972 or after 2015. I think that set is small enough we could review that and correct any that are data entry errors.

select * from SCHED_A  where extract(year from CONTB_RECEIPT_DT) < 1972;
58 rows

select * from SCHED_A  where extract(year from CONTB_RECEIPT_DT) > 2015;
75 rows

**Comment by noahmanger** [comment]
Do you expect these to be one time data errors that your system is now
catching from this point on? Or could they still happen in the future?

On Wed, Sep 23, 2015 at 9:59 AM, Paul Clark <notifications@github.com>
wrote:

> I put this Slack to but it might be useful here, too. Also we can look at
> other schedules and form tables.
>
> Looking at the SA table in goldengate.open.fec it looks like we only have
> 133 transactions that are either before 1972 or after 2015. I think that
> set is small enough we could review that and correct any that are data
> entry errors.
>
> select * from SCHED_A where extract(year from CONTB_RECEIPT_DT) < 1972;
> 58 rows
>
> select * from SCHED_A where extract(year from CONTB_RECEIPT_DT) > 2015;
> 75 rows
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC-web-app/issues/735#issuecomment-142610019>
> .
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146

**Comment by PaulClark2** [comment]
These types of errors could happen in the future --- filer errors and data entry errors.

**Comment by noahmanger** [comment]
Cool. So might be good to build some logic in to our system just to flag it
down the road. I have no idea what this would look like, but just a thought.

On Thu, Sep 24, 2015 at 11:24 AM, Paul Clark <notifications@github.com>
wrote:

> These types of errors could happen in the future --- filer errors and data
> entry errors.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC-web-app/issues/735#issuecomment-142962293>
> .
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146

**Comment by noahmanger** [comment]
Storymap card: https://18f.storiesonboard.com/m/fec/!card/hbgu5GvJC_3_gznUD8RvAQ

**Comment by jmcarp** [comment]
It doesn't sound like there's technical work to be done here, so I'm going to reassign to @noahmanger to figure out what action to take, if any.
