### ISSUE TITLE
Add disclaimer to /receipts + /disbursements about how far back data goes

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#736]
We need to specify on each page how far back the available data goes. And eventually would be good to add validation to the date fields so you can't set a date before the earliest limit.

**Comment by PaulClark2** [comment]
:+1: this was a clear takeaway from our meeting with the Commissioners yesterday

**Comment by noahmanger** [comment]
Great. I think I'd elevate a short-term solution (such as a simple text explanation on this page) to launch critical, but ideally it would be great to:
- Have form validation on the date filters
- If you're looking for an aggregate before the period where we show individual transactions, don't link to the the transactions

Moving this to this sprint. @emileighoutlaw and @LindsayYoung can you figure out language? @jenniferthibault where do you think it should go?

**Comment by LindsayYoung** [comment]
I can take this. I am coordinating with Emileigh.

**Comment by jenniferthibault** [comment]
On these browse pages, right?
https://fec-dev-web.18f.gov/receipts
https://fec-dev-web.18f.gov/disbursements

 @LindsayYoung / @emileighoutlaw if you can give me an idea of what the text will be, I'm glad to do a quick mockup, but placement will be determined by what it's saying

**Comment by jenniferthibault** [comment]
@LindsayYoung 's #746 places these content bits in the filter list here:

![screen shot 2015-09-23 at 8 05 44 pm](https://cloud.githubusercontent.com/assets/11636908/10062233/9663e238-622e-11e5-8d10-bb8537ccec39.png)

I would slightly re-group the elements in the list, and use an alert style pattern, like so:
![screen shot 2015-09-23 at 8 07 51 pm](https://cloud.githubusercontent.com/assets/11636908/10062261/ce726816-622e-11e5-8796-95c767f8b872.png)

What do you think @noahmanger ?

**Comment by PaulClark2** [comment]
I like this as it informs the user upfront the scope of the data.    

Can we also remind the user on the "results" page what filters they have applied.  

For example, I searched for receipts from Alabama >= $2,000.00
![receipts-header](https://cloud.githubusercontent.com/assets/11817734/10072591/ee8e0b98-6290-11e5-92aa-0775b9c16f21.png)

Perhaps using commerce sites as a model?  
![example-commerce](https://cloud.githubusercontent.com/assets/11817734/10072616/1e7a7be8-6291-11e5-98a0-c36e9193e311.png)

@wluoFEC @amykort

**Comment by AmyKort** [comment]
I agree--adding some information to the page to remind users of what filters they've applied is important. Even though it's in the URL, people don't think to look there. I'm happy with the suggested text above to say that results only go back to 2011, etc. One question--maybe for later--is whether we're going to need some explanation for really strange dates that show up. For example, if we say that these records start in 2011, but someone mistakenly reported a 2110 date or a 1911 date it makes people think that the search results are wrong.

**Comment by emileighoutlaw** [comment]
Content-wise, I think this is a great idea! And simple. Just:

"XX of XXXX results for *term 1*, *term 2*, *term 3*."

I think we'd use commas for a list of items and colons for subsets of items.

**Comment by jmcarp** [comment]
For what it's worth, filters from the URL are automatically applied to the filter panel. So if the URL includes something like `cycle=2012&cycle=2010`, the 2012 and 2010 election cycle boxes in the filter panel will be checked. The filters also auto-submit on change, so the filter panel widgets will always be in sync with the table results. Is there an additional benefit of copying the filter logic from the filter panel to the adjacent table?

**Comment by AmyKort** [comment]
When we were playing around with the site, we kept collapsing the filter panel. Also, only some of the filter options were showing on the page view. So, looking to the filters wasn't easy.

**Comment by PaulClark2** [comment]
:+1:  @AmyKort .   I like @emileighoutlaw idea it's simple and clean.  

For example, it would help remind me I filtered on Alabama, >$2,000
![untitled](https://cloud.githubusercontent.com/assets/11817734/10079136/5ebf7440-62b6-11e5-8525-d7d5a3d7a118.png)

**Comment by AmyKort** [comment]
I also like @emileighoutlaw idea

**Comment by emileighoutlaw** [comment]
I've finally had a good idea! Hold on, I have to go call my mom and tell her.

**Comment by jenniferthibault** [comment]
Looks like we've moved into new issue territory! To keep things clean, I'm separating the thread from here so that this one focuses only on disclaimer language. To talk more on filter breadcrumbs/tags, (which I think @noahmanger will have interaction thoughts on, let's head on over to #754

**Comment by jenniferthibault** [comment]
Reopening so that the styling in this comment can be implemented:
https://github.com/18F/openFEC-web-app/issues/736#issuecomment-142765359

**Comment by jenniferthibault** [comment]
See this https://github.com/18F/openFEC-web-app/issues/689#issuecomment-143338009  for full history, but a small icon change here to use an `i` instead of `!`:

![i_alert_info](https://cloud.githubusercontent.com/assets/11636908/10114153/b5f0ad38-63ba-11e5-8963-86887196b912.png)
