### ISSUE TITLE
Committee links not working

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#737]
https://fec-dev-web.18f.gov/
![untitled](https://cloud.githubusercontent.com/assets/11817734/10030700/189277d0-6147-11e5-8b7e-29b06d48649b.png)

The  "All PACs active 2015-2016 »"  and "All independent expenditure committees active 2015-2016 »" links don't work.

**Comment by LindsayYoung** [comment]
These look like they are working now, @PaulClark2 can you confirm and close the issue when you get a chance?

**Comment by PaulClark2** [comment]
@LindsayYoung Yes the links are working
