### ISSUE TITLE
Datatable loading overlay misplaced for some tables

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC-web-app#739]
Tables with a scrolling body seem to show the loading overlay correctly, but other tables draw the loading overlay elsewhere on the page. For example, here's the loading screen on the committee detail aggregate by size:

<img width="1440" alt="screen shot 2015-09-22 at 6 23 02 pm" src="https://cloud.githubusercontent.com/assets/1633460/10033363/18f62d56-6157-11e5-9b25-0efad1f75b86.png">

**Comment by noahmanger** [comment]
I'm pretty sure this should be fixed in my last PR. I just had to add
position: relative to .dataTables_wrapper.

On Tue, Sep 22, 2015 at 6:24 PM, Joshua Carp <notifications@github.com>
wrote:

> Tables with a scrolling body seem to show the loading overlay correctly,
> but other tables draw the loading overlay elsewhere on the page. For
> example, here's the loading screen on the committee detail aggregate by
> size:
>
> [image: screen shot 2015-09-22 at 6 23 02 pm]
> <https://cloud.githubusercontent.com/assets/1633460/10033363/18f62d56-6157-11e5-9b25-0efad1f75b86.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC-web-app/issues/739>.
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146

**Comment by jmcarp** [comment]
Rad.
