### ISSUE TITLE
Change Glossary Definition for Independent Expenditure

### ISSUE THREAD

**Issue by AmyKort** [18F/openFEC-web-app#758]
@emileighoutlaw
Can we change the glossary definition of Independent Expenditure so that it matches the definition from the glossary of the June 2014 Candidate Guide?

Independent expenditure
An expenditure for a communication that expressly advocates the election or defeat of a clearly identified candidate and that is not made in cooperation, consultation or concert with, or at the request or suggestion of, any candidate, or his or her  authorized committees or agents, or a political party committee or its agents. 11 CFR 100.16.

**Comment by emileighoutlaw** [comment]
Can do! :)
