### ISSUE TITLE
Change Glossary Definition for Electioneering Communication

### ISSUE THREAD

**Issue by AmyKort** [18F/openFEC-web-app#759]
@emileighoutlaw
Can we change the glossary definition of Electioneering Communication so that it matches the definition from the June 2014 Candidate Guide?

Electioneering communication
Any broadcast, cable or satellite communication that:
•	Refers to a clearly identified candidate for federal office;
•	Is publicly distributed within certain time periods before an election; and
•	Is targeted to the relevant electorate. 11 CFR 100.29

**Comment by emileighoutlaw** [comment]
Of course! On it.
