### ISSUE TITLE
explanation on aggregates on committee page older that 2011

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC-web-app#772]
I know we talked about running the aggregates for older records and just calculating them once.That would be better. If we don’t do that, we should at least have text that we have not populated maps for older data, or something like that.

**Comment by LindsayYoung** [comment]
The same would go for the comparisons on the election pages.

**Comment by noahmanger** [comment]
Story - Understand the limits of our itemized data: https://18f.storiesonboard.com/m/fec/!card/e5abRHE1pjajIznUELlqgg
