### ISSUE TITLE
some links on committee browse broken

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC-web-app#773]
Links from committee browse page are giving all the cycles, and the page breaks if it does not have entries for all of those cycles.

http://localhost:3000/committee/C00587592/?cycle=2012&cycle=2014&cycle=2016
http://localhost:3000/committee/C00587717/?cycle=2012&cycle=2014&cycle=2016

**Comment by jmcarp** [comment]
Should be fixed in #765.
