### ISSUE TITLE
Broken links out to committees on committee transfer tab

### ISSUE THREAD

**Issue by konklone** [18F/openFEC-web-app#774]
On the ["Between committees" tab for a committee](https://fec-proxy.18f.gov/data/committee/C00548669/?tab=between-committees&cycle=2014), the link out to other committees is broken. The link shown here:

![image](https://cloud.githubusercontent.com/assets/4592/10119937/d6806de0-6473-11e5-9fc8-682e4e3041c2.png)

Links to:

```
https://fec-dev-cms.18f.gov/committee/C00420398/```
```

which is a 404. It could be that it's going out to `fec-dev-cms` instead of `fec-proxy`, because when I manually change it to:

```
https://fec-proxy.18f.gov/data/committee/C00420398/
```

It works fine.

**Comment by jmcarp** [comment]
Fixed in #765, along with many more broken links. Thanks for catching!
