### ISSUE TITLE
Fix "Invalid party code" and "unknown" status

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#775]
Not sure where these values come from, but if it's possible to fix, that would be great.

![screen shot 2015-09-26 at 3 16 28 pm](https://cloud.githubusercontent.com/assets/1696495/10120130/acb1839e-6461-11e5-8d2c-d81575bcfb3f.png)

**Comment by jmcarp** [comment]
This candidate (ID P60013265) has a `party_affiliation` of 999 and a `party_affiliation_desc` of "Invalid Party Code" in the `dimparty` table. But according to the candidate's F2, the correct party should be "IDP" / "Independence Party". @PaulClark2, can you look into this when you get a chance?

**Comment by PaulClark2** [comment]
There were 27 party codes missing from the DW table.  We've added them and they are in postgres now, too.

select * from dimparty where party_sk > 10000050;
select * from dimparty where party_affiliation = 'IDP';

**Comment by noahmanger** [comment]
Has this been resolved yet?

**Comment by jmcarp** [comment]
Looping back on this, I'm still seeing invalid parties in the database. @PaulClark2, am I looking in the wrong place? There's still a record in `dimparty` with a `party_affiliation_desc` of "Invalid Party Code", and about 1600 candidates are still linked to that party row. Here's a sample query:

```
select distinct(cand_id) from dimcand join dimcandoffice using (cand_sk) join dimparty using (party_sk) where party_affiliation = '999';
```

**Comment by PaulClark2** [comment]
This might require us to refresh CFDM (data warehouse schema) to get the new entries in the reference table to be applied to the correct rows in the various DIM tables.   I'll ask our DBA folks if they have other ideas.

**Comment by noahmanger** [comment]
This is now working 
![image](https://cloud.githubusercontent.com/assets/1696495/11083372/9dcfc9f8-87e3-11e5-8796-e0dbf72af97f.png)
