### ISSUE TITLE
To provide consistent experience across browsers, fix the "hide filter" button on firefox on linux

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC-web-app#791]
"Hide filter" cutoff in upper left 

![screenshot from 2015-09-29 11_12_27](https://cloud.githubusercontent.com/assets/4406333/10222359/72e2bf48-6821-11e5-8453-15ec3388ad74.png)

**Comment by LindsayYoung** [comment]
This was ice wheseal too

**Comment by noahmanger** [comment]
This is working on my version of Firefox. Moving to the icebox until we can verify it's still a problem.
