### ISSUE TITLE
Bug: To provide consistent experience across browsers, fix the select arrows on firefox on linux

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC-web-app#792]
![screenshot from 2015-09-29 11_00_38](https://cloud.githubusercontent.com/assets/4406333/10222439/f584786a-6821-11e5-9794-35517e81a944.png)

This shot was taken with Iceweasal/Firefox on Debian

**Comment by noahmanger** [comment]
As far as I can tell, `-moz-appearance` stopped working around version 30, but seems to be working now. I'm going to move this to the icebox until we can verify it's still a problem.
