### ISSUE TITLE
Variable coverage periods for candidate financial summaries

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#796]
Also see Slack (#fec-partners) conversation on 9/17/15

As a user I would like to see:
2-year financial summaries for house candidates
            regular general elections are predictable
4-year financial summaries for presidential candidates
            general election always predictable
6-year financial summaries for senate candidates
            senate class elections predictable

@jwchumley @LindsayYoung @jmcarp

**Comment by PaulClark2** [comment]
It might be useful to focus on regular elections first and then deal with house and senate special elections.   The coverage periods for regular elections are predictable.  

For example:  
House:	            2013-2014;  2015-2016;  2017-2018
President:          2009-2012;  2013-2016;  2017-2020
Senate class 1:  2007-2012;  2013-2018;  2019-2024 
Senate class 2:  2009-2014;  2015-2020;  2021-2026
Senate class 3:  2005-2010;  2011-2016;  2017-2022

**Comment by noahmanger** [comment]
This is captured in other issues with the wireframes. Closing it out.
