### ISSUE TITLE
In order to better understand the data for one's district, add office-holder information to election pages

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#799]
Lindsay, Josh, Jen and I just discussed a number of short-term fixes to election pages to prevent confusion and/or fix bad data. Please chime in if I'm missing anything:
- [ ] Show current officeholder on election pages: This will bring consistency to the election search results page.
- [ ] If possible, show _both_ current senators on election pages and search results, but make clear that only one is up for election
- [ ] Come up with a better name for "Current officeholder": On elections in previous cycles will show the person who held office at the time of the election, this is confusing to be called "Current" when really it's "Contemporary". @emileighoutlaw do you have thoughts?
- [ ] Figure out Olympia Snowe's 2011 election: Olympia Snowe's page has a link to the 2011 election, but that election has no data on it. Figure out what's going on here and if it's a pattern.

Missing anything?

**Comment by PaulClark2** [comment]
Snowe filed a F2 with 2011 as the election year:  http://docquery.fec.gov/pdf/351/11020371351/11020371351.pdf

**Comment by emileighoutlaw** [comment]
Hmm. Could you label the officeholder "officeholder" and the challenger "challenger" ?

**Comment by LindsayYoung** [comment]
We could add the year, so that it is explicit- "2012 office holder"

I am also looking at the Snowe data, I am looking to see if there is a better way of handling special elections that we could implement quickly.

**Comment by emileighoutlaw** [comment]
Yeah, I think `2012 officeholder` would be okay

**Comment by LindsayYoung** [comment]
I am going into more depth about Snowe, in 18F/openFEC#1248

**Comment by noahmanger** [comment]
Card: https://18f.storiesonboard.com/m/fec/!card/uJ4VWw-ewHuoXznTwnnq1g
