### ISSUE TITLE
Wireframe new cycle behavior

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#801]
Wireframe a solution to allow users to easily view Presidential and Senate financial summaries for the full 4 or 6 year cycle, respectively, while also allowing them to view the traditional 2-year periods. 

Decisions to make / questions to address:
- Does this advanced select only live on candidate pages? Or also their committee principal committee pages?
- How does this work with adjusting years on election pages?
- How does it balance the two methods we have for traversing time: choosing an election year and adjusting the date range for data viewed?

**Comment by noahmanger** [comment]
I've got wireframes for different approaches to this new time period select on InVision, as well as how it would work on candidate and election pages: https://invis.io/RE4GG62GB

After discussing with the team today, we're leaning towards going with Option A of a `<select>` with `<optgroup>`s to group two-year periods for each election year. 

But the plan is to test that against one or two of the other options as static prototypes this week. If this approach works, it's definitely simpler to implement. But I'm a little concerned it may be confusing, so it will be good to test.

Happy to walk through these more over video call on Wednesday if it's helpful.

**Comment by PaulClark2** [comment]
For the beta release we'll need to modify Option A so that for a Senate candidate the drop down menu would look like the one below. This should be the first option users are presented.  The default would be to the current full cycle.  We should include as many other options as the teams decide is useful to present to users. 

        **Full Cycle 2012**
        2011-2012
        2009-2010
        2007-2008
        **Full Cycle 2006**
        2005-2006
        2003-2004
        2001-2002

@wluoFEC @amykort @jwchumley @amypike 

https://github.com/18F/openFEC-web-app/issues/821

**Comment by noahmanger** [comment]
Just to clarify: are you saying for the release we need to *implement* this or simply update the wireframes to reflect this?

Second, are you saying that we don't include an option for "All: 2011 - 2016" and you want to use "Full Cycle 2016" to choose that time period?

**Comment by AmyKort** [comment]
Just update the wireframe to reflect this. And, yes, please go with the "Full Cycle 2016" language instead of the All: 2011 - 2016 language.

**Comment by AmyKort** [comment]
Also, Thank You!

**Comment by PaulClark2** [comment]
You're welcome Amy.  Again sorry I wasn't clear @noahmanger .  Like @AmyKort said we don't need to implement this we just need something folks can comment on.

**Comment by noahmanger** [comment]
This is resolved.
