### ISSUE TITLE
limit typeahead to statutory candidates.

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#804]
In addition to a statutory candidate filter on the candidates page, what do you think about limiting typeahead suggestions to those as well? 

Would be nice to not suggest garbage results:

[deleted screenshot...too crass. But just search "Trump" to see what I mean]

**Comment by noahmanger** [comment]
Posted this on friday, but here's a ~ping~. Would love to get this figured out.

**Comment by LindsayYoung** [comment]
I deleted that one manually from the data bases-- I don't know how it came back. :/

I like that idea for the typeahead search. I do think that we don't want to be too aggressive and take it out of all search, so you can't find those candidates if you really want to.

**Comment by leahbannon** [comment]
I like the idea of taking it out of typeahead but leave it in for actual searches.

**Comment by noahmanger** [comment]
Yep, exactly. That's what I'm thinking.

**Comment by LindsayYoung** [comment]
This is an easy fix but there are some data holes. I want to take a look at our filtering tomorrow. 

I am seeing candidates filtered out that should have candidate or former candidate status: 
ISRAEL, STEVE J.
COSTELLO, RYAN A

We are pulling the most recent status, from dimcandproperties. Which makes sense, but seems to have holes. I am going to take a look tomorrow to see if the dimcandstatusici table is actually better to use, though that has holes too.  There might be some logic to fill the holes, like nulls after candidate status should be treated as former candidates. I will take a look and then confirm solution with FEC.
