### ISSUE TITLE
In order to comply with OGC: Content Pages: Issue #1 of 3 - Electronic Filing Page

### ISSUE THREAD

**Issue by amypike** [18F/openFEC-web-app#812]
@emileighoutlaw  I spoke with Jeff and found out a little about the validation process.  When a filer uses e-file software to produce a filing, the software encrypts the filing and then provides the user with a validation number.  When the filer goes to upload that filing to the fec server, the server encrypts the filing in the same way and also produces a validation number.  Those two validation numbers should match.   Perhaps our sentence should be edited to say something like this:  "Once you upload your filing to the FEC, we'll send you an e-mail or fax confirming receipt of the report, which will have a validation number.  This validation number should match the validation number your filing software gave you."  Or something like that?  @amykort.

**Comment by emileighoutlaw** [comment]
Ah yes! A mystery solved. I think a slight tweak on the sentence you wrote will be perfect. Thanks for investigating, @amypike! :)
