### ISSUE TITLE
In order to comply with OGC: Content Pages: Issue #2 of 3 - Citation for the Post-General Election Reports

### ISSUE THREAD

**Issue by amypike** [18F/openFEC-web-app#813]
Hi @emileighoutlaw !  This is an easy one:  The citation for the post-general report is 11 CFR 104.5(a)(2)(ii)(A) and (B). @AmyKort

**Comment by emileighoutlaw** [comment]
Excellent!!

**Comment by emileighoutlaw** [comment]
Has been fixed in Wagtail
