### ISSUE TITLE
In order to comply with OGC: Content Pages: Issue #3 of 3 - "Learn more about pre-election reports" page

### ISSUE THREAD

**Issue by amypike** [18F/openFEC-web-app#814]
@emileighoutlaw  @amykort   This is the last one, and it is an easy one - I double-checked the comments from RAD/Info and the language we discussed on Tuesday is accurate.  The sentence (as the three of us edited it) should read:  "Pre-election reports are pre-primary, pre-general and pre-runoff reports.  File these reports for any primary, runoff or general election your candidate is involved in, including special elections."  THANK YOU!

**Comment by emileighoutlaw** [comment]
Awesome! Thanks @amypike !
