### ISSUE TITLE
Repair search by state/district functionality

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC-web-app#819]
Searching by state and district seems do be down, but searching by zip code is still working:

https://fec-proxy.18f.gov/data/elections/?cycle=2016&state=CA

**Comment by LindsayYoung** [comment]
Yea, the dev site is acting up. There are a few queries that are acting up on the dev server and working fine on production and locally. :bug: <= it is hiding

**Comment by LindsayYoung** [comment]
I am seeing an error in new relic that says, 
```
sqlalchemy.exc:NoSuchTableError: ofec_sched_a_aggregate_size_merged_mv
```

Could it be because we are still creating the older aggregates, since that merged earlier?

**Comment by jmcarp** [comment]
It looks like this issue (and the contribution by size issue) have been resolved after merging #1261 and letting the views rebuild. @jenniferthibault, would you mind verifying that this is behaving as expected on the proxy site?

**Comment by jenniferthibault** [comment]
Verified! Both are working on proxy.

**Comment by jmcarp** [comment]
:sunglasses:
