### ISSUE TITLE
In order to help users find more content below the landing page hero section, we will add a downward pointing arrow

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC-web-app#820]
One the beta landing page, data landing page (/data) , and registration landing page (/registration-and-reporting), add a centered 90 degree triangle that matches the border color. This arrow will provide a visual clue for users to scroll down for more.
![screen shot 2015-10-08 at 4 47 00 pm](https://cloud.githubusercontent.com/assets/11636908/10379673/99ec8166-6ddd-11e5-9deb-25e2b3261943.png)
![screen shot 2015-10-08 at 4 48 49 pm](https://cloud.githubusercontent.com/assets/11636908/10379671/99e9a1bc-6ddd-11e5-8751-5044f81e3e53.png)
![screen shot 2015-10-08 at 4 49 06 pm](https://cloud.githubusercontent.com/assets/11636908/10379672/99ebca96-6ddd-11e5-86b8-56892003da6b.png)

**Comment by LindsayYoung** [comment]
"Downward pointing arrow" sounds like a yoga pose. ;)

**Comment by jenniferthibault** [comment]
Hahaha, you beat me to it @LindsayYoung

**Comment by jenniferthibault** [comment]
No longer needed with the new hero designs planned in https://github.com/18F/fec-style/issues/330
