### ISSUE TITLE
So that users can explore and respond to different interactions, wireframe date range option for financial summaries

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#821]
For the beta release, we'll need to modify the wireframes, https://invis.io/RE4GG62GB, in Issue #801 to include a date range slider option. 
        
@wluoFEC @amykort @jwchumley @amypike

**Comment by noahmanger** [comment]
Can you clarify: are you asking to see a version with an actual date range slider? We hadn't discussed that, and there's a number of challenges with that interaction. Also, are you saying that you just want to see that in wireframes or implemented?

**Comment by AmyKort** [comment]
We're looking for a wireframe that would show what a date slider might look like. It would allow people for example to pick their own beginning and ending dates and see summary data that way. The beginning and ending points would be limited to reports filed. For example, I want to see  everything from the July 2014 quarterly report to the July 2015 quarterly report. The idea is to give people something to look at and respond to in wireframe form--not that this is implemented. @PaulClark2 @wluoFEC @jwchumley should jump in to correct me where I'm wrong.

**Comment by PaulClark2** [comment]
@AmyKort that's correct.  @noahmanger sorry I wasn't clearer with my description

**Comment by noahmanger** [comment]
Cool, thank you. I believe there are some technical limitations on this end, but we can talk about that further.

**Comment by LindsayYoung** [comment]
My former employer had trouble implementing a version of this and decided to give that up. Happy to explain more but, I think that if we do a slider, it should be locked to 1-year increments.

**Comment by jenniferthibault** [comment]
Addressed in #824 and https://github.com/18F/FEC/issues/71
