### ISSUE TITLE
To help users understand the time period they're looking at, add a tooltip to explain the two-year period select

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#824]
Using the pattern implemented elsewhere (such as with the "Unique only" filter on /receipts), add a tooltip to two-year period selects on candidate, committee and election pages. The tooltip should explain what this means and also include links to a GitHub issue that contains wireframes for the 2/4/6 year version and invites the user to comment. 

**Steps:**
- [x] @emileighoutlaw write content for the tooltip (see below for sample language)
- [x] I'll implement
- [x] @jenniferthibault create new issue with mockups

**Draft language:** 
> This site currently groups data by two-year period. This means that the page you're looking at doesn't necessarily include all of this candidate or committee's activity since their last election. We're working on a new interface to allow you to view data for the entire four or six years between presidential or senate elections, and we want your feedback. Visit this issue on GitHub to view the latest designs and comment there or on the feedback button at the bottom of this page.

That language is rough and verbose, but wanted to include the main points I think we need to hit.

**Comment by emileighoutlaw** [comment]
Working on this now

**Comment by emileighoutlaw** [comment]
I workshopped this with my roomie, who consequently has *no* FEC experience. Here's what we came up with. Not a lot shorter, but she understood it. We can at least use it as a jumping off point. Thoughts?

This site groups data in two-year periods— if a candidate or committee has been active more than two years, it won't show all their data. We're working on a four-year view for presidential data and a six-year view for Senate data. But we need your feedback. See the latest designs on GitHub, and let us know what you think. You can also leave comments using the feedback button at the bottom of this page.

**Comment by noahmanger** [comment]
I like this.

**Comment by jmcarp** [comment]
AFAIK, we don't know that we're going to be working on four- and six-year views, specifically--we know that we're working on some way of showing more (and maybe less) data than two year chunks.

**Comment by noahmanger** [comment]
Good point. Let's make it a little more generic for now.

**Comment by emileighoutlaw** [comment]
How about: 
>This site groups data in two-year periods— if a candidate or committee has been active more than two years, this page won't show all their data. We're currently working to create additional views, but we need your help. See the latest designs on GitHub, and let us know what you think. You can also leave comments using the feedback button at the bottom of this page.

**Comment by noahmanger** [comment]
:+1:

**Comment by jenniferthibault** [comment]
These are the mockups I was planning to put into the new issue—they use a senate race as an example for each type of cycle select. Do these work? If we prefer, I can move the interaction notes to text in the GitHub issue instead of in the mockup itself

![candidate - senate copy](https://cloud.githubusercontent.com/assets/11636908/10521777/a12ca0de-733f-11e5-86a9-5720b6bee611.png)

![candidate - senate copy 2](https://cloud.githubusercontent.com/assets/11636908/10521792/a7d821ba-733f-11e5-8bd9-b19b0f57a66f.png)

![candidate - senate copy 3](https://cloud.githubusercontent.com/assets/11636908/10521794/a7ddf1da-733f-11e5-91f3-f072e173d4ac.png)

![candidate - senate copy 4](https://cloud.githubusercontent.com/assets/11636908/10521793/a7daa52a-733f-11e5-89e2-a09d26e08453.png)

**Comment by noahmanger** [comment]
Nice. I like the idea of moving the notes into the body of the issue, with headings separating the different versions. 

@paulclark2 anything missing from these?

**Comment by PaulClark2** [comment]
@noahmanger  I think this covers everything

@jenniferthibault Thanks for mockups they look great. For the A:  Single dropdown we need to merge "2016 Election" and "All:  2011-2016" so that they become a single entry "Full Cycle 2016."

Full Cycle 2016
  2015 - 2016
  2013 - 2014
  2011 - 2012
Full Cycle 2010
  2009 - 2010
  2007 - 2008
  2005 - 2006

@amykort @wluoFEC

**Comment by noahmanger** [comment]
Heads up: because of the way that HTML `<select>` elements work, we won't be able to bold or style the "Full Cycle XXXX" items. Right now they're `<optgroup>` titles, which is what differentiates them visually, but they are not selectable items.

**Comment by PaulClark2** [comment]
@emileighoutlaw @jmcarp I tend to agree with Josh about this.  We need to explain that currently we are using 2-year periods.  If, in the end, we use committee reporting cycles then PACs and party committees have a 1-year reporting cycle and as we've been discussing candidates have 2, 4 or 6 year reporting cycles depending upon office.

**Comment by PaulClark2** [comment]
Thanks @noahmanger 

Maybe something like this so that "full cycle xxxx" is selectable?  

2016 Election
  Full Cycle 2016
  2015 - 2016
  2013 - 2014
  2011 - 2012
2010 Election
  Full Cycle 2010
  2009 - 2010
  2007 - 2008
  2005 - 2006

**Comment by noahmanger** [comment]
Works for me. Of course we'll test it out and see if it makes sense to users.

**Comment by jenniferthibault** [comment]
If "Full cycle" is a phrase users know and associate (and it sounds like it might be, but testing TBD?) I'd like to also make clear the start and end date. It's long, but would look like this:

2016 Election
 Full Cycle 2011–2016
 2015 - 2016
 2013 - 2014
 2011 - 2012
2010 Election
 Full Cycle 2005–2010
 2009 - 2010
 2007 - 2008
 2005 - 2006

**Comment by noahmanger** [comment]
:+1: should probably be "Full cycle" (lowercase c)

**Comment by jenniferthibault** [comment]
good catch :) I'll work up some new mockups with this integrated, and will start the new issue

**Comment by noahmanger** [comment]
Already started one here https://github.com/18f/fec/issues/71

**Comment by PaulClark2** [comment]
Thanks!   Agreed all this is subject to usability testing.

**Comment by PaulClark2** [comment]
@noahmanger @jenniferthibault 

ok ... I have more information.   The default needs to be "Full cycle" and in the case of a senate candidate page the default summary finanical information needs to cover 6 years.  So for a 2016 senate candidate the default needs to be Full cycle 2016 and the default coverage period needs to be 1/1/2011 to most recent filing in 2015.  The data might not matter for the beta release if the mockups are only going to show the top of the page.  

Question:  For the beta release these mockups will or will not be functioning?   My understanding was that they would just be images that folks could comment on.   

@wluoFEC

**Comment by PaulClark2** [comment]
So for the image / mockup that folks will comment on we need the dropdown to look like this. 

Full Cycle 2016
2015 - 2016
2013 - 2014
2011 - 2012
Full Cycle 2010
2009 - 2010
2007 - 2008
2005 - 2006

**Comment by jenniferthibault** [comment]
Can do. These will just be static images for people to comment on, not interactive prototypes. I'm also planning on using just the cropped section with the first headline as you're seeing here, so that it's more obvious that we are only comparing one specific tool. This means that we don't need to worry about the data until actually implementing one of the solutions after getting feedback.

**Comment by AmyKort** [comment]
Perfect!

**Comment by PaulClark2** [comment]
:+1: 

Excellent!   Thanks @jenniferthibault  and @noahmanger .  So the "Full cycle" version will be Option A and the financial summary text will be "Financial summary for 2011-2016."

**Comment by jenniferthibault** [comment]
You got it! Here's what A looks like @PaulClark2 . I'm still working on the others now.

<img width="786" alt="screen shot 2015-10-15 at 3 50 14 pm" src="https://cloud.githubusercontent.com/assets/11636908/10525755/8bedb036-7354-11e5-9b26-943540064cd6.png">

**Comment by PaulClark2** [comment]
@jenniferthibault you're great and thanks

**Comment by PaulClark2** [comment]
Hi @jenniferthibault one more comment about the Option A dropdown.  Should "Full cycle 2016" repeat.  Or is this usual dropdown behavior?   

If it was just a choice, can we alter the mockup so that second "Full cycle 2016" does not appear.  

@wluoFEC

**Comment by noahmanger** [comment]
The idea here is that this just uses the native browser `<select>` element, which will render different for each browser. It will actually look like this (on Chrome):

![screen shot 2015-10-15 at 2 09 57 pm](https://cloud.githubusercontent.com/assets/1696495/10527661/878fbea2-7346-11e5-9238-7e3968df3113.png)

Whichever `<option>` is currently selected remains in the list.
