### ISSUE TITLE
To help users understand complex technical content, add additional phrases to the glossary

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/openFEC-web-app#828]
@amypike @amykort Here are the words I've identified so far that I'd like to add into the glossary. Is there somewhere I can look for legal definitions of these? Many thanks!

- Receipt
- Disbursement
- Source prohibition
- SSF
- General public political advertising

**Comment by amypike** [comment]
Another effort
to help users understand
our FEC speak:

Receipt: Anything of value (money, goods, services of property) received by a political committee. (no citation, definition is from Candidate Guide)
Disbursement: Any purchase or payment made by a political committee or any other person that is subject to FECA,  11 CFR 300.2(d).
SSF - A political committee established, administered or financially supported by a corporation or labor organization, popularly called a corporate or labor political action committee or PAC.  See 11 CFR 114.1(a)(2)(iii). The term "financially supported" does not include contributions to the SSF, but does include the payment of establishment, administration or solicitation costs. 11 CFR 100.6(b)

"Source prohibition" and "General public political advertising" are trickier so let's talk about those off-line.

**Comment by emileighoutlaw** [comment]
Our best haiku yet. :) Adding these in today. We can talk about the trickier ones next time we're together

**Comment by AmyKort** [comment]
@emileighoutlaw: Please wait to add additional glossary terms--we might still want to tinker with the language before it goes out. Thanks!

**Comment by emileighoutlaw** [comment]
Hey! So those are the definitions the OGC specifically asked us to add in for the registration and reporting pages (so I already have them up in the glossary now). Can we keep tinkering, and if we still don't have a good consensus, I'll pull them down before launch?

**Comment by AmyKort** [comment]
These will be great additions when we launch the registration and reporting pages. Let's save them for that launch. Thanks. @wluoFEC

**Comment by noahmanger** [comment]
https://18f.storiesonboard.com/m/fec/!card/LgBFd2PuCGYcyjnUEHzR2Q

**Comment by emileighoutlaw** [comment]
New terms have been added and merged in. :+1:
