### ISSUE TITLE
"Hide filters" is partly visible in Firefox

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC-web-app#830]
AFAIK, the "Hide filters" text should be hidden until hover, but in Firefox, part of it's peeking out:

<img width="550" alt="screen shot 2015-10-14 at 3 44 20 pm" src="https://cloud.githubusercontent.com/assets/1633460/10495559/8c7f9912-728a-11e5-8f1c-ed78e774eb6b.png">

cc @noahmanger

**Comment by noahmanger** [comment]
I'm not able to replicate this. Can you give me any more info?

**Comment by jmcarp** [comment]
Huh, looks like my Firefox was a few versions behind. If you downgrade to Firefox 37, I think you'll be able to replicate, but Firefox is normally pretty aggressive about pushing out new versions (except apparently for me), so now I'm thinking it's not worthwhile. I think this is fine to close.
