### ISSUE TITLE
To provide a clear search interface, consider consolidating or reorganizing similar search tools

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC-web-app#835]
We have several different entry points for searching for candidates. They're all somewhat different, but also show some overlapping information. This came up during the offsite, so I wanted to flag it for discussion. Nothing is necessarily wrong here--just wondering whether we can merge some of this functionality at some point, and/or make it easier to find.
- https://fec-proxy.18f.gov/data/?search_type=candidates&search=bartlet
- https://fec-proxy.18f.gov/data/candidates/?name=bartlet
- https://fec-proxy.18f.gov/data/elections/

**Comment by noahmanger** [comment]
Ha, Jen, Jeremy and I were just talking about this today. Thanks for flagging.

**Comment by noahmanger** [comment]
This should also include work around weighting search results.

**Comment by noahmanger** [comment]
Referencing this here: https://18f.storiesonboard.com/m/fec/!card/71Cv_9xvjTU3dTnTx3CXqg
