### ISSUE TITLE
Bug: Committee schedule A tables are missing

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#836]
On committee receipts tabs, the map shows up with values, but the table next to it is missing: https://fec-proxy.18f.gov/data/committee/C00213512/?cycle=2016&tab=receipts

![screen shot 2015-10-14 at 5 18 03 pm](https://cloud.githubusercontent.com/assets/1696495/10501544/badc838a-7297-11e5-8501-0403753e9e61.png)

I'm seeing this error: 

```https://fec-dev-api.18f.gov/v1/committee/C00213512/schedules/schedule_a/by_state/?api_key=&per_page=99&page=1&sort=-total&cycle=2016&hide_null=true Failed to load resource: the server responded with a status of 422 (status code 422)```

**Comment by jmcarp** [comment]
This is working again--looks like a few indexes didn't get added to that aggregate table. Not sure of a straightforward way to automate checks for this, but we only rarely rebuild these tables, so I'm fine to check manually for now.
