### ISSUE TITLE
Remove Glossary Entry for Communication Cost

### ISSUE THREAD

**Issue by AmyKort** [18F/openFEC-web-app#840]
Please take down the glossary entry for Communication Cost--we're going to tinker with the language a little before it goes live. Thanks!

**Comment by LindsayYoung** [comment]
Just talked to @AmyKort 
She said it was ok to keep if we edited to match what is in the Candidate Guide exactly: 
```
Any broadcast, cable or satellite communication that:

   Refers to a clearly identified candidate for federal office;
   Is publicly distributed within certain time periods before an election; and
   Is targeted to the relevant electorate.

11 CFR 100.29.
```

**Comment by AmyKort** [comment]
This is a separate issue. The definition above is for Electioneering Communication. I am discussing the definition of Communication Cost here.

**Comment by emileighoutlaw** [comment]
Hey there. So the current FEC website has Communication Cost as: 

>52 U.S.C. 30118 allows “communications by a corporation to its stockholders and executive or administrative personnel and their families or by a labor organization to its members and their families on any subject,” including the express advocacy of the election or defeat of any Federal candidate.  The costs of such communications must be reported to the Federal Election Commission under certain circumstances.

Can we use that?

**Comment by PaulClark2** [comment]
No we need to remove the glossary entry for Communication Cost.   @wluoFEC

**Comment by AmyKort** [comment]
We're not providing language on the beta site within the same context as language is provided on the current site. Please remove the glossary entry. Thanks.
