### ISSUE TITLE
Remove Glossary Entry for Electioneering Communication

### ISSUE THREAD

**Issue by AmyKort** [18F/openFEC-web-app#841]
Please take down the glossary entry for electioneering communication. We're going to tinker with the language a little before it goes live.

**Comment by LindsayYoung** [comment]
I copied this verbatim from the current FEC site 
http://www.fec.gov/pages/brochures/electioneering.shtml

Are you sure we can't continue with this for now and update it later?

I have been adding links for each definition that I add. 
https://github.com/18F/fec-style/commit/6a5293785c0aca892189d6319c1c70d0cd8a8eb3

**Comment by PaulClark2** [comment]
We need to remove the glossary entry for Electioneering Communication @wluoFEC

**Comment by AmyKort** [comment]
We're not providing language on the beta site within the same context as language is provided on the current site. Please remove the glossary entry. Thanks.

**Comment by LindsayYoung** [comment]
No problem! Sorry for misunderstanding you.
