### ISSUE TITLE
In order to find committees (esp super PACs) that are opposing or supporting a given candidate, users want the ability to filter committees by the candidate they are supporting or opposing. 

### ISSUE THREAD

**Issue by onezerojeremy** [18F/openFEC-web-app#850]
In usability testing, users consistently attempt to first find independent expenditure only (super PACs) supporting or opposing a given candidate through the committee search.

In order to support this, we might consider adding the ability to filter committees by whether they have supported or opposed a given candidate. (not totally sure if this is possible, or how it would work from a data perspective)

Clearly needs both design work, and problem solving on the data side as well. If it's not possible, we'll need to consider special navigational aids to help people find relevant Independent Expenditure Only activity. 

Related to #701.

**Comment by noahmanger** [comment]
Big +1 to this. We've been seeing this come up a while. 

It kind of relates to the big filter re-think I discuss here too https://github.com/18F/openFEC-web-app/issues/815

**Comment by noahmanger** [comment]
This is captured on the storymap so closing.
