### ISSUE TITLE
bug: Sometimes the favicon on the data site doesn't load

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC-web-app#852]
It works most of the time, this is an example of an error message on chrome.
(Thanks @jcscottiii!)

![pasted image at 2015_10_16 02_41 pm](https://cloud.githubusercontent.com/assets/4406333/10550337/6b339dcc-7414-11e5-9309-671a695f27a1.png)

**Comment by noahmanger** [comment]
I fixed this.
