### ISSUE TITLE
So that users understand why districts may be missing from election search, add disclaimer

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#854]
We want to add a disclaimer of some sort to the election search page along the lines of:

> Results shown only include districts where candidates have filed to run for [year]. 

- [x] @emileighoutlaw write content
- [x] @jenniferthibault: where should we place this?
- [ ] I'll implement

**Comment by noahmanger** [comment]
This is something we want to do this sprint, right?

**Comment by jenniferthibault** [comment]
I'd say so!

**Comment by emileighoutlaw** [comment]
Yep! I'm working on the content now.

**Comment by emileighoutlaw** [comment]
> These results only show districts where candidates have filed to run in [year].

Was also toying with the idea of a two-sentence disclaimer, which is longer but more clearly spells out the "why no results?" piece:

> This [page? tab? map?] shows districts where candidates have filed to run in [year]. If no candidate has filed with the FEC, no results will appear.

Thoughts?

**Comment by LindsayYoung** [comment]
Right now, we are not showing districts that don't have data to show. So they could have filed, but if we don't have any financial reports we are not creating a page. 

Would an empty page be more or less confusing?

**Comment by emileighoutlaw** [comment]
Ah, interesting. Does this get closer to the truth?

> This page shows financial data by district. Candidates may have registered with the FEC but not yet disclosed financial data— in which case, no results will appear.

**Comment by LindsayYoung** [comment]
Yes, that is what we are currently doing- though we have debated back and forth on that a few times and there is a that could add that if that would be better for users. (If we added that PR, we still wouldn't have districts where people haven't registered yet.)

**Comment by emileighoutlaw** [comment]
Hmmmm:

> No results? This page shows data by district, and "no results" can happen for several reasons. For example, no candidates may have registered. Or, candidates may have registered but not yet filed financial data.

**Comment by noahmanger** [comment]
I'd rather have the disclaimer be specific to whatever the rules we're operating with, so if we change the rules we just change the disclaimer. So I'd go with:
> This page shows financial data by district. Candidates may have registered with the FEC but not yet disclosed financial data— in which case, no results will appear.

**Comment by jenniferthibault** [comment]
I can't tell if this message will show up all the time, or only on the occasion that no results are presented, but I think we should use the "feedback" pattern for the user, from the style guide below. I think the "alert" pattern might be a bit too much:

![screen shot 2015-10-20 at 3 05 43 pm](https://cloud.githubusercontent.com/assets/11636908/10618110/12230dd2-773c-11e5-987f-fe56217a9d58.png)

That would be placed under the results section, like below:

![screen shot 2015-10-20 at 3 04 43 pm](https://cloud.githubusercontent.com/assets/11636908/10618128/25267446-773c-11e5-84ee-7fc28b4253c1.png)

If it does only show when no results are presented, maybe the "alert" style is more appropriate

**Comment by emileighoutlaw** [comment]
How about this for content? 

> This page shows data by district. "No results" can happen for several reasons. For example, candidates may have registered with the FEC but not yet disclosed financial data.

**Comment by noahmanger** [comment]
:+1: to both visuals and language. I'll implement.

**Comment by noahmanger** [comment]
Actually, just realized that this language isn't quite right. It's not just that "no results" message appears, but that you could get districts but not all districts. So I think we want something more like:

> This page shows elections where candidates have filed to run and have reported financial data. If no candidates have filed or reported for a particular election, it may not show up here.

**Comment by emileighoutlaw** [comment]
?: 

> This page shows campaign finance data by district. If no candidates have filed (or if candidates have filed but not yet reported financial data), the district may not show up here.

**Comment by noahmanger** [comment]
Works for me if it works for @LindsayYoung and @jmcarp

**Comment by LindsayYoung** [comment]
While we are at it can we also note that the district maps are approximate. 

We are not getting all of the detail so that maps load faster so they will be wrong around the edges in many cases.

**Comment by noahmanger** [comment]
> This page shows campaign finance data by district. If no candidates have filed (or if candidates have filed but not yet reported financial data), the district may not show up here. District maps on this page are approximate.

**Comment by noahmanger** [comment]
@emileighoutlaw This work?

**Comment by emileighoutlaw** [comment]
LGTM!

**Comment by LindsayYoung** [comment]
That makes me happy!
