### ISSUE TITLE
To help users find "other spending", try to relabel the "Other spending" tab

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#855]
Per @onezerojeremy : 

Usability testing is indicating that users aren't associating "Other Spending" with the data that will be available on that tab, and therefore aren't clicking. They also don't reliably associate "Independent Expenditures" with Super Pacs. 

Task: 
How would you find which Super PACs are supporting or opposing Hillary Clinton?
User 1, relatively new to campaign finance:
>"I don’t know, but that’s actually the kind of stuff I want to find."
[on the candidate's page, scrolling around for Super PACs]
>"Okay so how would I find Super PACs? I guess this is just the one committee? Hillary for America is the Super PAC? It’d be nice to see like something that designates the key, like if Hillary for America is the Super PAC or if it’s a 501C or a different type of PAC? I still have no idea. Oh that’s her principal campaign committee. I don’t know if that means Super PAC."
User 2, campaign finance professional:
>“Other spending? It’s not very intuitive. You would think that means because you’re on the Hillary Clinton page you’d think that’s other spending by the candidate or the candidate’s committee."

Don't have good instincts on what to call it (that will pass legal muster); recommend we keep gathering data for now, but it's strikes me that our language isn't matching user expectations yet.

**Comment by emileighoutlaw** [comment]
#858 also talks about this. I'm offering an idea over there for a temp solution; this issue seems like a good one for longterm discussion of language.

**Comment by noahmanger** [comment]
Story card: https://18f.storiesonboard.com/m/fec/!card/xXORfv6n8LlhiznUEFZhfg

**Comment by onezerojeremy** [comment]
from 11/20 usability testing:
One person assumed that "other spending" was a more technical, in-depth sort of spending that only pro-users would be interested in. Also, one user pointed out that the converse would be nice, namely that they wanted to look at a given committee and see which candidates they've supported. Both failed to find this, which both thought was "very interesting" data when we lead them to it.

**Comment by noahmanger** [comment]
This was just merged in for this release.
