### ISSUE TITLE
To collect users for usability testing, add ethnio popup to bottom right of beta.fec.gov

### ISSUE THREAD

**Issue by leahbannon** [18F/openFEC-web-app#856]

**Comment by jenniferthibault** [comment]
Hold please! See #866 for communication & feedback trategies around this before any implementation

**Comment by jenniferthibault** [comment]
We have this covered int he next steps of #866 — Ethnio will be on the home page and data home page (sharing the cookie so people still only see it once) but on the bottom left so that it doesn't overlap the feedback tool on the right.
