### ISSUE TITLE
So users can better understand and apply filters, consider language edits to >$5K filter

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/openFEC-web-app#859]
Considering alternatives to this language, which could confuse non-expert users:

<img width="180" alt="screen_shot_2015-10-16_at_4 37 27_pm_360" src="https://cloud.githubusercontent.com/assets/10552702/10579937/f5709644-7648-11e5-9889-6af8c0a3ab80.png">

Is this correct? The three options under `Candidates raising more than $5,000` are:
- `Statutory candidate` (which means they've raised more than $5,000 for the current cycle?), 
- `Future candidate` (which means they’ve raised more than $5,000 but for a future cycle?), and 
- `Statutory candidate in prior cycle` (which means they raised more than $5,000 but for a past cycle?) 

cc @LindsayYoung @noahmanger @jmcarp

**Comment by emileighoutlaw** [comment]
Jamming on this again. What are your thoughts on: 

> Candidates raising more than $5,000
- Prior to selected cycles (or election years)
- During selected cycles (or election years)
- After selected cycles (or election years)

**Comment by AmyKort** [comment]
How about something more like this (edit me):

    Candidates raising more than $5,000

        For election held prior to selected cycle
        For selected election cycle
        For election held after selected cycle

@emileighoutlaw

**Comment by emileighoutlaw** [comment]
I like this a lot more than what we have now.

Thoughts @jmcarp @noahmanger @LindsayYoung ?

**Comment by noahmanger** [comment]
Better, but I still find the structure of the field label awkward. What about:

`Limit to candidates who raised more than $5,000`

**Comment by AmyKort** [comment]
I think that's fine. I have a knee-jerk reaction to think contribution limit whenever I see "limit" in this context. Is that because I've worked here to long?

**Comment by AmyKort** [comment]
Limited to candidates who raised more than $5,000

**Comment by AmyKort** [comment]
?

**Comment by noahmanger** [comment]
Hmmmm. I'll let Emileigh be the final say on verb conjugation. I like the imperative (is that right?) form more than past participle in this case, but I get your point. Maybe "Restrict to candidates...." ?

_Hoping I'm remembering my 10th grade english well_

_Instantly regretting getting into a grammar discussion with people with graduate degrees in English_

**Comment by AmyKort** [comment]
Restricted to is perfect. Thank you!

**Comment by AmyKort** [comment]
Sorry: restrict to.

I live in the past.

**Comment by emileighoutlaw** [comment]
I'm hesitant to add anything like "restrict or limit" here. If we added `restrict to`, our language would be inconsistent with the other filters, all of which restrict/limit/filter the data in some way but don't specifically say `restrict` `limit` or `filter`.

<img width="292" alt="screen shot 2015-11-09 at 9 42 14 am" src="https://cloud.githubusercontent.com/assets/10552702/11036382/426528ec-86c6-11e5-8ed8-97f8e274caee.png">

@noahmanger, would the language feel less awkward if it were `Candidates who raised more than $5,000` ?

**Comment by noahmanger** [comment]
That's a good point. I was thinking about that too. I like that idea. Let's test it! I can make the change and have it testable for Thursday.

**Comment by noahmanger** [comment]
There's one other option though that we haven't addressed: ''Not yet a candidate'". What should that be?

**Comment by emileighoutlaw** [comment]
Criminy. I didn't even see that one. If we change the others, I'll keep jamming on that last filter.

What does "Not yet a candidate" mean? Does @AmyKort know? Or @jmcarp?

**Comment by AmyKort** [comment]
If you've registered with the FEC, but not reached the $5,000 threshold, then you are reporting but not yet a candidate. 

Is this what the data reflects?

**Comment by emileighoutlaw** [comment]
So `Not yet a candidate` are people who haven't yet reached the $5,000 threshold? 

If that's the case, it doesn't seem like a child of `Candidates who raised more than $5,000` — it seems like we should pull it out and call it something like `Candidates who haven't raised $5,000`

**Comment by noahmanger** [comment]
I agree with @emileighoutlaw that it's incongruous. But I don't think we need a whole separate filter. I'd vote for just removing that.

**Comment by noahmanger** [comment]
Also, we're testing this today so should get some data on how legible these suggested options are.

**Comment by noahmanger** [comment]
Moving conversation from the PR back over there. Josh said https://github.com/18F/openFEC-web-app/pull/961#discussion_r45282953 :

> Maybe too nit-picky, but I'm not sure this is right. First of all, there isn't always a selected election cycle. Second, the candidate records are using the most recent candidate status value, not the candidate status value(s) of the selected cycle(s), if any.

How do you respond @emileighoutlaw and @AmyKort ?

**Comment by emileighoutlaw** [comment]
Blurg. Okay, I'm going to have to think about this for a minute.

**Comment by emileighoutlaw** [comment]
Hey @jmcarp, just want to make sure I understand correctly:

If the user selects an election cycle, the results will show the records for that selected cycle. If no cycle is selected, it defaults to the most recent two years of data? 

I don't know that I think we need to spell out the second piece about candidate status value. Or if we do, maybe it would be a better tooltip?

**Comment by noahmanger** [comment]
If there's no cycle selected, then it just shows all data.

**Comment by noahmanger** [comment]
I think what we mean is that Past and Future means relative to the actual current election cycle (so today, 2016), right?

Or can you be a "past election cycle candidate" for an election in the past if you raised $5,000 for that election cycle before that election cycle? 

This is screwy.

**Comment by AmyKort** [comment]
We shouldn't care when you raised the money. Candidates raise funds that are designated for a particular election. The issue is that you have registration and reporting requirements once you raise or spend in excess of $5,000 designated for that election. At that point you are "active" in that election for the purposes of the FECA. I thought the purpose of this filter was to allow people to filter out individuals who reported with us even though they weren't statutorily required to do so. Or committees that are continuing to report after the election cycle in which their candidate ran.

**Comment by AmyKort** [comment]
Does it still default to the 2-year cycle if we default to 2-4-6?

**Comment by AmyKort** [comment]
Or started raising money before the beginning of the election cycle for which they reach the threshold.

**Comment by jmcarp** [comment]
The candidate status values that we show aren't related to the cycles in the filter panel. For most attributes in the candidate browse view, we use the most recent available value (e.g., name, district, status).

@AmyKort: the 2/4/6-year aggregates only apply to financial summary data (receipts, disbursements, etc.), and not to the data in the candidate browse view (https://beta.fec.gov/data/candidates/).

**Comment by emileighoutlaw** [comment]
One more round of questions:

- If the candidate records (past, future, present) are always the most recent status value, why do we need these three options. Why not just have "candidates who raised more than $5,000" regardless of the cycle? Who would use the past/present/future filters, and how?

**Comment by noahmanger** [comment]
That's a good question. @LindsayYoung ?

**Comment by emileighoutlaw** [comment]
Still wondering about the answer to this question, @jmcarp

**Comment by noahmanger** [comment]
Take-away from call: collapse all options into a single filter for "Has raised more $5,000"

**Comment by LindsayYoung** [comment]
dependency for the web-app change is 18F/openFEC/issues/1469

**Comment by emileighoutlaw** [comment]
Woohoo!!!!!
