### ISSUE TITLE
Bug: on development site, top banner overlaps glossary functionality, and glossary can't be closed

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC-web-app#864]
I'm guessing the solution is to move the glossary down the same height as the banner, OR, don't make the banner sticky, and let the user scroll away from it on the page.

![screen shot 2015-10-20 at 9 51 59 am](https://cloud.githubusercontent.com/assets/11636908/10609185/69bb76dc-7710-11e5-9113-e98825280707.png)

cc @noahmanger / @jmcarp

**Comment by emileighoutlaw** [comment]
I also just noticed the banner gets stuck on the Candidate pages— when you scroll down and then scroll back up, it gets stuck cutting off the "Contact" link on the top.

<img width="1249" alt="screen shot 2015-10-20 at 10 03 11 am" src="https://cloud.githubusercontent.com/assets/10552702/10609473/efb6ab0c-7711-11e5-83b2-599fcc2c662f.png">
