### ISSUE TITLE
To improve the reliability of the site, improve test coverage and refactor as needed

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC-web-app#865]
# Unit tests

Much of the client-side logic was written before the project started to use unit tests. As a result, most older javascript doesn't have unit tests, and isn't written in a format amenable to unit testing. This increases the time necessary to fix bugs and add features. The following features are in need of tests:
- [ ] Tab lists
- [x] Data tables
- [x] Table filters
- [ ] Table panels
- [ ] Election pages
- [ ] Miscellaneous utilities
- [ ] Accordions (in fec-style)
# Integration tests

We have a handful of integration tests implemented using Selenium that verify that all the components of the application work together correctly. These tests are potentially very useful, since we don't have a manual QA team, but we haven't updated them for a while, so there's a lot they don't cover. They're also written using the low-level Selenium API, meaning they're verbose and hard to read and write. I'd like to write Selenium tests using the "page object" pattern going forward: http://martinfowler.com/bliki/PageObject.html. This will help organize our Selenium tests and make the code more concise.

Pages to test:
- [ ] Election detail
- [ ] Election search
# Notes

None of this is urgent, but I think it's important that we unit-test a feature before we change it. This is relevant to the work that @jenniferthibault has been doing on the election page: I'd like to hold off on changes until we have tests, and since there are designs that are ready for implementation, adding tests here is a relatively high priority. Our accordions also don't have unit tests, but we also aren't planning to make major changes to them, so tests are less urgent there (although still worthwhile).

I can start working through the higher-priority testing items anytime, and if @LindsayYoung and @noahmanger have the time and interest, we can split up the work.

**Comment by noahmanger** [comment]
Card: https://18f.storiesonboard.com/m/fec/!card/xqcdHVJ85BIaCznTwmqB7g
