### ISSUE TITLE
bug: Election page "Contributions by size" should be "Individual contributions by size"

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC-web-app#872]
The aggregates we show, come from contributions [from individuals](https://github.com/18F/openFEC/blob/develop/data/sql_incremental_aggregates/prepare_schedule_a_aggregate_size.sql#L25).

~~update links to add `contributor_type=individual` on election pages~~
~~update links to add `contributor_type=individual` on committee pages~~
 - [ ] update words on election pages

<img width="1077" alt="screen shot 2015-10-21 at 12 49 32 pm" src="https://cloud.githubusercontent.com/assets/4406333/10644150/e3dd8574-77f4-11e5-9826-1b18d7420e70.png">

**Comment by jmcarp** [comment]
Looks like we're already using `is_individual=true` on the relevant pages. I think we just need to update the language on the election page to clarify that we're only talking about individual contributions in the "Fundraising comparison" section.

Thoughts @emileighoutlaw?

**Comment by LindsayYoung** [comment]
I thought `is_individual=true` filters out the earmarked funds and `contributor_type=individual` shows only donations from individuals.

**Comment by jmcarp** [comment]
Unfortunately, it's a little more complicated than that. Filtering for `is_individual` restricts the results to transactions that are both from individuals and not earmarked. This is the filter we're using to build individual aggregates, not `contributor_type`.

**Comment by emileighoutlaw** [comment]
So that I understand correctly, it's "Individual contributions (not earmarked) by donation size" ?

**Comment by LindsayYoung** [comment]
So there were two things going on, what parameters we need for filtering and what we should call that section.
 - I think that "Individual contributions by donation size" is close enough. 
 - Thanks for talking with me earlier Josh, filtering for individuals is already included in the `is_individual=true` filtering. I updated the top of the ticket to reflect that. The data was just messy so I couldn't see that it was already filtered.

**Comment by noahmanger** [comment]
This language issue was resolved in #898
