### ISSUE TITLE
Bug: Some filings should have panels but don't

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#883]
On https://fec-proxy.18f.gov/data/filings/?committee_id=C00575795, the row for "July 15 (Q2) report  and Semi-annual 2015" has an arrow to suggest it has a panel but it does not have the `.js-panel-trigger` class and it can't open a panel.

**Comment by jmcarp** [comment]
Looks like this was fixed in #885, and the offending row in the table linked above no longer has an arrow on dev. Can this be closed @noahmanger?

**Comment by noahmanger** [comment]
This works now.
