### ISSUE TITLE
To align user and team expectations, revisit beta homepage "What's next?" content

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/openFEC-web-app#884]
#### Current content
<img width="1025" alt="what s next" src="https://cloud.githubusercontent.com/assets/10552702/10678840/c5f3cf20-78e2-11e5-9de6-862caa26f868.png">

^^ I think this is a little out of date

#### Suggested revision
What's next?
A few of the things we're working on:
- Registration, reporting and compliance resources
- Improvements to campaign finance data tools, including exportable data
- Further improvements to the new look and feel of the website

cc @leahbannon

#### Tasks to completion:
 - [ ] Finalize copy @emileighoutlaw 
 - [ ] Implement @jenniferthibault (if a text-only change, @emileighoutlaw can implement)

**Comment by emileighoutlaw** [comment]
cc @LindsayYoung @noahmanger @jmcarp @jenniferthibault 

I'd love to make this edit before the code freeze. What are your thoughts on the above, proposed new next?

**Comment by noahmanger** [comment]
So are you proposing dropping the point about AOs?

**Comment by emileighoutlaw** [comment]
I was— only because my understanding is that the legal tools are much further out on the horizon than the others. Do we want to promote features that are many months in the future?

**Comment by noahmanger** [comment]
Story: https://18f.storiesonboard.com/m/fec/!card/4LO6eJ8e9p-fLDnTx3QZPg

**Comment by emileighoutlaw** [comment]
Closing this; no longer relevant
