### ISSUE TITLE
Bug: Candidate filings not showing up on candidate pages

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#887]
Seems to be all candidate pages.

**Comment by noahmanger** [comment]
Also independent expenditures.

**Comment by noahmanger** [comment]
Sorry, IEs _are_ showing up. Disregard that last comment.

**Comment by noahmanger** [comment]
Bah. Sorry, it's just not working for me locally. But I am ahead of the dev site, so keeping this open for someone to double-check.

**Comment by jmcarp** [comment]
Let's double-check once any last pending patches are deployed.

**Comment by jmcarp** [comment]
@noahmanger now that the latest code is on dev and prod, can you check and see if this is an issue? I'm not sure which candidates were acting up before, so not sure how to test.

**Comment by noahmanger** [comment]
Seems to be working.
