### ISSUE TITLE
Ethno bug on fec.gov

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC-web-app#892]
On Internet Explorer, if you use a control or function key a JS error from Ethnio pops up.

We will want to check out settings and contact Ethnio if the problem persists. 

Did not know where to put this so I put it here so we don't forget it.

**Comment by jmcarp** [comment]
Ping @noahmanger. This makes the site pretty hard to use under IE.

**Comment by noahmanger** [comment]
Ugh. Not sure what to do about this in the short term. We could hide the script for IE? Can someone email info@ethn.io with the bug info? They're very responsive.

**Comment by LindsayYoung** [comment]
I can't reproduce this I tried IE 10, 11 I am emailing Pat for more details.

**Comment by noahmanger** [comment]
Resolved by turning off Ethnio for IE 8 and lower.
