### ISSUE TITLE
When sorting "Support/Oppose" table is removed

### ISSUE THREAD

**Issue by nickbristow** [18F/openFEC-web-app#906]
I believe this is because there is no data for this entry?

https://beta.fec.gov/data/candidate/H8VT01016/?tab=other-spending

<img width="1011" alt="sanders__bernard_congressman_-_candidate_overview_-_beta_fec_gov" src="https://cloud.githubusercontent.com/assets/5296248/10799800/2338108c-7d85-11e5-9837-9bd623963142.png">

*click sort on other spending -->

<img width="1028" alt="sanders__bernard_congressman_-_candidate_overview_-_beta_fec_gov" src="https://cloud.githubusercontent.com/assets/5296248/10799812/2dafa1ec-7d85-11e5-9628-e4c8daa90c3e.png">

**Comment by noahmanger** [comment]
Yeah this seems to just be a bug arising from bad data.

@jmcarp is this something we want to address on the frontend?

**Comment by noahmanger** [comment]
That record no longer exists and I'm not seeing this bug anywhere else. Closing.
