### ISSUE TITLE
To clarify language for users, make "from state" more precise

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/openFEC-web-app#920]
A couple places on the data site, we say a variation of `Total amount received from state`. On a literal level, it looks like this is saying the *state* gave the money.

<img width="521" alt="screen shot 2015-11-04 at 11 54 15 am" src="https://cloud.githubusercontent.com/assets/10552702/10945279/d0a5f134-82ea-11e5-88ba-c60ac3d084e7.png">

A couple options:
`Total amount received in state`
`Total amount received from contributors in state`
`By state: total amount received`

Either of these look good? Y'all have other ideas?

cc @jenniferthibault @LindsayYoung @noahmanger

**Comment by jenniferthibault** [comment]
I get a little confused when it's changed to `in state` but any of those options with `by state` makes sense to me! 

Perhaps the middle option, `Total amount received from contributors in state` is the most comprehensively accurate, but I think I'd have to choose the last `By state: total amount received` 

Does anything need to change in the toggles?
<img width="974" alt="screen shot 2015-11-04 at 5 19 34 pm" src="https://cloud.githubusercontent.com/assets/11636908/10953867/5aa099ca-8318-11e5-83d4-53a887e1bad7.png">

**Comment by emileighoutlaw** [comment]
I think the toggles are clear as is.

Agreed that the middle option (albeit accurate) is a little verbose. :)

**Comment by noahmanger** [comment]
I was just going to make this change and then remembered that we have a bunch of language inconsistencies between the committee page and election page. 

![image](https://cloud.githubusercontent.com/assets/1696495/11190652/9bd02c62-8c4b-11e5-8cf9-96a3f5f0e5d4.png)

We should have common language for:
- Map title
- Map description
- Toggle title

**Comment by emileighoutlaw** [comment]
Would it work to have both be:
- Map title: "Individual contributions by state" 
- Map description: "The total amount of contributions received from individuals"

What's the toggle title?

**Comment by noahmanger** [comment]
I think I like "Contributor state" for the toggle title. 

And for the description can we just add "in each state" to the end?

> The total amount of contributions received from individuals in each state

**Comment by emileighoutlaw** [comment]
Agreed on "Contributor state" for the toggle title.

Do you think it's unclear that we mean "in each state" if we don't say it? I took it out because I thought it was pretty clear without it (and thought folks might be more likely to read the description if it were shorter), but I'm amendable to other ideas!

**Comment by noahmanger** [comment]
Sure! Let's give it a shot.

**Comment by noahmanger** [comment]
Actually, I think we oughta just remove the description. We don't use it on other similar tables.

**Comment by emileighoutlaw** [comment]
Cool! Bold! I love the idea. Cut the description!
