### ISSUE TITLE
To simplify build process, switch from browserify to webpack

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC-web-app#921]
Browserify's code-splitting functionality isn't great, and using browserify requires us to use a separate build tool (at the moment, gulp). I propose that we replace browserify and gulp (and their many associated plugins) with webpack to simplify our build process.

**Comment by noahmanger** [comment]
Moved to story map: https://18f.storiesonboard.com/m/fec/!card/9jSngScPr5z0XznUD8RvAQ

Closing.

**Comment by jmcarp** [comment]
Why close this? Aren't we going to wind up creating the same issue again? FWIW, I may knock this out some weekend on my own time.
