### ISSUE TITLE
To prevent regressions, share variables between JS and SASS

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC-web-app#924]
Some information is currently duplicated between our scripts and styles, such as breakpoints. Like any code duplication, this is error-prone--it's easy to make a change to the JS without making the parallel change to the SASS. We should make this harder to screw up.
- Easy version: add a single JS and a single SASS file with shared variables, with comments reminding us to keep both files in sync. Code is still duplicated, but the duplication is contained to two files.
- More complicated but better version: store all shared configuration in a single JSON file, and import it from the JS and SASS. This looks like an issue the community is still figuring out, but one promising approach is https://github.com/Updater/node-sass-json-importer.
- Best version: write the scripts and styles so that they don't have to share information in the first place.

cc @noahmanger @msecret

**Comment by noahmanger** [comment]
Interesting. Of the two options, I think I prefer the second one, even if it's more complicated.

_But_, we only do this in one place as far as I can tell, which is in showing and hiding different columns at different breakpoints when the panels open and close.

I think my preference would be to find a way around setting breakpoints in the JS at all if we can find a way around it. Given how many annoyances we've run into with the way datatables renders column widths and the like, it may be worth looking a smarter way to do all of the above.

**Comment by jmcarp** [comment]
The second option's definitely better if we have to do either. But yes, it's definitely preferable if the JS and SASS don't have to share any information. I'll update the issue. The reason I was thinking about this was because @msecret asked about a hard-coded breakpoint in the filter panel in https://github.com/jmcarp/openFEC-web-app/blob/feature/refactor-filter-panel/static/js/modules/filter-panel.js#L35-L41.

**Comment by noahmanger** [comment]
Oh yeah, I caught that after I made my comment. So there's a couple places
where we make breakpoints in the JS.

On Wed, Nov 4, 2015 at 4:45 PM, Joshua Carp <notifications@github.com>
wrote:

> The second option's definitely better if we have to do either. But yes,
> it's definitely preferable if the JS and SASS don't have to share any
> information. I'll update the issue. The reason I was thinking about this
> was because @msecret <https://github.com/msecret> asked about a
> hard-coded breakpoint in the filter panel in
> https://github.com/jmcarp/openFEC-web-app/blob/feature/refactor-filter-panel/static/js/modules/filter-panel.js#L35-L41
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC-web-app/issues/924#issuecomment-153917383>
> .
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146

**Comment by msecret** [comment]
I think it'd be good to try and not do breakpoints in JS. The panel can be a little tricky but I'm pretty sure there's a way ad

**Comment by noahmanger** [comment]
Card: https://18f.storiesonboard.com/m/fec/!card/q2sPXkB6Xur_rjnUEFZhfg
