### ISSUE TITLE
Decide design direction for 2/4/6 cycle select

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC-web-app#933]
Based on preliminary usability tests and feedback on https://github.com/18F/FEC/issues/73 , decide which design direction to build for live user testing

Story map card: [2/4/6 cycle select](https://18f.storiesonboard.com/m/fec/!card/qv-XXBL-Je7ikjnTowJqCg)

**Comment by noahmanger** [comment]
So, in Slack discussions the other day we decided on Option B from that issue. I'm closing this and opening a new one for making the design refinements Jeremy included in his comment.
