### ISSUE TITLE
Build version of 2/4/6 cycle select for usability testing

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC-web-app#934]
Based on design direction determined by #933 , build and implement cycle select on staging for user testing.

Story map card: [2/4/6 cycle select](https://18f.storiesonboard.com/m/fec/!card/qv-XXBL-Je7ikjnTowJqCg)

**Comment by noahmanger** [comment]
Assigning to Josh.

**Comment by noahmanger** [comment]
This is done. Deploying now.
