### ISSUE TITLE
In order to determine if it's meeting user needs, test 2/4/6 cycle select with users

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC-web-app#935]
Test tool from #934 with users 

Story map card: [2/4/6 cycle select](https://18f.storiesonboard.com/m/fec/!card/qv-XXBL-Je7ikjnTowJqCg)

**Comment by jenniferthibault** [comment]
Use this testing to decide final direction of tool

**Comment by onezerojeremy** [comment]
Tested on 11/12 and 11/20. Results, also in #967: 

People did not associate the the 2 year cycle toggles with the word "all". Possible remediation ideas: Make "All" triggered on page load, make it appear to deselect the other toggles. (One person thought "All" referred to all election years, as opposed to all years in that election cycle).

There are a couple of things going on here, but I think the simplest change to the page, that is, triggering all on load and making it appear consistent with how the other cycle select toggles work (that is, selected with the others deselected), may actually be sufficient to make them easily understood.

**Comment by noahmanger** [comment]
Done.
