### ISSUE TITLE
To prevent users from encountering irrelevant information, hide tabs where not applicable

### ISSUE THREAD

**Issue by jmcarp** [18F/openFEC-web-app#937]
As described in https://github.com/18f/fec/issues/134, we're currently showing the disbursements tab for IE-only committees, but that tab isn't relevant in those cases. We should hide tabs by committee type such that tabs that aren't applicable aren't displayed.

**Comment by noahmanger** [comment]
No prior discussion, so closing this out in favor of this story card: https://18f.storiesonboard.com/m/fec/!card/KyvZREVXsH_KvjnUD8RvAQ
