### ISSUE TITLE
Bug: On mobile, filters are still clickable even when hidden

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#947]
Something about the way that the filter panel is hidden on mobile makes it possible to actually click the filters even though they're not visible when the panel is collapsed. This prompts the keyboard to pop up on screen.

**Comment by noahmanger** [comment]
Update: This actually seems to be an issue with the Safari bug and the date filters referenced here https://github.com/18F/openFEC-web-app/issues/930

To test, on the iOS simulator, load beta.fec.gov/data/receipts and tap anywhere. Then, in the Safari inspector, console.log the `document.activeElement` and it's the first custom date field. This seems to be the case regardless of where you tap.

@jmcarp any ideas on this?

**Comment by noahmanger** [comment]
This also seems to be resolved. Can someone just double check?

1. Go to beta.fec.gov/data/receipts on a phone or the iOS simulator
2. Tap on one of the table rows 
3. Verify that you didn't get jumped down to a hidden field somewhere

**Comment by ccostino** [comment]
@noahmanger:  I just took a look on my iPhone 6 (latest version of iOS and Safari) and I don't think I jumped to anything - the screen stayed at the top of the contributor information section (so the View all and View original image links were at the top of my screen).

**Comment by noahmanger** [comment]
Cool, thanks for checking. Yeah, I think this is a non-issue now.
