### ISSUE TITLE
Revise cycle select based on usability feedback

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#967]
**Story:** In order for users to view summary totals for natural cycles, add the ability for users to view data in 4 and 6 year increments.

**Tasks:**
- [x] @onezerojeremy synthesize usability findings
- [x] Discuss design changes with @jenniferthibault 
- [x] I'll implement

**Comment by onezerojeremy** [comment]
Usability Testing:  
People did not associate the the 2 year cycle toggles with the word "all". Possible remediation ideas: Make "All" triggered on page load, make it appear to deselect the other toggles. (One person thought "All" referred to all election years, as opposed to all years in that election cycle).  

There are a couple of things going on here, but I think the simplest change to the page, that is, triggering all on load and making it appear consistent with how the other cycle select toggles work (that is, selected with the others deselected), may actually be sufficient.

**Comment by jenniferthibault** [comment]
@emileighoutlaw can you help us out with finding a good word or short phrase for the "All" button in this toggle? 

![screen shot 2015-11-23 at 10 34 44 am](https://cloud.githubusercontent.com/assets/11636908/11340863/f18a7748-91cd-11e5-9d83-4fb771748f19.png)

Jeremy's suggestion to revert to single button toggles for the next test makes sense to me!

**Comment by noahmanger** [comment]
Language-wise, we could go back to the original suggestion from FEC: "Full cycle: 2015 - 2016". It's verbose, but maybe that's what we need?

When you say revert to single-button toggles do you mean just showing the "all" option selected instead of making the others look selected too?

**Comment by jenniferthibault** [comment]
Correct, that is what I meant! Or at least, that's what I was interpreting @onezerojeremy to say. no?

**Comment by emileighoutlaw** [comment]
I'm keen on "Full cycle: 20XX–20XX" for the language edit

**Comment by noahmanger** [comment]
Sounds good. I'll implement that.

**Comment by noahmanger** [comment]
Made these changes. If there's further changes to make, we can add them as new issues.
