### ISSUE TITLE
Campaign Finance Home Nav Item underperforming

### ISSUE THREAD

**Issue by onezerojeremy** [18F/openFEC-web-app#968]
After many weeks of testing, it is increasingly clear that many people are not rightly interpreting the primary nav link as a link to the beta data home. Because the user's hover fires before the click, many users don't rightly assume that they can click on "Campaign Finance Data" navigation item to take them to the data home, and thus miss the beta data home.   

![nav-problem](https://cloud.githubusercontent.com/assets/474916/11314950/dd8d89ea-8fb8-11e5-8345-517dc3db28f8.gif)

This may account for the relatively larger amount of bounced traffic from the home (though 
![screen shot 2015-11-20 at 6 58 13 pm](https://cloud.githubusercontent.com/assets/474916/11314953/e0147e6c-8fb8-11e5-9eb4-2a19bdcd4011.png)

If we want more data on this more before doing anything, we might consider putting analytics flags on the "campaign finance" nav item, "campaign finance" nav hover (if that's even possible), and the "campaign finance" call to action lower on the page (both link to the same page). It won't be hard science, but you might expect a relatively larger portion of users to click to the home from the nav hover than any of the sub-pages. Others may have better ideas for how to test this.

**Comment by onezerojeremy** [comment]
Tested this again on 12/03, consistently found that users are not immediately clear on the fact that the Campaign Finance Data menu tab was clickable.

**Comment by jenniferthibault** [comment]
THANK YOU FOR TESTING THIS! As you know, I've been wondering :) 

If we were to duplicate the link as the first item in the drop-down, what would your testing indicate we should name it? cc @emileighoutlaw

**Comment by noahmanger** [comment]
This is the way we do it on mobile:

![image](https://cloud.githubusercontent.com/assets/1696495/11633839/55d92362-9cc2-11e5-9379-0698bf840b0b.png)

The reason we do it there is because the top item has to open the sub-menu. But it would be really easy to just show the repeated link on desktop.

**Comment by jenniferthibault** [comment]
Nice! Seems like a logical first step to me.

**Comment by onezerojeremy** [comment]
Agreed! Let's try it!

**Comment by emileighoutlaw** [comment]
I third! Let's go with that!

**Comment by noahmanger** [comment]
With no style adjustments, this is how it looks: 

![image](https://cloud.githubusercontent.com/assets/1696495/11758683/06195b44-a023-11e5-8ee9-eeae54b2a059.png)

Looks a little weird to me. Jen what would you like?

**Comment by jenniferthibault** [comment]
Ultimately, I think we should move back towards the mega menu, which will help us separate the "Browse" from the actual navigation better. Here's from an earlier mockup:

![menu - 1 copy 3](https://cloud.githubusercontent.com/assets/11636908/11787536/3802198c-a25a-11e5-8ea9-cf2714543563.png)


For now, I think these style tweaks to the borders (which more closely match mobile styles) should do it:

![menu - 1 copy 4](https://cloud.githubusercontent.com/assets/11636908/11787551/4566cbc2-a25a-11e5-8771-675937fe8913.png)

**Comment by noahmanger** [comment]
+1 to both. Will do.

On Mon, Dec 14, 2015 at 9:01 AM, Jennifer Thibault <notifications@github.com
> wrote:

> Ultimately, I think we should move back towards the mega menu, which will
> help us separate the "Browse" from the actual navigation better. Here's
> from an earlier mockup:
>
> [image: menu - 1 copy 3]
> <https://cloud.githubusercontent.com/assets/11636908/11787536/3802198c-a25a-11e5-8ea9-cf2714543563.png>
>
> For now, I think these style tweaks to the borders (which more closely
> match mobile styles) should do it:
>
> [image: menu - 1 copy 4]
> <https://cloud.githubusercontent.com/assets/11636908/11787551/4566cbc2-a25a-11e5-8771-675937fe8913.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC-web-app/issues/968#issuecomment-164494988>
> .
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146

**Comment by onezerojeremy** [comment]
I like the initial solution a lot! 

I also wanted to note that I recall there being some movement away from mega-menus in broader UX circles, and think if we’re heading that way we should do so knowingly.

https://github.com/north/north
https://www.uie.com/articles/mega_menus/
