### ISSUE TITLE
Only show tabs relevant to particular committee types

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#977]
**[Story](https://18f.storiesonboard.com/m/fec/!card/KyvZREVXsH_KvjnUD8RvAQ)**: So that users only see relevant information on committee pages, only show tabs for the type of data that that committee has.

**Tasks:**
- [x] Decide logic
- [x] Implement

**Comment by noahmanger** [comment]
One question I have about this: is the correct way to write the logic here based on the type of committee or based on the data we have for them? Can we reliably assume that all committees of a certain type will always have X type of data and never Y type?

**Comment by jmcarp** [comment]
A thought about this: could the spreadsheet live in the github wiki on the API repo? I can never keep track of google docs.

Also, IMO we should stick to the committee type here. What do you think @LindsayYoung?

**Comment by noahmanger** [comment]
Oh smart. I'd be in favor of more of this type of thing living in the Github wiki, which would also help with partner collaboration.

**Comment by noahmanger** [comment]
Self-assigning this for now to figure out the logic and design of how we show what when.

**Comment by noahmanger** [comment]
Just talked with @LindsayYoung and @jenniferthibault and here's what we discussed. Basically, we want a couple layers of logic:
1. Selectively show certain tabs based on the kind of committee they are.
2. Then, based on what data they've reported, either hide or disable tabs for which there is no data.

We're still discussing the relative merits of disabling vs hiding, but the underlying code will be the same. If we do choose to hide them, we need to come up with a way to communicate why certain tab aren't included.

**Comment by noahmanger** [comment]
Remaining tasks:
- [ ] Finalize logic around type-based tabs
- [ ] Design interaction around hiding or disabling 
- [ ] Implement frontend

**Comment by LindsayYoung** [comment]
doc with tabs and types:
https://docs.google.com/spreadsheets/u/1/d/1aMkZf4LWQ6RUulOGwfQzQPZM0PxyJh0QUpUXw0dwGBk/edit?usp=drive_web

**Comment by LindsayYoung** [comment]
Doc with tabs and types:
https://docs.google.com/spreadsheets/u/1/d/1tqdTPZq-o51F6_gZ4WbJ0OPbAuWzx2enT65fK33c3f4/edit?usp=drive_web

**Comment by noahmanger** [comment]
So this all seems pretty straightforward:
![screen shot 2016-01-21 at 7 00 42 pm](https://cloud.githubusercontent.com/assets/1696495/12501393/5385aa22-c071-11e5-9777-246631053587.png)

I'm just not sure what to do about the "kind of" cells for type Z committees. Do those just need special views for those tabs? Seeing as these are old, I'm inclined to just come up with a modified financial summary tab and hide the other tabs for these committees since all data is available in the filings.

**Comment by leahbannon** [comment]
If a SuperPAC is IE-only, they’ll never have data about contributor occupation or employer, right? Are we addressing that here at all? Should we consider explaining this? Does the explanation that we currently provide address this? Ex: https://fec-proxy.18f.gov/data/committee/C00571372/?tab=receipts

Or... should I open a separate issue?

**Comment by noahmanger** [comment]
Well, they actually have that data, it's just not showing up for some unrelated reason...hmmm. (Being IE-Only just has to do with the type of activity they do).

**Comment by jenniferthibault** [comment]
After thinking on this a over a longer period of time and navigating around different types of committee pages, I'm coming back to the disable/vs don't show at all tab question.

I think it will be less confusing if we disable tabs that don't have relevant data instead of removing them completely. 
The strongest reason I have behind this is that there are so many types of committees, that asking a user to remember that "this committee is a XYZ type, so those tabs are missing because the info doesn't exist" seems like a farther stretch than asking users to understand that "this committee has no data in this tab, so it's not clickable".

**Comment by noahmanger** [comment]
Resolved in https://github.com/18F/openFEC-web-app/pull/1058
