### ISSUE TITLE
Figure out navigation to IE, EC, and CC browse pages

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#980]
**[Story](https://18f.storiesonboard.com/m/fec/!card/I0bne6Rqsx8cNznTwmRr_g):** So that users can view itemized Independent Expenditures, Communication Costs, and Electioneering Communications, users can filter and browse them all.

**Goal:** We have separate issues to create these pages, but this task is to figure out how you get to them from the data landing page and the nav menu.

**Comment by noahmanger** [comment]
@jenniferthibault I'm assigning to you but let me know if you want me to take it.

**Comment by jenniferthibault** [comment]
@noahmanger this is part of the sub-views we discussed yesterday, correct? Not separate, new browse categories (at the same level as Candidates, Filings, Receipts, Disbursements, etc) right?

**Comment by noahmanger** [comment]
Yeah, I think we can bracket this to think about in the bigger picture.

**Comment by jenniferthibault** [comment]
See latest mockups & concepts in https://github.com/18F/openFEC-web-app/issues/1003

**Comment by jenniferthibault** [comment]
Closing this in favor of keeping discussion to one big IA issue in #1003
