### ISSUE TITLE
Test download performance

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#984]
Per the discussion in the meeting today, we should put the date exporting (for candidates, committees, and filings) through the paces to make sure it holds up to real world use. 

My concern is less that it will cause the site to grind to a halt, but more that it will simply take way too long for people to get their exports, causing them to think the system is broken. 

So at the risk of being overly cautious, let's test how it works when we really load up the queue.

I may be misunderstanding the technical issues at play, so correct me if this isn't a concern.

**Comment by noahmanger** [comment]
@LindsayYoung or @jmcarp do either of you want to take this?

**Comment by jmcarp** [comment]
FWIW, the dev database runs on a less powerful machine than the prod database, so benchmarks on the dev database will underestimate performance on prod. Which isn't necessarily a bad thing. We could upgrade the staging database to use the same specs as prod, but that would raise costs.
