### ISSUE TITLE
Deploy a release

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#985]
As discussed today, we want to shoot for a release of the following features on Wednesday, December 16:
- 2/4/6 cycle selects on candidate pages
- Data exporting for candidates, committees and filings
- Candidate committee registration content
- Independent expenditure tabs on committee pages

Apart from the separate issues in resolving these features, the plan is to:
- [ ] Merge all features into `develop` and subsequently deploy to staging by end of day Monday
- [ ] FEC perform final QA on Tuesday
- [ ] Deploy to production by end of day Wednesday

@jmcarp sorry we had this convo without you. Do you see any problems with this schedule?

**Comment by jmcarp** [comment]
Thoughts:

* Neither the backend nor frontend for data downloads has been reviewed. Prefer not to merge either into develop until reviews are finished, which includes resolving any issues that might come up during review. I'll see who's available for reviews on Monday, unless anybody wants to start looking around today. I also don't know where the review of the new cycle selects is at.
* Presumably, #984 also needs to happen before releasing the download feature. Do we have a plan for carrying out that testing? Has it been assigned?
* Hard to say whether one day for QA and part of another day to resolve any issues is enough--it should be fine if we only turn up minor issues, but it doesn't leave a lot of wiggle room.

**Comment by noahmanger** [comment]
Ah thanks. Good points all around.

- On reviews before merge: Oh absolutely. Sorry, I had the unwritten expectation that things only get merged in after review. I didn't realize the download things still hadn't been reviewed. Do we want outside reviewers for both? Shawn is working on the cycle review today.
- Agreed, #984 should happen first. I'm happy to take the lead, but it might be more useful for you or Lindsay to do it as you understand what's going on.
- And yeah, not a lot of wiggle room for QA. 

I'll throw these concerns back to the team. The thought was that we didn't want to launch anything on friday, so if next weds or thurs are out of the question, then we're looking at the week after, which then gets into Christmas week. Not the end of the world, just something to be aware of.

**Comment by jmcarp** [comment]
I think this can be closed--the release is out, minus the download feature.
