### ISSUE TITLE
missing glossary items 'communication costs' and 'electioneering communication'

### ISSUE THREAD

**Issue by leahbannon** [18F/openFEC-web-app#996]
These headers have glossary links but nothing shows up in the glossary when I click on them.
<img width="1368" alt="screen shot 2015-12-16 at 10 40 47 pm" src="https://cloud.githubusercontent.com/assets/4323988/11863124/16052426-a446-11e5-82d3-23086ef07fcf.png">

**Comment by jmcarp** [comment]
IIRC, we were asked to remove that content from the glossary (which is why the text is blank), so it sounds like the solution here is to remove the links. @emileighoutlaw can you confirm?

**Comment by emileighoutlaw** [comment]
That's correct! I'll remove today.
