### ISSUE TITLE
make the legal resources section visually consistent

### ISSUE THREAD

**Issue by leahbannon** [18F/openFEC-web-app#997]
The legal resources section on these 2 pages looks really different.

<img width="1241" alt="screen shot 2015-12-16 at 11 03 36 pm" src="https://cloud.githubusercontent.com/assets/4323988/11863534/719c3b82-a449-11e5-93c2-f564c1880a8e.png">
<img width="1221" alt="screen shot 2015-12-16 at 11 03 52 pm" src="https://cloud.githubusercontent.com/assets/4323988/11863536/740fd05e-a449-11e5-8387-e09d74695db2.png">

**Comment by noahmanger** [comment]
Oh yep, this is a small change that needs to be made in the admin area of the CMS. I tried to fix it, but the admin area is currently missing necessary static assets, so I can't do anything yet.

**Comment by noahmanger** [comment]
Fixed this.
